### ISSUE TITLE
1.21.3 Crash

### ISSUE THREAD

**Issue by mcgamer48ft** [vectorwing/FarmersDelight#1003]
### Minecraft version

1.21.3

### Farmer's Delight version

1.2.4a

### NeoForge version

21.3.1-beta

### Description

Can't launch.  Get a Mixin Error

### Steps to reproduce

Launch the game with 1.21.3 NeoForge --> Boom

### Mod list

		Dynamic Crosshair 8.2+1.21.2 (dynamiccrosshair)
		Dynamic Crosshair API 1.1 (dynamiccrosshairapi)
		Fabric Rendering API 3.3.0+1.21.2-pre1 (fabric_renderer_api_v1)
		Farmer's Delight 1.2.4a (farmersdelight)
		Forgified Fabric API Base 0.4.42+d1308ded19 (fabric_api_base)
		Forgified Fabric BlockView API (v2) 1.0.10+9afaaf8c19 (fabric_block_view_api_v2)
		Forgified Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 (fabric_rendering_data_attachment_v1)
		Jade 16.0.1+neoforge (jade)
		libbamboo 1.13 (libbamboo)
		Minecraft 1.21.3 (minecraft)
		NeoForge 21.3.1-beta (neoforge)
		Sodium 0.6.0-beta.3+mc1.21.2 (sodium)

### Logs

https://mclo.gs/8f0IAW8

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Farmer's Delight has not been ported to 1.21.3 yet. In fact, I didn't even know NeoForge was already updated for this snapshot. 😆
