### ISSUE TITLE
Skillets are waterloggable on 1.20 but not on 1.21

### ISSUE THREAD

**Issue by lzm11111111** [vectorwing/FarmersDelight#1005]
### Minecraft version

1.21.1

### Farmer's Delight version

1.2.4a

### NeoForge version

21.1.72

### Description

Placing a skillet underwater will pop of instead of being waterlogged, it works fine on 1.20

### Steps to reproduce

1. Place a skillet underwater
2. it will pop of

### Mod list

Farmer's Delight 1.2.4a

### Logs

None

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This will be addressed in version 1.2.5 of FD, with explicit waterlogging implementations for the skillet.
