### ISSUE TITLE
Skillet is used as a weapon and cannot be damaged

### ISSUE THREAD

**Issue by TakimotoEirlo** [vectorwing/FarmersDelight#1006]
Skillet is used as a weapon and cannot be damaged. This is too unbalanced. Is there any way to adjust it?

**Comment by vectorwing** [comment]
Welp, something went wrong with its porting to 1.21, it seems; it should be taking damage. I'll take a look later.

**Comment by TakimotoEirlo** [comment]
Is Minecraft 1.21.1 Noeforge

**Comment by TakimotoEirlo** [comment]
> Welp, something went wrong with its porting to 1.21, it seems; it should be taking damage. I'll take a look later.

Is it fixed?

**Comment by vectorwing** [comment]
Fixed on commit 3614401, should be out on 1.2.5 soon.
