### ISSUE TITLE
Torchflowers can't be cut into 2 orange dye

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#1013]
### Minecraft version

1.20

### Farmer's Delight version

1.2.5

### NeoForge version

nuh uh

### Description

Torchflowers can't be cut into 2 orange dye

### Mod list

- farmer's delight
- Clayworks
- Blueprint
- Environmental 
- Other mods that will hopefully not randomly remove a recipe from the game

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Added on commit db5cd10.

**Comment by thelegitdolt** [comment]
thanks vcetor wing
