### ISSUE TITLE
unable to play

### ISSUE THREAD

**Issue by Alexanderiea** [vectorwing/FarmersDelight#1015]
unable to find mcreate_link in curse forage thus i am unable to play my mod pack on curse forage

**Comment by TheGridExpert** [comment]
What do you mean by "mcreate_link"?

**Comment by vectorwing** [comment]
Sorry, this board is for issues with the mod. It sounds like you're having issues with a launcher instead, and we can't really help with that.

**Comment by Alexanderiea** [comment]
That is not the issue I am having the game launches just fine my problem is
that you are requiring an external app in order to use this mod the app I
have absolutely no use for. The issues that I'm having is that the game
launches but before the game can reach its in-game menu where you select
single player multiplayer or other options it crashes and or freezes and
therefore I cannot play. And curse forage does not have the app in which I
am looking for because it is not a mod.

**Comment by vectorwing** [comment]
FD does not require any form of mobile app whatsoever; it's just a Java mod. If it is, something might be wrong with your Minecraft setup.

Could you please provide the following info?
- Screenshots of your instance
- Logs (latest.log, crash logs and so on);
- Mod list, Forge and MC version etc.

**Comment by Alexanderiea** [comment]
Well I play mods using curse forage. I don't know what else to tell you
because what you guys are requiring for Farmers delight is not on curse
forage.
