### ISSUE TITLE
Aquaculture 'unbreakable' neptunium knife is breaking when used with a cutting board

### ISSUE THREAD

**Issue by MuteTiefling** [vectorwing/FarmersDelight#1017]
### Minecraft version

1.21.1

### Farmer's Delight version

1.2.5

### NeoForge version

21.1.77

### Description

Aquaculture 'unbreakable' neptunium knife is breaking when used with a cutting board.

They believe you're not checking if the tool is allowed to take damage, however the same tool with the Unbreakable component attached works fine. Just raising the issue here as well as they're saying they can't do anything about it. 

https://github.com/TeamMetallurgy/Aquaculture/issues/484

### Steps to reproduce

1. Place Cutting Board
2. Get Neptunium Knife
3. Start chopping rice panicles
4. Notice the knife taking damage

### Mod list

![image](https://github.com/user-attachments/assets/078f5e37-beef-43d9-a605-3054107c1d42)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by Lethosos** [comment]
Important question: What other mods do you have installed as well?

**Comment by GirafiStudios** [comment]
Can be closed, was fixed on my end :)
