### ISSUE TITLE
Fully grown tomato crops display as transparent on maps

### ISSUE THREAD

**Issue by JoshPKT** [vectorwing/FarmersDelight#1020]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.5

### NeoForge version

Forge - 47.2.0

### Description

The block farmersdelight:tomatoes displays as transparent on maps. Notably, this is not an issue for the block farmersdelight:budding_tomatoes, which displays correctly as a shade of green on maps. This can be confusing, as it can make it look like all the tomatoes you planted have vanished when viewed on a map, as well as just looking aesthetically unpleasing.

### Steps to reproduce

1. Plant a tomato crop.
2. Bonemeal it, or wait until it is fully grown.
3. Make a map, or view it on minimap or worldmap mod.

### Mod list

Xaero's Minimap
Xaero's World Map
+others that aren't relevant

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Seems I forgot to undo an experiment, and it had no map color defined.
Fixed on commit 6da9d0e.
