### ISSUE TITLE
Waterlogged Skillets during Structure Generation

### ISSUE THREAD

**Issue by craisinlord** [vectorwing/FarmersDelight#1021]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.5

### NeoForge version

Forge 47.2.0 and 47.3.12

### Description

I'm the dev of the Integration Structures mods and I've been having an issue with structures containing waterlogged skillets when they are not waterlogged in the nbt file. I'm guessing there's something weird about the default nbt data? 

I have had multiple players report this bug to me, and I've seen it as well

![2024-11-25_17 11 48](https://github.com/user-attachments/assets/ca047081-c626-4fb2-a874-c5f8cf293c36)

### Steps to reproduce

1. Install Integrated Villages
2. Locate a village with skillets. Oasis village, Mossy Mounds, or Marketstead village
3. Find house with skillets

### Mod list

[Guard Villagers (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/guard-villagers)
[Mixin In Heaven (by pOtAto__bOy)](https://www.curseforge.com/minecraft/mc-mods/mixin-in-heaven)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[[Let's Do] Vinery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery)
[Integrated Dungeons and Structures (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/idas)
[CommandStructures (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/commandstructures)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Athena (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/athena)
[Underground Villages, Stoneholm (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/underground-villages-stoneholm)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Simply Cats (by Mnesikos)](https://www.curseforge.com/minecraft/mc-mods/simply-cats)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Easel Does It! (by dolthhaven)](https://www.curseforge.com/minecraft/mc-mods/easel-does-it)
[Domestication Innovation (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/domestication-innovation)
[[Let's Do] API (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/do-api)
[Wares (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/wares)
[Furnish (by wouink_)](https://www.curseforge.com/minecraft/mc-mods/furnish)
[Another Furniture (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/another-furniture)
[Artifacts (by ochotonida)](https://www.curseforge.com/minecraft/mc-mods/artifacts)
[Chipped (by terrariumearth)](https://www.curseforge.com/minecraft/mc-mods/chipped)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[LibX (by noeppi_noeppi)](https://www.curseforge.com/minecraft/mc-mods/libx)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Embeddium (by FiniteReality)](https://www.curseforge.com/minecraft/mc-mods/embeddium)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[[Let's Do] Meadow (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow)
[Supplementaries (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/supplementaries)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Feywild (by saphienyako)](https://www.curseforge.com/minecraft/mc-mods/feywild)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Cloud Storage (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-cloud-storage)
[Integrated API (by CraisinLord)](https://www.curseforge.com/minecraft/mc-mods/integrated-api)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Blueprint (by TeamAbnormals)](https://www.curseforge.com/minecraft/mc-mods/blueprint)
[Sawmill (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/sawmill)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[~SCORCHED GUNS 2~ (by Ribs498)](https://www.curseforge.com/minecraft/mc-mods/scorched-guns)
[Sodium/Embeddium Options API (by Txni)](https://www.curseforge.com/minecraft/mc-mods/sodium-options-api)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Rats (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/rats)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[The Graveyard (FORGE/NEOFORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Building Gadgets (by Direwolf20)](https://www.curseforge.com/minecraft/mc-mods/building-gadgets)
[Quark (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/quark)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Alex's Caves (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-caves)
[Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[CERBON's API [Forge | Fabric | NeoForge] (by Cerbon)](https://www.curseforge.com/minecraft/mc-mods/cerbons-api)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lendercataclysm)
[Lionfish API (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/lionfish-api)
[Radium Reforged (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/radium-reforged)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Paragliders (by Tictim)](https://www.curseforge.com/minecraft/mc-mods/paragliders)
[Zetter — Painting Mod (by dantaeusb)](https://www.curseforge.com/minecraft/mc-mods/zetter)
[WorldEdit (by sk89q)](https://www.curseforge.com/minecraft/mc-mods/worldedit)
[Ars Nouveau (by baileyholl2)](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau)
[Create: Better Villager (by Reggarf)](https://www.curseforge.com/minecraft/mc-mods/create-better-villager)
[Repurposed Structures (Neoforge/Forge) (by telepathicgrunt)](https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)
[Bosses of Mass Destruction [Forge | NeoForge] (by Cerbon)](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Better Archeology (by Pandarix)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)
[End Remastered [NeoForge/Fabric] (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/endremastered)
[Zetter Gallery — Share Paintings (by dantaeusb)](https://www.curseforge.com/minecraft/mc-mods/zetter-gallery)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Legacy: [Let's Do] Bakery (by satisfy)](https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery)
[Monobank (by mortuusars)](https://www.curseforge.com/minecraft/mc-mods/monobank)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Regions Unexplored (forge/fabric) (by UHQ_GAMES)](https://www.curseforge.com/minecraft/mc-mods/regions-unexplored)
[OctoLib (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/octo-lib)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Zeta (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/zeta)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Ice and Fire: Dragons (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons)
[Bountiful (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/bountiful)
[Sodium/Embeddium Dynamic Lights (by Txni)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Complementary Shaders - Unbound (by EminGT)](https://www.curseforge.com/minecraft/shaders/complementary-unbound)
[Kambrik (by Ejektaflex)](https://www.curseforge.com/minecraft/mc-mods/kambrik)
[Building Wands (by nicguzzo)](https://www.curseforge.com/minecraft/mc-mods/building-wands)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Balm (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Create: Dynamic Village (by syslev)](https://www.curseforge.com/minecraft/mc-mods/dynamic-village)
[Sodium/Embeddium Extras (by Txni)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)

### Logs

[latest.log](https://github.com/user-attachments/files/17910110/latest.log)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
I forgot to define the default state of `waterlogged` to false in the constructor.
Maybe I could release a quick fix with the recent translations.

**Comment by craisinlord** [comment]
That would be great! Thanks!

**Comment by vectorwing** [comment]
Fixed on commit bdec994.
