### ISSUE TITLE
Farmer's Delight Neoforge crashing

### ISSUE THREAD

**Issue by CreatureOtaku2X** [vectorwing/FarmersDelight#1034]
I'm having a problem with Farmer's Delight Neoforge crashing. I've tried reinstalling the mod, but that didn't help.

**Comment by vectorwing** [comment]
Please follow the [**Bug Report**](https://github.com/vectorwing/FarmersDelight/issues/new?assignees=&labels=&projects=&template=bug_report_form.yml) template when posting issues. We won't be able to help unless you provide the information requested in the template, such as:
- Crash logs
- Mod list
- Versions of Farmer's Delight, NeoForge and Minecraft etc.

**Comment by CreatureOtaku2X** [comment]
Here's the crash: [crash-2024-12-14_00.42.57-client.txt](https://github.com/user-attachments/files/18137387/crash-2024-12-14_00.42.57-client.txt)

I have no mods other than Farmer's Delight and the version of the mod is FarmersDelight-1.21.1-1.2.6, the latest release of minecraft is 1.21.4, and the NeoForge version 21.4.22-beta.

**Comment by vectorwing** [comment]
Ahh, you're trying to run FD on 1.21.4, that's why it crashed. 😓

Sorry, Farmer's Delight hasn't been ported to this version yet, only for 1.21.1 at the moment.
