### ISSUE TITLE
[1.16.4] Issue with Cooking Pot 

### ISSUE THREAD

**Issue by sr1ki** [vectorwing/FarmersDelight#104]
**Description**
The cooking pot isn't producing food even when ingredients are put into it. 

**Steps to reproduce:**
I'm running Farmer's Delight along with other mods so they might be the fault of this? I'm not entirely sure. This might not be a bug but something of my own fault but I'm new to GitHub and mods in general so please bear with me, thank you!!  

**Expected behavior:**
I expected it to cook the food and it did not. 

**Screenshots**
None to show. 

**Mod list:**
AutoRegLib
CreativeCore
Farmer's Delight
Item Physic Mod
Quark
Reusable Rockets 
Surrounding Indicators Mod 
Xaero's Minimap Mod

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Well, it could be many things:
- Is your pot heated from below, and bubbling? (Stoves, Campfires etc.);
- Are your ingredients correct? Check JEI to make sure!
- Is there anything funky being printed in your game logs?

If you can, share some screenshots of your pot setup, and the interface with your ingredients.

**Comment by sr1ki** [comment]
Yes the pot is being heated with a stove and the ingredients are correct. 
![cooking pot](https://user-images.githubusercontent.com/76128630/102406483-a2a22600-3fb8-11eb-8a49-a9afa51354ea.png)

Also how would I check the game logs and know what's wrong with it if there is something wrong?

**Comment by sr1ki** [comment]
Yes the pot is being heated and the ingredients are correct. But how would I check my game logs and what would something wrong look like? 
![cooking pot](https://user-images.githubusercontent.com/76128630/102406835-2a883000-3fb9-11eb-95b3-22eebef6252a.png)

**Comment by vectorwing** [comment]
That looks like you're trying to make Chicken Soup, right? It requires a carrot. Swap either the onion or the potato for it. 👍 

![image](https://user-images.githubusercontent.com/5566692/102419614-e576f480-3fde-11eb-82dc-cd3daff403ca.png)

**Comment by sr1ki** [comment]
Oh thank you, I honestly have no idea how I didn't notice that earlier??? Thank you so much for helping me out anyway even over something dumb like this.

**Comment by vectorwing** [comment]
No problem! Glad to know it's working, at least. 😄
