### ISSUE TITLE
Help (I can't use the cutting board) 

### ISSUE THREAD

**Issue by RoekieCookie** [vectorwing/FarmersDelight#113]
I joined a valhelsia multi-player server wanted to learn more about Farmers Delight. However, I can't seem to use the cutting board? I can place cabbage or beef down and I crafted a kitchen knife but even when I have my knife equipped with F I can't cut the cabbage?? I read the wiki but it gives very little information, so my question is; what are the controls to use the cutting board?? I've tried every key for hours without luck. Please help, I just wanna cut some cabbage.

**Comment by vectorwing** [comment]
The Knife should not be in your off-hand, your ingredients should.

The Cutting Board will take ingredients from any hand, preferrably the off-hand, but uses the main hand for tools. You need to right-click (use) the knife on the board after placing the cabbage, like so:

![image](https://user-images.githubusercontent.com/5566692/103153860-82b9f180-4772-11eb-873b-434d1b35ad55.png)

If I recall correctly, Valhelsia has knives from other mods too, and I'm not sure if they're tagged. Can you show me a picture of your setup?

**Comment by RoekieCookie** [comment]
You're right, I made the wrong knife. I'm an idiot. Thanks man!
