### ISSUE TITLE
[Suggestion] Add support for Abnormals pantries

### ISSUE THREAD

**Issue by evanbones** [vectorwing/FarmersDelight#116]
Absolutely love this mod and how well it works in vanilla+ packs.

For a small QOL tweak, it would be fantastic to get Abnormals wood variations on pantries.

Suggested wood types with Abnormals mods installed:

[Autumnity]
Maple

[Endergetic Expansion]
Poise

[Upgrade Aquatic]
Driftwood
River

[Atmospheric]
Rosewood
Morado
Yucca
Kousa
Aspen
Grimwood

[Environmental]
Willow
Cherry
Wisteria

**Comment by Bobisnotap** [comment]
People are actually already working on textures for those, please be patient.

**Comment by Lethosos** [comment]
It is likely that this will go into an addon mod, along with other woods (such as Biomes You Go!, and Biomes O' Plenty.)

But this is much further down the road, so there's no signpost along Vectorwing's roadmap that points to it yet.

**Comment by vectorwing** [comment]
This is a very popular request, especially for MCA mods in particular. Chances are it will happen someday, just not right now, as there are other pressing issues on the way.

I want to round up the mod into reasonable feature-completeness before considering crossover content, as many elements are still changing between versions. 👍
