### ISSUE TITLE
TeamAbnormals mods: Compatibility Issue

### ISSUE THREAD

**Issue by COLDW0LF** [vectorwing/FarmersDelight#117]
Hi there,

Love the mod!
Just wanted to let you know that the Team Abnormals mods have changed their naming system,
which has broken your compatibility; "driftwood_log_stripped" is now "stripped_driftwood_log", etc.

I hope this is helpful for you. I've been tweaking recipes and solving error logs for a custom pack using OpenLoader, 
so if you want me to upload the changes after I've done them I'd be more than happy to.

**Comment by vectorwing** [comment]
Hello! Thanks for spotting it; I haven't messed with integration in a while, so this would've totally skipped me. 😄

Moments after you posted the issue, @Partonetrain posted a PR fixing the IDs, and I got it merged. If you have other recipe integrations besides those, I'd be happy to take a look!

**Comment by COLDW0LF** [comment]
If I come up with any more, I'll let you know! ;)

**Comment by vectorwing** [comment]
I'll close this issue for now, as I'm about to review integrations for stuff I might have missed. Thanks for reminding!
