### ISSUE TITLE
[1.16.4] wild crops ignoring config

### ISSUE THREAD

**Issue by ColdFang** [vectorwing/FarmersDelight#125]
**Description**
crops are generating despite being set to false in config

**Steps to reproduce:**
1.disable wild crop in config (farmersdelight-common)
2.see them ingame 

**Expected behavior:**
no more wild crops ingame

**Screenshots**
![Screenshot_7](https://user-images.githubusercontent.com/13708113/104504190-5f9c9800-55e2-11eb-97ce-363a0b274dd7.png)

**Mod list:**
Forge: 35.1.36
Farmers Delight: 0.2.4b
will post full modlist if needed

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
It seems I completely forgot to re-add configuration checks when changing to the new biome gen event in 1.16.3...

Thank you for spotting it. Will be fixed in the upcoming version. 👍

**Comment by vectorwing** [comment]
Fixed on commit 43c7cba, should be on FD 0.3.0 soon.
