### ISSUE TITLE
[Wiki] Files whose Names Contain ":" are not Clonable

### ISSUE THREAD

**Issue by WuzgXY-GitHub** [vectorwing/FarmersDelight#127]
![](https://user-images.githubusercontent.com/62000315/104811517-09746280-5837-11eb-8b6a-86d7ed67edae.png)
![](https://user-images.githubusercontent.com/62000315/104811508-f1044800-5836-11eb-82d7-fa86cc3a53f8.png)

**Comment by vectorwing** [comment]
Huh, I didn't even know the wiki could be cloned! Though in hindsight it makes sense, since every edit has a commit message.
I can try changing the name around for now. On a first try, it didn't render a - digit, but I'll find something out.

**Comment by vectorwing** [comment]
Names have been changed up. Can you try cloning again?

**Comment by WuzgXY-GitHub** [comment]
It can be cloned successfully now. Thanks for the fix!
