### ISSUE TITLE
Pantries and Food crates aren't flammable

### ISSUE THREAD

**Issue by WitheredWasabi** [vectorwing/FarmersDelight#134]

**Comment by vectorwing** [comment]
According to the Minecraft wiki, none of the wooden storage blocks (chest, barrels etc.) are flammable, so I opted to make pantries non-flammable as well. Also, although the crates have wood to contain the crops, I'm not sure if they should themselves be flammable.

Now, I did forget to make Rice Bales flammable. I can pass through the blocks and try to define them in the next dot release. 👍

**Comment by vectorwing** [comment]
I did some preemptive flammability on Bales and Wild Crops, on commit ce240b4. Since there's a critical bug right now, I'll release this now and work on other flammable candidates later.
