### ISSUE TITLE
[MC Version] Vanilla vegetable crates drop nothing upon breaking

### ISSUE THREAD

**Issue by oswaldino** [vectorwing/FarmersDelight#136]
**Description**
See title.

**Steps to reproduce:**
Get carrot crate and cabbage crate, place them down, try to retrieve. Carrots are not returned in any way.

**Expected behavior:**
Carrot blocks should drop the same way as cabbage.

**Mod list:**
Frost Eternal mod pack

**Comment by vectorwing** [comment]
I'll fix it later tonight. 👍

**Comment by vectorwing** [comment]
Fixed on commit 0b04a0d.
