### ISSUE TITLE
[Suggestion] Cooking book

### ISSUE THREAD

**Issue by MegaGamer265** [vectorwing/FarmersDelight#140]
It would be cool if we had a recipe book that can also be placed.

**Comment by vectorwing** [comment]
My endgame wish for the Cooking Pot is to integrate vanilla Minecraft's recipe book interface. Though I'm unsure how viable that is, might require some mixin voodoo to work properly.

In the worst case scenario, I might consider a book item, though I'm leaning against the idea for now. ^^
