### ISSUE TITLE
[1.16.4] Breaking Wild Rice in water in Creative removes the water

### ISSUE THREAD

**Issue by bageldotjpg** [vectorwing/FarmersDelight#145]
**Description**
If you break Wild Rice that is in water when the player is in Creative mode, the water will disappear.

**Steps to reproduce:**
* Place Wild Rice in water
* Break it (in Creative mode)

**Expected behavior:**
The water should stay (like when you break other water plants or the rice crop)

**Screenshots**
![image](https://user-images.githubusercontent.com/55970498/105607594-36f46b00-5d65-11eb-99ce-38a0acbf8461.png)
![image](https://user-images.githubusercontent.com/55970498/105607596-3956c500-5d65-11eb-9c15-4cd6df382c32.png)

**Mod list:**
* Forge 36.0.1
* Farmer's Delight 0.3.1

**Comment by vectorwing** [comment]
Huh. I did notice the water vanishing, but my tests were mostly on large lakes where it gets filled immediately. 😓
I'll fix it up on a dot release.

**Comment by vectorwing** [comment]
Fixed on commit 52de20d.
