### ISSUE TITLE
[1.16.4+] Request to add cat food

### ISSUE THREAD

**Issue by jengendler** [vectorwing/FarmersDelight#151]
**Description**
Love that there are dog and horse food items with buffs. Would love to see the same with cat food as well, for our furry little creeper reppellers! It would probably be something with fish and/or chicken (perhaps minced), broth (like bone), and maybe a little grain like rice.  :)

**Comment by vectorwing** [comment]
Hello! Glad to know these two items are seeing use x)
I thought about cat food, but given they're more of a household pet, I couldn't see many advantages or effects they could use from a custom food. These foods are designed to enhance the pet's strengths when going out, for the most part.
I can take a shot sometime. If you have ideas for what it could do, feel free to suggest. 👍

**Comment by jengendler** [comment]
I go caving with cats to avoid creepers, but sometimes the cats wander just far enough away (because pets like to wander) allowing a creeper to get through to me. I've definitely gone caving with several cats at once and it gets a little nutty. 

Maybe the cat food increases the range at which creepers will stay away from them for a set duration. Or feeding it to them gives the player a short creeper repellent effect. Not sure if any of this would be possible but would be fun!

**Comment by vectorwing** [comment]
That's such an interesting use case! Always cool to hear other strategies, it didn't cross my mind. 😄
I can put some thought on it, though it sounds a bit tougher to implement the current ideas. Thanks for sharing anyway!

**Comment by jengendler** [comment]
Perhaps instead of creeper repel range, it provides the 'glowing status effect' on nearby creepers for a set duration, allowing the player to see them outlined through blocks. Ringing a bell applies this effect to illagers within 32 blocks, so it may be possible to use this method to target a different mob type like creepers. Just a thought!

**Comment by jengendler** [comment]
Another idea for a cat treat is a chance to invoke the cat's gift behavior (which normally occurs 70% of the time when a tamed cat wakes up along with its owner). I can see this being particularly useful for 1.17, because rabbit hide is in the cat gift loot table.

**Comment by vectorwing** [comment]
Hi there! I'm closing this suggestion's issue. If you'd like to reopen it, please go to the new **Discussions** tab on this repository. Suggestions must be posted there from now on. 👍
