### ISSUE TITLE
[Discussion] Food Balance

### ISSUE THREAD

**Issue by vectorwing** [vectorwing/FarmersDelight#152]
So... the mod has been out for a while. I assume it was enough time for some people to get a feel for the current balance of foods, so I'm opening a little discussion here.

I did some playtesting on my own, watched some folks play with FD live in front of me (on servers), and others on streams. But that's arguably not very good data. Below are some of my own observations; please feel free to comment on this issue to discuss the topics at hand, so the mod can improve further! 😊

## Comfort
This effect is a bit weird right now. Not only is it not very intuitive, it's also not very useful.

Comfort makes you immune to **Slowness** (an effect applied by Witches and Strays), **Weakness** (afflicted by nothing in vanilla) and **Hunger**. This seemed interesting at first, but rarely does it seem to become useful or instrumental in gameplay. Nourishing meals always seem to be more interesting (and indeed, currently cost a bit more to craft).

The idea behind it was that soups and stews are "warm and cozy" foods that raise your vitality, with Slowness representing cold in-game.

I have considered redesigning Comfort to do something else, but couldn't quite pinpoint what yet. Some ideas:

- Slow regeneration (0.5 per second?) for longer periods of time;
- Reduces damage rates from Poison and Wither;

What do you think? Any interesting ideas for what Soups and Stews could grant to players?

## Nourished
Conversely, the Nourished effect is a grand success. It can easily extend the time required to eat again, being a very useful effect during exhausting activities like long sprint-jumping trips, or Create's Hand Crank (hehe).

But I also think it's a bit _too_ good right now. Granted we cannot balance food costs around a plethora of auto-farming mods, but this hunger extension also makes you need to spend less of your food supplies to make meals. In some playthroughs, I was able to subside on 48 Grilled Salmon for _several_ in-game days, and had no incentive to try different meals, or even the non-plated ones.

One of the objectives of Farmer's Delight is to encourage **food diversity**: give players the ability to unite their ingredients into something greater than their sum, but also to experiment with which food they carry along on their activities. So ideally, different kinds of meals (maybe different kinds of ingredients) could have unique applications. For example, protein-heavy meals being better for combat, fish-based meals making you swim faster, certain veggies or pastries improving mining through Haste etc.

None of this is solidified yet, so I'd like to hear opinions about the current meta of Nourished in foods. Is it too easy to be forever well-fed? Should meals cost more, or should the effects of foods be shorter?

## Finger Foods
Continuing on the trend above, some of the lesser food items of FD currently have "burst effects" tied to them:

- The Sandwiches (except for Egg) apply either Strength or Resistance for 15 seconds, as a form of "second wind" during combat;
- Mixed Salad and Fruit Salad apply a burst of Regeneration, due to being healthy and refreshing;
- Melon Popsicles give a tiny burst of Fire Resistance for 8 seconds, to save players in a pinch while being much worse than proper potions.

The idea was for these fully-stackable, but less nourishing foods to accompany meals, or stand on their own, for players who prefer more hands-on utility now and then. Has it been useful to anyone? What's your experience trying these out?

---

Thanks for reading! Hope the mod's enjoyable as of now. 😄

**Comment by Bobisnotap** [comment]
Alright, let me give my thoughts on this.
Comfort I feel could be buffed to include the slower regen and damage over time reduction, but also keep it's pre-existing effects to not confuse people too much.
Nourished is pretty easy to abuse, so it definitely needs the nerf.
The smaller foods with the short bursts of effects are super handy, however I have abused the salad's regen a ton in past survival worlds. Like a ton. Basically how I was able to survive both the ender dragon and wither fights.

**Comment by hvdklauw** [comment]
I agree comfort could use a buff, I think levetation resistance might be a nice addition here besides the wither/poison as you are comfortable enough to not float?

Nourishment is very nice, I really hate the food system in minecraft and this helps me cope 

Finger foods, I totally missed these buffs because during a fight my thought is usually that bigger is better to get hearths back, so I have to try them out.

As for the food diversity, the spice of life carrot edition already gives you a reason to do this, not sure how to add to this, but maybe if you make/eat many different foods you get better at cooking, so you get more per craft?

**Comment by shattyyt** [comment]
> As for the food diversity, the spice of life carrot edition already gives you a reason to do this, not sure how to add to this, but maybe if you make/eat many different foods you get better at cooking, so you get more per craft?
SOLCarrot is an unbalanced mod. Use SOLPotato if you want it to be balanced.
About the finger food buffs, i really dislike them. They're very very easy to make potions. I think they should all be nerfed. 
About nourishment, they should be hard to make, so why does the buff reduce the amount you need to eat them to sustain hunger? Hard to make food is hard. 
About the foods overall, i think that once you eat a type of food that grants youu buffs there should be a period before you can get that buff again. Eating 2-3 other food could reduce this timer.

**Comment by Ad3lineL** [comment]
i really like the nourished effect since i dont need to eat every few blocks, but some system to punish the player for eating the same food constantly might be good, im currently relying hard on several stacks of vegetable pasta with no real reason to switch from it to a worse food

**Comment by shattyyt** [comment]
every few blocks?  pshhh even without the effect a good food can make you saturated for minutes

**Comment by vectorwing** [comment]
> Comfort I feel could be buffed to include the slower regen and damage over time reduction, but also keep it's pre-existing effects to not confuse people too much.

See, I feel that adding all of these to Comfort would be too much. Ideally, an effect should do one thing, not several different ones. With that said, making it a slow regen would quite literally be just worse regen, so I'm divided.

> The smaller foods with the short bursts of effects are super handy, however I have abused the salad's regen a ton in past survival worlds. Like a ton. Basically how I was able to survive both the ender dragon and wither fights.

Interesting take. It's good to see someone was testing these foods, as I entirely expected them to be sidestepped over meals due to how the design is working. Perhaps I underestimated Regeneration then; my idea was that it would be controlled by not being able to eat when you're at full hunger, but if you're taking damage, you *will* immediately become hungry again anyway. Might take a look at it.

> About the finger food buffs, i really dislike them. They're very very easy to make potions. I think they should all be nerfed.
About nourishment, they should be hard to make, so why does the buff reduce the amount you need to eat them to sustain hunger? Hard to make food is hard.

Hmm... I was expecting the inability to eat when full to control their powers. Is it really too overpowered to have a few short seconds of them? Because otherwise, I'm not quire sure what they could do instead.

The main problem with balancing foods for Minecraft is defeating the best food in the game: **Steak**.

Steak is extremely overpowered. You can quickly amass it, it heals enough hunger for most situations and compounds a lot of saturation. If a given meal is *worse* than Steak, players will just stick to it, since they already need to kill cows to get Leather for bookshelves. Sadly, I also agreed to not nerf any vanilla foods, since it angers players and coerces them into using your content, so it's a big looming threat on the mod's horizon. x)

The initial sentiment was for foods to do more than just fulfill hunger, such as tiny beneficial effects, or a longer-lasting improvement. What do you think the foods could apply instead? Should they, regardless of the above, just be normal foods without side effects?

> About the foods overall, i think that once you eat a type of food that grants youu buffs there should be a period before you can get that buff again. Eating 2-3 other food could reduce this timer.
> As for the food diversity, the spice of life carrot edition already gives you a reason to do this, not sure how to add to this, but maybe if you make/eat many different foods you get better at cooking, so you get more per craft?

It's a bit tough to attach more stats to players based on what they eat, and I'm not sure I'd like to intrinsically change the player's stats like that. Minecraft is very much about the items you hold, so permanent effects like that seem less interesting to me.

**Comment by vectorwing** [comment]
Finally, regarding Nourished: yeah, seems like it should have its length clamped. It's already great enough at just 4-5 minutes, it doesn't need to go all the way to 8. I might even play with situational exhaustion protection, perhaps.

**Comment by shattyyt** [comment]
> 
> 
> > Comfort I feel could be buffed to include the slower regen and damage over time reduction, but also keep it's pre-existing effects to not confuse people too much.
> 
> See, I feel that adding all of these to Comfort would be too much. Ideally, an effect should do one thing, not several different ones. With that said, making it a slow regen would quite literally be just worse regen, so I'm divided.
> 
> > The smaller foods with the short bursts of effects are super handy, however I have abused the salad's regen a ton in past survival worlds. Like a ton. Basically how I was able to survive both the ender dragon and wither fights.
> 
> Interesting take. It's good to see someone was testing these foods, as I entirely expected them to be sidestepped over meals due to how the design is working. Perhaps I underestimated Regeneration then; my idea was that it would be controlled by not being able to eat when you're at full hunger, but if you're taking damage, you _will_ immediately become hungry again anyway. Might take a look at it.
> 
> > About the finger food buffs, i really dislike them. They're very very easy to make potions. I think they should all be nerfed.
> > About nourishment, they should be hard to make, so why does the buff reduce the amount you need to eat them to sustain hunger? Hard to make food is hard.
> 
> Hmm... I was expecting the inability to eat when full to control their powers. Is it really too overpowered to have a few short seconds of them? Because otherwise, I'm not quire sure what they could do instead.
> 
> The main problem with balancing foods for Minecraft is defeating the best food in the game: **Steak**.
> 
> Steak is extremely overpowered. You can quickly amass it, it heals enough hunger for most situations and compounds a lot of saturation. If a given meal is _worse_ than Steak, players will just stick to it, since they already need to kill cows to get Leather for bookshelves. Sadly, I also agreed to not nerf any vanilla foods, since it angers players and coerces them into using your content, so it's a big looming threat on the mod's horizon. x)
> 
> The initial sentiment was for foods to do more than just fulfill hunger, such as tiny beneficial effects, or a longer-lasting improvement. What do you think the foods could apply instead? Should they, regardless of the above, just be normal foods without side effects?
> 
> > About the foods overall, i think that once you eat a type of food that grants youu buffs there should be a period before you can get that buff again. Eating 2-3 other food could reduce this timer.
> > As for the food diversity, the spice of life carrot edition already gives you a reason to do this, not sure how to add to this, but maybe if you make/eat many different foods you get better at cooking, so you get more per craft?
> 
> It's a bit tough to attach more stats to players based on what they eat, and I'm not sure I'd like to intrinsically change the player's stats like that. Minecraft is very much about the items you hold, so permanent effects like that seem less interesting to me.

instead of attaching stats you could attach effects like "Fed Up"?

**Comment by Jirlandez** [comment]
Think you should do 2 things to encourage people to eat a variety of foods. One negative and one positive. The negative would be the more you eat a single food, the less hunger shanks it will fill. The positive could give some passive effects like more saturation from foods. Also got this idea, what if some foods had innate effects? Basically the more after eating a variety of foods and reaching a certain threshold, some foods that don’t give effects will start giving effects like nourishing or strength but once you stop eating a variety those innate effects will go away. Maybe some foods require you eat a certain combo of foods to get past the threshold. Finger foods should def be shorter, sandwich’s could easily give strength for 5s which still might be too long. That’s all I can think of off the top of my head, sorry for being all over the place too lol

**Comment by hvdklauw** [comment]
| instead of attaching stats you could attach effects like "Fed Up"?
You would still need to track somewhere which food it was you are Fed up with. 
I like this idea, and if you then eat more of the same you get a nausia effect too maybe?

**Comment by vectorwing** [comment]
Adding negative or persistent changes to repetitive eating isn't a good option, IMO; it just further nags the player for "playing wrong", which causes more frustration than enjoyment. Plus, I have no idea how to actually code that. :P

Thinking more about it, perhaps forcing food diversity isn't the way to go. Instead, players could have reasons to "pick a different meal for X activity", even if they ultimately stick to just one: sidegrade benefits between food categories/flavors that are better than snacking on individual ingredients. There is the issue of balancing finger foods (stack to 64) against bowl foods (stack to 16) and the benefits involved, but I suppose the bowl foods could just generally be more nourishing in such case, or else things become too "tiered".

After further playtesting on a casual modded instance, I began eating more of the finger foods instead of nourishing meals to see how they handle; overall, they lasted long enough that I wasn't too bothered with frequent eating. It made me wonder even more if "selective exhaustion protection" could be a good idea. However, that has the added hurdle of finding a way to tell which exhaustion sources are happening to the player, which last time I checked, isn't viable without coremodding.

My current takeaways for a future balance update (subject to more changes):
- Make all Nourished foods last for a much shorter time: from 1-2 minutes to perhaps 4 at best;
- Think of something less intense for the salads to grant. I can't make them have good hunger points due to them being salads, but something else might be nice;
- Play with the idea of either custom effects or less impactful ones, such as Haste I (it never instamines stone) for carb-heavy meals, or swimming for seafood.

No idea what to do with Comfort yet, though. lol

**Comment by Mike-U5** [comment]
So a minor thing I would like to note is that certain foods provide less food points than their ingredients.
For example, chicken burgers and melon ice. It might be nice if every food gave at least as much nourishment as their ingredients.

**Comment by shattyyt** [comment]
Looking back on this, making a lesser effect is easy. Perhaps the salads could grant that. Like a heart every 4-5 seconds?

**Comment by Dradon7** [comment]
Just had this idea: What if comfort was a one hit high level resistance? So you eat a comfort food, you get comfort, and then the first time you take damage in the next minute (or however long the effect lasts), you take much less damage, and then the effect goes away. You eat soup, you feel comforted and relaxed around your base, but only until you get a wake up call from some cactus or a surprise hole.

**Comment by Kaligraphy22** [comment]
Hi there. I was listening to yorkmouseModz's spotlight on Farmer'a Delight just a minute ago (even though I've been using this mod for a while now). I also just completed a raid on an ocean monument and had the thought - the comfort buff currently blocks slowness, hunger and weakness. How about instead of weakness, it blocks mining fatigue?

**Comment by vectorwing** [comment]
>  How about instead of weakness, it blocks mining fatigue?

Considered at first, but given how it's used in vanilla, it would trivialize Ocean Monuments. :(

**Comment by vectorwing** [comment]
This discussion resulted in some positive changes, but it's gotten a bit stale. Also, GitHub opened a new **Discussions** feature I might start using instead, so I'm archiving this issue.

Thanks everyone for the good pointers!
