### ISSUE TITLE
Cutting board recipes not working for blocks

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#153]
First time using github, so i apologize if i'm doing something really obvious wrong. I tried to use a cutting board today on wood to get bark, but apparently it wasn't working. The axe refused to interact with the cutting board.I'm sorry if I'm missing something obvious. I will provide my latest.log here and my mod list. thanks you
<img width="620" alt="Screen Shot 2021-01-25 at 2 00 46 PM" src="https://user-images.githubusercontent.com/50085439/105771682-c8a2da80-5f15-11eb-8f4b-7b22725bf675.png">
[latest.log](https://github.com/vectorwing/FarmersDelight/files/5869933/latest.log)

**Comment by Lethosos** [comment]
Were you using Modded wood? The cutting board isn't currently set up for compat, so datapacks need to be added to support it. I have some on hand, since it looks like you are using the Abnormals mods. I'll put up a copy from my pack tonight for you, I suggest using Openloader to auto install for every world you make with your pack.

**Comment by thelegitdolt** [comment]
> Were you using Modded wood? The cutting board isn't currently set up for compat, so datapacks need to be added to support it. I have some on hand, since it looks like you are using the Abnormals mods. I'll put up a copy from my pack tonight for you, I suggest using Openloader to auto install for every world you make with your pack.

I'm pretty sure modded wood had worked before. I'm testing with vanilla woods right now.

Yeah, it worked, you were right. I tried it with a birch wood and it worked. Thank you.

**Comment by Lethosos** [comment]
Okay, no problem. It's been an interesting topic on the Discord about modded wood support.

**Comment by vectorwing** [comment]
Modded woods are kind of a can of worms, and in order for them to be strippable, manual recipes must be written for each one. So far we have integrations for MCAbnormals mods and IIRC Silent Gear, but there's a bunch more to go, I'm afraid.

If you have a mod that adds woods, you can suggest it for folks to integrate, or make a PR with your own .json files if you prefer. ^^

**Comment by Brun333rp** [comment]
so, auto-compatibility with modded logs and woods is not possible?
