### ISSUE TITLE
1.16.5 Chickens do not eat FD seeds.

### ISSUE THREAD

**Issue by The-Arcanian** [vectorwing/FarmersDelight#154]
**Description**
Chickens cannot be bread using FD seeds.

**Steps to reproduce:**
Try to feed a chicken a FD seed.

**Expected behavior:**
To be able to breed chickens with FD seeds.

**Mod list:**
Forge 36.0.1
AkashicTome-1.4-14
AppleSkin-mc1.16.2-forge-1.0.14
astralsorcery-1.16.4-1.13.9
AutoRegLib-1.6-47
BetterAdvancements-1.16.3-0.1.0.102
Botania-1.16.4-410
bwncr-1.16.4-3.9.16
ClientTweaks_1.16.3-5.2.0
cloth-config-forge-4.1.3
Clumps-6.0.0.13
Controlling-7.0.0.12
Corail-Recycler-NE-1.16.4-360
CraftingTweaks_1.16.3-12.2.0
create-mc1.16.3_v0.3e
curios-forge-1.16.4-4.0.3.3
DynamicSurroundings-1.16.4-4.0.3.5
FarmersDelight-1.16.3-0.3.1
FastFurnace-1.16.3-4.3.0
FastLeafDecay-v25
FastWorkbench-1.16.3-4.4.1
flatbedrock-1.16.4-1.1.6
ftb-gui-library-1604.1.1.26
HarderBranchMining-1.16.2-2.61.0.12
Hwyla-forge-1.10.11-B78_1.16.2
InventoryEssentials_1.16.3-2.2.0
InventoryHud_1.16.x.forge-3.1.4
inventorysorter-1.16.1-18.1.0
jei-1.16.4-7.6.1.65
jeiintegration_1.16.4-6.1.1.11
JustEnoughResources-1.16.3-0.12.0.100
mgui-1.16.4-3.1.3
minecolonies-0.13.581-ALPHA-universal
moreoverlays-1.18.11-mc1.16.4
morered-1.16.4-2.0.1.2
observerlib-1.16.4-1.5.1
Patchouli-1.16.4-48
Placebo-1.16.3-4.3.3
QuarkOddities-1.16.3
Quark-r2.4-297
SereneSeasons-1.16.4-4.0.0.86-universal
StorageDrawers-1.16.3-8.2.1
structurize-0.13.113-ALPHA-universal
Survive-1.16.5-3.1.2
swingthroughgrass-1.16.4-1.5.3
tellme-forge-1.16.4-0.9.1
tetra-1.16.4-3.5.3
tombstone-1.16-6.2.3
totaldarkness-1.2-1.16.3
UnionLib-1.16.5-3.2.3
voyage-1.16.4-1.0.3
WailaHarvestability-mc1.16.2-forge-1.1.13

**Comment by vectorwing** [comment]
This is a known limitation. To accomplish it, I would probably have to mixin the chicken entity directly, as it eats a hardcoded list of seeds composed of only vanilla ones.

This may be worked on someday, but for now there's not much I can do without being disruptive.

**Comment by Brun333rp** [comment]
well, I have two mods installed wich add new types of seeds: Druidcraft, wich adds Hemp Seeds, and Supplementaries, wich adds Flax Seeds, and both of them can be used to breed Chickens. 

Idk the limitation issues, but I bet that it would be possible to make Rice (both raw and cooked), Tomato Seeds and Cabbage Seeds usable to breed them.

**Comment by vectorwing** [comment]
They most likely use mixins to do it. If they accomplished it without problems, I might then check how they did it, depending on the code license.

**Comment by vectorwing** [comment]
Implemented on commit 9024613. 👍

**Comment by Brun333rp** [comment]
well, that's very good!
