### ISSUE TITLE
[1.16.4] Farmed Pumpkin doesn't make Lanterns or Iron Golems

### ISSUE THREAD

**Issue by FernCheese** [vectorwing/FarmersDelight#155]
**Description**
The pumpkin doesn't act as a pumpkin in recipes.

**Steps to reproduce:**
I am in normal difficulty survival mode. I discovered this issue when I tried to make an Iron Golem in the middle of a village. I then tried to make a Jack O' Lantern unsuccessfully. I have not tested other pumpkin recipes. Switching to creative did not solve the issue. I have not tried making a new world in survival and using the pumpkin.

**Expected behavior:**
I expected to make an Iron Golem upon placing the pumpkin on the Blocks of Iron. I expected to made a Lantern using a torch.

**Screenshots**
![image](https://user-images.githubusercontent.com/78076139/105968512-161a7580-60d7-11eb-9d4c-29b2201b7431.png)
![image](https://user-images.githubusercontent.com/78076139/105968672-4a8e3180-60d7-11eb-8acd-63e472b92345.png)

**Mod list:**
  [✔️] Aquaculture-1.16.4-2.1.11
  [✔️] AutoRegLib-1.6-47 (1)
  [✔️] BetterMineshafts-Forge-1.16.3-1.1.1
  [✔️] Bookshelf-1.16.4-9.3.18 (1)
  [✔️] BotanyPots-1.16.4-6.0.13
  [✔️] carrotslib-mc1.16.4-3.0b1
  [✔️] chiselsandbits-0.2.8-RELEASE
  [✔️] CraftableHorseArmour-1.16.X-1.4.0
  [✔️] DoggyTalents-1.16.4-2.0.1.2
  [✔️] DoubleSlabs-1.16-3.4.10
  [✔️] FarmersDelight-1.16.3-0.3.1
  [✔️] FarmingForBlockheads_1.16.3-7.2.1
  [✔️] FastLeafDecay-v25
  [✔️] furniture-7.0.0-pre19-1.16.3
  [✔️] GeneticAnimals-0_6_5
  [✔️] horse_colors-1.16.4-1.5.2
  [✔️] Horse-Carts-Mod-1.16.4
  [✔️] jei-1.16.4-7.6.0.62
  [✔️] mcw-bridges-1.0.4-mc1.16.4
  [✔️] mcw-doors-1.0.1fix-mc1.16.4
  [✔️] mcw-furniture-2.0.0-mc1.16.3
  [✔️] mcw-windows-1.0.2-mc1.16.4
  [✔️] Patchouli-1.16.4-48
  [✔️] Quark-r2.4-283 (1)
  [✔️] RealisticTorches-1.16.4-3.1.0
  [✔️] SereneSeasons-1.16.4-4.0.0.86-universal
  [✔️] StorageDrawers-1.16.3-8.2.1
  [✔️] TerraForged-1.16.4-0.2.0-BETA-7
  [✔️] vanillafoodpantry-mc1.16.4-6.0b1

**Comment by ochotonida** [comment]
The issue seems to be that you're using a regular pumpkin instead of a carved pumpkin. (Farmer's Delight doesn't make any changes to pumpkin farming as far as I'm aware)

**Comment by vectorwing** [comment]
Yup. You're supposed to carve these pumpkins to use them like that. It's been a long time since grown pumpkins generated carved. 😄

While FD changes nothing about pumpkins, you can use both shears and knives against pumpkins to carve them. Good luck!
