### ISSUE TITLE
1.16.4 Hot Coco Recipie is gone. 

### ISSUE THREAD

**Issue by Oriansenshi** [vectorwing/FarmersDelight#156]
My server recently updated its forge version from 35.1.32 to 35.1.37 and we updated our farmers delight version from 0.2.4 to 0.3.1  and my players noticed that the hot coco recipe is gone. This is troublesome for us because we use the survive mod, and we use the hot coco drink as one of the most common sources of the warmth effect. did i do something wrong with updating the server? or should i try rolling back to farmers delight 0.3?

**Comment by vectorwing** [comment]
It it just not showing on JEI, or are you unable to prepare Hot Cocoa at all?

![image](https://user-images.githubusercontent.com/5566692/106037051-e8243980-60b4-11eb-8765-707a25b89faf.png)

In either case, please send me the server logs, and a user's client logs if possible. You can fill up the Bug Report template to do so, it helps a lot.

**Comment by Oriansenshi** [comment]
we just tried to craft it, and it does craft just fine, but when they drink it, they dont get any of the effects of it. It normally gives comfort correct? the other stuff might be on the survive mod end of things, i will check the server settings on that.

**Comment by Oriansenshi** [comment]
i just checked the wiki, and i believe i have figured it out. it doesnt give comfort, but it removes a random potion effect. This is probably an issue with the survive mod, then. It is probably giving the warmed effect and then instantly removing it. Sorry to bother you.

**Comment by vectorwing** [comment]
No worries! Glad to know things are working. 👍
