### ISSUE TITLE
[1.16.5] FD Crashes

### ISSUE THREAD

**Issue by Quizer9O8** [vectorwing/FarmersDelight#160]
**Description**
FarmersDelight crashes Minecraft right after finishing up loading everything

**Steps to reproduce:**
Launch Minecraft with FD 0.3.1

**Expected behavior:**
An error message should appear.

**Screenshots**
Log: https://mcpaste.io/042957b2a837d5ee
![afbeelding](https://user-images.githubusercontent.com/19509275/106271678-2eea6e80-6230-11eb-9a73-ac41fae0a787.png)

**Mod list:**
FarmersDelight-1.16.3-0.3.1 / Forge 36.0.0

**Comment by ConductiveFoam** [comment]
From the log it seems that you're using Java 15, which is not supported by Forge. Please try again with Java 8

**Comment by Quizer9O8** [comment]
Hmmm, that's odd. I was certain I set to use Java 8 instead.
Anyways I changed the pathing directory towards `D:/Java/jre.1.8.0_281/bin/javaw.exe`
Which seems to have solved the problem.
