### ISSUE TITLE
Cooking Pot not showing GUI for one player on server

### ISSUE THREAD

**Issue by mastermokkel** [vectorwing/FarmersDelight#170]
**Description**
When right-clicking on the cooking pot, I can't open the GUI. It had been working earlier, and is still working for other players. I have tried relogging, removing all my items before dying, restarting the server and deleting my playerdata folder in the server.

**Steps to reproduce:**
I equipped a Quark backpack, which none of the other players have done yet - no clue if it's related, but I guess anything helps. I didn't use the cooking pot for a few days before or after that though.

**Expected behavior:**
Opening the GUI of the cooking pot and cooking some delicious meals 🥴 

**Mod list:**
forge-1.16.4-35.1.36-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2        |DONE      |NOSIGNATURE
		QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3              |DONE      |NOSIGNATURE
		repurposed_structures-1.16.4-2.3.4.jar            |Repurposed Structures         |repurposed_structures         |1.16.4-2.3.4        |DONE      |NOSIGNATURE
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |NOSIGNATURE
		MouseTweaks-2.13-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.13                |DONE      |NOSIGNATURE
		NetherPortalFix_1.16.3-7.2.1.jar                  |NetherPortalFix               |netherportalfix               |7.2.1               |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.431-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.431   |DONE      |NOSIGNATURE
		thatched-1.16.4-0.3.jar                           |Thatched Roof Villages        |thatched                      |version             |DONE      |NOSIGNATURE
		dungeons_plus-1.16.4-1.1.2.jar                    |Dungeons Plus                 |dungeons_plus                 |1.1.2               |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.66.jar                           |Just Enough Items             |jei                           |7.6.1.66            |DONE      |NOSIGNATURE
		OptiForge-MC1.16.4-0.4.6.jar                      |OptiForge                     |optiforge                     |0.4.6               |DONE      |NOSIGNATURE
		dungeons_mobs-1.16.4-1.0.3.jar                    |Dungeons Mobs                 |dungeons_mobs                 |1.0.3               |DONE      |NOSIGNATURE
		abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
		upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
		savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |DONE      |NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		Clumps-6.0.0.13.jar                               |Clumps                        |clumps                        |6.0.0.13            |DONE      |NOSIGNATURE
		XaerosWorldMap_1.11.10_Forge_1.16.5.jar           |Xaero's World Map             |xaeroworldmap                 |1.11.10             |DONE      |NOSIGNATURE
		Xaeros_Minimap_FP21.1.0_Forge_1.16.5.jar          |Xaero's Minimap Fair-Play     |xaerominimapfair              |21.1.0              |DONE      |NOSIGNATURE
		FastWorkbench-1.16.4-4.5.0.jar                    |FastWorkbench                 |fastbench                     |4.5.0               |DONE      |NOSIGNATURE
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |DONE      |NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.5.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.5.0               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
		performant-1.16.2-4-3.30m.jar                     |Performant                    |performant                    |3.30m               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |NOSIGNATURE
		decorative_blocks_abnormals-1.16.4-1.1.jar        |Decorative Blocks Abnormals   |decorative_blocks_abnormals   |1.1                 |DONE      |NOSIGNATURE
		endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
		starterkit_1.16.4-2.1.jar                         |Starter Kit                   |starterkit                    |2.1                 |DONE      |NOSIGNATURE
		randompatches-2.3.0-forge.jar                     |RandomPatches                 |randompatches                 |2.3.0-forge         |DONE      |92:f6:29:d4:09:89:f5:f5:98:5e:20:34:31:d0:7b:58:22:06:bd:a5:d1:6a:92:6e:ac:3d:8d:18:c5:b2:5b:d7
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |DONE      |NOSIGNATURE
		JEITweaker-1.16.5-1.0.1.11.jar                    |JEI Tweaker                   |jeitweaker                    |1.0.1.11            |DONE      |NOSIGNATURE
		durabilityviewer-1.16.4-forge35.0.7-1.10.jar      |Giselbaers Durability Viewer  |durabilityviewer              |1.16.4-forge35.0.7-1|DONE      |NOSIGNATURE
		CraftTweaker-1.16.5-7.1.0.110.jar                 |CraftTweaker                  |crafttweaker                  |7.1.0.110           |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.36-universal.jar                |Forge                         |forge                         |35.1.36             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Quark-r2.4-302.jar                                |Quark                         |quark                         |r2.4-302            |DONE      |NOSIGNATURE
		QuarkOPlenty-1.16.5-1.0.4.jar                     |Quark O' Plenty               |quarkoplenty                  |1.0.4               |DONE      |NOSIGNATURE
		cofh_core-1.16.3-1.1.6.jar                        |CoFH Core                     |cofh_core                     |1.1.6               |DONE      |NOSIGNATURE
		ensorcellation-1.16.3-1.1.2.jar                   |Ensorcellation                |ensorcellation                |1.1.2               |DONE      |NOSIGNATURE
		toms_storage-1.2.11.jar                           |Tom's Simple Storage Mod      |toms_storage                  |1.2.11              |DONE      |NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |DONE      |NOSIGNATURE
		dash-1.16.4-1.0.1.jar                             |Dash                          |dash                          |1.0.1               |DONE      |NOSIGNATURE
		structure_gel-1.16.4-1.7.5.jar                    |Structure Gel API             |structure_gel                 |1.7.5               |DONE      |NOSIGNATURE

**Comment by vectorwing** [comment]
Please submit your client logs from when you attempted to right-click the pot. Usually there will be an error popping up. Also, if your server owner can get them, send the server logs too.

**Comment by vectorwing** [comment]
Hello, @mastermokkel! Has the issue resolved, or is it still happening?

**Comment by vectorwing** [comment]
I'll be closing the issue, as it's become stale. Feel free to reopen it with the info I requested above, if you can.
