### ISSUE TITLE
[1.16.4] Cooking Pots don't have a recipe book to view the available recipes, unlike other work stations

### ISSUE THREAD

**Issue by Brun333rp** [vectorwing/FarmersDelight#171]
I don't know if this is intended, but unlike other work stations, Cooking Pots don't have a recipe book to view the available recipes, wich is inconsistent with vanilla Minecraft.

**Comment by vectorwing** [comment]
Integration with Minecraft's Recipe Book is desired, as stated in our Discord FAQ; however, that interface is hardcoded to work only on crafting tables and furnaces. Without certain PRs to Forge (or a lot of mixins), I'm unable to implement it for now.

**Comment by Brun333rp** [comment]
oh, that's sad :(
