### ISSUE TITLE
[1.16.5] Request - Config to allow cooking pots to spawn in worldgen

### ISSUE THREAD

**Issue by Alaberti** [vectorwing/FarmersDelight#173]
Just an idea for a "breath of the wild" inspired config option to see cooking pots out in the wild, over a campfire.

**Comment by vectorwing** [comment]
You know, this ain't a bad idea... I had plans to spawn filled pots as dungeon loot (a bit thwarted by a lack of access ease for loot injection), but if kept very light, it could be fun to find "campsites" now and then.

I played briefly with the concept. Though this isn't a promise, the idea is nice. Will keep it in mind!
![image](https://user-images.githubusercontent.com/5566692/107589276-69ff8100-6be4-11eb-9f0b-50d0f8fcd154.png)

**Comment by Alaberti** [comment]
*insert cautiously optimistic fist pump here*

**Comment by vectorwing** [comment]
I'm cleaning up the issues board, and closing "suggestion" issues for the time being. If you'd like to continue this idea, please reopen it on the new **Discussions** page; that's where suggestions should be posted from now on. 👍
