### ISSUE TITLE
[1.16.5] Missing crop block localization

### ISSUE THREAD

**Issue by ChloeDawn** [vectorwing/FarmersDelight#175]
**Description**
Crop blocks are missing localization

**Steps to reproduce:**
- Use a mod that expects block name localization (e.g Botanty Pots)
- See the raw translation key

**Expected behavior:**
Localized block names

**Screenshots**

![Screenshot of a botany pot with an unlocalized crop block](https://i.imgur.com/pnrzOkA.png)

**Mod list:**
- Forge 1.16.5-36.0.15
- Farmer's Delight 1.16.3-0.3.2

**Comment by vectorwing** [comment]
Nice catch. I just assumed they never showed up anywhere.
Commit bb6a31b fixes it for the languages I understand! 👍
