### ISSUE TITLE
[1.16.3] The Cooking Pot doesn't grant experience for recipes that supposedly grant it

### ISSUE THREAD

**Issue by eutro** [vectorwing/FarmersDelight#182]
**Description**
The Cooking Pot doesn't grant experience for recipes that supposedly grant it.

[CookingPotRecipe#getExperience()](https://github.com/vectorwing/FarmersDelight/blob/4732bd7d3825541fb7af2bf5fa985432060d112b/src/main/java/vectorwing/farmersdelight/crafting/CookingPotRecipe.java#L84) isn't referenced anywhere else, thus it appears the system is unimplemented.

**Steps to reproduce:**
1. Add an experience-granting recipe to the Cooking Pot using a data pack, or CraftTweaker (#181).
2. Craft the recipe.
3. Take out recipe outputs.
4. Experience disappointment at the lack of experience gained.

**Expected behavior:**
Taking out the result at the end grants experience to the player.

**Mod list:**
| Mod                          | Version            |
|----------------------------|---------------------|
| Farmer's Delight       | 1.16.3-0.3.2 #181 |
| Forge                        | 1.16.3-34.1.42 |
| JEI-1.16.3                 | 7.6.0.49           |
| CraftTweaker-1.16.3 | 7.0.0.48           |

**Comment by vectorwing** [comment]
Yeah... that `getExperience()` is currently a leftover.

I wasn't sure how experience storage and spawning worked on recipes yet, so I left it out of the Cooking Pot. But it would make sense for it to grant experience, and would incentivize cooking. I'll mark it as an enhancement.

**Comment by vectorwing** [comment]
Implemented on commit 08af9c0, as an upcoming feature. 👍
