### ISSUE TITLE
[1.16.5] [Enhancement] Give Cooking Pot Recipe Outputs NBT Data

### ISSUE THREAD

**Issue by Dradon7** [vectorwing/FarmersDelight#184]
I don't know how feasible this is, or how invasive of a change this would take, but it would be nice to be able to craft suspicious stew with potion effects in the cooking pot. I'm sure there's other uses to it as well, but that's pretty much what I'm after.

BTW, this is by far my favorite food mod. Keep up the great work!

**Comment by ConductiveFoam** [comment]
Seems not invasive at all, let's hope it gets merged :)

**Comment by vectorwing** [comment]
Merged! 👍
