### ISSUE TITLE
[1.16.4] Rice Duplication

### ISSUE THREAD

**Issue by Kavrrin** [vectorwing/FarmersDelight#188]
right clicking a fully grown rice plant with something in hand will duplicate the product endlessly. right clicking with an empty hand simply harvests it. easy to replicate and avoid, but just figured i'd make it known.

example video: https://youtu.be/JnV4-mUwLgk

also attached is current modlist in case of any unknown incompatibilities. 
![940e23af465b0e05d7b0f0bf9e219e7c](https://user-images.githubusercontent.com/35414606/108014372-b62f3480-6fdb-11eb-9c8c-dbd2ca802bd6.png)

**Comment by vectorwing** [comment]
Thank you for including a video. 👍

Yeah... that is most certainly _not_ an FD issue, as none if its crops have right-click interactions except for Tomatoes. This might be caused by either Quark or some other simple-harvest mod interfering with that interaction.

Is there anything being spammed in the logs? Also, if you can, try making a minimal instance with FD and whichever mods implement right-click harvest (e.g. Quark).

**Comment by Kavrrin** [comment]
just tried it with just FD, quark, and quark's dependency and (surprisingly) the rice seems unaffected? im gonna try to narrow this down a bit but i dont think its quark actually

**Comment by Kavrrin** [comment]
clarification: quark didn't reproduce the dupe affect but it DID allow me to right click harvest with something in hand, which is weird

**Comment by vectorwing** [comment]
That's expected; Quark introduces simple harvesting as one of its modules, and it can be done even with items on hand (you can even right-click using knives!). If both mods alone couldn't replicate the dupe, there must be another messing things up.

**Comment by Kavrrin** [comment]
OFFENDING MOD FOUND! sadly its a set of mods ive loved for a very long time, the Pam's Harvestcraft series. HOWEVER, there is an option to turn off her mod's version of right click harvesting in the pamhc2crops config under the misc features. doing so completely fixes the dupe. sorry to bother you, but other users with the same mods will need to disable this (might even fix that one onion harvesting bug too, im not sure)

![7bffdd329f0af7f709c867127a6419c4](https://user-images.githubusercontent.com/35414606/108020649-cef31680-6fea-11eb-97a1-c0819cb968c0.png)

**Comment by vectorwing** [comment]
That's okay! Glad you found out the cause of the issue. 😄

Might be worthwhile checking Harvestcraft's issue tracker and report it there, if no one else did; perhaps something is conflicting between their implementations, and you might have better info to help them now.

**Comment by copygirl** [comment]
As a side-note I found this also happens with the "Instant Pickup" feature of Fabrication, when using shears on Wild Rice.
