### ISSUE TITLE
[1.16.3] Obtaining brown mushroom colony?

### ISSUE THREAD

**Issue by beanboysprite** [vectorwing/FarmersDelight#192]
The recipe for a stuffed pumpkin requires a brown mushroom colony, but I'm unable to get the whole colony. I've been growing the colonies on rich soil in the dark, and I can shear them to get brown/red mushrooms from their respective colonies. I've tried using silk touch tools, left clicking with shears, and using a knife, but they all give me the small mushrooms. The small brown mushrooms can't be used in place of the brown mushroom colony either in the cooking pot recipe.

**Comment by vectorwing** [comment]
Mushroom Colonies can be harvested whole by **breaking** them with shears, once they're fully mature (5 caps). Right-clicking will clip off the caps.

**Comment by vectorwing** [comment]
I'll be closing the issue due to being stale. If the method above isn't working, feel free to reopen.
