### ISSUE TITLE
1.16.5 Mod interaction issue.

### ISSUE THREAD

**Issue by mikeskey** [vectorwing/FarmersDelight#195]
**Description**
This mod changes the standard drops from the Water Strainer Fisherman's Strainer (All 3) and replaces them with only farmer's delight drops. This shouldn't be happening as there is no way to get fish with both mods installed other than by using the fishing pole. The drops from farmers delight should be in addition to the standard drops of fish and other items...not a complete replacement.

**Steps to reproduce:**
Install Farmers delight 1.16.3-0.3.2 mod as well as Water Strainer mod 1.16.3-10.0.0.

**Expected behavior:**
Farmers delight crop drops need to be an addition to the strainer drops not a replacement.

**Comment by vectorwing** [comment]
FD doesn't do anything to change Fisherman loot tables, let alone that of different mods. The only thing it does is inject a new loot pool into chests at Village Houses, which preserves existing loot pools from vanilla and other mods as well. I'm not sure what could be the cause beyond a strange modpack change or interaction, and I can't seem to find the developer's repo to check.

Is anything funny showing up in the logs? Please fill out the bug report with your logs and your full mod list.

**Comment by vectorwing** [comment]
This issue has gotten a bit stale. I'll close it for now, but feel free to reopen with the details I requested above, when you can.
