### ISSUE TITLE
[1.16.5] Tatami Block/Mat Orientation Issues

### ISSUE THREAD

**Issue by SynfulChaot** [vectorwing/FarmersDelight#199]
**Description**
Non-connected Tatami Blocks and Single Tatami Mats are always oriented in the same direction and cannot be rotated.

**Steps to reproduce:**
Place Tatami Blocks or a mix of Single and Full Tatami Mats in both a North-South and West-East configuration.

**Expected behavior:**
When placing Tatami Blocks and Mats in a North-South orientation I expected the non-connected Tatami Blocks and Single Tatami Mats to be able to be oriented in such a way to match the visual tiling of the connected Tatami Blocks and Full Tatami Mats.

**Screenshot**
![2021-02-21_17 00 15](https://user-images.githubusercontent.com/8399891/108640319-f3c21080-7466-11eb-8732-11f88fe9f05e.png)

**Other Notes**
A side effect of how the Tatami Blocks are placed to form the connected double block appearance prevents them from being used with blocks like Botania's Abstruse Platform due to having to place the blocks against the side of an existing Tatami Block to gain the tiled appearance.  By comparison the similar Bamboo Mat from Quark gains its orientation from where it is placed against the ground, allowing you to not only tile them in any cardinal direction but also allows the Abstruse Platform to pick up the tiled appearance instead of only the non-connected appearance.

**Mod list:**
```
QuarkOddities-1.16.3.jar                          |Quark Oddities                |quarkoddities                 |1.16.3
jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62
CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6
SereneSeasons-1.16.4-4.0.0.80-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.4-4.0.0.76
forge-1.16.5-36.0.13-universal.jar                |Forge                         |forge                         |36.0.13
forge-1.16.5-36.0.13-client.jar                   |Minecraft                     |minecraft                     |1.16.5
FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2
Botania-1.16.4-411.jar                            |Botania                       |botania                       |1.16.4-411
Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48
Quark-r2.4-300.jar                                |Quark                         |quark                         |r2.4-300
```

**Comment by vectorwing** [comment]
I suppose the single mats could have a rotation. At first they didn't because it still seemed to look good, but making them orient isn't hard at all. Gonna mark it on the to-do.

As for the Abstruse Platform, I'm not quite sure how to properly fix it, since you're never meant to be able to place an incomplete half. Quark's Straw Mats don't have an unconnected form, so they always place as half of a pair, while FD's Tatami can only pair when placed against another unconnected Tatami. Shift-click already suppresses connection, so not sure how to go about it.

**Comment by SynfulChaot** [comment]
Quark's Straw Mats *do* have an unconnected form if you target near the center of the block you place them on.  It's only if you target near the edge of the block that they place an 'incomplete half' as you put it.

**Comment by vectorwing** [comment]
Ah, didn't know that. Quite clever!

Anyway, as I explained on Discord, I faced a limitation when changing the way an unpaired Tatami Block is placed, so it can only be rotated after being paired and unpaired again.

Other than that, the other changes were quite easy, and should be up on the next version. 👍
