### ISSUE TITLE
[Suggestion] Food Effects in tooltip

### ISSUE THREAD

**Issue by Mike-U5** [vectorwing/FarmersDelight#202]
I'd be helpful if food with special effect would show what effect it gives in it's tooltip.
It could be similar to the way potions display their effects in the tooltip.

**Comment by vectorwing** [comment]
Although vanilla foods don't have it, it does sound interesting. Potions already set that precedent anyway... I might take a look sometime.

**Comment by SynfulChaot** [comment]
Vanilla foods don't have it because they widely don't _have_ special effects.  I think it would definitely result in more people gravitating towards the foods due to more awareness.

**Comment by vectorwing** [comment]
Some do, such as Golden Apples, Pufferfish and Suspicious Stew. Though the latter two are meant to be a surprise deal.

**Comment by vectorwing** [comment]
This has been implemented to a small degree, in upcoming drink items. Not sure about foods, but we'll see!
