### ISSUE TITLE
[1.16.5] Placing cooking pot crashes my game

### ISSUE THREAD

**Issue by SadScourge** [vectorwing/FarmersDelight#205]
**Description**
Placing cooking pot crashes my game

**Steps to reproduce:**
Putting the block anywhere by hand/or by a dispenser

**Expected behavior:**
The block should appear and not make the game crash

**Logs**
https://pastebin.com/ci7Ycxvs

**Mod list:**
forge-1.16.5-36.0.42-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
FarmersDelight-1.16.3-0.3.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.3.2        |DONE      |NOSIGNATURE
delicateanddainty-0.1.4-1.16.4.jar                |Delicate and Dainty!          |delicateanddainty             |0.1.4-1.16.4        |DONE      |NOSIGNATURE
customizableelytra-1.16.4-1.2.0.jar               |Customizable Elytra           |customizableelytra            |1.2.0               |DONE      |NOSIGNATURE
swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |NOSIGNATURE
MouseTweaks-2.14-mc1.16.2.jar                     |Mouse Tweaks                  |mousetweaks                   |2.14                |DONE      |NOSIGNATURE
mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
jei-1.16.4-7.6.1.71.jar                           |Just Enough Items             |jei                           |7.6.1.71            |DONE      |NOSIGNATURE
jei-professions-1.0.0-1.16.4.jar                  |JEI Professions               |jeiprofessions                |1.0.0               |DONE      |NOSIGNATURE
fish_in_planks-1.16.5-0.3.jar                     |Fish in Planks                |fish_in_planks                |1.16.5-0.3          |DONE      |NOSIGNATURE
abnormals_core-1.16.4-3.0.6.jar                   |Abnormals Core                |abnormals_core                |3.0.6               |DONE      |NOSIGNATURE
buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |DONE      |NOSIGNATURE
berry_good-1.16.4-4.0.0.jar                       |Berry Good                    |berry_good                    |4.0.0               |DONE      |NOSIGNATURE
cookielicious-1.16.5-1.2.1.jar                    |Cookielicious                 |cookielicious                 |1.2.1               |DONE      |NOSIGNATURE
Jellyfishing-1.6.9.jar                            |Jellyfishing                  |jellyfishing                  |1.6.8               |DONE      |NOSIGNATURE
farmersdelightintegration-1.16.5-1.0.2.jar        |Farmer's Delight Integration  |farmersdelightintegration     |1.16.5-1.0.2        |DONE      |NOSIGNATURE
atmospheric-1.16.4-3.0.0.jar                      |Atmospheric                   |atmospheric                   |3.0.0               |DONE      |NOSIGNATURE
upgrade_aquatic-1.16.5-3.0.1.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.0.1               |DONE      |NOSIGNATURE
jeiintegration_1.16.5-7.0.1.15.jar                |JEI Integration               |jeiintegration                |7.0.1.15            |DONE      |NOSIGNATURE
extraboats-1.16.5-2.1.0.jar                       |Extra Boats                   |extraboats                    |2.1.0               |DONE      |NOSIGNATURE
savageandravage-1.16.4-3.0.0.jar                  |Savage & Ravage               |savageandravage               |3.0.0               |DONE      |NOSIGNATURE
BetterCaves-Forge-1.16.4-1.1.1.jar                |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.1        |DONE      |NOSIGNATURE
WeaponThrow-1.16.4-4.2.jar                        |Weapon Throw                  |weaponthrow                   |1.16.4-4.2          |DONE      |NOSIGNATURE
Clumps-6.0.0.17.jar                               |Clumps                        |clumps                        |6.0.0.17            |DONE      |NOSIGNATURE
autumnity-1.16.4-2.0.1.jar                        |Autumnity                     |autumnity                     |2.0.1               |DONE      |NOSIGNATURE
citadel-1.6.1.jar                                 |Citadel                       |citadel                       |1.6.1               |DONE      |NOSIGNATURE
alexsmobs-1.6.0.jar                               |Alex's Mobs                   |alexsmobs                     |1.6.0               |DONE      |NOSIGNATURE
AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |DONE      |NOSIGNATURE
YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
mightyarchitect-mc1.16.3_v0.5.jar                 |The Mighty Architect          |mightyarchitect               |0.5                 |DONE      |NOSIGNATURE
simplytea-1.16.5-2.3.4.jar                        |Simply Tea                    |simplytea                     |2.3.4               |DONE      |NOSIGNATURE
fantasy-forge-1.1.1.jar                           |Fantasy Mounts                |fantasy                       |1.0                 |DONE      |NOSIGNATURE
Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
BedBenefits-1.16.5-5.0.3.jar                      |BedBenefits                   |bedbenefits                   |5.0.3               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
endergetic-1.16.4-3.0.0.jar                       |The Endergetic Expansion      |endergetic                    |3.0.0               |DONE      |NOSIGNATURE
cfm-7.0.0-pre19-mc1.16.3.jar                      |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |NOSIGNATURE
architectury-1.7.117-forge.jar                    |Architectury                  |architectury                  |1.7.117             |DONE      |NOSIGNATURE
ftb-gui-library-1605.2.1.39-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.39         |DONE      |NOSIGNATURE
mountedpearl-1.16.3-1.0.0.jar                     |Mounted Pearl                 |mountedpearl                  |1.16.3-1.0.0        |DONE      |1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
dads_sewing-6.0.jar                               |Dad's Sewing                  |dads_sewing                   |6.0                 |DONE      |NOSIGNATURE
forge-1.16.5-36.0.42-universal.jar                |Forge                         |forge                         |36.0.42             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
Bountiful-1.16.4-3.3.0.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.0        |DONE      |NOSIGNATURE
Quark-r2.4-306.jar                                |Quark                         |quark                         |r2.4-306            |DONE      |NOSIGNATURE
AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
MmmMmmMmmMmm-1.16-1.0.1.jar                       |MmmMmmMmmMmm                  |dummmmmmy                     |1.0.1               |DONE      |NOSIGNATURE
scuba-gear-1.16.5-1.0.2.jar                       |Scuba Gear                    |scuba_gear                    |1.0.2               |DONE      |NOSIGNATURE
supplementaries-1.16.5-0.9.27.jar                 |Supplementaries               |supplementaries               |1.16.5-0.9.27       |DONE      |NOSIGNATURE
BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
neapolitan-1.16.4-2.0.1.jar                       |Neapolitan                    |neapolitan                    |2.0.1               |DONE      |NOSIGNATURE

**Comment by ConductiveFoam** [comment]
I am unable to reproduce this with just Farmer's Delight. Can you reduce your mod list? Are you using a pack?

**Comment by SadScourge** [comment]
Ok i found out which mod makes the game crash, it is farmer's delight integrations and this is doesn't make sense since it's an addon for farmer's.
You can reproduce the bug with the following mods:
abnormals_core-1.16.4-3.0.6.jar
FarmersDelight-1.16.3-0.3.2.jar
farmersdelightintegration-1.16.5-1.0.2.jar
endergetic-1.16.4-3.0.0.jar

**Comment by ConductiveFoam** [comment]
Thanks for narrowing it down, I'll have a look.

**Comment by Meghan92** [comment]
I can confirm that this is farmers integration causing the break

**Comment by vectorwing** [comment]
Please report the issue to their repository, if you can, to help them find the cause.
