### ISSUE TITLE
cooking pot and cutting board mod support

### ISSUE THREAD

**Issue by 0Navis0** [vectorwing/FarmersDelight#210]
- Cutting Board
    - Biomes O Plenty
        - fir wood
        - redwood
        - cherry wood
        - mahogany wood
        - jacaranda wood
        - palm wood
        - willow wood
        - dead wood
        - magic wood
        - umbran wood
        - hellbarck wood
    - Tinkers Construct
        - greenheart wood
        - skyroot wood
        - bloodshroom wood
    - Quark
        - stained wood
    - Botania
        - livingwood
        - dreamwood
        - shimerwood
    - Astral Sorcery
        - infused wood
    - Outer End
        - azure wood
- Cooking Pot
    - Inspirations
        - potato soup
    - Thermal
        - perspicacious stew
    - Fins and Tails
        - seafood soup

**Comment by Dradon7** [comment]
I think its safe to close this issue, mostly because abnormals delight exists and adds compat for about half that list. I know theres a mod that adds simply tea compat. Compat with 90% of those mods can be fixed with a datapack. The only downside to a datapack is that it can't make new pantry items/blocks for modded wood types and it can't make new cake/pie slice items for modded cakes/pies.
EDIT: spelling

**Comment by Hypsellis** [comment]
Yeah I know that Farmers Delight and Abdnormal Delight added a lot of missing compatibility. I didn't get the time yet to look again on the missing compatibility. I will update this issue soon when I will get the time. ;)

**Comment by 0Navis0** [comment]
I just updated this issue with a more detailed list. I also made more detailed list for other mods if it interests you.
https://github.com/KnightMiner/Inspirations/issues/204
https://github.com/svenhjol/Covalent/issues/6

**Comment by 0Navis0** [comment]
By the way I'm unsure if it's a good and coherent idea to be able to cut brick and clay on the cutting board, it should be used only for wood and food.

**Comment by vectorwing** [comment]
> By the way I'm unsure if it's a good and coherent idea to be able to cut brick and clay on the cutting board, it should be used only for wood and food.

The Cutting Board plays a little on the absurdity of Minecraft's workstations, doubling down on extra features.

Imagine it being like a stump or wood block, against which you strike an object to break it apart. Plus, striking wood isn't that different in impact from chipping off bricks from mortar and such.

**Comment by 0Navis0** [comment]
The rock and brick crafting should be kept to the furnace, kiln, and stonecutter. It would prevent you to have to support more blocks as well. Other wood blocks should be supported as well like planks, stairs, slabs, fences, fence gates, pressure plates, and buttons.

**Comment by vectorwing** [comment]
I'm cleaning up the issues board, and closing "suggestion" issues for the time being. If you'd like to continue this idea, please reopen it on the new **Discussions** page; that's where suggestions should be posted from now on. 👍
