### ISSUE TITLE
Using a bowl on a cooking pot with a full inventory deletes it, along with the food.

### ISSUE THREAD

**Issue by Luigipunch** [vectorwing/FarmersDelight#211]
When there is cooked food in a cooking pot and no bowl, the stored food that is in it is deleted when a bowl is used on the block, along with the bowl itself. This only occurs with a full inventory.

**Comment by vectorwing** [comment]
Fixed on commit 538bda5, though only on Survival mode, since the Creative method to add stacks always returns true. Will take a look some more later.
