### ISSUE TITLE
[1.16.5] Cooking Pot crashes your game when placed

### ISSUE THREAD

**Issue by StealthyCqts** [vectorwing/FarmersDelight#214]
When you place the cooking pot, the game closes

AL lib: (EE) alc_cleanup: 1 device not closed
does this help?

The mods we are using are:
Autumnity, environmental, endergetic, enhanced mushrooms, extra boats, more minecarts, more respawn anchors, buzzier bees, ensorcellation, alexs-mobs, farmers delight, farmers tea, farmers delight integration

Im using the GDLauncher if that is important

**Comment by vectorwing** [comment]
Sorry, this is a duplicate issue; Farmer's Delight Integration currently has a bug that causes the pot to crash due to unbound tags. I believe the dev is aware of it now. 👍
