### ISSUE TITLE
Vanilla Cooking Pot foods should stack to 16

### ISSUE THREAD

**Issue by Kisutora** [vectorwing/FarmersDelight#215]
Shouldn't Mushroom Stew, Rabbit Stew and Beetroot Soup stack to 16 to make them match with Farmer's Delight foods and make them useable too?
![image](https://user-images.githubusercontent.com/22685232/109546237-949d7500-7ad2-11eb-8190-50afbd74d4a1.png)

**Comment by vectorwing** [comment]
You missed a recent PR from @bageldotjpg that did exactly that. FD will make them stackable in future versions, together with compatibility for stacking other `SoupItem`s optionally.
