### ISSUE TITLE
1.16.5 Kinda a Issue with Knifes 

### ISSUE THREAD

**Issue by Xakair** [vectorwing/FarmersDelight#219]
So the knifes for PVP are OverPowered
The Dps is higher than a sword and it ads more pressure than a sword.

I would greatly appreciate a config option to modify the knife stats. 

i Don't have any mods installed that add enchantments

**Comment by vectorwing** [comment]
Thanks for the feedback!

Yeah, it seems more users are coming up with that conclusion as well. On my limited single player test, they actually seemed _worse_ than swords in DPS, but I might have underestimated the not-ready swing damage, or an actual PvP fight.

A branch is currently up for testing balance changes in many areas, and knives are being revisited a bit for the next version. 👍
