### ISSUE TITLE
[1.16.5] Chickens won't eat cabbage or tomato seeds

### ISSUE THREAD

**Issue by enduum** [vectorwing/FarmersDelight#223]
**Description**
Chickens won't eat cabbage or tomato seeds.

**Steps to reproduce:**
Find some cabbage seeds
Find a chicken
R-click chicken with seeds
Nothing happens

**Expected behavior:**
Chickens eating seeds from cabbages and tomatoes, just like they do every other seed. :p

**Mod list:**
Minecraft: 1.16.5
Forge: 36.0.45
Farmer's Delight: 0.3.2
[[Log]](https://pastebin.com/yLQCsgmE)
Tested on a clean install with no other mods.

**Comment by vectorwing** [comment]
As stated before, FD seeds and crops are not usable to breed vanilla animals yet, as Minecraft uses hardcoded lists of valid items that cannot be easily modified. This is planned for future updates.
