### ISSUE TITLE
[1.16.5] Rice despawning

### ISSUE THREAD

**Issue by pjlasl** [vectorwing/FarmersDelight#228]
I have noticed that after planting rice, it has a tendency to despawn. I had an entire rice paddy disappear. The log doesn't show anything breaking.

I have the latest Farmer's delight, Farmer's delight integration, and Farmer's delight compat installed.

**Comment by vectorwing** [comment]
Please fill the bug report template with your full mod list and, if possible, screenshots of your setup.
Also, try planting and growing some Rice on a minimal instance (only FD), as this sounds like another mod tinkering with the crop.

**Comment by vectorwing** [comment]
This issue has gotten stale, so I'm closing it. Feel free to reopen it if you can provide the details requested in my message above. 👍
