### ISSUE TITLE
[Suggestion] Recipe container tags

### ISSUE THREAD

**Issue by medsal15** [vectorwing/FarmersDelight#230]
Add the ability to use item tags for containers instead of a specific item in datapack recipes.

**Comment by vectorwing** [comment]
I suppose it could, though it raises an issue: an item can only have a single specific item as its container. When consumed, it would always give back the same thing, as opposed to the alternative containers provided by such tag.

Or did you intend for these tagged containers to not be given back by the item?

**Comment by medsal15** [comment]
I made this suggestion because I was making a custom datapack with vanilla food pantry, as it has some recipes that give the same items with multiple container under a tag. Upon consumption, only one of these tagged items is given back no matter which is used for crafting.

For exemple, carrot jam is craafted with any `#carrots:small_empty_jars`, but gives back an empty jar that fits in the tag.

**Comment by vectorwing** [comment]
I recently converted a similar issue to a discussion to keep it referenced, so I'll be closing this one. Here's the link:
https://github.com/vectorwing/FarmersDelight/discussions/734
