### ISSUE TITLE
[Suggestion] Serene Seasons compatible 

### ISSUE THREAD

**Issue by Dr-WeiAL** [vectorwing/FarmersDelight#233]
Can the Serene Seasons season system be added to the crops of this mod? 

![1](https://user-images.githubusercontent.com/47446553/112025023-b89f2400-8b6f-11eb-99d1-97d16d734e07.png)
![2](https://user-images.githubusercontent.com/47446553/112025035-bb017e00-8b6f-11eb-993d-eeeb2578cbf8.png)

https://www.curseforge.com/minecraft/mc-mods/serene-seasons
https://github.com/Glitchfiend/SereneSeasons

**Comment by SynfulChaot** [comment]
From what I understand of Serene Seasons, this would need to be added to the default configs of Serene Seasons itself.

**Comment by Dr-WeiAL** [comment]
> From what I understand of Serene Seasons, this would need to be added to the default configs of Serene Seasons itself.

Oh.. In other words, do I need to go to Serene Seasons's github issues to submit suggestions? 
I don’t know if you can understand what I’m saying, because I use the machine to translate(
