### ISSUE TITLE
[Suggestion] Simple Farming Compability

### ISSUE THREAD

**Issue by chief-turkler** [vectorwing/FarmersDelight#235]
I'm a user of both Simple Farming and Farmer's Delight, they seem to work together without issues except for some overlap.

![2021-03-23_20 15 42](https://user-images.githubusercontent.com/49252967/112198287-03777500-8c1e-11eb-84b9-f549fea3cc5b.png)
![2021-03-23_20 15 44](https://user-images.githubusercontent.com/49252967/112198296-05413880-8c1e-11eb-9ff1-078a9fd0b127.png)

Things like tomatoes seem to have some overlap. Would it be possible for a compability patch to be made?

**Comment by vectorwing** [comment]
Which overlap are you referring to? Both items are usable on all tomato-based recipes in both mods, and grow from different seeds.

If you mean that one should be disabled in favor of the other, that has to be done through modpack customization, such as editing FD's loot injections, and/or disabling Tomato Vines. Not sure whether SF provides ways to disable their own tomatoes, but you could perhaps edit out their seeds from generating.

**Comment by chief-turkler** [comment]
That is the overlap, there are two tomato items and neither can be used in the other mod's recipes.

**Comment by DaLumma** [comment]
Then simple farming probably doesn't use the forge tag(forge:vegetables/tomato), did you suggest it on their side too?

**Comment by vectorwing** [comment]
They certainly can be interchanged between the recipes of both mods, whether crafted or cooked. Both mods make use of the same Forge tags for them.

![image](https://user-images.githubusercontent.com/5566692/114258736-1f5d7380-999f-11eb-8a76-109dc16024f7.png)
![image](https://user-images.githubusercontent.com/5566692/114258743-2dab8f80-999f-11eb-89cc-ed76f69ce2ce.png)

If you can't interchange them, your modpack might be messing with tags or recipes. If you want either tomato to be unobtainable, there are ways to restrict their loot and drop generation; in FD's case, Tomato Vine generation can be disabled in the configs.

**Comment by chief-turkler** [comment]
oh cheers
