### ISSUE TITLE
[Suggestion] Rope should break if block above is broken

### ISSUE THREAD

**Issue by pjlasl** [vectorwing/FarmersDelight#244]
I had a rope attached to a tree, when I broke the tree down the rope stayed hanging in mid air.

It just makes sense, that if the block above the rope is broken, the rope should break.

**Comment by vectorwing** [comment]
Initially, Ropes were supposed to break in a chain, similar to Scaffolding, but back then I struggled with the neighbor detection logic. After playing a bunch and seeing people build, I felt as if Ropes being able to "float" like 1.16 Chains do was a nicer mechanic.

This might be revisited someday. Thanks for suggesting!
