### ISSUE TITLE
[1.16.5] Some blocks face don't rotate when generated by Structure Blocks/Worldgen

### ISSUE THREAD

**Issue by Zyohex** [vectorwing/FarmersDelight#246]
**Description**
I'm making a data pack that adds structures that use Farmer's Delight's blocks. During its testing I observed that when a structure is generated in a different angle than its original, some of its blocks from the mod don't change their orientation.
Those blocks are the following:
- All pantries
- Cooking Pot
- Cutting Board
- Stove
- Tatami Block

Some blocks that do change their orientation are the Basket, the Full Tatami Mat and the Half Tatami Mat.

**Steps to reproduce:**

1. Create a structure with these blocks and save it with a Structure Block
2. Load the structure in different angles

**Expected behavior:**
The aforementioned blocks should change their facing property with the structure's angle.

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/6224154/latest.log)

**Screenshots**
![2021-03-29_21 40 45](https://user-images.githubusercontent.com/81531066/112891088-fe13a200-90d7-11eb-8f74-22a3fd623157.png)

**Mod list:**

- forge-1.16.5-36.1.2-client.jar
- FarmersDelight-1.16.3-0.4.0.jar
- forge-1.16.5-36.1.2-universal.jar

**Comment by vectorwing** [comment]
Seems I might have forgotten a few relevant methods for these blocks. Will test the fix for the next dot release.

**Comment by vectorwing** [comment]
Fixed on commit 54d9c58. Thank you for spotting this, btw; I never actually used FD's directional blocks on my own structures, so this bug flew right past me. 😄

![image](https://user-images.githubusercontent.com/5566692/112916599-41b9dc00-90d7-11eb-8ef6-e6de897250a1.png)
