### ISSUE TITLE
Allow bread to be cut on a chopping board

### ISSUE THREAD

**Issue by pm065** [vectorwing/FarmersDelight#250]
Because everyone likes sliced bread.
(keeping it concise this time 😄)

**Comment by vectorwing** [comment]
I ended up going the "make bread easier to get" (Wheat Dough) instead of "make bread cuttable". In hindsight, a "pair of bread slices" item could've been a good way to make sandwiches more efficiently, but I felt it didn't add much to the process.

Thanks for suggesting, though!
