### ISSUE TITLE
[Suggestion] Cheese

### ISSUE THREAD

**Issue by hallowdarkfrost** [vectorwing/FarmersDelight#251]
I think the addition of cheese could open up even more possibilities for recipes! 

**Cheese** could be created by combining **milk** and **salt**. (In reality this would just make salty milk, and that sounds awful, so we have to use our imaginations here.)

**Salt** could be obtained by placing water buckets and a bowl in the cooking pot—at the end of the cooking process, the buckets are emptied, the water has been “boiled” away, and you’re left with a bowl of salt. 

The cheese itself, depending on what would be easier to implement, could either be just a straight item or would start out as a wheel that could be placed in the world or broken apart into four chunks of cheese.

As for actual uses for cheese, the first thing that came to mind for me was **pizza**! You could probably get away with a few different kinds of pizza with varying toppings (plain cheese, meat-covered, mushrooms, etc.) with the base ingredients being wheat dough, cheese, and tomatoes/tomato sauce. Or, if you wanted to keep it more unique and only have a single type of pizza available, I think a deep dish pizza that could be placed in the world would be pretty fun. (There are obviously a lot of other things cheese could be used for, but pizza has been on my mind lately.)

Farmer’s Delight is the food mod I’ve always wanted so I’m very much looking forward to its development in the future. Thanks for doing what you do!

**Comment by CheetahCyberBoi** [comment]
Oooh, nice

**Comment by HectorZaGa** [comment]
It could be interesting if a fungus is added to the mixture of milk and salt, so that there is fermentation, and that mixture is poured into a cauldron so that it sets, in this way the cauldron would be used, an object that is hardly ever used.

**Comment by vectorwing** [comment]
Thanks for the suggestion. Cheese is being considered, but not confirmed; it needs to go through some planning before anything is decided. I'll keep your points in mind, though!

I'll close this suggestion for now. If you'd like to keep the talk going, please reopen it on the **Discussions** tab. 👍
