### ISSUE TITLE
[Suggestion] Project MMO Compatibility

### ISSUE THREAD

**Issue by faeldray** [vectorwing/FarmersDelight#252]
[Project MMO](https://www.curseforge.com/minecraft/mc-mods/project-mmo) is a mod where you can level up different skills (agility, combat, farming, cooking, smithing, etc.) and you get better and better perks as you level.

So specifically, it would be great if cooking pots and stoves (and maybe cutting boards too?) gave cooking XP. Also, the perk of the cooking skill is that you get an increased chance of extra outputs as you level. So it would be great if cooking pots and stoves also supported that.

There is an API listed [about 3/4 of the way down this page](https://harmonised7.github.io/minecraft/pmmo/Features.html) although I'm not sure how helpful it could be to you.

**Comment by vectorwing** [comment]
Thanks for suggesting this integration! This seems a bit more involved, and at the moment I won't be able to give it much attention. I'll keep it in mind for future updates. 👍 

If you'd like to discuss this further, use the Discussions tab on this repo.
