### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by MixSan** [vectorwing/FarmersDelight#256]
Server crash when you put an egg from (abnorlas environment) in the oven.
==================================================
I noticed a lot of bugs with the oven in 1.16.5

**Comment by vectorwing** [comment]
1. Please fill out a proper bug report from the template, with your crash logs, mod list etc.
  https://github.com/vectorwing/FarmersDelight/issues/new/choose
2. Farmer's Delight has no oven. Did you mean the Stove?

I cannot help you unless you provide more information.

**Comment by MixSan** [comment]
So let's get started.

**Description**
When using food in the stove from other mods (not from FarmersDelight), the server crashes and ends the process.

**Steps to reproduce:**
I put food on the stove and when finished cooking it crashed.

**Expected behavior:**
Expected any food to be cooked.

**Logs**
Attached
[crash-2021-04-11_16.35.11-server.txt](https://github.com/vectorwing/FarmersDelight/files/6293818/crash-2021-04-11_16.35.11-server.txt)
[debug-3.log](https://github.com/vectorwing/FarmersDelight/files/6293860/debug-3.log)
[2021-04-11-3.log](https://github.com/vectorwing/FarmersDelight/files/6293861/2021-04-11-3.log)


**Screenshots**
Attached
![2021-04-12_09 12 28](https://user-images.githubusercontent.com/4050569/114339782-731eb700-9b6f-11eb-9e22-9ee43d267346.png)

**Mod list:**
Minecraft version - 1.16.5
Forge version - 36.1.4
Farmer's Delight version - 1.16.3-0.4.1
============================================
Farmer's delight
HT's TreeChop
Quark oddities
Project: Vibrant Journeys
Valhelsia Structures
CreativeCore
Just Enough Items
Abnormals core
Buzzier bees
Berry good
Farmer's Delight Integration
Personality
Atmospheric
Upgrade Aquatic
Extra Boats
Savage & ravage
TerraForged
Cooking for Blockheads
Autumnity
AutoRegLib
Abnormals Delight
Traveler's Backpack
Farmer's Delight Compats
Environmental
The endergetic expansion
Project MMO
Architectury
FTB GUI Library
Allurement
Farmer's Tea
Quark
AppleSkin
CFB to PMMO Compatibility
Valhelsia Core
Valhelsia Tweaks
Neapolitan

I love this mod and want it to be better. Thank you!

**Comment by vectorwing** [comment]
The interface in your screenshot does not belong to FD (our Stove doesn't have an interface), and the crash doesn't seem to be related to FD at all, I'm afraid.

Your crash log points to an issue with the mod **CFB to PMMO Compatibility**, so I would assume the workstation you're using is part of Cooking For Blockheads. I suggest you open this issue on that mod's issue board, with the same info you provided here, as they might be able to assist you better. 👍

**Comment by MixSan** [comment]
Thank you, it really is, a bug in a small fix that unites Cooking for Blockheads and Project MMO
