### ISSUE TITLE
[1.16.5] Configurable Rich Soil effectiveness

### ISSUE THREAD

**Issue by Mike-U5** [vectorwing/FarmersDelight#258]
It would be nice to have a config option to control how often the growth-spurt effect occurs on Rich Soil.

**Comment by vectorwing** [comment]
That's a good idea. As of now, Rich Soil has a 20% chance of succeeding with a boost every random tick, but I can see the importance of making the percentage configurable. I'll look into it!

**Comment by vectorwing** [comment]
Added on commit 50549ae. 👍
