### ISSUE TITLE
[1.16.5] Knife doesn't count towards achievement

### ISSUE THREAD

**Issue by RealSourceOfficial** [vectorwing/FarmersDelight#259]
**Description**
Crafted a Stone Knife (Mystical World) and didn't get "Hunt & Gather". Tried the Knife from Farmers Delight, still no acheivment.

**Steps to reproduce:**
(I'm using Valhelsia 3)
Craft Stone Knife
*THEN*
Craft Knife
 
**Expected behavior:**
Giving the Achievement :)

**Screenshots**
![image](https://user-images.githubusercontent.com/65256422/116754339-6b5b7100-a9bd-11eb-887c-189ffcf08e2c.png)
![image](https://user-images.githubusercontent.com/65256422/116754409-8b8b3000-a9bd-11eb-9160-d52260ddca4f.png)

**Mods**
Using Valhelsia 3

**Comment by DaLumma** [comment]
you crafted a Druidcraft knife and not a Farmer's Delight knife

**Comment by vectorwing** [comment]
If I recall correctly, both mods use the exact same flint + stick shaped recipe, so without a mod like Polymorph, one of them is unobtainable. Might be what happened here.

But yeah, the advancement only considers FD knives. Try making an Iron one if you can. 😉
