### ISSUE TITLE
[MC 1.16.5] add food like sushi, maki, kebab and fries

### ISSUE THREAD

**Issue by Shinoahra** [vectorwing/FarmersDelight#260]
You can add food like kebab, maki, sushi or fries with this food recipes

![192480F9-5F8B-4F7C-8740-466C539621A6](https://user-images.githubusercontent.com/83530403/116805775-f0af6480-ab28-11eb-9100-d163fea1b1c7.jpeg)
es
And fries with potatos in a cutting board for potato slice and in the cooking pot for fries and maybe do steak with fries sorry for my english it’s not my main language

**Comment by vectorwing** [comment]
Hi there!

Kebab is already in FD, in two forms:
- **Mutton Wrap**, made with Bread, Mutton, Cabbage, Tomato, and Milk (as a curd sauce);
- **Barbecue on a Stick**, skewered meats and veggies.

I'm still unsure regarding sushi, but I'll see what can be done.
