### ISSUE TITLE
[MC 1.16.5] Auto farm with villager

### ISSUE THREAD

**Issue by Shinoahra** [vectorwing/FarmersDelight#261]
I don’t really know if villager automatically farm the new crops add by this mod but it can be good do auto farming with the new crops with a farm like this
 https://youtu.be/q0bq-RnttBU and I don’t know too if the new crops spawn into village farmland
Sorry for my english it’s not my main language

**Comment by vectorwing** [comment]
Please make sure to test whether your suggestion already is added, and to also search the issue board for similar ones, before posting a new one.

Villagers are known to hardcode farming behavior to only vanilla crops and farmland. Adding to it involves delicate changes which are already being looked into.
