### ISSUE TITLE
[1.16.5 Enhancement] Pie Continuity

### ISSUE THREAD

**Issue by Dradon7** [vectorwing/FarmersDelight#265]
Vanilla pumpkin pie and FD pies are crafted differently. The pumpkin pie is much cheaper than an FD pie.

I propose the following recipes for the pies, which are shapeless, and are a compromise between the very expensive apple/chocolate pie, and the very cheap pumpkin pie:
**Pumpkin:**
_-sugar
-egg
-pumpkin slice
-pie crust_

**Apple:**
_-sugar
-wheat
-apple
-pie crust_

**Chocolate:**
_-sugar
-milk
-coco beans
-pie crust_

I haven't checked the food values, so they might need to be adjusted a bit to balance having cheaper pies. If this seems like a decent idea, I can make a PR with the recipes.

**Comment by vectorwing** [comment]
Thanks for the suggestion.

Pies from Farmer's Delight work differently than vanilla, which justifies their cost to a degree:
- They are place-able blocks, which can be sliced into 4 consumable pie slices, each feeding a cake bite's worth of hunger;
- They provide Speed I, as a nod to having a sugar rush.

Pumpkin Pie is planned to be integrated into FD's pie format in the future, with equivalent configs. This may entail a recipe change as well. Keep an eye for the next update! 😉
