### ISSUE TITLE
[1.16.5] Cooked Porkchop can't be cut into Cooked Bacon

### ISSUE THREAD

**Issue by Brun333rp** [vectorwing/FarmersDelight#268]
**Description**
Cooked Porkchop can't be cut into Cooked Bacon

**Steps to reproduce:**
1. Put a Raw Porkchop in a Cutting Board, and use a Knife on it. By doing so, you'll get Raw Bacon;
2. Now do the same with Cooked Porkchop. 

**Expected behavior:**
It's expected that you are able to cut it into Cooked Bacon, but for some reason this is not the case.

**Comment by vectorwing** [comment]
Cooked meats are "transformed" to an extent by the cooking process IRL, so they lose some traits. For example, you cannot chop a Cooked Steak into a Beef Patty, as the steak is already seared. Chicken Cuts, however, are just parts of the whole item, so it makes sense they can be cut when cooked.

Similarly here, a Cooked Porkchop is too changed by cooking to be cuttable into Cooked Bacon.

**Comment by Brun333rp** [comment]
so basically, it's intended for realism. that's reasonable then, thank you for the explanation
