### ISSUE TITLE
[Suggestion] Splash Milk Bottle

### ISSUE THREAD

**Issue by crafting-Aaron** [vectorwing/FarmersDelight#269]
You and your friend are out in a restaurant and he tries out that exotic fugu fish but the dish seems to be have been poorly prepared. Now he has the Nausea and Poison status effect and convulsing on the floor. What do you do?
A- Call an ambulance
B- Attempt CPR cause that's what you remembered in high school when someone is on the ground or something
C- Grab the nearest bottle of milk and smash it on your friend's face

If you answered C. You would probably be in trouble if your friend presses charges. But thankfully this is Minecraft so instead your friend would be instantly relieved of the poison and will thank you for helping him with such a refreshing beverage.

So, yeah. Splash milk. Really cool thing to have in an RPG modpack where you play the medic and just splash milk at people to cure them. Calcium sure is magical. Doesn't make sense that adding gunpowder makes milk explosive but we also got splash water bottles. Please explain, Notch.

**Comment by vectorwing** [comment]
Hard to execute, as Milk Bottles aren't actually potions, and the Brewing Stand is finicky with recipes.
Not a promise, but a similar idea might be considered in the future for a different kind of item. 😉
