### ISSUE TITLE
[1.16.5] Modded Materials Knife Support

### ISSUE THREAD

**Issue by Dradon7** [vectorwing/FarmersDelight#270]
**Feature Description**
Would it be possible to add placeholder knives for commonly added modded materials like copper, aluminum, brass, and silver? I'm not sure if this is outside the mod's scope, but it would be nice.

**Comment by vectorwing** [comment]
Though it would be convenient, some issues arise over inconsistent standards for durability/effectiveness. Brass and Aluminum aren't commonly used for tool heads, and it would be difficult for FD to define standards for the other metals.

Abnormals Delight currently implements knives on their own, for materials they introduce. I feel their method may be the more controlled option.
