### ISSUE TITLE
3D models on Cutting Board

### ISSUE THREAD

**Issue by jecowa** [vectorwing/FarmersDelight#272]
![Cutting Board](https://user-images.githubusercontent.com/8553687/119955433-aa9dc300-bf65-11eb-983b-43d897f599fe.png)

Use 3D models instead of item icons when available for food placed on Cutting Board.

**Comment by vectorwing** [comment]
Determining which items have a block to display isn't super easy; some of them would look wacky on the Cutting Board if I made them all display the block form (example: Wheat Seeds would look like the crop on age 0).

I might take a look later; maybe special-case it to pies and cakes, which are the main target here

**Comment by pm065** [comment]
Would a `farmersdelight:show_block_form_on_board` tag work here? You can never have too many customization tags :D

**Comment by vectorwing** [comment]
I have kinda decided against this idea, mostly due to how it would display short models against the full block ones. Sorry :(
