### ISSUE TITLE
[Suggestion] Update fried egg recipe to accept "#forge:eggs"

### ISSUE THREAD

**Issue by CriticAlias** [vectorwing/FarmersDelight#277]
Could you please update the fried egg recipe to accept the tag "#forge:eggs"?

**Comment by vectorwing** [comment]
I can't reliably predict what goes into that tag. Though `forge:eggs` is likely just for raw egg items, anyone could add cooked/fried ones there too. Plus, it would get in the way of cooking recipes for other modded eggs and be generally a nuisance to others.

This might be better off as case-by-case datapacks for each egg item instead.
