### ISSUE TITLE
[MC 1.16.5] Knife not showing or using durability when used

### ISSUE THREAD

**Issue by GauntAndreX8** [vectorwing/FarmersDelight#284]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
When i used the knife to cut down the grass it doesn't use any durability i think thats a bug

**Steps to reproduce:**
Well i did nothing i crafted it used it but doesn't show any durability

**Expected behavior:**

**Logs**
Even if the game didn't crash, please submit your client/server logs as well. They contain vital information to troubleshoot the issue.

**Screenshots**

**Mod list:**
Farmers delight
Forge
End remastered
Savage and Ravage
Hunter illager
The Conjuger
Optifine
Structure gel
Mowzie's Mobs
Alex's mobs
Mob Battle Mod
jei
guard villagers
citadel
abnormals core
Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
That's actually normal vanilla behavior. 😄

Tools don't lose durability when breaking "instamine" blocks such as Grass, Saplings or Flowers; only Shears are an exception. I couldn't get the Knife to take damage from those either. It should still take damage if used against blocks with resistance, such as Leaves or Tatami.

**Comment by GauntAndreX8** [comment]
tf i thought torches were the only items that doesn't use tools durability well thxs now i know now
