### ISSUE TITLE
[1.16.5] Basket's top transparent

### ISSUE THREAD

**Issue by derschnei** [vectorwing/FarmersDelight#287]
**Description**
When a block with a non-full hitbox is placed adjacent to the basket's open side it becomes transparent.
Maybe it's an Optifine issue though?

**Steps to reproduce:**
Not sure what group of blocks causes this. I did some testing and think the screenshot should give you a good idea.

**Expected behavior:**
It should still be drawn ;)

**Screenshots**
![2021-06-18_21 03 41](https://user-images.githubusercontent.com/86127432/122606624-8cfdde00-d079-11eb-9624-9ccc27c411d0.png)

Mod List: 
		forge-1.16.5-36.1.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		FarmersDelight-1.16.5-0.4.3.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.3        |DONE      |NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |DONE      |NOSIGNATURE
		theoneprobe-1.16-3.1.4.jar                        |The One Probe                 |theoneprobe                   |1.16-3.1.4          |DONE      |NOSIGNATURE
		ToolBelt-1.16.5-1.16.0.jar                        |Tool Belt                     |toolbelt                      |1.16.0              |DONE      |NOSIGNATURE
		architectury-1.17.22-forge.jar                    |Architectury                  |architectury                  |1.17.22             |DONE      |NOSIGNATURE
		ftb-gui-library-1605.2.1.41-forge.jar             |FTB GUI Library               |ftbguilibrary                 |1605.2.1.41         |DONE      |NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.3.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.3      |DONE      |NOSIGNATURE
		moreoverlays-1.18.14-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.14-mc1.16.5    |DONE      |NOSIGNATURE
		curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar      |Curious Shulker Boxes         |curiousshulkerboxes           |1.16.5-4.0.1.0      |DONE      |NOSIGNATURE
		jei-1.16.5-7.7.0.106.jar                          |Just Enough Items             |jei                           |7.7.0.106           |DONE      |NOSIGNATURE
		OptiForge-MC1.16.5-0.5.5.jar                      |OptiForge                     |optiforge                     |0.5.5               |DONE      |NOSIGNATURE
		ftb-chunks-1605.2.3-build.75.jar                  |FTB Chunks                    |ftbchunks                     |1605.2.3-build.75   |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.0-universal.jar                 |Forge                         |forge                         |36.1.0              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		curios-forge-1.16.5-4.0.5.2.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.2      |DONE      |NOSIGNATURE
		create-mc1.16.5_v0.3.1c.jar                       |Create                        |create                        |mc1.16.5_v0.3.1c+151|DONE      |NOSIGNATURE
		ShulkerTooltip-1.9.8.jar                             |Shulker Tooltip               |shulkertooltip                |1.9.8               |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1.jar                       |Journeymap                    |journeymap                    |5.7.1               |DONE      |NOSIGNATURE
		polymorph-forge-1.16.5-0.25.jar                   |Polymorph                     |polymorph                     |1.16.5-0.25         |DONE      |NOSIGNATURE
		AutoRegLib-1.6-49.jar                             |AutoRegLib                    |autoreglib                    |1.6-49              |DONE      |NOSIGNATURE
		Quark-r2.4-312.jar                                |Quark                         |quark                         |r2.4-312            |DONE      |NOSIGNATURE
		createplus-1.16.4_v0.3.1.3.jar                    |Create Plus                   |createplus                    |1.16.4_v0.3.1.3     |DONE      |NOSIGNATURE

Thank you for the project!

**Comment by vectorwing** [comment]
Yup, issue on my end. Thanks for opening it with so much information btw, I noticed it yesterday and didn't bother opening one myself. Helped me a ton! 😅
I fiddled with the render shape to get water to render correctly, but went overboard. Will be fixed for 0.5.

**Comment by derschnei** [comment]
oh forgot: the blocks on top are (kinda) non-full but basket is drawing correctly!

**Comment by vectorwing** [comment]
Fixed on commit 50ef08f, should be out in a minor release pretty soon (assuming nothing new appears). 👍
