### ISSUE TITLE
Support Other Mods's Wood Types and Materials

### ISSUE THREAD

**Issue by Blunder-G** [vectorwing/FarmersDelight#289]
It would be cool if we have other mods's wood types for decos (kitchen tools) and knifes
For ex: Enviromental, Atmospheric, Outer End, Biomes O'Plenty, Endergetic Expension, Ice and Fire etc.

**Comment by vectorwing** [comment]
These integrations will not be added in the main mod, as I cannot possibly account for every modded wood or ingot out there. Sorry about that.

Add-ons have been covering some of these, though. I recommend checking out Abnormals Delight, for integration with MC Abnormals mods! 😉 
https://www.curseforge.com/minecraft/mc-mods/abnormals-delight
