### ISSUE TITLE
Minor Inconsistency Between Campfire and Stove

### ISSUE THREAD

**Issue by Umpaz** [vectorwing/FarmersDelight#295]
When campfire is unlit you can still put the raw food on it. Can't with the stove

**Comment by vectorwing** [comment]
Hmm! I remember it not being possible to put items in unlit campfires before (you had to extinguish them after placing items). Perhaps that has changed and I never noticed it. Would open some decoration options.

**Comment by vectorwing** [comment]
Added this feature on commit 31221a6, should be out in the next version. 👍
