### ISSUE TITLE
Food Effects are too OP

### ISSUE THREAD

**Issue by Michael1986Anderson** [vectorwing/FarmersDelight#300]
Listen Vector I love your Mod,it is Clear that you are very skilled at it......BUt I have a massive Problem with it....The Effects

Okay so let me tell you why I dislike many Effects in your Mod 

1.
They are too OP,At this point you can stop making potions and instead make an Apple pie because that would be an better option

2.
it gets annoying to get random effects

These are my simple Problems but I am not just gonna stop there,ı am going to give out some solutions

Solution Number 1:A Complete Redeisgn of the Effects this Requires:
1.playing the Game and Looking up wich food items are easier to craft

2.Rebalance the effects with support of step 1,For an Example Removing the Watermelon popsicles Fire Resistance Effect beasue it is too easy to get

Solution Number 2:Release Another Version of your Mod without the Food Effects for Players like me Who Just want the Food and no the effects

Solution Number 3:Make an Options Menu for the Mod that allows you to disable food effects

Thats it, sorry if it came out too harsh,Hope you are doing well

**Comment by Michael1986Anderson** [comment]
Solution 4 is the Hardest of them all İt is a completely new ssytem for the Mod Basically there are 3 Catogories for New Food items these are:

İngredients:They are used for Crafting Basic Meals and dont fill much Hunger for example:Tomatoes,Bacon

Basic Meals:These can fill your hunger bar fine and some have reall minor effects for an example:Meatballs ad Spaghetti,HamBurger

Final One Hearthy Meals:These are not just Meals and can be considered Feast,They will fill your Hunger Multiple Times and Will also give Special Effects like Strenght but They are Hard to Craft and Must Placed and Requiresd a Bowl for consumption

**Comment by Friskygote** [comment]
I don't know if these comments referred to older versions of the mod or something (playing on 1.17.1 atm) but
personally I disagree with notion that effects are too OP. 
A lot of similar mods for food miss out the point by adding foods that add some flat hunger/saturation just like any other food in Minecraft, very often these kinds of processed food gives lower hunger/saturation than combined ingredients which doesn't particularly make a lot of sense. 
I feel like Farmer's Delight effects are actually a really good reward for the player for making food that requires some more effort to make. 
Collecting many ingredients to make some more filling food that will nourish the player for longer which makes the end game less about keeping those pesky bars full and allows players to actually do what they want. 
I don't know

**Comment by vectorwing** [comment]
Hi there! Thanks for sharing your opinion on the food balance.

Yeah... potion effects aren't my favorite solution. The goal here is to make it worthwhile to prepare meals, but there isn't much ground to cover with them in standard Minecraft.

I tried keeping these "burst effects" very short, mostly to act as second-winds more than anything, but some might be going far. This is something I'll look into over time with each update. Pies certainly feel excessive, and I might either take their Speed buff away, or shorten it to just a few seconds.

Some of the solutions proposed here are a bit drastic, however. I'd still rather keep the mechanics simple. Either way, a potential config to disable burst effects is being considered. 👍
