### ISSUE TITLE
crash on server

### ISSUE THREAD

**Issue by TheNimbleNinja** [vectorwing/FarmersDelight#304]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
crash on server
**Steps to reproduce:**
no idea
**Expected behavior:**
not to crash
**Logs**
https://gist.github.com/TheNimbleNinja/b9bce7901e578b23759c0e2a29ebb799

**Screenshots**
none
**Mod list:**
https://gist.github.com/TheNimbleNinja/d3e4d70c976af323ff2a20d59a08dfa5

**Comment by DaLumma** [comment]
1. this is the github for the forge version the issue tracker for the fabric version is [here](https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues?status=new&status=open)
2. this is already known
3. the issue template didn't get filled out correctly

**Comment by vectorwing** [comment]
Please read our pinned [README](https://github.com/vectorwing/FarmersDelight/issues/280) before posting new issues. This is a known problem with the Fabric version, so it should be on the BitBucket repo.
