### ISSUE TITLE
[1.16.5] Only vanilla shears are able to harvest mushroom colonies

### ISSUE THREAD

**Issue by Not-February** [vectorwing/FarmersDelight#308]
**Description**
As an example, I crafted Reliquary's Shears of Winter, and they cannot be used to break mushroom colony blocks to harvest the colony itself; you only get the 5 mushrooms. You can't use the shears to clip the colony either. Using vanilla shears works as intended.

I am hazarding a guess that this problem extends to other shears that mods add and not just this particular example, but I have not actually tested such examples at this time.

**Steps to reproduce:**
Use Reliquary's Shears of Winter on a Mushroom Colony, either right or left click. Compare same behavior to using vanilla shears.

**Expected behavior:**
It would be wonderful if this and other examples of mod-added shears items could be used to harvest mushroom colonies. The Shears of Winter work as expected to extend shearing behavior to blocks from *other* mods(primary example: I tested right click shearing behavior against Habitat's fairy mushrooms, which can be sheared with any shears-esque items to get a mushroom back if its colony contains more than one mushroom at the time), so I'm not sure why they aren't working with mushroom colonies when everything else seems to work fine.

**Mod list:**
``Forge 36.2.0``
``Farmer's Delight 1.16.5-0.4.5``
``Abnormals Core 3.2.0``
``Habitat 0.3a2``
``Reliquary 1.16.5-1.3.5.1100``

**Comment by vectorwing** [comment]
Chances are those modded shears lack the `forge:shears` tag, which FD consults to determine if an item works as shears.

Some mods have their shears tagged, which allows them to interact with mushroom colonies. If not tagged, a datapack can be made to give them this tag, or the suggestion can be passed to the developers.

To check if a pair of shears is tagged:

1. Open the Creative Mode menu;
2. Search for `#shears` in the search bar, like so:
![image](https://user-images.githubusercontent.com/5566692/129645268-2f41fe30-09da-4410-9ffa-d84402d67f61.png)

If these shears show up, but somehow still don't work, please let me know.

**Comment by Not-February** [comment]
Okay, these shears are definitely not tagged with that - I will see if tagging it makes it work, thank you.

**Comment by vectorwing** [comment]
Hi there, @Febilian! Did tagging these shears work out? Asking so I can close the issue.

**Comment by Not-February** [comment]
Ah sorry! Yes, it was definitely because the shears weren't tagged. I added the tag with a datapack and it worked!

**Comment by vectorwing** [comment]
Good to know it's working! Thanks for your time. 😄
