### ISSUE TITLE
[MC 1.16.5] Large number of Render Errors.

### ISSUE THREAD

**Issue by Devestatio** [vectorwing/FarmersDelight#313]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
while loading the logs spam a lot of warnings about render errors with the block images for pie and pie_slices

**Steps to reproduce:**
Happens every time I load the pack.

**Expected behavior:**
Texture needs to be corrected to fix the error?

**Logs**
https://paste.ee/p/7XBcn

**Screenshots**
![image](https://user-images.githubusercontent.com/4734339/130542961-b3f21c68-ad38-4203-8e01-be1f996313bc.png)
the spam is too long to post it all in one shot, but it just repeats for all the sides of the textures.

**Mod list:**
Mods:
  [✔️] abnormals_core-1.16.5-3.2.0
  [✔️] abstoneedition-2.0.6-mc1.16.3-16.5
  [✔️] AdLods-1.16.5-4.1.8.0-build.0177
  [✔️] AkashicTome-1.4-16
  [✔️] appleskin-forge-mc1.16.x-2.1.0
  [✔️] Aquaculture-1.16.5-2.1.20
  [✔️] architectury-1.20.29-forge
  [✔️] AttributeFix-1.16.5-10.1.3
  [✔️] AutoRegLib-1.6-49
  [✔️] AxesAreWeapons-1.3-forge-1.16.5
  [✔️] B3M-1.16.4-02
  [✔️] balancedenchanting-1.0
  [✔️] BetterAdvancements-1.16.5-0.1.0.108
  [✔️] betteranimals-1.16.4-5.5.0
  [✔️] betteranimalsplus-1.16.5-10.2.0
  [✔️] BetterCaves-Forge-1.16.4-1.1.2
  [✔️] BetterDungeons-1.16.4-1.2
  [✔️] betterendforge-1.16.4-1.6.0
  [✔️] BetterMineshafts-Forge-1.16.4-2.0.4
  [✔️] BetterStrongholds-1.16.4-1.2.1
  [✔️] BiomesOPlenty-1.16.5-13.1.0.482-universal
  [✔️] Bookshelf-Forge-1.16.5-10.2.27
  [✔️] BotanyPots-1.16.5-7.0.17
  [✔️] BotanyTrees-1.16.5-3.0.5
  [✔️] byg-1.3.1
  [✔️] caelus-forge-1.16.5-2.1.3.1
  [❌] cavebiomeapi-1.16.5-1.3.1.jar (disabled)
  [❌] CavesAndCliffsBackport-1.16.5-6.2.jar (disabled)
  [✔️] cfm-7.0.0pre22-1.16.3
  [✔️] champions-forge-1.16.5-2.0.1.7
  [✔️] chiselsandbits-0.3.4-RELEASE
  [✔️] chunkloaders-1.1.7-mc1.16.5
  [✔️] citadel-1.7.3-1.16.5
  [✔️] cloth-config-4.11.26-forge
  [✔️] Clumps-6.0.0.25
  [✔️] collective-1.16.5-2.58
  [✔️] comforts-forge-1.16.5-4.0.1.2
  [✔️] compactores-1.16.5-3.0.3
  [✔️] compactstorage-1.16.5-5.1b17
  [✔️] Compressium-1.16.5-1.2.3
  [✔️] connectedglass-1.0.8-mc1.16.5
  [✔️] constructionwand-1.16.5-2.2
  [✔️] Controlling-7.0.0.23
  [✔️] CookingForBlockheads_1.16.5-9.3.3
  [✔️] corail_pillar-1.16-5.0.0
  [✔️] corail_recycler-1.16.5-5.1.0
  [✔️] corail_woodcutter_extension_byg-1.0.0
  [✔️] corail_woodcutter-1.16-1.3.2
  [✔️] CosmeticArmorReworked-1.16.5-v4
  [✔️] CraftingTweaks_1.16.5-12.2.1
  [✔️] CTM-MC1.16.1-1.1.2.6
  [✔️] culinaryconstruct-forge-1.16.5-4.0.0.6
  [✔️] curios-forge-1.16.5-4.0.5.2
  [✔️] curiouselytra-forge-1.16.5-4.0.2.3
  [✔️] CyclopsCore-1.16.5-1.11.8
  [✔️] dankstorage-3.16
  [✔️] DarkUtilities-1.16.5-8.0.10
  [✔️] DimStorage-1.16.5-4.4.1
  [✔️] Ding-1.16.5-1.3.0
  [✔️] dynviewdist-2.0
  [✔️] EasyMagic-v1.0.2-1.16.5
  [✔️] elevatorid-1.16.5-1.7.13
  [✔️] EmendatusEnigmatica-1.16.5-1.2.9
  [✔️] EnchantmentDescriptions-1.16.5-7.0.12
  [✔️] endergetic-1.16.4-3.0.0
  [✔️] endertanks-1.16-1.9.5
  [✔️] EntityCulling-1.16.5-2.1.6
  [✔️] EverlastingAbilities-1.16.5-1.7.2
  [✔️] FarmersDelight-1.16.5-0.4.6
  [✔️] FarmingForBlockheads_1.16.5-7.3.1
  [✔️] FasterLadderClimbing-1.16.4-0.2.1
  [✔️] fastfurnaceminusreplacement-1.1-1.16.3
  [✔️] FastLeafDecay-v25
  [✔️] FastWorkbench-1.16.4-4.5.1
  [✔️] fishtraps-0.1.3
  [✔️] flourpower-1.16.x-1.2.0
  [✔️] FluxNetworks-1.16.5-6.1.7.12
  [✔️] ForgeEndertech-1.16.5-7.2.0.0-build.0177
  [✔️] fortunate-2.10.1-MC-1.16.4
  [✔️] fortune-gives-experience-1.16.2-1.0.0
  [✔️] ftb-backups-2.1.1.6
  [❌] ftb-chunks-forge-1605.3.1-build.41.jar (disabled)
  [✔️] ftb-library-forge-1605.3.1-build.58
  [❌] ftb-teams-forge-1605.2.1-build.20.jar (disabled)
  [✔️] ftb-ultimine-forge-1605.3.0-build.25
  [✔️] GameMenuModOption-1.16.4-1.8
  [✔️] HealthOverlay-1.16.5-3.0.0
  [✔️] industrial-foregoing-1.16.5-3.2.14.5-13
  [✔️] infernal-expansion-2.1.1
  [✔️] infernalmobs-1.16.2.1
  [✔️] InventoryHud_[1.16.2-1.16.5].forge-3.3.0
  [✔️] inventorypets-1.16.5-2.0.15
  [✔️] invtweaks-1.16.4-1.0.1
  [✔️] itemcollectors-1.1.2-mc1.16.5
  [✔️] jei-1.16.5-7.7.1.118
  [✔️] JER-Integration-1.1.0
  [✔️] journeymap-1.16.5-5.7.3
  [✔️] JustEnoughResources-1.16.5-0.12.1.122
  [❌] kubejs-forge-1605.3.14-build.60.jar (disabled)
  [❌] kubejs-mekanism-1604.1.1.6.jar (disabled)
  [✔️] Lollipop-1.16.5-3.2.9
  [✔️] lootbagmod-1.16.5-2.3.1
  [✔️] lootr-1.16.5-0.0.7.21
  [✔️] MaxHealthFix-Forge-1.16.5-1.0.4
  [✔️] mcw-doors-1.0.3-mc1.16.5
  [✔️] mcw-furniture-2.0.1-mc1.16.5
  [✔️] mcw-trapdoors-1.0.2-mc1.16.5
  [✔️] mcw-windows-1.0.3-mc1.16.5
  [✔️] Mekanism-1.16.5-10.0.21.448
  [✔️] MiniCoal2-1.16.1-0.0.2-universal
  [✔️] MixinBootstrap-1.0.5
  [✔️] mob_grinding_utils-1.16.5-0.4.23
  [✔️] morebakedfoods-1.1.1
  [✔️] moredragoneggs-1.4
  [✔️] moreoverlays-1.18.15-mc1.16.5
  [✔️] MouseTweaks-2.14-mc1.16.2
  [✔️] NaturesCompass-1.16.5-1.9.1-forge
  [✔️] Neat+1.7-27
  [✔️] NetherPortalFix_1.16.3-7.2.1
  [❌] OptiFine_1.16.5_HD_U_G8.jar (disabled)
  [✔️] overloadedarmorbar-5.1.0
  [✔️] packedup-1.0.23a-mc1.16.5
  [✔️] PackingTape-1.16.5-0.10.1
  [✔️] paintings-1.16.4-7.0.0.1
  [❌] pamhc2crops-1.16.3-1.0.2.jar (disabled)
  [❌] pamhc2foodcore-1.16.3-1.0.2.jar (disabled)
  [❌] pamhc2foodextended-1.16.3-1.0.4.jar (disabled)
  [❌] pamhc2trees-1.16.3-1.0.1.jar (disabled)
  [✔️] Patchouli-1.16.4-53.1
  [✔️] Penguin-Lib-1.16.5-0.4.3
  [✔️] Piscary-1.16.5-1.0.3
  [✔️] Placebo-1.16.4-4.5.0
  [✔️] polymorph-forge-1.16.5-0.25
  [✔️] Powah-1.16.5-2.3.16
  [✔️] prefab-1.6.5.8
  [✔️] Quark-r2.4-316
  [✔️] randomloot-1.16.5-2.3.9
  [✔️] Regrowth-1.16.4-1.16.5-1.35.0.22
  [❌] repurposed_structures_forge-3.2.1+1.16.5.jar (disabled)
  [❌] ResourcefulBees-1.16.5-0.9.9.1.jar (disabled)
  [✔️] rhino-1605.1.2-build.47
  [✔️] RingsOfAscension-1.16.4-1.6.0
  [✔️] Runelic-1.16.5-7.0.1
  [✔️] saveandloadinventories_1.16.5-1.5
  [✔️] SBM-WoodenShears-1.16.5-1.1.0
  [✔️] shetiphiancore-1.16-3.8.5
  [✔️] shutupexperimentalsettings-1.0.3
  [✔️] simpledelights-1.1
  [✔️] simplefarming-1.16.5-1.3.8
  [✔️] simplemagnets-1.1.2-mc1.16.5
  [✔️] SimpleStorageNetwork-1.16.5-1.4.0
  [✔️] sounddeviceoptions-1.4.2
  [✔️] SoundFilters-0.14_for_1.16.2
  [✔️] SpartanShields-1.16.5-2.1.2
  [✔️] structurize-0.13.208-ALPHA-universal
  [✔️] supermartijn642configlib-1.0.9-mc1.16
  [✔️] supermartijn642corelib-1.0.12-mc1.16.5
  [✔️] swingthroughgrass-1.16.4-1.5.3
  [✔️] tanknull-2.3-1.16.4
  [✔️] TerraForged-1.16.5-0.2.14
  [✔️] theoneprobe-1.16-3.1.4
  [❌] tiered-1.16.5-1.2.3-forge-beta.jar (disabled)
  [✔️] time-in-a-bottle-1.1.0
  [✔️] titanium-1.16.5-3.2.8.4-10
  [✔️] Toast-Control-1.16.4-4.3.1
  [✔️] tombstone-1.16.5-6.5.0
  [✔️] ToolStats-1.16.5-6.0.1
  [✔️] torchmaster-2.3.8
  [✔️] toughnessbar-6.1
  [✔️] trashcans-1.0.10-mc1.16.5
  [✔️] TrashSlot_1.16.3-12.2.1
  [✔️] UnionLib-1.16.5-3.3.7
  [✔️] valhelsia_core-16.0.9
  [✔️] valhelsia_structures-1.16.5-0.1.4
  [✔️] villagespawnpoint_1.16.5-1.8
  [✔️] Waystones_1.16.5-7.6.2
  [✔️] YungsApi-1.16.4-Forge-12

**Comment by vectorwing** [comment]
Hey there! This is a known issue related to CTM (Connected Textures Mod), and has been posted here before.
Follow this issue for updates: https://github.com/Chisel-Team/ConnectedTexturesMod/issues/149
