### ISSUE TITLE
Suggestion: Villagers breed with crops

### ISSUE THREAD

**Issue by StrangerSon71** [vectorwing/FarmersDelight#314]
It would be a nice little vanilla feature to allow villagers to breed with the Farmers Delight crops, noticed that they didn't in Crucial 2.

**Comment by vectorwing** [comment]
This would be nice, but it requires a few intricate mixins I couldn't get a chance to work on yet. Might be done in a future release.

For now, I recommend using the mod **Smarter Farmers**, which accomplishes this goal across multiple mods:
https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant
