### ISSUE TITLE
Using bone meal on mushrooms on rich soil doesn't seem to do anything

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#315]
**Description**
Using bone meal on mushrooms on rich soil doesn't seem to do anything

**Steps to reproduce:**
1. place down a mushroom on rich soil
2. spam bone meal on it
3. observe that it does nothing

**Expected behavior:**
Maybe grow an extra mushroom or two per bone meal.

**Comment by vectorwing** [comment]
This is intended. Mushroom Colonies are slow growers, but provide extra produce right from their first stage of growth. Neither Rich Soil nor Bone Meal can speed them up.

If you mean growing a giant mushroom, a certain level of darkness is required, IIRC. Should work on all terrains.

**Comment by thelegitdolt** [comment]
alright, i see. but is it possible perhaps make it so you can't use bone meal on the mushrooms at all to avoid confusion?

**Comment by vectorwing** [comment]
Took me a while to understand what you meant. You didn't specify you were bonemealing growing _colonies_, which apparently are accepting bone meal during growing stages, even though they shouldn't.

This is indeed a bug. IGrowable has weird method wording... I'll sort this out for 0.5.

**Comment by vectorwing** [comment]
Fixed on commit 3efd156, should be out with version 0.5. Thanks for the report!
