### ISSUE TITLE
1.16.5- Mugs aren't held correctly in off-hand

### ISSUE THREAD

**Issue by WitheredWasabi** [vectorwing/FarmersDelight#316]
**Description**
Mugs are held upside down in the off-hand

**Steps to reproduce:**
Get hot cocoa and hold it in your off-hand

**Expected behavior:**
The mug being held right-side up in both hands

**Logs**
https://pastebin.com/gf4LbnB4

**Screenshots**
![unknown](https://user-images.githubusercontent.com/38932715/131266109-a1677aa3-bdcc-4725-9d7b-8f648c34dbf9.png)

**Mod list:**
Forge-36.2.2, FarmersDelight-1.16.5-0.4.6, & Abnormals mods

**Comment by vectorwing** [comment]
IIRC, I might have fixed this down the line on the `develop-0.5` branch, but forgot to port it over to 0.4.6 when it released. My bad.

I'll double-check the model template later. 👍

**Comment by vectorwing** [comment]
Checked just now, and yes, I fixed it on the upcoming 0.5 version. Thank you for documenting the bug, though! 👍
