### ISSUE TITLE
Another Feast Idea

### ISSUE THREAD

**Issue by vivvyinks** [vectorwing/FarmersDelight#318]
Meatloaf: wheat flour, potato, steak, and tomato sauce in the cookpot, served on a bowl/plate. Really just a feast idea that does something with the other meat type in Minecraft.

**Comment by thelegitdolt** [comment]
seems kinda cheap for a whole feast

**Comment by vectorwing** [comment]
I'm cleaning up the issues board, and closing "suggestion" issues for the time being. If you'd like to continue this idea, please reopen it on the new **Discussions** page; that's where suggestions should be posted from now on. 👍
