### ISSUE TITLE
[1.16.5 Forge] Unable to resolve texture

### ISSUE THREAD

**Issue by OcrSu** [vectorwing/FarmersDelight#322]
Log:https://paste.loliidc.cn/?63155d8f7d7ebfcf#EdbvPppZFnWuhGKqKfAuCZ4Niewz7uwFtBTwCM8FJt7u

**Comment by vectorwing** [comment]
Hey there! This is a known issue related to CTM (Connected Textures Mod), and has been posted here before. Please search closed issues before opening new ones.

Follow this issue for updates: Chisel-Team/ConnectedTexturesMod#149

If your pack does not contain CTM, please post your mod list here.
