### ISSUE TITLE
[MC Version] Issue title

### ISSUE THREAD

**Issue by Sixdd6** [vectorwing/FarmersDelight#335]
**Description**
Hoeing Rich Soil turns it into Farmland, not Rich Farmland

**Steps to reproduce:**
Get Rich Soil
Hoe that Rich Soil
Notice it turns to regular Farmland

**Expected behavior:**
Hoed Rich Soil should create Rich Farmland.

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/7385032/latest.log)

**Screenshots**

**Mod list:**
[modlist.txt](https://github.com/vectorwing/FarmersDelight/files/7385037/modlist.txt)

**Comment by vectorwing** [comment]
Testing this on a modded instance using Farmer's Delight 0.5 (which you're using), I couldn't replicate this problem. All Hoes succeeded in turning it to Rich Soil Farmland:

![image](https://user-images.githubusercontent.com/5566692/138190290-1256db0d-ce61-467b-93fa-391fe25a13ee.png)

Chances are you're either
- Using a modded hoe hardcoded to create normal farmland;
- Using a mod that modified hoes to only create normal farmland.

Please post a screenshot with your setup (hoes used, blocks of Rich Soil that were tilled). Also, try reducing your instance and testing this problem in a Creative World to identify a possible cause.

**Comment by Sixdd6** [comment]
Not sure what the problem would be but it seems to be on my end, I'll reopen the issue if I discover what the problem is.
