### ISSUE TITLE
[MC 1.15.2] - [Forge 31.2.31] Errors on Server Launch

### ISSUE THREAD

**Issue by Snaitf** [vectorwing/FarmersDelight#34]
Just added Farmer's Delight to my server, but am getting several errors on launch.  It doesn't stop the server from running, and I haven't tested any of the mod's features yet, but thought you should know ;) 

Server Log:  https://pastebin.com/PMuvWJxr

**Comment by vectorwing** [comment]
Oh my! Seems like something is busting a lot of mods attempting loot table injections, though from the log I couldn't fully tell what it can be.

Could you please post your list of mods, and the Forge version you're using? Did this start happening only when Farmer's Delight was added, or is this a new modpack?

**Comment by Snaitf** [comment]
Wow, quick reply...  :)

Forge version is in topic, 31.2.31

This just started happening after adding Farmer's Delight.  Didn't happen before, and it's the only thing I've changed.

Mod List:
![image](https://user-images.githubusercontent.com/9423729/88718214-a14a8c80-d0ef-11ea-842b-d0c91759535d.png)

**Comment by vectorwing** [comment]
Just gave this a minimal instance test... and it seems to be a clash with Abnormals Core. My loot table injections just start to fail horribly, and both loot tables end up wiped.

I might have done something dumb during onLootLoad. Thanks for finding it, I'll look into it tonight.

**Comment by vectorwing** [comment]
Nope, not fixed yet. The problem was me apparently forgetting to add .name() to my injections. Gonna open another branch to actually fix it, and also add some generic forge tags to my items.

**Comment by vectorwing** [comment]
Fixed now! Thanks for helping me troubleshoot it on discord! New version's up.
