### ISSUE TITLE
ID mismatch preventing multiplayer connection

### ISSUE THREAD

**Issue by FastBoye127** [vectorwing/FarmersDelight#343]
I'm trying to connect to a server, the world of which is a copy of a singleplayer world I created. It works fine in singleplayer, but when I try to connect to the server, I get this:
![Screenshot 2021-11-05 143943](https://user-images.githubusercontent.com/35196473/140569299-5716379e-be98-4cc9-8fba-37f577b6e172.png)
Any help?

**Comment by vectorwing** [comment]
Sorry for the delay.

These lines are merely referring to the removal of a deprecated block, `tall_rice_crop`, which was done on version 0.5 of the mod. It should not be causing a disconnect, as Forge automatically removes instances of that block on world load.

If you're still facing this issue, please post the logs (server included, if possible) and your mod list.

**Comment by FastBoye127** [comment]
It turned out to be due to a corrupted server world. Thank you!

**Comment by vectorwing** [comment]
No problem! Glad to know it was figured out. =)
