### ISSUE TITLE
[Suggestion] Skillet Recipe Type

### ISSUE THREAD

**Issue by NightmareTwilight** [vectorwing/FarmersDelight#346]
Basically, a "custom" skillet recipe type. It would be the same as normal, just that it's skillet exclusive. I believe adding a SKILLET_RECIPE to the IRecipeSerializer should be enough (though the skillet itself would, of course, need to check for that too, perhaps with the skillet type being prioritized?).

**Comment by vectorwing** [comment]
It was planned at first, but archived because of how difficult it was to implement the Skillet back then.
Might add it in the future, but it's a bit low-priority for now Thanks for the reminder!
