### ISSUE TITLE
[1.16.5] right clickin a stove with an egg trows one egg

### ISSUE THREAD

**Issue by LeoBeliik** [vectorwing/FarmersDelight#348]
**Description**
right clicking a stove with an egg (to make fried eggs) uses one egg in the stove and throws other in the world, consuming 2 eggs in the process.

**Steps to reproduce:**
have more than one egg in your hand
right click with em in the stove
consume two
sometimes spawn a chicken in the process

**Expected behavior:**
place one egg in the stove and not throw any egg.

**Screenshots**
https://user-images.githubusercontent.com/11804768/142420318-ad3d5e75-d1a4-4215-bd5c-eab84394c2ef.mp4

**Mod list:**
FarmersDelight-1.16.5-0.5.1
jei-1.16.5-7.7.1.134
forge-1.16.5 - 36.2.8
*I tested it with only those mods to be sure is not mod incompatibility*

**Suggestion**
In the stove topic, could you add a way to remove items from it? (sneak + right click with an empty hand)
as for now, the only way to remove an item from the stoves (lit and unlit) is to break it

**Comment by vectorwing** [comment]
Seems I'm defaulting to the CONSUME action result instead of PASS here, and the fix isn't trivial.
Thanks for reporting; I'll take a look.

**Comment by vectorwing** [comment]
Commit ebe0d4a fixes the issue. I'll see about letting items be removed; though the campfire doesn't let you do that, there's no reason the stove can't do it. I did it for the Skillets, after all. 😆
