### ISSUE TITLE
[1.16.5] Need config to turn off trades for own custom trade creation

### ISSUE THREAD

**Issue by Darkmega18** [vectorwing/FarmersDelight#349]
it's not a bug, just an issue. 

I'm not finding a config option that allows turning off of trades. cause apparently despite turning off the option that can stop the buying of veges etc, apparently I'm still getting the odd apple pie and meal in the trades also. Can these be turned off?

**Comment by vectorwing** [comment]
Farmer's Delight, by itself, does not introduce pies or meals to any villager trades. The trades it does add are for selling the mod's crops, at Novice and Apprentice levels.

Check your mod list if you have any add-ons, or if your modpack has custom trades.

**Comment by Darkmega18** [comment]
Hrm. odd. a friend said the pie in the villager trade window was an FD apple pie. but ok, I'll double check it I guess...

**Comment by vectorwing** [comment]
The pie likely belongs to FD, but the trade was likely registered by another mod, or through a modpack integration.

**Comment by Darkmega18** [comment]
Yeah... and thats the complicated bit. finding whos integrating it under my nose. :V

**Comment by vectorwing** [comment]
I'll be closing this issue now, since it's unrelated to vanilla FD. Good luck finding the mod! 👍
