### ISSUE TITLE
[Meta] Item & Recipe Integration (Forge Tags)

### ISSUE THREAD

**Issue by vectorwing** [vectorwing/FarmersDelight#35]
I haven't fully implemented compatibility and integration on the mod's items yet, and I'm still wondering what is the best way to approach that. For example: tagging items like Rice so that other mods can use it on rice-related recipes (forge:rice?).

If anyone has resources or recommendations on how to go about this, or how other farming mods do it, please let me know here!

**Comment by vectorwing** [comment]
Also, if anyone's savvy with it, we're open to pull requests tagging either items or recipes to be compatible with recipes/ingredients of other mods!

**Comment by WenXin20** [comment]
Hello, I believe Simple Farming does something similar, it uses tags by putting fruits and veggies in tags such as `forge:crops/onions`, `forge:vegetables/onions`, and `forge:fruits/orange`.
https://github.com/cweckerl/simplefarming/tree/1.15/src/main/resources/data/forge/tags/items

**Comment by vectorwing** [comment]
Hmm! SF and Pam's seem to share a lot of tags, though Pam's really covers every use case it has. I'll adopt those. Thanks for letting me know!

**Comment by WenXin20** [comment]
Hi again!
Mulch is missing the `forge:dirt` tag, which means modded plants can't be placed on it or be used in recipes. Maybe the same for Organic Compost?

And if wild crops are given the `minecraft:small_flowers` tag, bees will pollinate them. :)

**Comment by shattyyt** [comment]
Bees are already pollinating the crops with the recent commits, don't know about mulch though

**Comment by WenXin20** [comment]
Oh, I meant the wild crop plants that spawn in the world.

**Comment by vectorwing** [comment]
Oh yeah, I added them to `minecraft:small_flowers` like you suggested! Bees are now attracted to them as blocks and can be bred with them. It's in the newest branch, feature/moar-foods. I'm checking the other tags as well, and adding some I missed (such as `forge:rawfish` and `forge:cookedfish`

**Comment by vectorwing** [comment]
Integration seems good for now, I'll reopen this some other time.
