### ISSUE TITLE
[1.16.5] Nourishment Incompatible with AppleSkin

### ISSUE THREAD

**Issue by IdrisQe** [vectorwing/FarmersDelight#351]
**Description**
With Farmer's Delight and AppleSkin installed, when having the Nourishment buff which visually replaces the hunger icons, Appleskin's Saturation overlay, Exhaustion overlay, and "amount restored when holding food" overlay aren't visible or functional.

**Expected behavior:**
Ideally the icons would change colour as expected, while the overlays surrounding them would remain, and the functionality of showing how much food will be restored when holding an edible item would remain.

**Mod list:**
Forge 36.2.8
Appleskin 2.2.0
Farmer's Delight 0.5.1

Modpack being used is *Create: Above and Beyond* version *1.2*.
Others are included but *shouldn't* have any bearing on this issue as none affect the Hunger UI in any way (unless something really strange is being done in the background that doesn't actually alter anything visually or functionally)

**Comment by vectorwing** [comment]
Turns out I was increasing the overlay's Z level for no good reason.
Commit c0ffcd7 fixes it, should be out in the next version. 👍
