### ISSUE TITLE
Farmer's Delight don't like me using textures

### ISSUE THREAD

**Issue by Klouver-github** [vectorwing/FarmersDelight#352]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
SO I am trying to load a resource pack but as it is loading for past couple it'll then crash and give me -1 "FarmerDelight:Comfort_food before it was bound"

**Steps to reproduce:**
I used a resource pack called Duger's Minor Edits

**Expected behavior:**
it doesn't like texture packs

**Logs**
https://paste.gg/p/anonymous/0acaab62c7db4892a85556184692157a

**Screenshots**
I don't have and know how to show that part

**Mod list:**
I am using Farmer's Delight 0.5.2 and forge 1.16.5 - 36.2.19

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
This has nothing to do with resource packs. It seems my recent addition to tooltips is facing problems with the `comfort_foods` tag; although it worked fine on my modded instances, something down the line is causing an unbound tag crash with it. I'll need to investigate the cause later. 

For now, try removing the mods listed on line 34396 of your log, one by one, and see if any of them might be causing it:
https://paste.gg/p/anonymous/0acaab62c7db4892a85556184692157a#pastefile1-l34396

**Comment by Lariag** [comment]
Would setting "foodEffectTooltip" to false prevent the error?
I've had this crash 4 or 5 times but always while flying fast with elytra, both in the end and the overworld in case that's relevant.

**Comment by vectorwing** [comment]
Seems like consulting tags on this event might be problematic. Well, at least it coincides with a refactor I wanted to do, in which this tag would be removed anyway.

I'll fix this up for the next version.

**Comment by vectorwing** [comment]
I just released version 0.5.3 on Curseforge, which should fix this issue. If it doesn't, feel free to reopen.
