### ISSUE TITLE
[1.16.5] Cakes still drops slices if mined with a knife with silk touch

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#355]
**Description**
Cakes still drops slices instead of the whole cake if mined with knife with silk touch

**Steps to reproduce:**
1. Enchant a knife with silk touch
2. Place down a cake
3. Mine that cake with a knife

**Expected behavior:**
If a whole cake is minedwith a knife with silk touch, the whole cake drops instead of le slices

**Logs**
I doubt it matters and i'm too lazy so no

**Screenshots**
No

**Mod list:**
No

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
The current method of making a knife obtain slices from cakes uses loot modifiers, which are currently not consulting whether the tool has Silk Touch. Normally, cakes cannot even be obtained as such in vanilla, so it didn't cross my mind.

I'm not sure whether to change this, to be honest; it would make more sense for *any* Silk Touch tool to grab a full cake back, so adding that only to the knife seems off. It might be better to just let it continue getting slices, at least for now.

**Comment by thelegitdolt** [comment]
sounds good
