### ISSUE TITLE
[1.16.5] Installing Farmer's Delight Breaks Thermal Machine UI/Inventory visually

### ISSUE THREAD

**Issue by starryfae** [vectorwing/FarmersDelight#356]
**Description**
Trying to put items in Thermal machines with Farmer's Delight installed, the items do not appear to go into the machine, and stay in the client's inventory in the GUI. This was tested on a sever. However, the items move out of the inventory and into the machine when all gui's are closed.

Behavior is normal with any other inventory.

**Steps to reproduce:**
Install Thermal series and COFH mods, install farmer's delight, connect to server, attempt to put items into thermal machines

**Expected behavior:**
Items to instantly go into block machine inventory slots from thermal series

**Logs**

**Screenshots**

**Mod list:**

		forge-1.16.5-36.2.20-client.jar      
		FarmersDelight-1.16.5-0.5.2.jar      
		forge-1.16.5-36.2.20-universal.jar   
		cofh_core-1.16.5-1.4.0.6.jar         
		thermal_foundation-1.16.5-1.4.1.7.jar
		thermal_expansion-1.16.5-1.4.1.3.jar 
		thermal_innovation-1.16.5-1.4.1.3.jar
		thermal_locomotion-1.16.5-1.4.1.2.jar
		thermal_cultivation-1.16.5-1.4.1.3.jar

[debug.log](https://github.com/vectorwing/FarmersDelight/files/7696066/debug.log)

[latest.log](https://github.com/vectorwing/FarmersDelight/files/7696067/latest.log)

**Comment by vectorwing** [comment]
Welp... the ItemTooltipEvent REALLY dislikes when you use tags, it seems. It's breaking all manner of things!
I need to rollback this ASAP, apparently. Sorry for the trouble; I'll try and prioritize this fix next.

**Comment by starryfae** [comment]
Thank you!

**Comment by vectorwing** [comment]
I just released version 0.5.3 on Curseforge, which should fix this issue. If it doesn't, feel free to reopen.
