### ISSUE TITLE
1.18 fabric, incompatible with Wild World

### ISSUE THREAD

**Issue by Chuunkyz** [vectorwing/FarmersDelight#359]
when i launch a new world with farmers delight and wild world, i have a datapack error. and removing one of the two mods is the only way to make the game work
idk if that's on their end so i reported to wild world too

**Comment by vectorwing** [comment]
Hi there! Please read the pinned issue before posting:
https://github.com/vectorwing/FarmersDelight/issues/280

This issue board is only for the Forge version. The Fabric port of FD has its own board; please post it there:
https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues
