### ISSUE TITLE
[Farmers Delight MC 1.16.5] Villagers do not harvest on Rich Soil

### ISSUE THREAD

**Issue by TheSwitzVirgin** [vectorwing/FarmersDelight#361]
I recently swapped the vanilla dirt farmland with the rich soil farmland of the mod and I only planted there the vanilla crops, like potatoes and carrots. After the crops were ready to be harvested the Villagers don't harvest them.

**Steps to reproduce:**
Changed Dirt Farmland with the Rich Soil Farmland and planted with vanilla crops. But the Villagers don't harvest the crops.

**Expected behavior:**
The Villagers harvesting the vanilla crops from the Rich Soil farmland.

**Mod list:**
		Camels-1.16.5-1.0.0.jar                           |Camels Mod                    |camels                        |1.0.0               |DONE      |NOSIGNATURE
		blue_skies-1.16.5-1.1.3.jar                       |Blue Skies                    |blue_skies                    |1.1.3               |DONE      |NOSIGNATURE
		supermartijn642configlib-1.0.4-mc1.16.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.4               |DONE      |NOSIGNATURE
		blood-particles-1.16.3-1.0.1.jar                  |Blood Particles               |blood_particles               |1.0.1               |DONE      |NOSIGNATURE
		potiondescriptions-1.16.3-1.4.0.jar               |Potion Descriptions           |potiondescriptions            |1.16.3-1.4.0        |DONE      |NOSIGNATURE
		infernal-expansion-forge-1.3.jar                  |Infernal Expansion            |infernalexp                   |Release 1.3         |DONE      |NOSIGNATURE
		TRansliterationLib-1.0.1.jar                      |TRansliterationLib Mod        |transliterationlib            |1.0.1               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.66.jar                           |Just Enough Items             |jei                           |7.6.1.66            |DONE      |NOSIGNATURE
		DoggyTalents-1.16.5-2.1.0.0.jar                   |Doggy Talents 2               |doggytalents                  |2.1.0.0             |DONE      |NOSIGNATURE
		mcw-windows-1.0.3-mc1.16.5.jar                    |Macaw's Windows               |mcwwindows                    |1.0.3               |DONE      |NOSIGNATURE
		caelus-forge-1.16.5-2.1.3.0.jar                   |Caelus API                    |caelus                        |1.16.5-2.1.3.0      |DONE      |NOSIGNATURE
		Kobolds-1.5.1.jar                                 |Kobolds                       |kobolds                       |1.0.0               |DONE      |NOSIGNATURE
		farsight-1.4.2-1.16.5.jar                         |Farsight                      |farsight_spyglasses           |1.4.2-1.16.5        |DONE      |NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.10.0-build.0037.jar     |Forge Endertech               |forgeendertech                |7.0.10.0            |DONE      |NOSIGNATURE
		BetterPortals-1.16.4-0.3.2.jar                    |YUNG's Better Portals         |betterportals                 |1.16.4-0.3.2        |DONE      |NOSIGNATURE
		villagernames_1.16.5-3.3.jar                      |Villager Names                |villagernames                 |3.3                 |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.3.jar                      |TerraForged                   |terraforged                   |0.2.3               |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		mcw-paintings-1.0.0-mc1.16.4-5.jar                |Macaw's Paintings             |mcwpaintings                  |1.0.0               |DONE      |NOSIGNATURE
		journeymap-1.16.5-5.7.1b4.jar                     |Journeymap                    |journeymap                    |5.7.1b4             |DONE      |NOSIGNATURE
		citadel-1.8.1-1.16.5.jar                          |Citadel                       |citadel                       |1.8.1               |DONE      |NOSIGNATURE
		alexsmobs-1.12.0.jar                              |Alex's Mobs                   |alexsmobs                     |1.12.0              |DONE      |NOSIGNATURE
		TravelersBackpack-1.16.5-5.4.2.jar                |Traveler's Backpack           |travelersbackpack             |5.4.2               |DONE      |NOSIGNATURE
		YungsApi-1.16.4-Forge-4.jar                       |YUNG's API                    |yungsapi                      |1.16.4-Forge-4      |DONE      |NOSIGNATURE
		netheritehorsearmor-1.7.jar                       |Netherite Horse Armor Mod     |netheritehorsearmor           |1.7                 |DONE      |NOSIGNATURE
		Multiplayer-Server-Pause-1.16.5-Forge-1.0.0.jar   |Multiplayer Server Pause      |serverpause                   |1.0.0               |DONE      |NOSIGNATURE
		curioofundying-forge-1.16.4-5.1.0.0.jar           |Curio of Undying              |curioofundying                |1.16.4-5.1.0.0      |DONE      |NOSIGNATURE
		MutantBeasts-1.16.4-1.1.3.jar                     |Mutant Beasts                 |mutantbeasts                  |1.16.4-1.1.3        |DONE      |d9:be:bd:b6:9a:e4:14:aa:05:67:fb:84:06:77:a0:c5:10:ec:27:15:1b:d6:c0:88:49:9a:ef:26:77:61:0b:5e
		Bookshelf-1.16.5-10.0.1.jar                       |Bookshelf                     |bookshelf                     |10.0.1              |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		guardvillagers-1.16.5.1.2.6.jar                   |Guard Villagers               |guardvillagers                |1.2.6               |DONE      |NOSIGNATURE
		mcw-doors-1.0.2-mc1.16.5.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.2               |DONE      |NOSIGNATURE
		iceandfire-2.1.9-1.16.5.jar                       |Ice and Fire                  |iceandfire                    |2.1.9-1.16.5        |DONE      |NOSIGNATURE
		carryon-1.16.5-1.15.5.15.jar                      |Carry On                      |carryon                       |1.15.5.15           |DONE      |8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		Wandering-Bag-1.16.5-1.0.2.jar                    |Wandering Bag                 |wandering_bag                 |1.0.2               |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.23-universal.jar                |Forge                         |forge                         |36.1.23             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		shetiphiancore-1.16-3.8.5.jar                     |ShetiPhian-Core               |shetiphiancore                |3.8.5               |DONE      |NOSIGNATURE
		MoreCraftingTables+-+1.16.5.jar                   |More Crafting Tables Mod      |mctb                          |1.16.5 - 1.0.0      |DONE      |NOSIGNATURE
		MmmMmmMmmMmm-1.16-1.0.1.jar                       |MmmMmmMmmMmm                  |dummmmmmy                     |1.0.1               |DONE      |NOSIGNATURE
		twilightforest-1.16.5-4.0.546-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |DONE      |NOSIGNATURE
		tl_skin_cape_forge_1.16.5-1.19.jar                |TLSkinCape                    |tlskincape                    |1.19                |DONE      |19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		supplementaries-1.16.5-0.16.1.jar                 |Supplementaries               |supplementaries               |1.16.5-0.16.0       |DONE      |NOSIGNATURE
		betterendforge-1.16.4-1.4.1.jar                   |BetterEnd Forge               |betterendforge                |1.16.4-1.4.1        |DONE      |NOSIGNATURE
		DynamicSurroundings-1.16.4-4.0.3.8.jar            |Dynamic Surroundings        |dsurround                     |1.16.4-4.0.3.8      |DONE      |b4:98:14:b9:76:55:25:4f:e5:5f:4d:71:90:87:43:5b:f9:d5:3a:02:60:42:5e:da:1f:15:9c:ff:be:a9:7c:77
		structure_gel-1.16.5-1.7.8.jar                    |Structure Gel API             |structure_gel                 |1.7.8               |DONE      |NOSIGNATURE
		selene-1.16.5-1.7.jar                             |Selene                        |selene                        |1.16.5-1.0          |DONE      |NOSIGNATURE
		corpse-1.16.5-1.0.0.jar                           |Corpse                        |corpse                        |1.16.5-1.0.0        |DONE      |NOSIGNATURE
		forge-1.16.5-36.1.23-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |NOSIGNATURE
		FarmersDelight-1.16.5-0.4.2.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.4.2        |DONE      |NOSIGNATURE
		customizableelytra-1.16.4-1.4.3.jar               |Customizable Elytra           |customizableelytra            |1.16.4-1.4.3        |DONE      |NOSIGNATURE
		morevillagers-FORGE-1.16.5-1.5.4.jar              |More Villagers                |morevillagers                 |1.5.4               |DONE      |NOSIGNATURE
		EnchantmentDescriptions-1.16.5-7.0.8.jar          |EnchantmentDescriptions       |enchdesc                      |7.0.8               |DONE      |eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		[1.16.5]Gender-1.7.5.jar                          |Gender                        |gender                        |1.7.5               |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.459-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.439   |DONE      |NOSIGNATURE
		EndRemastered-R352.jar                            |End Remastered 3.5.2          |endrem                        |1.16.3              |DONE      |NOSIGNATURE
		SaveYourPets-1.16.2-1.0.0.5.jar                   |Save Your Pets                |syp                           |1.0.0.5             |DONE      |NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		mcw-trapdors-1.0.1-mc1.16.5.jar                   |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.1               |DONE      |NOSIGNATURE
		mcw-fences-1.0.0-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.0               |DONE      |NOSIGNATURE
		AdLods-1.16.4-4.1.3.0-build.0034.jar              |Large Ore Deposits            |adlods                        |4.1.3.0             |DONE      |NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |DONE      |NOSIGNATURE
		Bountiful-1.16.4-3.3.0.jar                        |Bountiful                     |bountiful                     |1.16.4-3.3.0        |DONE      |NOSIGNATURE
		majrusz-library-1.16.4-2.0.1.jar                  |Majrusz Library               |majrusz_library               |2.0.1               |DONE      |NOSIGNATURE
		notenoughanimations-1.1.0.jar                     |NotEnoughAnimations Mod       |notenoughanimations           |1.1.0               |DONE      |NOSIGNATURE
		SpartanShields-1.16.4-2.1.1.jar                   |Spartan Shields               |spartanshields                |2.1.1               |DONE      |NOSIGNATURE
		Patchouli-1.16.4-50.jar                           |Patchouli                     |patchouli                     |1.16.4-50           |DONE      |NOSIGNATURE
		diet-forge-1.16.5-0.30.jar                        |Diet                          |diet                          |1.16.5-0.30         |DONE      |NOSIGNATURE
		collective-1.16.5-2.64.jar                        |Collective                    |collective                    |2.64                |DONE      |NOSIGNATURE
		multibeds-1.16-1.7.8.jar                          |Multi-Beds                    |multibeds                     |1.7.8               |DONE      |NOSIGNATURE
		ToughAsNails-1.16.5-4.0.1.23-universal.jar        |Tough As Nails                |toughasnails                  |1.16.5-4.0.1.15     |DONE      |NOSIGNATURE
		survivaloverhaul-1.16.5-0.4.1b.jar                |Survival Overhaul             |survivaloverhaul              |1.16.5-0.4.1b       |DONE      |NOSIGNATURE
		SereneSeasons-1.16.5-4.0.1.91-universal.jar       |Serene Seasons                |sereneseasons                 |1.16.5-4.0.1.91     |DONE      |NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar                   |Curios API                    |curios                        |1.16.5-4.0.5.3      |DONE      |NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |DONE      |NOSIGNATURE
		illagersweararmor-1.0.4.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.4               |DONE      |NOSIGNATURE
		TinyChests-1.4.2.jar                              |Tiny Chests                   |tinychest                     |1.4.2               |DONE      |NOSIGNATURE
		majruszs-difficulty-1.16.4-1.1.0.jar              |Majrusz's Progressive Difficul|majruszs_difficulty           |1.1.0               |DONE      |NOSIGNATURE
		majruszsaccessories-1.16.5-0.1.4.jar              |Majrusz's Accessories         |majruszs_accessories          |0.1.4               |DONE      |NOSIGNATURE
		SpartanWeaponry-1.16.4-2.1.0-beta-4.jar           |Spartan Weaponry              |spartanweaponry               |2.1.0 beta 4        |DONE      |NOSIGNATURE
		SolarHelmet-1.1.0.jar                             |SolarHelmet                   |solarhelmet                   |1.1.0               |DONE      |NOSIGNATURE
		curiouselytra-forge-1.16.5-4.0.2.0.jar            |Curious Elytra                |curiouselytra                 |1.16.5-4.0.2.0      |DONE      |NOSIGNATURE
		mcw-furniture-2.0.1-mc1.16.5.jar                  |Macaw's Furniture             |mcwfurnitures                 |2.0.1               |DONE      |NOSIGNATURE
		globalxp-1.16.5-v1.8.jar                          |Global XP                     |globalxp                      |v1.8                |DONE      |NOSIGNATURE
		The_Undergarden-1.16.5-0.5.2.jar                  |The Undergarden               |undergarden                   |0.5.2               |DONE      |NOSIGNATURE
		chunkloaders-1.1.6-mc1.16.5.jar                   |Chunk Loaders                 |chunkloaders                  |1.1.6               |DONE      |NOSIGNATURE
		Aquaculture-1.16.5-2.1.21.jar                     |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.21       |DONE      |NOSIGNATURE
		AdChimneys-1.16.4-6.0.6.0-build.0037.jar          |Advanced Chimneys             |adchimneys                    |6.0.6.0             |DONE      |NOSIGNATURE
		illagers_plus-1.16.4v1.7.2.jar                    |Illagers+                     |illagers_plus                 |1.16.4v1.7.2        |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.5-2.10.2.jar               |Falling Tree                  |fallingtree                   |2.10.2              |DONE      |NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                      |Small Ships Mod               |smallships                    |1.10.1              |DONE      |NOSIGNATURE
		valhelsia_core-16.0.9.jar                         |Valhelsia Core                |valhelsia_core                |16.0.9              |DONE      |NOSIGNATURE
		valhelsia_structures-1.16.5-0.1.2.jar             |Valhelsia Structures          |valhelsia_structures          |1.16.5-0.1.2        |DONE      |NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |DONE      |NOSIGNATURE
		chiselsandbits-0.2.10-RELEASE.jar                 |Chisels & bits                |chiselsandbits                |NONE                |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.4-2.0.1.jar           |YUNG's Better Mineshafts      |bettermineshafts              |1.16.4-2.0.1        |DONE      |NOSIGNATURE
		NekosEnchantedBooks-1.16-1.0.0.jar                |NekoпїЅs Enchanted Books        |nebs                          |1.0.0               |DONE      |NOSIGNATURE
		EnderMail-1.16.5-1.2.0.jar                        |Ender Mail                    |endermail                     |1.16.5-1.2.0        |DONE      |NOSIGNATURE
		farlanders-1.16.4-1.3.9.jar                       |The Farlanders                |farlanders                    |1.3.9               |DONE      |NOSIGNATURE

**Comment by vectorwing** [comment]
This is a known limitation with vanilla code. Villagers are hard-coded to look specifically for normal Farmland and nothing else; similarly, they only consider vanilla crops "replantable", despite being able to break modded ones.

Tweaking this from FD's end takes quite a bit of code, and I couldn't get around to planning this yet, but the issue is known.

As a workaround for now, I recommend checking this mod out, by the creator of Supplementaries:
https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant

**Comment by TheSwitzVirgin** [comment]
Thanks for the fast answer, I checked it now with the mod "Smarter Farmers", but they still don't plant on the Rich Soil farmland. Thank you for the help anyway 👍

**Comment by luo-zi** [comment]
> Thanks for the fast answer, I checked it now with the mod "Smarter Farmers", but they still don't plant on the Rich Soil farmland. Thank you for the help anyway 👍谢谢你的快速回答，我现在用国防部“聪明的农民”检查了一下，但是他们仍然不种植在肥沃的土地上。谢谢你的帮助，无论如何。

If you  place an vanilla farmland next to them, that just work.
