### ISSUE TITLE
[Suggestion] Allow blank spaces/locking slots.

### ISSUE THREAD

**Issue by AppleMangoOrange** [vectorwing/FarmersDelight#365]
Automation of cooking pots is currently a bit difficult.
May I suggest a blank slot item which will work similar to the 'Crafter Slot Cover' from the create mod. Essentially; when the cooking pot is cooking, this item will always remain in the cooking pot and never be cooked.
An alternative could be to lock slots of the cooking pot to only accept certain items.
This will be useful in automating the cooking pot using only redstone and with the help of no other mods.

**Comment by Umpaz** [comment]
Imo it would be best to allow ingredients to go in through a hopper in the top and let container items to in through side hoppers. Makes most sense too me

**Comment by vectorwing** [comment]
Thanks for the suggestion! We have an open issue which compiles ideas to solve this design; feel free to post your ideas there:

#26

I'm a bit hesitant to add lock buttons or extra slots, as it would further pollute a GUI that's already more complex than average. The more we add to this screen, the less intuitive it becomes. I'm considering it, though; depends on whether more internal solutions end up working or not.

> Imo it would be best to allow ingredients to go in through a hopper in the top and let container items to in through side hoppers. Makes most sense too me

The pot currently does that; top takes ingredients, sides take containers, both bottom and sides can extract outputted meals.

**Comment by Adirelle** [comment]
> Essentially; when the cooking pot is cooking, this item will always remain in the cooking pot and never be cooked.

Brick could have this function, e.g. put 3 bricks in the bottom of your pot, then add ingredients.

**Comment by vectorwing** [comment]
Closing this, as the concept has been noted for study.
