### ISSUE TITLE
[suggestion] pig feed/allowing cabbage to be edible for pigs

### ISSUE THREAD

**Issue by scarfapalooza** [vectorwing/FarmersDelight#367]
I like the idea of pigs being able to be bred with cabbage as well as the idea of pigs having a type of feed like horse or dog food and it provides maybe more drops when having the effects or even allowing them to breed more piglets than if you were to feed them with normal carrots/beetroots/potatoes

**Comment by vectorwing** [comment]
Thanks for the suggestion! (y)

In 1.16 I was able to make Chickens and Pigs be tempted by crops and seeds from FD; however, the implementation failed on 1.17 and above. I'm still looking for a way to get it working again, but it's still pending.

As for Pig Feed and increasing drops, FD already has solutions for this: the **Knife** and the **Cutting Board**. Killing Pigs with a Knife will sometimes drop Ham, which can be cut for 2 Porkchops and 1 Bone. Beyond that, you can use the Looting enchantment to increase yields.
