### ISSUE TITLE
[1.18.1] Pirate speaks pantries translations are bugged

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#369]
**Description**
Cabinets are unlocalized in pirate speak

**Steps to reproduce:**
Turn on pirate speak. Observe that the cabinets name are *wood type* Cabinets instead of Cabinet o' *wood type*, as stated in en_pt

**Comment by thelegitdolt** [comment]
<img width="620" alt="Screen Shot 2021-12-29 at 12 05 45 AM" src="https://user-images.githubusercontent.com/50085439/147640638-9cbea2bd-a5f4-4d31-bd23-c5e767ba5cad.png">

**Comment by thelegitdolt** [comment]
ye it still says "pantry" instead of "cabinet" which i guess is the new localization thing?

**Comment by vectorwing** [comment]
Commit 6731a74 fixes this issue. Thanks for spotting it; my Replace tool seems to have skipped these files.

**Comment by thelegitdolt** [comment]
:thumbsup:
