### ISSUE TITLE
[1.18.1] Mismatched Tags / Missing Required Tags

### ISSUE THREAD

**Issue by oitsjustjose** [vectorwing/FarmersDelight#370]
**Description**
When re-joining a server, I often (not 100% of the time, but definitely more than 50%) will get a failure on connection stating that I am missing required tags to join the server. Restarting the instance resolves this, but may be related to a more critical issue:

On a server, when running `/reload` the process fails due to `Missing required tags: ResourceKey[minecraft:root / minecraft:block]:forge:mineable/knife`.

Since you seem to add a custom tool-type for the knife, I am *pretty* sure that this is a Farmer's Delight issue. If I'm mistaken let me know - there's only one other mod that adds a knife and it's for crafting only (Filet Knife from Aquaculture)

**Steps to reproduce:**
Cannot reliably repro on client.

On server, simply run `/reload` to see failure.

**Expected behavior:**
To not fail to /reload, throwing `Reload failed; keeping old data` message.

**Logs**
[https://gist.github.com/oitsjustjose/290a27e5f27990f7c6776f94fb151234](https://gist.github.com/oitsjustjose/290a27e5f27990f7c6776f94fb151234)

**Mod list:**
**Forge**: 39.0.9
**Farmer's Delight**: 1.18.1-1.0.0

[Full List](https://dv2ls.com/code?id=70Vkxq5TB)

**Comment by vectorwing** [comment]
This might be a goof from porting shenanigans. When I was studying how to implement a `mineable` for knives, I read that having a `forge` variant would let mods add blocks to it more universally. I registered it... but I never actually datagenned the tag itself. 🤦‍♂️

Funny enough, your logs also pointed to some integration recipes which skipped my radar and need updating. Thanks for that! 👍

**Comment by vectorwing** [comment]
Commit dfb6e27 should hopefully fix this issue (it generates an empty `forge:mineable/knife`). I also went ahead and updated knives to actually make use of this tag, rather than continue using the outdated 1.16 material checks...

This should be out for both 1.17 and 1.18 in the next patch. If that fails, feel free to reopen. 👍
