### ISSUE TITLE
[1.16.5] Off hand items getting placed on cutting board

### ISSUE THREAD

**Issue by Rodg88** [vectorwing/FarmersDelight#371]
**Description**
Right clicking most items on the cutting board while also holding something in your off-hand will put the off-hand item on the cutting board instead of the main hand item. However cakes and wheels of cheese in the main hand will still be prioritized over the off-hand.

**Steps to reproduce:**
Hold any non-food in your off-hand, and try to place a raw beef from your main hand on the board. 

**Expected behavior:**
It should probably ignore any non-cuttable off-hand items. While having a stack of cuttable items in the off hand, and a knife in your main, and just right-clicking is quite nice for fast cutting, I'd rather it just ignored the off-hand entirely to stop it stealing my shield. If it could still allow cuttable items to be placed via off-hand, that would obviously be the ideal situation.

**Screenshots**
![image](https://user-images.githubusercontent.com/2611674/147728342-c53f73f8-e941-4dd8-a485-71deb9c7e2c1.png)

**Mod list:**
Playing Enigmatica 6, Forge 36.2.21, FarmersDelight-1.16.5-0.5.4.jar
https://gist.github.com/Rodg88/30b70c6a97a2a8f812bd29a35e6a7eb7

**Comment by vectorwing** [comment]
There is a tag for that: `farmersdelight:offhand_equipment`. Items in it cannot be placed on the Cutting Board from the off-hand.

Chances are the Enigmatica pack hasn't added these shields to this tag (search #offhand_equipment in Creative to check); I recommend suggesting this enhancement to them.

**Comment by MuteTiefling** [comment]
Nice, honestly had no idea this tag existed. Thanks :D
