### ISSUE TITLE
Add wiki entries about finding crops

### ISSUE THREAD

**Issue by WhoAteDaCake** [vectorwing/FarmersDelight#373]
Which biomes the crops can be found in etc. I've been looking for an hour and still can't find any rice 🤷

**Comment by thelegitdolt** [comment]
rice is found in jungles + swamp biomes just a heads up

**Comment by vectorwing** [comment]
https://github.com/vectorwing/FarmersDelight/wiki/Wild-Crops

**Comment by WhoAteDaCake** [comment]
I'm so sorry, I've been looking at getting started section not finding anything 🤦

**Comment by WhoAteDaCake** [comment]
@vectorwing Can it only be found in puddles? I went through multiple jungle biomes without encountering one

**Comment by hbloom1783** [comment]
Rice only grows in dirt that's under exactly one block of water.  The top of the plant sticks up into the air, and it's bright golden yellow.  It can take quite a bit of looking to find.  I think you can sometimes find it in sunken ship chests and so forth?
