### ISSUE TITLE
[1.18.1] FD 1.0.2 requires Forge 39.0.18

### ISSUE THREAD

**Issue by lamoyrl90** [vectorwing/FarmersDelight#384]
From the patch notes and Github code, it looks like the open bracket on Forge version wasn't actually caught in the build that was uploaded to Curseforge:

net.minecraftforge.fml.ModLoadingException: Mod §efarmersdelight§r requires §6forge§r §o39.0.18§r
§7Currently, §6forge§r§7 is §o39.0.36

**Comment by lamoyrl90** [comment]
From the .jar's mods.toml:

[[dependencies.farmersdelight]]
    modId="forge"
    mandatory=true
    versionRange="[39.0.18]"
    ordering="NONE"
    side="BOTH"

**Comment by vectorwing** [comment]
I accidentally uploaded a stale build of 1.0.2 to CurseForge instead of the latest, after testing that tag; I briefly forgot how the syntax worked for specifying that version as minimal.

Patch should be out in a few minutes.

**Comment by vectorwing** [comment]
https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/3608961
