### ISSUE TITLE
FORGE 1.18.1 Farmer's Delight

### ISSUE THREAD

**Issue by driftirl** [vectorwing/FarmersDelight#388]
Hi all i have Farmer's Delight installed on my server but when rice is fully grown it only drops seeds upon harvest and no rice can somebody please help me

**Comment by vectorwing** [comment]
Hey there! Could you please elaborate? Please post the mod versions, and/or a screenshot.

Rice is a two-stage crop: it grows roots underwater, and panicles above water. Harvesting the top side when it's golden yellow will give you a **Rice Panicle**. If you use a Knife, it will give you **Rice** and **Straw** instead.

Rice, the white pile of grain, is the crop's seed. Is anything not working as described?
