### ISSUE TITLE
Server Crashing

### ISSUE THREAD

**Issue by LemonPie-Coding** [vectorwing/FarmersDelight#389]
Minecraft 1.18.1 
Forge 39.0.45
**Server crash error.**
My server crash after load.
![1](https://user-images.githubusercontent.com/98069978/150262781-d77c8f44-519d-4267-bd54-69c12a6b2588.png)

Mod List:
![2](https://user-images.githubusercontent.com/98069978/150262943-82ebfa2a-e80a-4ebf-8a1c-11cb1e12e45b.png)
![3](https://user-images.githubusercontent.com/98069978/150262947-a753691e-f33a-4e09-accb-8207899ac751.png)

**Comment by vectorwing** [comment]
Known issue with Forge 39.0.45 and above. A method was deprecated, which FD was still using somewhere.
Follow this issue for updates, and downgrade to .44 in the meantime: #390
