### ISSUE TITLE
[1.18.1] Server Crash by placing Pot on Stove.

### ISSUE THREAD

**Issue by octopies** [vectorwing/FarmersDelight#390]
**Description**
Caused the server to crash itself by placing a cooking pot on top of the stove block.

**Steps to reproduce:**
Created a stove, for the first time, placed it down. 
Created a cooking pot, for the first time.
Placed cooking pot on top of the stove.
Crash.

**Expected behavior:**
I expected the achievement "Dinner's Served" and to open the pot GUI

**Logs**
https://mclo.gs/X7JSJCx

Did a roll back, tried the stove and pot in another location. Same result

**Mod list:**
 forge-1.18.1-39.0.45-universal.jar, ImmersiveEngineering-1.18.1-7.1.0-145.jar, collective-1.18.1-3.8.jar, appleskin-forge-mc1.18-2.2.0.jar, treeharvester_1.18.1-4.2.jar, journeymap-1.18.1-5.8.0beta10.jar, AutoRegLib-1.7-52.jar, Quark-3.0-334.jar, StorageDrawers-1.18.1-10.1.1.jar, jei-1.18.1-9.2.3.78.jar, repurposed_structures_forge-4.0.9+1.18.1.jar, Repurposed_Structures-Immersive_Engineering_v2.zip, EasyMagic-v3.2.1-1.18.1-Forge.jar, PuzzlesLib-v3.1.3-1.18.1-Forge.jar, TradingPost-v3.1.2-1.18.1-Forge.jar, EnchantingInfuser-v3.1.1-1.18.1-Forge.jar, FarmersDelight-1.18.1-1.0.2a.jar

**Comment by vectorwing** [comment]
Forge 39.0.45 removed a reference to a broken method for saving data, which I accidentally left being used. I'll have to release a patch to take my reference out later, but gotta figure it out first.

Please downgrade your Forge to version **39.0.44** in the meantime.

**Comment by RealAmandaLive** [comment]
Should users downgrading their Forge versions itself be enough or do we need to do any changes server side?

**Comment by vectorwing** [comment]
Server and client must both downgrade.

**Comment by vectorwing** [comment]
Fixed on commit 8fb8892, the 1.0.3 patch is under review on CF currently.
