### ISSUE TITLE
Crash When placing cooking pot in 1.18.1

### ISSUE THREAD

**Issue by lumpypancakes** [vectorwing/FarmersDelight#399]
[crash-2022-01-24_17.26.05-server.txt](https://github.com/vectorwing/FarmersDelight/files/7930254/crash-2022-01-24_17.26.05-server.txt)

**Comment by lumpypancakes** [comment]
Works fine on independent install. Most likely some compat issue with another mod.

**Comment by vectorwing** [comment]
Huh... That makes no sense. You are on the latest FD and Forge, that method was renamed, and it's still crashing?
But if it's working correctly on a minimal instance, it could be a bad mod interaction. Are you using any launchers or modpacks?
