### ISSUE TITLE
1.18.1 Pot Breaks Chunk Rendering

### ISSUE THREAD

**Issue by darkshadow543** [vectorwing/FarmersDelight#406]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Placing the pot causes a crash, and then chunk the pot was placed in will not render upon reopening the world.
**Steps to reproduce:**
What did you do to cause the issue? Can it be replicated?
Place a cooking pot on a stove, the game should crash.

Reopen the world, and the chunk should stop rendering.

**Expected behavior:**
I just expected to place the pot and use it.

**Logs**
[crash-2022-01-28_18.40.02-server.txt](https://github.com/vectorwing/FarmersDelight/files/7962643/crash-2022-01-28_18.40.02-server.txt)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/7962653/latest.log)

**Screenshots**
![2022-01-28_18 46 30](https://user-images.githubusercontent.com/14943673/151640181-2873d15b-b473-4054-a31a-3ca3f37cc520.png)

**Mod list:**
In the crash report

Thank you for helping with the project! Your reports are appreciated!

**Comment by MythrilBagels** [comment]
Make sure the mod is updated to the latest version, since Vectorwing has already fixed the issue

**Comment by vectorwing** [comment]
Please ensure your mods folder does not contain an older version of FD still installed.

Forge 1.18 is still in Beta, so many breaking changes are occurring. Currently, Forge is loading older .jar's while stating it's the newer one. This causes the bug to repeat, despite having a version that fixes it.

Always ensure you're only adding a single .jar of a mod at a time, and make frequent backups. 👍
