### ISSUE TITLE
Planting Rice Server-sided crash

### ISSUE THREAD

**Issue by DizzyPrime** [vectorwing/FarmersDelight#412]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Planting Rice seems to crash the game server-side.

**Steps to reproduce:**
Server-side, try to plant rice on tilled dirt

**Expected behavior:**
Rice to be planted or not be planted.

**Logs**
https://pastebin.com/SFcT4BWk

**Screenshots**

**Mod list:**
https://pastebin.com/SFcT4BWk (Included at the bottom of the crash report)

Thank you for helping with the project! Your reports are appreciated!

**Comment by MythrilBagels** [comment]
Ima do Vector's job for him. This issue has already been fixed, upgrade to the latest version of the mod

**Comment by DizzyPrime** [comment]
Ah, server was on an older version, mb
