### ISSUE TITLE
Suggestion:  throwable tomatoes

### ISSUE THREAD

**Issue by NixityNull** [vectorwing/FarmersDelight#417]
It would be cool if tomatoes sometimes dropped rotten tomatoes (sort of like how potato crops sometimes drop poisonous potatoes) and you could throw them at people like snowballs. also they would generate in shipwreck loot instead of normal tomatoes,

**Comment by RaymondBlaze** [comment]
Rotten tomatoes does not sound very "delightful", eh? LOL
BTW, Farmer's Delight actually has [integration](https://github.com/vectorwing/FarmersDelight/tree/1.18.1/src/main/resources/data/farmersdelight/potato_cannon_projectile_types) with [Create](https://github.com/Creators-of-Create/Create): cabbages, onions, tomatoes, pumpkin slices and even pies can be used as projectiles by the Potato Canon in Create. Maybe have a try if you like?

**Comment by NixityNull** [comment]
you don't shoot tomatoes at people out of a cannon, you throw them. Shooting them with a tomato cannon is stupid and its just not the same. People don't bring tomato cannons to shoot at terrible performances, and the fact that the cannon is for all crops, not just tomatoes, entirely devalues tomatoes' status as the most iconic food to use as a projectile.

 Also saying it "isn't delightful" isn't a valid excuse, and I would prefer that you would not dismiss my ideas given you are not a contributor to the project and as such have no say in the matter.

**Comment by vectorwing** [comment]
> Also saying it "isn't delightful" isn't a valid excuse, and I would prefer that you would not dismiss my ideas given you are not a contributor to the project and as such have no say in the matter.

That was uncalled for; they were just joking. People are free to give feedback on suggestions if they want, they don't need to be a contributor to do so.
As for the suggestion: I have an idea for throwable tomatoes which still needs to be explored; might show up in a minor release sometime. Thanks for the suggestion anyway!

**Comment by thelegitdolt** [comment]
It happened
