### ISSUE TITLE
[1.18.1] Wild Rice dropping item without Shears or Silk Touch

### ISSUE THREAD

**Issue by MythrilBagels** [vectorwing/FarmersDelight#418]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
When breaking the top half of the Wild Rice block found in swamps or jungles, it drops the item "Wild Rice" which is normally obtained when breaking with Shears or Silk Touch. Breaking the bottom half works as intended. Breaking either with Shears or Silk Touch works as intended.

I have a theory that it may be Create: Alloyed as we have had issues with loot tables related to shears in the past and I wouldn't be surprised.

**Steps to reproduce:**
Find/Place Wild Rice in your world.
Break the top half of the block with an empty hand and receive the "Wild Rice" item
Break the bottom half of the block with an empty hand and receive the "Rice" item
Break either the top or bottom half of the block with Shears and receive the "Wild Rice" item

**Expected behaviour:**
Breaking either half of the Wild Rice block with an empty hand should drop the "Rice" item, rather than the "Wild Rice" item, which is supposed to be obtained when using Shears or Silk Touch

**Logs**
I looked through latest.log and there was nothing of note.

**Screenshots**

**Mod list:**
FarmersDelight-1.18.1-1.1.0-pre2
1.18.1-forge-39.0.55

alloyed-1.18.1-v0.1b (Potential cause of issue)
appleskin-forge-mc1.18-2.2.0
carryon-1.18.1-1.17.0.7
cloth-config-6.1.48-forge
configured-1.5.1-1.18.1
create-mc1.18.1_v0.4d
DripSounds-1.18-0.3.0
enchantment_lore_forge-1.0
Fallingleaves-1.18.1-1.2.4
ferritecore-4.1.1-forge
fishingreal-1.18-1.2
flywheel-forge-1.18-0.6.0
jei-1.18.1-9.1.2.54
musicdr-1.4.0
OptiFine_1.18.1_HD_U_H4
selene-1.18-1.11
sit-1.18-1.3.1
soundphysics-forge-1.18.1-1.0.4
supplementaries-1.18.1-1.1.7
twigs-1.1.4-forge

Thank you for helping with the project! Your reports are appreciated!

**Comment by FortressNebula** [comment]
Yeah the issue seemed to be the `wild_rice.json` loot table - the bottom half uses the `forge:shears` tag, but the upper doesn't. I've submitted a PR ( #419 ) sorting that out (which I've confirmed works).

**Comment by vectorwing** [comment]
Yup, that PR fixed the problem. Though I'm unsure why the described issue was caused by it... Double plant loot tables are always a headache.
Thanks for the fix, @FortressNebula! 👍
