### ISSUE TITLE
[1.16.5] Suggestion/Bug Rope is not flammable

### ISSUE THREAD

**Issue by noahcroghan** [vectorwing/FarmersDelight#420]
Rope does not catch fire, and you can place it in lava.
I feel like it should not be able to do this

**Comment by vectorwing** [comment]
Hmm, perhaps they could be. Although fire would float around them weirdly, it does make sense, and it's not a block with tile entities either.

But the rope replacing lava is totally a bug, nice catch. I'll put it on the backlog.

**Comment by vectorwing** [comment]
I decided to not make the Rope flammable, as Ladders aren't either, and it would cripple some of their use cases, combined with them not being full blocks.

That said, I fixed the lava substitution bug, and it will be added to the next 1.16 and 1.18 patches. Thank you! 👍
