### ISSUE TITLE
[1.16.5] [Suggestion] Add Roasted Coffee Beans Recipe From Raven Coffee Mod

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#421]
Hello, I just want to make a suggestion to add this to the recipes of the stove.
Coffee beans go on it and it gives roasted coffee beans. The beans are from Raven Coffee mod.

MC: 1.16.5
Forge: 36.2.20

**Comment by vectorwing** [comment]
Heyo! The Stove can only process **campfire** recipes; the mod's author would need to add such recipe for it to work on stoves.
Cases like these, I usually consider it better for the original author to implement, as I don't want to trample their mod's balance.
