### ISSUE TITLE
[1.18] Hunt and Gather advancement triggers irrationally

### ISSUE THREAD

**Issue by DWX12** [vectorwing/FarmersDelight#423]
**Description**
When I start up a world, if I have something like a sword from a start kit or even just grabbing a spawn egg from JEI, the Hunt and Gather advancement triggers.

**Steps to reproduce:**
Start world
Grab any spawn egg or any sort of weapon such as a sword from creative or JEI
Advancement should trigger

**Expected behavior:**
Advancement should trigger from crafting a Farmer's Delight knife

**Logs**
Latest log:
(https://www.toptal.com/developers/hastebin/lacuruduku.yaml)

**Screenshots**
NA

**Mod list:**
Forge: 39.0.79
Farmer's Delight: 1.18 - 1.0.3
Mod list: https://www.toptal.com/developers/hastebin/yopiqiluti.apache

**Comment by iDaemien** [comment]
Also noticed this. Something as simple as picking up seeds after breaking grass triggers this advancement.

**Comment by vectorwing** [comment]
Hmm, strange. I cannot replicate this on either a fresh install, or most of my test instances. I suspect a rogue mod interaction, or a wrongly configured datapack, is messing with it.

That said, your **Hastebin** links have expired, and I can no longer access the log and mod list to replicate your issue. Could you please re-upload them on [Pastebin](https://pastebin.com/)?

**Comment by vectorwing** [comment]
@DWX12, when you're available, please repost your logs on Pastebin, as they have expired.
I'll be closing this issue for now, since I was still unable to replicate it, but feel free to reply later.

**Comment by vectorwing** [comment]
Found the issue! The **Copper's Delight** add-on changes this advancement to include their knives, but the syntax seems outdated. Having them installed will make the advancement trigger with any item, not just knives.

I might redirect this over to them later, but feel free to do so if you'd like. 👍
