### ISSUE TITLE
[MC Version] Issue title

### ISSUE THREAD

**Issue by Kevino36** [vectorwing/FarmersDelight#43]
**Description**
Right clicking on the pot does nothing, but consistently adds an error to the log

**Steps to reproduce:**
Right click on the pot

**Expected behavior:**
A GUI should appear

**Mod list:**
GoProne (by Alpvax)
Simple Planes (by przemykomo)
Cycle Paintings (by Serilum)
Bookshelf (by DarkhaxDev)
Just Enough Items (JEI) (by mezz)
Goblin Traders (by MrCrayfish)
Nether Portal Spread (by Serilum)
Druidcraft (by VulpTheHorseDog)
Just Another Head Mod (JAHM) (by FuffledFuffles)
Sword Blocking Combat (by Fuzs_)
Dark Paintings (by DarkhaxDev)
Culinary Construct (by TheIllusiveC4)
Extra Boats (by Markus1002)
Slime Tweaks (by DarkhaxDev)
Waystones2Waypoints (by Noobanidus)
Lightning Tweaks (by jamiebrassel__)
RandomPatches (by TheRandomLabs)
Bamboo Blocks (by bageldotjpg)
Sneaky Magic (by Fuzs_)
Savage & Ravage (by Farcr)
Discernment (by Phylogeny)
XercaMod (by xerca0)
Upgrade Aquatic (by minecraftabnormals)
Storage Drawers (by Texelsaur)
No Hostiles Around Campfire (by Serilum)
Let Sleeping Dogs Lie (by ohaiiChun)
Birds Nests and Treasures (by FizixTira)
Charmonium (by svenhjol)
Taffy - Date and Forecast (TaffyDAF) (by Gerflargle)
AppleSkin (by squeek502)
Permasomnia (by Seneschal_Luwin)
Charm (by svenhjol)
Joy of Painting (by xerca0)
Double Slabs (by CJMinecraft01)
Initial Inventory (by Jaredlll08)
Cloth Config API (Forge) (by shedaniel)
Cute Kiwi Birds - new animal (by lordloss_)
Waystones (by BlayTheNinth)
Material Master (by Fuzs_)
Open Loader (by DarkhaxDev)
Straw Golem Reborn (by CommodoreThrawn)
Xaero's World Map (by xaero96)
Lithium (Forge) (by jellysquid_)
AI Improvements (by DarkGuardsman)
Spice of Life: Carrot Edition (by lordcazsius)
Bridge Maker (by GeheimagentNr1)
Beacons For All (by TheIllusiveC4)
Enchant With Mob (by bagu_chan)
MysticalLib (by EpicSquid315)
The One Probe (by McJty)
Buzzier Bees (by bageldotjpg)
Bloomful (by bageldotjpg)
Anvil Tweaks (by tfarecnim)
Bedspreads (by TheIllusiveC4)
Atmospheric (by paradiscal)
Crash Utilities (by Darkere)
Enhanced Mushrooms (by Ep1c312)
Inspirations (by KnightMiner)
Deadly End Phantoms (by the_infamous_1)
Cursed (by DarkhaxDev)
Health Overlay (by Terrails)
Swamp Expansion (by Farcr)
Shulker's Faithful Factories (Previously Cobbler) (by britishnickk)
Immersive Engineering (by BluSunrize)
Guard Villagers (by almightytallestred)
No Potion Shift (by mezz)
The Endergetic Expansion (by endergized)
V-Tweaks (by oitsjustjose)
Fairy Lights (by pau101)
Copy-Paste (by joshiejack)
Mounted Pearl - Bring your mount along when you enderpearl (by Lothrazar)
Create (by simibubi)
Sully's Mod (by hooplurd)
TerraForged (by dags_)
Mystical World (by EpicSquid315)
mGui (by mickelus)
Upsizer Mod [FORGE] (by The_Wabbit0101)
MixinBootstrap (by LX_Gaming)
Just Player Heads (by Serilum)
Named Areas (by Serilum)
Rotten Creatures (by RPorotos)
Patchouli (by Vazkii)
Save My Stronghold! (by YUNGNICKYOUNG)
Caelus API (Forge) (by TheIllusiveC4)
>Mantle (by mDiyo)
Performant (by someaddon)
Book Display (by Astavie)
InvMove (by PieKing1215)
CraftTweaker (by Jaredlll08)
YUNG's Better Caves (by YUNGNICKYOUNG)
Ensorcellation (by TeamCoFH)
Enchanted Wolves (by javisel)
OfflineSkins (by LainMI)
Dimensional Dungeons (by Catastrophe573)
Tool Belt (by gigaherz)
Overloaded Armor Bar (by tfarecnim)
Botania (by Vazkii)
Conjurer's Cookbook (by cosmicparticl)
Polymorph (Forge) (by TheIllusiveC4)
NetherPortalFix (by BlayTheNinth)
End Teleporters (by Markus1002)
Create Integration (by mc_Grimmauld)
Enigmatic Legacy (by VictorShadow_)
Music Maker Mod (by xerca0)
OptiForge (by ZekerZhayard)
Kottle (by Alex_wells)
AttributeFix (by DarkhaxDev)
>CoFH Core (by TeamCoFH)
Quark (by Vazkii)
Bag of Yurting (by Commoble)
Just Enough Resources (JER) (by way2muchnoise)
Farmer's Delight (by vectorwing)
Berry Good (by minecraftabnormals)
Cull Particles (by tfarecnim)
Combustive Fishing (by TheIllusiveC4)
Horse Debug Info (by ATE48)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Powered Nautilus Shells (by Mawathilde)
Decorative Blocks (by stohun)
Collective (by Serilum)
Backpacked (by MrCrayfish)
Covalent (by svenhjol)
Archer's Paradox (by TeamCoFH)
Better Advancements (by way2muchnoise)
Quark Oddities (by Vazkii)
Scenic (by Vaelzan)
AutoRegLib (by Vazkii)
Abnormals Core (by SmellyModder)
Incubation (by Markus1002)
Potion of Bees (by Commoble)
Global XP (by bl4ckscor3)
Fast Leaf Decay (by olafskiii)
Wandering Trader Improvements (by block_vader)
Champions (by TheIllusiveC4)
Autumnity (by Markus1002)
Simply Tea! (by EpicSquid315)
ItemZoom (by mezz)
Simple Sorcery (by deadlygolemgaming)
JEI Enchantment Info (by Phylogeny)
Curios API (Forge) (by TheIllusiveC4)
Tetra (by mickelus)
FPS Reducer (by bre2el)
Fast Furnace minus Replacement (by tfarecnim)
FastWorkbench (by Shadows_of_Fire)
>Mouse Tweaks (by YaLTeR)
iChunUtil (by ohaiiChun)
Phosphor (Forge) (by jellysquid_)
Curio of Undying (Forge) (by TheIllusiveC4)
Bottle Your Xp (by Serilum)
Xaero's Minimap (by xaero96)
Curious Shulker Boxes (Forge) (by TheIllusiveC4)
Extended Nether (by blackgear27)
Placebo (by Shadows_of_Fire)
Strange (by svenhjol)
Speed Fall Damage (by sircaptaincaleb)
Curious Elytra (Forge) (by TheIllusiveC4)
JEI Integration (by SnowShock35)

The error log shows that Straw Golem is causing the error, and while I haven't tested it yet it's likely that the mod will work fine when straw golem is not installed.

**Comment by vectorwing** [comment]
As we discussed in Discord, the issue seems indeed to occur with both Straw Golem Reborn and Farmer's Delight in the same instance. Despite no golems spawned, some circumstances cause the Cooking Pot to fail to open a GUI with these errors in the log:

https://gist.github.com/vectorwing/7fe7100e32a81a64024b05b9cf179032

The most reliable way to replicate so far:
- Place a Campfire
- Place a Cooking Pot above it
- Break the Campfire
- Right-click the Cooking Pot

I am not sure what could be causing it yet, but I'll keep an eye for solutions and update you here. Sorry for the inconvenience.

P.S.: Please try to format your issue better next time, according to the template's guidelines (e.g. title).

**Comment by vectorwing** [comment]
OK, the issue is fixed! I delegated the capabilities to LockableTileEntity for now, and it's no longer breaking the GUI. Please update to 0.1.3 on Curseforge.

Now, this has caused a different issue that I'll have to work on, but I can open that one myself. Thanks for the patience!
