### ISSUE TITLE
[1.18.1] Slight misorder in Creative

### ISSUE THREAD

**Issue by bageldotjpg** [vectorwing/FarmersDelight#431]
**Description**
It is very small but it is noticeable and bothering, Birch Cabinet should follow Spruce Cabinet instead of Oak Cabinet in registry order. In vanilla, all wood variant blocks go Oak -> Spruce -> Birch -> Jungle -> Acacia -> Dark Oak. Changing this order won't mess anything up, just fix a very mild inconsistency.

https://github.com/vectorwing/FarmersDelight/blob/fa860fd8bc0f7471c69a5abff4143f5a9ddd33ac/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L55

https://github.com/vectorwing/FarmersDelight/blob/fa860fd8bc0f7471c69a5abff4143f5a9ddd33ac/src/main/java/vectorwing/farmersdelight/common/registry/ModBlocks.java#L61

**Comment by vectorwing** [comment]
Well, there's a highly specific gripe. x)
I mean, fair. In my head it was Oak - Birch - Spruce, for some reason. I'll flip the registries around. 👍

**Comment by vectorwing** [comment]
Fixed on 1.16.5 and 1.18.1, should be out in the next patches.
