### ISSUE TITLE
Enhancement to ropes: Have a way for rope to be collected from the top

### ISSUE THREAD

**Issue by jjac31415** [vectorwing/FarmersDelight#432]
Hello,

I'm not sure if this would be possible, but it would be nice to be able to gather the rope back into your inventory from the top. Perhaps right click or sneak-right click with an empty hand on the top segment of rope would gather the lowest segment back into your inventory.

I have no idea how hard this would be, and even without it the rope is a very cool item :)
Thank you for this wonderful mod.

Jerry

**Comment by vectorwing** [comment]
This was actually in the plans, yeah! After a lot of play, I noticed ropes weren't easy to retrieve, like a water bucket can be sometimes.

LimonBlaze opened a PR introducing something similar to what I envisioned. I'll take a look and discuss it with them first and see where it goes; if it's approved, it will likely be on a minor release.

**Comment by vectorwing** [comment]
Added on commit 1538311, thanks to @LimonBlaze's PR contribution. Should be out as a feature in the next release.
