### ISSUE TITLE
[1.18.1] (Bug/suggestion) Cooked bacon from cooked porkchop

### ISSUE THREAD

**Issue by jolopapina** [vectorwing/FarmersDelight#434]
I can't cut cooked porkchop into cooked bacon on a cutting board. It seems strange to me, even though I can chop raw pork.

**Comment by vectorwing** [comment]
This is an intentional skip, as a Cooked Porkchop is too "changed" to be sliced into bacon form.

Some meat portions can only be cut prior to, or after, cooking, due to fundamental changes in the meat. For example, you cannot mince a cooked steak either. But thanks for the pointer!

**Comment by jolopapina** [comment]
ok, thanks
