### ISSUE TITLE
[1.15.2] No straw recipe

### ISSUE THREAD

**Issue by D-Bigboy-302** [vectorwing/FarmersDelight#44]
Mod Version: 1.15.2-0.1.2
Forge Version: 31.2.33

I cannot seem to find any way for obtaining straw.

**Comment by AbbyGrail** [comment]
this is not an issue, you have to break grass, grown wheat and grown rice with any type of the knives from this mod. and the advancements hints the recipe

**Comment by D-Bigboy-302** [comment]
@nrtcb You are right! Don't know how I missed that... 😅 Thank you for your time!
