### ISSUE TITLE
[1.18.1] Cooking pot breaks game/server

### ISSUE THREAD

**Issue by MrAK-v** [vectorwing/FarmersDelight#443]
Description:
If you place down a cooking pot, it will permanently corrupt the chunk you placed it in and crash the game if you're playing singleplayer and server if you're playing multiplayer.

Steps to reproduce:
Place down cooking pot

Expected behavior:
Cooking pot will be placed down, nothing else will happen

Logs: Not sure how to get these, bug report page broke as well

**Comment by MythrilBagels** [comment]
My guess is you're using an old version of the mod. I recall this issue being fixed already

**Comment by vectorwing** [comment]
Duplicate issue. You are likely playing an outdated version of FD, or you left an old version inside the `mods` folder.

Please update to the latest release (as of now, 1.0.3), and ensure **there are no other .jar files of FD in the folder**, as those will be loaded instead, and repeat the chunk corruption.
