### ISSUE TITLE
[SUGGESTION 1.18.1] Compatability with quark

### ISSUE THREAD

**Issue by jolopapina** [vectorwing/FarmersDelight#446]
Simply. Blossom and azalea cabinets. Thats all.

**Comment by vectorwing** [comment]
Hi there! Just a heads-up: suggestions are better off in the **Discussions** tab. ^^

That said, FD doesn't directly add cabinets for modded woods. Add-ons are free to create and maintain these integrations, however; an example is Abnormals Delight, which adds a few for the woods in Team Abnormals mods. Thanks for proposing, though!

**Comment by jolopapina** [comment]
Oh, sorry, I didn't notice this tab, because other minecraft githubs usually don't have it. About Abnormals Delight, this mod is outdated and doesn't support quark
