### ISSUE TITLE
Cutting board issue

### ISSUE THREAD

**Issue by washinoboku** [vectorwing/FarmersDelight#450]
I been playing Valhelsia Enhanced Vainilla 1.18 and trying to automate cutting board but doesnt aceppt items from hoppers or emit redstone singal for observer too. Dispencer interact properly and of course the player itself. This modpack has a mod name Pipe and the pipes dont recognize the board as "inventory" to connect to transfer items. There is some config to change if this was intencional?

**Comment by vectorwing** [comment]
You seem to be playing the Fabric port; this issues board is only for the Forge version of FD.
The Fabric issues board is this one:
https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues

IIRC, the Fabric port has not ported automation features for the Cutting Board as of yet, sorry. :(
