### ISSUE TITLE
[1.17.1] Chickens not eat vanilla seeds

### ISSUE THREAD

**Issue by MSandro** [vectorwing/FarmersDelight#456]
**Description**
I can't feed chickens with vanilla seeds (wheat seeds)

**Steps to reproduce:**
try to breed Chickens with normal seeds

**Comment by vectorwing** [comment]
I wasn't able to replicate this on a minimal instance contain only Farmer's Delight 1.0.2 and Forge.
Try running a new instance with only FD installed to see if the issue persists. If not, another mod is the cause.
