### ISSUE TITLE
[1.18.2] Incompatibility with "Raised" mod

### ISSUE THREAD

**Issue by cosmicgelatin** [vectorwing/FarmersDelight#461]
**Description**
Installing the mod [Raised](https://www.curseforge.com/minecraft/mc-mods/raised) causes the Comfort heart sheen to be misaligned. Raised moves the hotbar and other hud elements up, but the heart sheen from Comfort stays in the same position.

**Steps to reproduce:**
Install Raised and Farmer's Delight with the new Comfort effect.

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/8549549/latest.log)

**Screenshots**
![2022-04-24_07 26 44](https://user-images.githubusercontent.com/10190210/164974176-904867f9-4c4e-418d-9991-3adb3a04baab.png)

**Comment by vectorwing** [comment]
Yeah, the height was hardcoded due to implementation problems. I'll have to revisit the height equation here, so that it's not always on the topmost health bar.

**Comment by vectorwing** [comment]
Fixed on commit 17088ab! 👍
