### ISSUE TITLE
1.18.2 Inconsistent Comparator Readings with Organic Compost Conversion

### ISSUE THREAD

**Issue by onetoxiczombie** [vectorwing/FarmersDelight#465]
**Description**
Inconsistent Comparator readings with Organic Compost turning into Rich Soil. It updates to the correct single if you update the Comparator in some way.

**Steps to reproduce:**
Hook up a Comparator to an organic compost and just watch.

**Expected behavior:**
Quoting Vector; 
"compost should actually be giving a decreasing comparator signal
from something like 8, down to 1
with rich soil giving zero"

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/8578575/latest.log)
Log of a rich soil with a comparator output and Redstone dust in a newly created Superflat world so 70% of everything should be taken up by the Rich Soil converting.

**Screenshots**
![2022-04-27_16 02 34](https://user-images.githubusercontent.com/80938914/165652472-0cd69784-52ef-4fb6-bb18-10b9a325427d.png)
![2022-04-27_16 02 48](https://user-images.githubusercontent.com/80938914/165652491-bac9ef4f-7059-44d0-b994-76050425939e.png)
![2022-04-27_16 03 14](https://user-images.githubusercontent.com/80938914/165652502-6f299313-5c3d-4fe7-9fc3-442581fb0051.png)
![2022-04-27_16 03 30](https://user-images.githubusercontent.com/80938914/165652517-9b675984-0f56-441c-96a0-070f642661ac.png)
![2022-04-27_16 03 37](https://user-images.githubusercontent.com/80938914/165652522-d30cacf8-28b5-4f06-9748-dec8bec46917.png)

![2022-04-27_16 05 24](https://user-images.githubusercontent.com/80938914/165652527-8fd90981-73bb-4309-bf39-f10b5ad67dd6.png)
I updated the Comparator in this one

**Mod list:**
FarmersDelight-1.18.2-1.1.0.jar

**Forge Version**
Forge - 40.1.0

**Comment by vectorwing** [comment]
Nice catch! Turns out I used the wrong flags when updating their state, so it never posted block updates.
Fixed on commit aefedfd.
