### ISSUE TITLE
[1.18.2] Mekanism Meka-Tool doesn't turn Rich Soil to Rich Soil Farmland

### ISSUE THREAD

**Issue by WFPhantom** [vectorwing/FarmersDelight#467]
**Description**
Mekanism offers an end game tool that's pretty much all the tools combined including a hoe, but right-clicking a rich soil does nothing. Vanilla hoes still work, and mekanism meka-tool works on vanilla grass/dirt. If this is not an issue at your end, I will open an issue on mekanism's page

**Steps to reproduce:**
1. Get Meka-Tool
2. Right Click the Rich Soil

**Expected behavior:**
Rich Soil turns to Rich Soil Farmland

**Mod list:**
Forge 4.1.0
Farmer's Delight 1.1
Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Yeah, I had to downgrade the hoe tilling implementation until Forge updated the tool actions. :(
Fixed on commit 9daf0c8, ready for the next release.

**Comment by WFPhantom** [comment]
it still doesnt work
