### ISSUE TITLE
[1.18.2] villagers with FD trades give too large discounts

### ISSUE THREAD

**Issue by kuba26038** [vectorwing/FarmersDelight#468]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
i traded with some farmers. i then noticed that instead of offering a normal ammount of onions for one emerald, such as 24, they offered just 5 per 1. i traded some more, and it quickly became 1 for 1, without hero of the village or any zombie curing.

**Steps to reproduce:**
-get a farmer villager with FD trades
-trade with the villager a small ammount of said trade, exit the trading GUI and see his trades again
-the trades are much cheaper now 

**Expected behavior:**
discounts should scale exactly like the same for both vanilla and modded trades

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/8604839/latest.log)

**Screenshots**
![obraz](https://user-images.githubusercontent.com/81324988/166292374-abbf5d43-69e0-4a53-97ee-e3ce3d565696.png)
![obraz](https://user-images.githubusercontent.com/81324988/166292390-d4a583e9-98bc-4d56-8a57-6841c7f7fb7a.png)

**Mod list:**
[crash-2022-05-02_19.03.09-client.txt](https://github.com/vectorwing/FarmersDelight/files/8604842/crash-2022-05-02_19.03.09-client.txt)

i hope this isn't only because of some random mod i have that i already forgot about

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Turns out I misjudged which price multiplier I needed to pass; it should be 0.05, but I put 1.
Fixed on commit 1987002, will be out in the next patch.
