### ISSUE TITLE
[Suggestion] Cooking pot could be inserted and extracted arbitrary items from arbitrary face

### ISSUE THREAD

**Issue by Phoupraw** [vectorwing/FarmersDelight#471]
Only container items can play a role in the container slot, and only food ingredients can play a role in the input slot, so it is possible to distinguish the slot that an item should be inserted by item itself other than the face where it is inserted. For extracting, actually there is the only need to get the output. Therefore, if cooking pot could be inserted arbitrary items from arbitrary face, it will still work, also this will reduce needed pipes.

(I just want to make Create's mechanical arm able to directly interact with cooking pot \(￣︶￣*\)) , which looks industrially romantic.)

**Comment by vectorwing** [comment]
Thanks for sharing your thoughts; we usually keep suggestions into the **Discussions** tab.

I'm not sure I agree. Any item can play any role in a recipe; restricting which things can be an ingredient or a container would cause limitations. For example, **Pumpkin** is both an ingredient and a container.

Though we can expect a bowl or bottle to always be a container, deciding which other items are doesn't scale properly; plus, someone may want bowls/bottles as input for some unique interaction in a modpack.

The Cooking Pot does currently have issues with stack sizes from item-moving blocks, which still need to be addressed; but we have an issue compiling ideas for it: #26

**Comment by vectorwing** [comment]
Gonna close this since it isn't an issue, but feel free to reply anyway, either here on the other one! 👍
