### ISSUE TITLE
[1.18.2] Index out of bounds 128 out of 65

### ISSUE THREAD

**Issue by Ibshara** [vectorwing/FarmersDelight#476]
**Description**
Every one and a while the client would crash on startup with the message 
Failure message: Farmer's Delight (farmersdelight) encountered an error during the common_setup event phase

**Steps to reproduce:**
Unfortunately it happens 1 out of 5 or 6 times, after closing the client, and restarting the error does not occur 

**Expected behavior:**
n/a

**Logs**
https://pastebin.pl/view/6d82b83d

**Mod list:**
Running the DirewolfPack 1.18.2 
with forge v 40.1.20
and farmers Delight 1..18.2-1.1.1

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
After asking around with some folks, this could be a race condition with some libs, while the game registers FD's LootItemFunctions. It might be fixed if I enqueue them; will take a look later.

**Comment by vectorwing** [comment]
Fixed on commit 1987002, will be out in the next patch. 👍
