### ISSUE TITLE
[1.18.2] Breaking tall grass with Knives does not drop straw.

### ISSUE THREAD

**Issue by The-Arcanian** [vectorwing/FarmersDelight#479]
**Description**
Breaking tall grass with Knives does not drop straw.

**Steps to reproduce:**
Break tall grass with a knife.

**Expected behavior:**
Straw to sometimes drop.

**Logs**
[Log](https://gist.github.com/The-Arcanian/bf8833cfecda00ebb203a0fd7c96c6ef)

**Mod list:**
SuperCircuitMaker2-0.2.4+1.18.2.jar               
YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        
supermartijn642configlib-1.0.9-mc1.18.jar         
Incendium_v5.0.3.jar                              
rubidium-0.5.2a.jar                               
InsaneLib-1.4.6-mc1.18.2.jar                      
glassential-forge-1.18.2-1.2.3.jar                
ForgeEndertech-1.18.2-9.0.1.0-build.0767.jar      
darkness-forge-mc118-2.0.89.jar                   
CTM-1.18.2-1.1.4+4.jar                            
Controlling-forge-1.18.2-9.0+19.jar               
Placebo-1.18.2-6.2.1.jar                          
citadel-1.11.2-1.18.2.jar                         
YungsApi-1.18.2-Forge-2.0.8.jar                   
mightyarchitect-mc1.18.1_v0.6.jar                 
moreminecarts-1.4.5.jar                           
feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.jar
Bookshelf-Forge-1.18.2-13.0.13.jar                
Apotheosis-1.18.2-5.3.4.jar                       
jeed-1.18.2-1.10.jar                              
clickadv-1.18.2-2.5.jar                           
PickUpNotifier-v3.2.0-1.18.2-Forge.jar            
balm-3.0.3+0.jar                                  
WaterStrainer-1.18.2-13.0.0.jar                   
AdPother-1.18.2-6.0.1.0-build.0767.jar            
JustEnoughResources-1.18.1-0.13.1.141.jar         
dragonfight-1.18.2-2.0.jar                        
cloth-config-6.2.57-forge.jar                     
soundphysics-forge-1.18.2-1.0.6.jar               
revampedwolf-1.18.2-1.2.0.jar                     
TKLib-0.0.11+1.18.2.jar                           
PathToDirt-1.4.0-mc1.18.2.jar                     
EquipmentCompare-1.18.1-1.2.12.jar                
AdvancementPlaques-1.18.1-1.4.2.jar               
TinySkeletons-v3.2.1-1.18.2-Forge.jar             
ProfessionLock-1.18-1.0.0.1.jar                   
FarmersDelight-1.18.2-1.1.1.jar                   
torchmaster-18.1.0.jar                            
curious-armor-stands-1.18.1-4.0.0.jar             
entangled-1.3.11-forge-mc1.18.jar                 
AmbientSounds_FORGE_v5.0.16_mc1.18.2.jar          
supermartijn642corelib-1.0.18-forge-mc1.18.jar    
Botania-1.18.2-432.jar                            
curios-forge-1.18.2-5.0.7.0.jar                   
Patchouli-1.18.2-67.jar                           
corail_woodcutter-1.18.2-2.3.2.jar                
blockui-1.18.2-0.0.47-ALPHA.jar                   
collective-1.18.2-4.25.jar                        
time-in-a-bottle-2.1.0-mc1.18.1.jar               
villagertools-1.18-1.0.2.jar                      
seamless_loading_screen-1.18-3.0.0.jar            
YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     
tombstone-7.4.5-1.18.2.jar                        
buildersaddition-1.18.2-20220308a.jar             
constructionwand-1.18.2-2.7.jar                   
architectury-4.3.53.jar                           
moreoverlays-1.20.5-mc1.18.1.jar                  
HarderNaturalHealing-1.18.1-1.39.0.10.jar         
productivebees-1.18.2-0.9.0.4.jar                 
AdChimneys-1.18.2-8.1.0.0-build.0767.jar          
inventoryessentials-forge-1.18-4.0.1.jar          
enchantwithmob-1.18.2-4.1.0.jar                   
bwncr-forge-1.18.1-3.10.18.jar                    
FastLeafDecay-28.jar                              
YungsBetterMineshafts-1.18.2-Forge-2.1.1.jar      
voidtotem-forge-1.18.2-1.3.1.jar                  
geckolib-1.18-forge-3.0.15.jar                    
randombonemealflowers_1.18.2-1.6.jar              
BetterAdvancements-1.18.1-0.1.2.122.jar           
QuarkOddities-1.18.jar                            
inventorysorter-1.18-19.0.0.jar                   
clienttweaks-forge-1.18.1-7.1.0.jar               
StylishEffects-v3.1.0-1.18.2-Forge.jar            
rhino-forge-1802.1.12-build.171.jar               
ftb-library-forge-1802.3.6-build.115.jar          
flatbedrock-1.4.2-build.10+mc1.18.2.jar           
jei-1.18.2-9.7.0.194.jar                          
kubejs-forge-1802.5.2-build.428.jar               
VisualWorkbench-v3.3.0-1.18.2-Forge.jar           
AttributeFix-Forge-1.18.2-14.0.1.jar              
scannable-1.18.2-forge-1.7.6+135af8a.jar          
goblintraders-1.7.1-1.18.2.jar                    
ponderjs-1.18.1-1.0.4a.jar                        
HarderBranchMining-1.18.2-1.40.0.14.jar           
Fallingleaves-1.18.2-1.3.2.jar                    
FastSuite-1.18.2-3.0.2.jar                        
Clumps-forge-1.18.2-8.0.0+8.jar                   
shutupexperimentalsettings-1.0.5.jar              
Serene+Seasons-1.18.2-7.0.0.13.jar                
framedcompactdrawers-1.18-4.0.2.jar               
configured-1.5.3-1.18.2.jar                       
curioofundying-forge-1.18-5.3.0.0.jar             
create-confectionery1.18.2_v1.0.6.jar             
bedspreads-forge-1.18.1-5.1.0.5.jar               
catalogue-1.6.0-1.18.1.jar                        
blueprint-1.18.2-5.3.2.jar                        
randomium-1.18.2-1.9.jar                          
rubidium_extras-1.18.2_v1.3.1.jar                 
forge-1.18.2-40.1.19-universal.jar                
chalk-1.18.2-1.2.1.jar                            
tellme-forge-1.18.1-0.10.0.jar                    
craftingtweaks-forge-1.18.1-14.0.2.jar            
client-1.18.2-20220404.173914-srg.jar             
MobPC-1.18-1.0.0.0.jar                            
EnchantmentDescriptions-Forge-1.18.2-10.0.3.jar   
swingthroughgrass-1.18.1-1.8.0.jar                
Jade-1.18.2-5.1.0.jar                             
CreativeCore_FORGE_v2.6.9_mc1.18.2.jar            
AdLods-1.18.2-6.0.0.0-build.0342.jar              
NethersDelight-1.18.2-2.2.0.jar                   
domum_ornamentum-1.18.2-1.0.41-ALPHA-universal.jar
ceramicshears-1.18.2-1.6.1.1.jar                  
mmlib-1.0.2-1.18.2.jar                            
corn_delight-1.0.3-1.18.2.jar                     
Iceberg-1.18.2-1.0.40.jar                         
flywheel-forge-1.18-0.6.2.jar                     
alloyed-1.18.2-v1.3c.jar                          
create-mc1.18.2_v0.4.1.jar                        
createdeco-1.2.7-1.18.2.jar                       
createplus-1.18.1_v0.4.0.1.jar                    
FarmersRespite-1.18.2-1.2.0.jar                   
LegendaryTooltips-1.18.2-1.2.4.jar                
diet-forge-1.18.2-1.3.1.0.jar                     
NotEnoughBreeding-1.18.1-1.0.0.jar                
FastWorkbench-1.18.2-6.0.2.jar                    
AutoRegLib-1.7-53.jar                             
AkashicTome-1.5-20.jar                            
Quark-3.2-356.jar                                 
StorageDrawers-1.18.2-10.2.0.jar                  
entityculling-forge-mc1.18-1.5.1.jar              
Regrowth-1.18.2-1.40.0.28.jar                     
InventoryHud_[1.18].forge-3.4.4.jar               
structurize-1.18.2-1.0.379-BETA.jar               
multi-piston-1.18.2-1.2.3-ALPHA.jar               
Seed+Drop-1.18.2-2.2.0.jar                        
kubejs-create-1802.2.1-build.16.jar               
minecolonies-1.18.2-1.0.636-BETA.jar              
FastFurnace-1.18.2-6.0.3.jar                      
World+Stripper-1.18.2-3.1.0.jar                   
appleskin-forge-mc1.18-2.4.0.jar                  
lootr-1.18.2-0.2.16.52.jar                        
ferritecore-4.2.1-forge.jar                       
connectedglass-1.1.3-mc1.18.jar                   
PuzzlesLib-v3.3.3-1.18.2-Forge.jar                
Enhanced_Celestials-forge-1.18.2-2.0.6.jar        
HarderFarther-1.18.1-18.39.0.9.jar                
ChiselsBits-forge-1.18.2-1.2.87-universal.jar     
createaddition-1.18.2-20220424a.jar

**Comment by MythrilBagels** [comment]
It's dropping for me, I'd say maybe you have a mod that changes it somehow

**Comment by The-Arcanian** [comment]
Looks like it was Seed Drop. Forgot I had that. Could probably replicate it with KubeJS and not break straw drops.
