### ISSUE TITLE
[MC Version] "Cabinets" of any kind of woodmaterial crash our game. Can't open again.

### ISSUE THREAD

**Issue by stanley04520** [vectorwing/FarmersDelight#486]
**Description**
"Cabinets" of any kind of woodmaterial crash our game. Can't open again.

**Steps to reproduce:**
make cabinets and lay out it on anywhere.

**Expected behavior:**
Crash game and can't open again.

**Logs**
---- Minecraft Crash Report ----
// There are four lights!

Time: 6/3/22, 1:43 AM
Description: Unexpected error

java.lang.IllegalArgumentException: Cannot get property class_2746{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{farmersdelight:jungle_pantry}
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.isWaterlogged(HudPointedBlock.java:776)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.drawPointedBlock(HudPointedBlock.java:130)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.<init>(HudPointedBlock.java:121)
	at lordrius.essentialgui.gui.GuiSectionsList.<init>(GuiSectionsList.java:18)
	at net.minecraft.class_329.handler$zgi000$render(class_329.java:1538)
	at net.minecraft.class_329.method_1753(class_329.java:416)
	at net.minecraft.class_757.method_3192(class_757.java:858)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2688.method_11654(class_2688.java:98)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.isWaterlogged(HudPointedBlock.java:776)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.drawPointedBlock(HudPointedBlock.java:130)
	at lordrius.essentialgui.gui.hud.HudPointedBlock.<init>(HudPointedBlock.java:121)
	at lordrius.essentialgui.gui.GuiSectionsList.<init>(GuiSectionsList.java:18)
	at net.minecraft.class_329.handler$zgi000$render(class_329.java:1538)
	at net.minecraft.class_329.method_1753(class_329.java:416)

-- Affected level --
Details:
	All players: 2 total; [class_746['wavemanz'/365, l='ClientLevel', x=80.45, y=69.18, z=-143.25], class_745['stanleycheng'/9159, l='ClientLevel', x=128.03, y=64.00, z=-38.53]]
	Chunk stats: 1024, 750
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,63,-32), Section: (at 0,15,0 in 8,3,-2; chunk contains blocks 128,-64,-32 to 143,319,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 2761427 game time, 3630566 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 542851392 bytes (517 MiB) / 4104126464 bytes (3914 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2504
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7288
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21357.70
	Virtual memory used (MB): 16377.30
	Swap memory total (MB): 5120.00
	Swap memory used (MB): 269.46
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	Fabric Mods: 
		architectury: Architectury 4.4.68
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		bettervillage: Better Village 1.0.0
		biomemakeover: Biome Makeover 1.18.2-1.4.23
		cloth-config: Cloth Config v6 6.2.62
			cloth-basic-math: cloth-basic-math 0.6.1
		crockpot: Crock Pot 0.9.1+1.18.2
		duckling: Duckling 1.0.5
		essentialgui: EssentialGUI 1.7.3+1.18.2
		fabric: Fabric API 0.53.4+1.18.2
			fabric-api-base: Fabric API Base 0.4.4+d7c144a860
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.1+2373a54560
			fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
			fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
			fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
			fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.5+d82b939260
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.1+ee261a3e60
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.19+ffb2c71e60
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.16+d7c144a860
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
			fabric-item-api-v1: Fabric Item API (v1) 1.5.0+85719ab760
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.12+91896a4960
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.4+d8d7804a60
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.1+81ea5b3c60
			fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
			fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.1+032c981d60
			fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
			fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.0+2afceb2960
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
			fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
			fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.2+f4563ac860
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.6
		farmersdelight: Farmer's Delight 1.18.2-0.2.1
		geckolib3: Geckolib 3.0.42
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.10
		minecraft: Minecraft 1.18.2
		modid: Creatures Of The Snow 2.0.0+1.18.2
		orcinus: Hedgehog 1.18.2-1.1.0
		phosphor: Phosphor 0.8.1
		pigeons: Pleasant Pigeons 1.3.0
		sodium: Sodium 0.4.1+build.15
			org_joml_joml: joml 1.10.2
		travelerstitles: Traveler's Titles 1.18.2-Fabric-2.1.1
		wildlife: Wildlife 1.18.2-1.0
		xaerominimapfair: Xaero's Minimap 22.8.2
		xaeroworldmap: Xaero's World Map 1.23.1
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
	Launched Version: fabric-loader-0.14.6-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.88, NVIDIA Corporation
	Window size: 1920x1017
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Operation is not valid from the core profile.' x 1
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: 繁體中文 (台灣)
	CPU: 12x Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 2 / 8; [class_3222['wavemanz'/365, l='ServerLevel[鴨子大廚]', x=80.45, y=69.18, z=-143.25], class_3222['stanleycheng'/9159, l='ServerLevel[鴨子大廚]', x=127.16, y=64.00, z=-39.00]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental

**Screenshots**
The game crashes the moment you place it

**Mod list:**
as above.

**Comment by vectorwing** [comment]
This is not the correct issues board for the Fabric port. Please send your issue to the board linked below:
https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues
