### ISSUE TITLE
Issue with mod going into server

### ISSUE THREAD

**Issue by KlorpDotVr** [vectorwing/FarmersDelight#488]
when i start my server up with your mod i get a notification stating that i failed to connect with the issue stating

"minecraft:worldgen/configured_ferature?farmersdelight:patch_wild_carrots"

If i could get any help this would be greatly appreciated

**Comment by vectorwing** [comment]
Please follow the Bug Report template, and provide your game logs so I can help you figure out the cause.

**Comment by vectorwing** [comment]
I'm closing this issue for now because it's gotten stale. Feel free to reopen with the requested info if you still need help.
