### ISSUE TITLE
[1.18.2] Farmers Delight Log Spam

### ISSUE THREAD

**Issue by ardissaps** [vectorwing/FarmersDelight#490]
https://paste.atlauncher.com/view/83407104-2dad-4a26-8766-6a722b219c5f

**Comment by vectorwing** [comment]
This issue board is only for the **Forge** version of Farmer's Delight, and you're playing the Fabric port.
Please read the pinned issue for the Fabric issues board on BitBucket: https://github.com/vectorwing/FarmersDelight/issues/280
