### ISSUE TITLE
1.18.2 Mohist Stove Bug

### ISSUE THREAD

**Issue by DimiDDos** [vectorwing/FarmersDelight#497]
i put farmers delight on my server
and when i and other harmful mobs and players step on a stove
i and others get instantly kicked
and when a mob steps on it and takes damage
my server dies 
can u help to explain the problem to me

Mod List
alexsmobs
Citadel
Create
Emotecraft
Farmer's Delight
Framework
Moonlight Lib
MrCrayfish's Furniture Mod
MrCrayfish's Gun Mod
OptiFine_1.18.2_HD_U_H6
Plasmo Voice
Supplementaries
Xaero's World Map

**Comment by vectorwing** [comment]
After discussing this on Discord a bit, and asking other devs for assistance, this really seems to be an issue with Mohist itself.

The CraftBukkit version they use is incompatible with custom damage types: it checks only vanilla ones, and throws an exception for modded ones. Stoves use a custom damage source for their death message.

I suggest reopening this issue over at Mohist's issues board; they might be able to work on this issue from their end. 👍
