### ISSUE TITLE
[1.18.2] Cannot Place Seed on Richsoil

### ISSUE THREAD

**Issue by ardissaps** [vectorwing/FarmersDelight#498]
Can't plant on Rich Soil :
![image](https://user-images.githubusercontent.com/82106625/177004403-ddf29508-d347-40f8-a77e-236f6be0ad1e.png)

**Comment by vectorwing** [comment]
I'm gonna need more details in order to properly help you:

- Are you playing on Forge or Fabric?
- If you're using a modpack, please post your mod list, with the version of FD you're using.

**Comment by ardissaps** [comment]
> I'm gonna need more details in order to properly help you:
> 
> * Are you playing on Forge or Fabric?
> * If you're using a modpack, please post your mod list, with the version of FD you're using.

Sorry! I found the problem it was from the [MoreTags](https://modrinth.com/mod/moretags) mod! :)
