### ISSUE TITLE
[1.18.2 fabric] Cannot harvest mushroom in this colony

### ISSUE THREAD

**Issue by rejectshuati** [vectorwing/FarmersDelight#505]
When left click a colony with shears you can only acquire five mushroom rather than a colony as described in the mod introduction, silk touch doesn't work either.

**Comment by vectorwing** [comment]
This issues board is only for the **Forge** version of the mod, as I'm unable to help with the Fabric ports.
You're facing a known issue on Fabric. Please read the pinned issue and go to this board:
https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues
