### ISSUE TITLE
[MC Version] Waterlogged basket should leak

### ISSUE THREAD

**Issue by SandWoodJones** [vectorwing/FarmersDelight#506]
Please lower the water 1 or 2 pixels so that it doesn't leak
![image](https://user-images.githubusercontent.com/35671374/179375052-d97adf19-5283-43d9-b27a-959d259b265b.png)

**Comment by vectorwing** [comment]
I'm unable to control the actual shape of water blocks inside a block, like the Basket. And even if I corrected the handles upward, it would still be visibly open when facing sideways.

Sorry, this one's just gonna stay like that, relying on surface tension. But thanks for suggesting! 😄
