### ISSUE TITLE
[FABRIC 1.18.2] Cutting board doesn't work with CREATE mod.

### ISSUE THREAD

**Issue by CHERRYRACHH** [vectorwing/FarmersDelight#507]
**Description**
When trying to use the cutting board with the Create mod to, for instance, make an automated Burger farm it doesn't allow it.

**Steps to reproduce:**
Having a funnel attached to the Cutting board should allow the steak to pass through and put it on the cutting board, but it doesn't. It just sits outside the funnel.

**Expected behavior:**
Having a funnel attached to the Cutting board should allow the steak to pass through and put it on the cutting board.

**Mod list:**
We are playing with **Valhelsia: Enhanced Vanilla - 1.18** ver. 1.2.3 with MCA Reborn added in. 
( https://www.curseforge.com/minecraft/modpacks/valhelsia-enhanced-vanilla/relations/dependencies?page=10 )

**Comment by vectorwing** [comment]
Please read the pinned issue: **This board is only for issues related to the Forge version of FD.**
Fabric issues go into the following issues board: https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues

And yes, seems to be a known issue. The port's Cutting Board isn't currently compatible with item insertion such as hoppers yet.
