### ISSUE TITLE
[1.18.2] Crops do not display seasonal information

### ISSUE THREAD

**Issue by MarioSMB** [vectorwing/FarmersDelight#508]
**Description**
With the addition of Serene Seasons support there was a portion mistakenly left out: season information on the grown crops! Currently it is only displayed on the seeds.

**Steps to reproduce:**
Check the description of Wheat and Wheat Seeds, both will display their fertile season, as an example.

**Expected behavior:**
Crop fruits and vegetables should display the season just as their seeds do, thanks!

**Mod list:**
Forge 40.1.68
Farmer's Delight 1.1.2

**Comment by vectorwing** [comment]
After taking a look again over vanilla and FD items, only Wheat seems to follow this rule; other produce like Beetroot and Melon don't. But yes, it would probably be more informative to have them marked too.

I'll see if I can figure out how that's done.

**Comment by MarioSMB** [comment]
That's a strange inconsistency I hadn't noticed - going to submit a bug report to the Serene Seasons team as well, thanks.

**Comment by vectorwing** [comment]
I tried my hand at figuring this one out, but had no luck. Seems like some association is done between Wheat and Wheat Seeds, but tags didn't accomplish a similar thing. Might be done in-code.

Decided to leave this backlogged to check later, if an answer comes up. Thank you!

**Comment by MarioSMB** [comment]
No worries there, even the Serene Seasons developer is a little unsure of the inconsistency at this stage and mentioned that seasonal information should probably only be shown on seeds and plantable crops.  
Apologies for not mentioning that sooner, definitely safe to close this one!
