### ISSUE TITLE
Make support for scavenging super easy

### ISSUE THREAD

**Issue by bageldotjpg** [vectorwing/FarmersDelight#509]
It would be cool if the scavenging loot modifiers were updated to use entity type tags instead of a strict entity type to make them more easily expandable. Example:
The `farmersdelight:scavenging_feather` loot modifier could use a `farmersdelight:scavenging/feather` or `farmersdelight:scavenging_feather` or `farmersdelight:drops_feather` or `farmersdelight:scavenging/drops_feather` entity type tag, just something along those lines, instead of checking `minecraft:chicken` so other mods can just add things to those entity tags. Same could be applied to the other scavenging loot modifiers, especially like leather and string, but all of them would be useful.

**Comment by thelegitdolt** [comment]
omg bagel i'm your biggest fan
