### ISSUE TITLE
[1.19] Improvement with forge Recommended 1.19 - 41.1.0

### ISSUE THREAD

**Issue by aecuto** [vectorwing/FarmersDelight#510]
https://files.minecraftforge.net/net/minecraftforge/forge/

**Comment by gohkenytp** [comment]
What I noticed from the creator which he quotes: "It will be done when it's done."

**Comment by vectorwing** [comment]
Well, I suppose thanks for letting me know RB was released. 😆
Guess this means I can now start porting safely. And yeah, can't give an ETA on it, it will be done when it's done. 👍
