### ISSUE TITLE
Actual cold protection and Tough as Nails integration

### ISSUE THREAD

**Issue by GatoLeyo** [vectorwing/FarmersDelight#512]
So, the comfort effect protects from "cold" but when you enter powder snow you still get frozen, it would be nice if the effect protects from that kind of freezing and not only slowness. Also, if there is Tough as Nails installed the effect of ice resistance could be combined with comfort

**Comment by vectorwing** [comment]
Comfort's association with "cold and sickness" has mostly been taken out after the 1.1 update - it now focuses on replenishing health instead.

Are you playing on the 1.16 version, or on Fabric? These versions likely don't have these changes, and still use the old Comfort effect.

**Comment by vectorwing** [comment]
I'm closing this issue, as it's gotten stale. But just to conclude:
- If you're on 1.16, freezing wasn't yet implemented. If you're on the Fabric port, you might have to wait for the advancement texts to update;
- Comfort is no longer about "cold and sickness" in 1.18, hence why it doesn't protect from freezing.
- As for TaN integration, I think there was an add-on working on it before; might be worth checking if the integration can be done easily later.

Thank you! 👍
