### ISSUE TITLE
[1.19] Skillet does not display ingredient when cooking handheld

### ISSUE THREAD

**Issue by vectorwing** [vectorwing/FarmersDelight#515]
**Description**
When cooking an item on a handheld Skillet, the item is not displayed on its surface.

During the 1.19 port, the current model implementation for rendering food in a handheld Skillet has stopped working, and must be revisited. However, I was unable to do this im a timely manner, so the port will be released with this issue for now.

**I'm looking for help in regards to fixing this issue.** If anyone is looking to solve it, feel free to contact me or open a pull request.

![image](https://user-images.githubusercontent.com/5566692/182689143-d3abcce6-3763-4c25-9fea-67a21dfd67b1.png)

**Steps to reproduce:**
1. Hold a Skillet in your hand, and a cookable ingredient in the other;
2. Stand next to a heat source;
3. Hold the use key to cook the item.

**Expected behavior:**
The Skillet should render the ingredient inside of its model, similar to the 1.18 versions.

**Mod list:**
FarmersDelight-1.19-1.1.2
Forge 41.1.0+

**Comment by edgarogh** [comment]
I think I managed to get it to work. It took me like 3h but it ended up being extremely simple (it may be worth mentioning that I knew nothing about Minecraft's rendering system 3h ago too).

I will open a PR within a few hours, I'm just trying to see how I can make the code cleaner. Ping me if it looks like I somehow fell asleep and forgot about it :wink: 

![screenshot of a cod inside a held skillet](https://user-images.githubusercontent.com/46636609/217091085-0c64f761-58aa-421f-afc5-4cbf96bca071.png)

**Comment by vectorwing** [comment]
Fixed on pull request #633. Thank you, @edgarogh!
