### ISSUE TITLE
1.19 & likely 1.18: Horse does not follow you when holding Horse Feed

### ISSUE THREAD

**Issue by WitheredWasabi** [vectorwing/FarmersDelight#519]
**Description**
In 1.18, a change was introduced where horses now followed players holding golden food, to assist in easier navigation of horses across huge bodies of water introduced with the new terrain generation. Horse Feed is crafted with a Golden Carrot, and has one in the sprite, so it would be expected that the horse would show interest in players holding it.

**Steps to reproduce:**
1. Join a new world
2. Hold Horse Feed near a horse
3. Horse will be uninterested 

**Expected behavior:**
Horse follows you when holding Horse Feed.

**Logs**
https://pastebin.com/G4qWEKWU

**Screenshots**
![2022-08-05_13 01 41](https://user-images.githubusercontent.com/38932715/183153406-d666b796-3dc8-43b9-a6ac-65d18cad96cc.png)
Horse is uninterested in the Horse Feed.

**Mod list:**
FD: [Farmer's Delight 1.19 - 1.1.2](https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/3916069)
Forge: 41.1.0

**Comment by vectorwing** [comment]
I wasn't even aware this was added... huh.
I'll look into making Horse Feed do that.

**Comment by vectorwing** [comment]
Added on commit https://github.com/vectorwing/FarmersDelight/commit/3532f6cfc138d82e8a7df4077eb379a86ccfc2b2, should be out in 1.2.2 soon.
