### ISSUE TITLE
[Suggestion] Visual display of basket contents

### ISSUE THREAD

**Issue by MarioSMB** [vectorwing/FarmersDelight#525]
The basket is a nice decorative storage block, but it seems a little strange to be able to see through and inside it and not see any items in it when it's full!  
It would be a nice touch to display states of full-ness in a similar manner to compost bins, so it looks like it has a bunch of random items thrown in.

**Comment by vectorwing** [comment]
I'm converting this issue into a discussion, as that's the current place for posting suggestions. 👍
