### ISSUE TITLE
[1.19.2] Crash with 3 mods

### ISSUE THREAD

**Issue by tofika** [vectorwing/FarmersDelight#527]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Game crash with only 3 mods in folder

**Steps to reproduce:**
mc 1.19,2, forge 43.1.2
in folder mods contain three mods:
1. blueprint-1.19-6.0.6.jar
2. farmersdelight-1.19-1.1.2.jar
3. neapolitan-1.19-4.0.1.jar

**Logs**
The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Farmer's Delight (farmersdelight) encountered an error during the done event phase
Exit Code -1

**Screenshots**

**Mod list:**
        client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
        farmersdelight-1.19-1.1.2.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.1.2          |DONE      |Manifest: NOSIGNATURE
        blueprint-1.19-6.0.6.jar                          |Blueprint                     |blueprint                     |6.0.6               |DONE      |Manifest: NOSIGNATURE
        forge-1.19.2-43.1.2-universal.jar                 |Forge                         |forge                         |43.1.2              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
        neapolitan-1.19-4.0.1.jar                         |Neapolitan                    |neapolitan                    |4.0.1               |DONE      |Manifest: NOSIGNATURE

Thank you for helping with the project! Your reports are appreciated!

**Comment by murao-kun** [comment]
Neapolitan is not working on 1.19.2 yet. That the issue. If you will take it out it will work fine. If you will get Farmers Delight out, it will still crash.

**Comment by vectorwing** [comment]
Yeah, Blueprint and Neapolitan are not currently compatible with 1.19.2, according to their modpages. FD 1.1.2, however, is working on all 1.19 releases, after testing locally.

I suggest keeping an eye on these mods' updates, for now. 👍
