### ISSUE TITLE
[MC Version] Issue title

### ISSUE THREAD

**Issue by wuggyfoot** [vectorwing/FarmersDelight#532]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Upon loading into a world I am given an error "Invalid player data"
Seems to be an incompatibility with Roughly Enough Items.
I do not have this problem when using Just Enough Items.

**Steps to reproduce:**
Load into any world, existing or new.
I believe this is also reproduceable in 1.19 as well.

**Expected behavior:**
I expected to be able to log into a world.

**Logs**
https://paste.ee/p/T3ACv

**Screenshots**
https://puu.sh/JiZ3S/0130448123.png

**Mod list:**
  [✔️] AmbientSounds_FORGE_v5.0.16_mc1.18.2
  [✔️] appleskin-forge-mc1.18.2-2.4.1
  [✔️] architectury-4.9.83-forge
  [✔️] balm-3.2.0+0
  [✔️] bbs-1.0.2-1.18.2
  [✔️] BetterModsButton-v3.2.2-1.18.2-Forge
  [✔️] BetterThanBunnies-1.18-1.2.0
  [✔️] BetterThanLlamas-1.18-1.1.1
  [✔️] Bookshelf-Forge-1.18.2-13.2.49
  [✔️] BowInfinityFix-1.18.x-rv11
  [✔️] catalogue-1.6.2-1.18.2
  [✔️] clienttweaks-forge-1.18.1-7.1.0
  [✔️] cloth-config-6.2.62-forge
  [✔️] Clumps-forge-1.18.2-8.0.0+15
  [✔️] configured-1.5.4-1.18.2
  [✔️] Controlling-forge-1.18.2-9.0+22
  [✔️] craftingtweaks-forge-1.18.2-14.0.3
  [✔️] CraftPresence-1.18.2-Release-1.8.11-universal
  [✔️] CreativeCore_FORGE_v2.6.15_mc1.18.2
  [✔️] curios-forge-1.18.2-5.0.7.1
  [✔️] DeLogger-4.0.0-build.4+mc1.18.2
  [✔️] Ding-1.18-1.3.0
  [✔️] eccentrictome-1.18.2-1.8.0
  [✔️] effective_fg-1.1
  [✔️] EnchantmentDescriptions-Forge-1.18.2-10.0.8
  [✔️] extremesoundmuffler-3.28_forge-1.18.2
  [✔️] EyesInTheDarkness-1.18.2-1.2.7
  [✔️] Fallingleaves-1.18.2-1.3.2
  [✔️] FarmersDelight-1.18.2-1.1.2
  [✔️] FastLeafDecay-28
  [✔️] flatbedrock-1.4.2-build.10+mc1.18.2
  [✔️] ftbbackups2-forge-1.18.2-1.0.13
  [✔️] ftb-chunks-forge-1802.3.6-build.147
  [✔️] ftb-essentials-1802.1.7-build.42
  [✔️] ftb-library-forge-1802.3.6-build.140
  [✔️] ftb-teams-forge-1802.2.6-build.51
  [✔️] ftb-ultimine-forge-1802.3.3-build.55
  [✔️] geckolib-forge-1.18-3.0.36
  [✔️] glassential-forge-1.18.2-1.2.3
  [✔️] Iceberg-1.18.2-1.0.44
  [✔️] illuminations-forge-1.18.2-0.0.4
  [✔️] InventoryHud_[1.18].forge-3.4.4
  [✔️] inventorysorter-1.18-19.0.0
  [✔️] kubejs-forge-1802.5.4-build.535
  [✔️] LegendaryTooltips-1.18.2-1.3.0
  [✔️] light-overlay-6.0.5-forge
  [✔️] lootr-1.18.2-0.2.19.56
  [✔️] Measurements-1.18-1.2
  [✔️] mob_grinding_utils-1.18.2-0.4.44
  [✔️] modnametooltip-1.18.1-1.18.0
  [✔️] MouseTweaks-forge-mc1.18-2.21
  [✔️] NaturesCompass-1.18.2-1.9.7-forge
  [✔️] Notes-1.18.2-1.2.4
  [✔️] okzoomer-1.18.2-1.1.0
  [✔️] Patchouli-1.18.2-71.1
  [✔️] Placebo-1.18.2-6.6.3
  [✔️] polymorph-forge-1.18.2-0.44
  [✔️] PresenceFootsteps-1.18.2-1.5.0-beta2-forge
  [✔️] Prism-1.18.2-1.0.1
  [✔️] radium-0.7.10
  [✔️] radon-0.8.1
  [✔️] rer-2.5.2
  [✔️] rhino-forge-1802.1.14-build.225
  [✔️] RoughlyEnoughItems-8.3.529
  [✔️] RoughlyEnoughItems-jei-internals-workaround-8.3.529
  [✔️] RoughlyEnoughProfessions-fabric-1.18.2-1.0.1
  [✔️] RoughlyEnoughTrades-1.1
  [✔️] rubidium_extras-1.18.2_v1.3.2
  [✔️] rubidium-0.5.3a
  [✔️] screenshot-to-clipboard-1.0.9-forge
  [✔️] shutupexperimentalsettings-1.0.5
  [✔️] Snad-1.18.2-1.22.04.15a
  [✔️] SoL-Carrot-1.18.1-1.12.0
  [✔️] soundphysics-forge-1.18.2-1.0.6
  [✔️] starlight-1.0.2+forge.546ae87
  [✔️] The_Graveyard_1.9.2_(FORGE)_for_1.18.2
  [✔️] theoneprobe-1.18-5.1.1
  [✔️] Tips-Forge-1.18.2-5.0.8
  [✔️] ToastControl-1.18.2-6.0.3
  [✔️] tombstone-7.4.11-1.18.2
  [✔️] topaddons-1.18.2-2.3.0-beta
  [✔️] torohealth-1.18-forge-2
  [✔️] trashslot-forge-1.18.1-11.0.2
  [✔️] tumbleweed-1.18-0.4.12
  [✔️] uneffectual-1.18.2-1.0.0.1
  [✔️] waystones-forge-1.18.2-10.1.0
  [✔️] Xaeros_Minimap_22.13.2_Forge_1.18.2
  [✔️] XaerosWorldMap_1.26.6_Forge_1.18.2
  [✔️] YouDied-1.18.1-1.0.0.3

Thank you for helping with the project! Your reports are appreciated!

**Comment by wuggyfoot** [comment]
Game works without Roughly Enough Resources

**Comment by vectorwing** [comment]
Yeah, seems to be some conflict with RER, though the stacktrace doesn't make it clear on which end the bug happens. There seem to be a few related issues on RER's issue board, where it happens with other mods.

For now I'd just recommend disabling RER, and checking their issue board. I'll take a deeper look on this later.

**Comment by vectorwing** [comment]
After looking at a more recent issue, this does seem to be a problem with Roughly Enough Resources indeed. I'm closing this issue and referring to the new one for now: #565

**Comment by vectorwing** [comment]
Update: turns out this was on my end. I made a mistake when setting up my loot functions, which caused the error.

Fixed on commit https://github.com/vectorwing/FarmersDelight/commit/65919116d1aecbded2e4ac1429d574d6d58615f5, should be out later for 1.18, 1.19 and 1.20. 👍
