### ISSUE TITLE
[1.18.2] Make crate's dough and Farmer delight's wheat dough compatible with eachother

### ISSUE THREAD

**Issue by CZdigger146** [vectorwing/FarmersDelight#536]
As of now, it is very anoying to craft one dough in a crafting table while the create dough (less useful) is crafted by easily washing flour. Wouldn't it be much simpler to be able to use create's dough for FD's recipes?

**Comment by vectorwing** [comment]
Sorry for the late reply! Both items are now tagged as `forge:dough` as of version 1.2 of FD, and should be interchangeable in recipes. 👍
