### ISSUE TITLE
[1.18.2] Bowl Duping With Cooking Pot 

### ISSUE THREAD

**Issue by MokahTGS** [vectorwing/FarmersDelight#537]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Placing stacks of ingredients in the cooking pot, and a stack of bowls lets you create meals that automatically fill up the output slot with a finished meal.  When this slot is full with 16 meals the pot keeps cooking and starts filling up the finished meal slot.  All this time it is kicking out bowls.  When the output slot is full it doesn't use up bowls that are stacked in the bowl slot...but you keep getting bowls when the meals finish. 

Screenshot: https://www.dropbox.com/s/x1njkjpqifb9hlf/2022-09-12_20.35.24.png?dl=0

**Mod list:**
https://pastebin.com/F0wULmPu

This is the Cosmic Magitech Modpack - I'm the owner and we don't do any scripting.

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
The recipe you're preparing uses Tomato Sauce, which is contained in a bowl.

When an ingredient has a leftover container, the pot ejects it from its top side, needing to be collected by a Hopper, Basket or similar block. It's not duplicating the bowls.

For recipes like these, you can point a hopper to the pot's side, catching bowls and putting them in the bowl slot automatically. 👍
