### ISSUE TITLE
[Suggestion] Rubber Tapping

### ISSUE THREAD

**Issue by Entralia** [vectorwing/FarmersDelight#538]
Greetings, Farmer's Delight Team!

Thanks kindly for making this wonderful mod -- thoroughly enjoying it!

Just a little suggestion, perhaps explore 'Rubber Tapping' ?
Seems very apt for your quality > quantity approach.

Regardless, thanks kindly for your time & efforts!
Take care, stay safe, and be well :)

Warm Regards,
Entralia

**Comment by vectorwing** [comment]
Hi there! I'm converting this to a discussion, as this isn't technically an issue; we can continue it over in the Discussions tab.
