### ISSUE TITLE
[1.18.2] Can't plant on Rich Soil Farmland

### ISSUE THREAD

**Issue by Fannfair** [vectorwing/FarmersDelight#541]
**Description**
I cannot place any type of seeds on the rich soil farmland. The only thing that works is mushrooms on regular rich soil

**Logs**
I am unable to get any server/client logs. 

**Mod list:**
Currently running the Medieval Minecraft Fabric Modpack V12 on 1.18.2

**Comment by vectorwing** [comment]
Hey there! Sorry, this issue board is only for the **Forge** version of Farmer's Delight.
To report an issue with the Fabric port, click here: https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues
