### ISSUE TITLE
[1.18.2] Rich Soil gets reverted

### ISSUE THREAD

**Issue by xFirefalconx** [vectorwing/FarmersDelight#544]
**Description**
Rich soil disappears. 
To be more concrete, it turns back to dirt, as soon as any sort of tree grows atop of it. (Dynamic trees don't apply, they cannot grow on righ soil)
I feel like this is a possibly wanted behaviour, but I would prefer to have it toggle on/off in the future. There are some mods like the pokecube one where berry bushes occasionally turn into trees (without my permission, too), and I lose my hard-earned rich soil. 

**Steps to reproduce:**
Place rich soil, plant any type of crop/sapling that turns into a tree. Wait or use bone meal (and equivalents). Observe the rich soil disappear. 

**Expected behavior:**
There is a config file where I can tell it not to do this. Or just don't let it happen at all, if it's not intentional. 

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/9610716/latest.log)

**Screenshots**
Can't really add any. Just Rich Soil and in the next moment plop a tree and it's back to dirt.

**Mod list:**
Mod List:
BorderlessWindow-1.18-1.4.0.jar |Borderless Window |borderlesswindow |1.18-1.4.0 |DONE |Manifest: NOSIGNATURE
Kiwi-1.18.2-forge-6.1.3.jar |Kiwi |kiwi |6.1.3 |DONE |Manifest: NOSIGNATURE
supermartijn642configlib-1.1.6-forge-mc1.18.jar |SuperMartijn642's Config Libra|supermartijn642configlib |1.1.6 |DONE |Manifest: NOSIGNATURE
pamhc2trees-1.18.2-1.0.3.jar |Pam's HarvestCraft 2 - Trees |pamhc2trees |1.0.1 |DONE |Manifest: NOSIGNATURE
mcw-windows-2.0.3-mc1.18.2.jar |Macaw's Windows |mcwwindows |2.0.3 |DONE |Manifest: NOSIGNATURE
bambooeverything-1.2.7-build.14+mc1.18.2.jar |Bamboo Everything |bambooeverything |1.2.7-build.14+mc1.1|DONE |Manifest: NOSIGNATURE
sophisticatedcore-1.18.2-0.5.9.115.jar |Sophisticated Core |sophisticatedcore |1.18.2-0.5.9.115 |DONE |Manifest: NOSIGNATURE
modnametooltip-1.18.1-1.18.0.jar |Mod Name Tooltip |modnametooltip |1.18.0 |DONE |Manifest: NOSIGNATURE
waystones-forge-1.18.2-10.1.0.jar |Waystones |waystones |10.1.0 |DONE |Manifest: NOSIGNATURE
Clumps-forge-1.18.2-8.0.0+15.jar |Clumps |clumps |8.0.0+15 |DONE |Manifest: NOSIGNATURE
journeymap-1.18.2-5.8.5-forge.jar |Journeymap |journeymap |5.8.5 |DONE |Manifest: NOSIGNATURE
Controlling-forge-1.18.2-9.0+22.jar |Controlling |controlling |9.0+22 |DONE |Manifest: NOSIGNATURE
village-employment-1.18.2-1.5.1.jar |Village Employment |village_employment |1.5.1 |DONE |Manifest: NOSIGNATURE
Placebo-1.18.2-6.6.4.jar |Placebo |placebo |6.6.4 |DONE |Manifest: NOSIGNATURE
tumbleweed-1.18-0.4.12.jar |Tumbleweed |tumbleweed |1.18-0.4.12 |DONE |Manifest: NOSIGNATURE
NaturesCompass-1.18.2-1.9.7-forge.jar |Nature's Compass |naturescompass |1.18.2-1.9.7-forge |DONE |Manifest: NOSIGNATURE
EnderBags-1.18.1-8.0.0.jar |Ender Bags |ender_bags |8.0.0 |DONE |Manifest: NOSIGNATURE
configured-1.5.4-1.18.2.jar |Configured |configured |1.5.4 |DONE |Manifest: NOSIGNATURE
wooltostring-forge-1.18.2-1.0.1.jar |Wool-to-String |wooltostring |1.18.2 |DONE |Manifest: NOSIGNATURE
DungeonCrawl-1.18.2-2.3.10.jar |Dungeon Crawl |dungeoncrawl |2.3.10 |DONE |Manifest: NOSIGNATURE
farmingforblockheads-forge-1.18.2-10.0.2.jar |Farming for Blockheads |farmingforblockheads |10.0.2 |DONE |Manifest: NOSIGNATURE
Bookshelf-Forge-1.18.2-13.2.50.jar |Bookshelf |bookshelf |13.2.50 |DONE |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
BadMobs-1.18.2-13.01.jar |BadMobs |badmobs |13.01 |DONE |Manifest: NOSIGNATURE
sophisticatedbackpacks-1.18.2-3.18.24.704.jar |Sophisticated Backpacks |sophisticatedbackpacks |1.18.2-3.18.24.704 |DONE |Manifest: NOSIGNATURE
guardvillagers-1.18.2.1.4.3.jar |Guard Villagers |guardvillagers |1.4.3 |DONE |Manifest: NOSIGNATURE
creeperconfetti-3.11.jar |Creeper Confetti |creeperconfetti |3.11 |DONE |Manifest: NOSIGNATURE
FriendlyGriefing-1.18.2-1.0.1.jar |Friendly Griefing |friendlygriefing |1.0.1 |DONE |Manifest: NOSIGNATURE
keepmysoiltilled_1.18.2-1.1.jar |Keep My Soil Tilled |keepmysoiltilled |1.1 |DONE |Manifest: NOSIGNATURE
Book Fishing 1.0.0 - 1.18.2.jar |Book Fishing |book_fishing |1.0.0 |DONE |Manifest: NOSIGNATURE
balm-3.2.0+0.jar |Balm |balm |3.2.0+0 |DONE |Manifest: NOSIGNATURE
SnowRealMagic-1.18.2-forge-4.2.1.jar |Snow! Real Magic! |snowrealmagic |4.2.1 |DONE |Manifest: NOSIGNATURE
passiveendermen_1.18.2-3.0.jar |Passive Endermen |passiveendermen |3.0 |DONE |Manifest: NOSIGNATURE
blueprint-1.18.2-5.5.0.jar |Blueprint |blueprint |5.5.0 |DONE |Manifest: NOSIGNATURE
InfoDataPack-1.18.1-2.0.2.8.jar |Info DataPack |infodatapack |2.0.2.8 |DONE |Manifest: 15:a4:a3:0e:d2:f8:64:0c:a4:97:30:5f:48:ba:5f:69:f9:23:42:14:a8:5a:60:3a:b1:b1:29:1a:0a:37:3c:79
jei-1.18.2-9.7.1.255.jar |Just Enough Items |jei |9.7.1.255 |DONE |Manifest: NOSIGNATURE
carryon-1.18.2-1.17.0.8.jar |Carry On |carryon |1.17.0.8 |DONE |Manifest: NOSIGNATURE
JustEnoughResources-1.18.2-0.14.1.171.jar |Just Enough Resources |jeresources |0.14.1.171 |DONE |Manifest: NOSIGNATURE
cloth-config-6.4.90-forge.jar |Cloth Config v4 API |cloth_config |6.4.90 |DONE |Manifest: NOSIGNATURE
3dskinlayers-forge-1.4.6-mc1.18.2.jar |3dSkinLayers |skinlayers3d |1.4.6 |DONE |Manifest: NOSIGNATURE
forge-1.18.2-40.1.74-universal.jar |Forge |forge |40.1.74 |DONE |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
VendingMachine-1.18.2-1.0.0.7.jar |Vending Machine |vm |1.0.0.7 |DONE |Manifest: NOSIGNATURE
ChinjufuMod[1.18.2]6.2.3.jar |Chinjufu Mod |chinjufumod |6.2.3 |DONE |Manifest: NOSIGNATURE
Better Fishing Rods 1.0.0 - 1.18.2.jar |Better Fishing Rods |better_fishing_rods |1.0.0 |DONE |Manifest: NOSIGNATURE
JEIEnchantmentInfo-1.17.1-2.0.0.jar |JEI Enchantment Info |jeienchantmentinfo |1.17.1-2.0.0 |DONE |Manifest: NOSIGNATURE
selene-1.18.2-1.17.9.jar |Selene |selene |1.18.2-1.17.9 |DONE |Manifest: NOSIGNATURE
supplementaries-1.18.2-1.5.4.jar |Supplementaries |supplementaries |1.18.2-1.5.4 |DONE |Manifest: NOSIGNATURE
client-1.18.2-20220404.173914-srg.jar |Minecraft |minecraft |1.18.2 |DONE |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0🇩🇪ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
mcw-bridges-2.0.3-mc1.18.2.jar |Macaw's Bridges |mcwbridges |2.0.3 |DONE |Manifest: NOSIGNATURE
FarmersDelight-1.18.2-1.1.2.jar |Farmer's Delight |farmersdelight |1.18.2-1.1.2 |DONE |Manifest: NOSIGNATURE
EnchantmentDescriptions-Forge-1.18.2-10.0.9.jar |EnchantmentDescriptions |enchdesc |10.0.9 |DONE |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
TerraBlender-forge-1.18.2-1.2.0.126.jar |TerraBlender |terrablender |1.2.0.126 |DONE |Manifest: NOSIGNATURE
swingthroughgrass-1.18.2-1.9.0.jar |SwingThroughGrass |swingthroughgrass |1.18.2-1.9.0 |DONE |Manifest: NOSIGNATURE
ExtendedItemInformation-4.0.2-1.18.2.jar |Extended Item Information |eii |4.0.2-1.18.2} |DONE |Manifest: NOSIGNATURE
MouseTweaks-forge-mc1.18-2.21.jar |Mouse Tweaks |mousetweaks |2.21 |DONE |Manifest: NOSIGNATURE
betterspawnercontrol_1.18.2-1.6.jar |Better Spawner Control |betterspawnercontrol |1.6 |DONE |Manifest: NOSIGNATURE
bettersafebed-1.18-forge-a.jar |Better Safe Bed |bettersafebed |1.18-forge-a |DONE |Manifest: NOSIGNATURE
Beekeeper-1.18.2-1.0.0.4.jar |Beekeeper |bk |1.0.0.4 |DONE |Manifest: NOSIGNATURE
pamhc2crops-1.18.2-1.0.4.jar |Pam's HarvestCraft 2 - Crops |pamhc2crops |1.0.1 |DONE |Manifest: NOSIGNATURE
supermartijn642corelib-1.0.19-forge-mc1.18.jar |SuperMartijn642's Core Lib |supermartijn642corelib |1.0.19 |DONE |Manifest: NOSIGNATURE
skylightlanterns-1.18.2-1.0.0.jar |Skylight Lanterns |skylightlanterns |1.0.0 |DONE |Manifest: NOSIGNATURE
smoothboot-mc1.18.2-1.0.1.jar |Smooth Boot (Reloaded) |smoothboot |1.0.1 |DONE |Manifest: NOSIGNATURE
PokemonPaintings-1.18.2.0.1.jar |Pokemon Paintings |pokemon_paintings |1.0.0 |DONE |Manifest: NOSIGNATURE
pamhc2foodextended-1.18.2-1.0.4.jar |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended |1.0 |DONE |Manifest: NOSIGNATURE
memorysettings-1.18.2-2.2.jar |memorysettings mod |memorysettings |1.18.2-2.2 |DONE |Manifest: NOSIGNATURE
pamhc2foodcore-1.18.2-1.0.3.jar |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore |1.0.1 |DONE |Manifest: NOSIGNATURE
collective-1.18.2-4.64.jar |Collective |collective |4.64 |DONE |Manifest: NOSIGNATURE
polymorph-forge-1.18.2-0.45.jar |Polymorph |polymorph |1.18.2-0.45 |DONE |Manifest: NOSIGNATURE
AutoRegLib-1.7-53.jar |AutoRegLib |autoreglib |1.7-53 |DONE |Manifest: NOSIGNATURE
AkashicTome-1.5-20.jar |Akashic Tome |akashictome |1.5-20 |DONE |Manifest: NOSIGNATURE
BetterThirdPerson-Forge-1.18.2-1.8.1.jar |Better Third Person |betterthirdperson |1.8.1 |DONE |Manifest: NOSIGNATURE
villagebellrecipe_1.18.2-1.4.jar |Village Bell Recipe |villagebellrecipe |1.4 |DONE |Manifest: NOSIGNATURE
Regrowth-1.18.2-1.40.0.31.jar |Regrowth |regrowth |1.18.2-1.40.0.31 |DONE |Manifest: NOSIGNATURE
pokecube-aio-1.18.2-3.17.12.jar |Pokécube Core |pokecube |3.17.12 |DONE |Manifest: NOSIGNATURE
Level-One-MC1.18.2-v1.5.0.jar |Level One |level_one |1.5.0 |DONE |Manifest: NOSIGNATURE
better-loading-screen-1.4.0.jar |Better Loading Screen |better_loading_screen |1.4.0 |DONE |Manifest: NOSIGNATURE
bamboo2-1.18.1_0.4.jar |Bamboo 2: Modded Boogaloo |bamboo2 |1.18.1_0.4 |DONE |Manifest: d9:5b:38:8a:ff:8c:c9:4e:89:6a:79:60:e4:89:ad:f0:3f:6e:91:48:3d:4f:71:d5:42:18:2a:dd:01:b1:b5:33
mcw-roofs-2.2.0-mc1.18.2-forge.jar |Macaw's Roofs |mcwroofs |2.2.0 |DONE |Manifest: NOSIGNATURE
moreoverlays-1.20.9-mc1.18.2.jar |More Overlays Updated |moreoverlays |1.20.9-mc1.18.2 |DONE |Manifest: NOSIGNATURE
autoplant-1.18.2-1.0.0.jar |autoplant |autoplant |1.18.2-1.0.0 |DONE |Manifest: NOSIGNATURE
bettermending-forge-1.2.1+1.18.2.jar |Better Mending |bettermending |1.2.1 |DONE |Manifest: NOSIGNATURE
VillagersRespawn-1.18.1-1.39.0.5.jar |Villagers Respawn Mod |villagersrespawn |1.18.1-1.39.0.5 |DONE |Manifest: NOSIGNATURE
ExNihiloSequentia-1.18.2-20220818-010806.jar |Ex Nihilo: Sequentia |exnihilosequentia |1.18.2-20220818-0108|DONE |Manifest: NOSIGNATURE
benched-1.2.1-mc1.18.jar |Benched |benched |1.2.1 |DONE |Manifest: NOSIGNATURE
FastLeafDecay-28.jar |FastLeafDecay |fastleafdecay |28 |DONE |Manifest: NOSIGNATURE
exoticbirds-1.18.2-1.8.0.jar |Exotic Birds |exoticbirds |1.8.0 |DONE |Manifest: NOSIGNATURE
Disenchanting-forge-1.18.2-2.1.0.jar |Disenchanting |disenchanting |1.18.2-2.1.0 |DONE |Manifest: NOSIGNATURE
DynamicTrees-1.18.2-0.11.0-Alpha2.jar |Dynamic Trees |dynamictrees |1.18.2-0.11.0-Alpha2|DONE |Manifest: NOSIGNATURE
DynamicTreesPlus-1.18.2-0.1.0-Alpha1.jar |Dynamic Trees Plus |dynamictreesplus |1.18.2-0.1.0-Alpha1 |DONE |Manifest: NOSIGNATURE
so_many_enchants-1.6.0 (1.18).jar |So Many Enchants!!! |so_many_enchants |1.6.0 (1.18) |DONE |Manifest: NOSIGNATURE
betterfoliage-3.1.3.jar |Better Foliage |betterfoliage |3.1.3 |DONE |Manifest: NOSIGNATURE
BiomesOPlenty-1.18.2-16.0.0.109-universal.jar |Biomes O' Plenty |biomesoplenty |1.18.2-16.0.0.109 |DONE |Manifest: NOSIGNATURE
DynamicTreesBOP-1.18.2-3.0.0-ALPHA1.jar |Dynamic Trees for Biomes o' Pl|dtbop |1.18.2-3.0.0-ALPHA1 |DONE |Manifest: NOSIGNATURE
Quark-3.2-358.jar |Quark |quark |3.2-358 |DONE |Manifest: NOSIGNATURE
xptome-1.18.2-2.1.6.jar |XP Tome |xpbook |2.1.6 |DONE |Manifest: NOSIGNATURE

**Comment by vectorwing** [comment]
The tough part about creating a custom "dirt" is accounting for trees converting it back into normal dirt. ;_;

I had a mixin to solve this for Giant Spruce trees, but it apparently uses an entirely different mechanism than normal, making it fail against Azalea trees, for example. I can probably mixin into the more generic `setDirtAt()` method and see if it covers more use cases, including from the mods you described above.

**Comment by xFirefalconx** [comment]
Late reply but maybe you could get inspiration from the "KeepMySoilTilled" mod, perhaps they found a solution to this sort of issue. I figured the soil gets tilled even if it wasn't before in that mod, so maybe they use a replacement or state command to do so. That behaviour also applies to rich soil being tilled though so maybe it looks for the tilled variant and replaces, regardless of mod version or normal dirt 🤔 I believe that it's a really difficult matter. Thank you for taking the time to look at it.

**Comment by vectorwing** [comment]
@xFirefalconx, this issue has been addressed as of update 1.2.1 of FD. There is now a mixin to prevent most tree growth methods from changing Rich Soil blocks under them, which currently applies to Giant Spruce and Azalea; this should fix most modded interactions as well.

Since this issue is old, I'll be closing it as done. If even with 1.2.1 this problem still occurs, feel free to reply and I'll reopen.

**Comment by xFirefalconx** [comment]
![grafik](https://github.com/vectorwing/FarmersDelight/assets/106652912/5feed2c8-3a33-4b07-985e-81bd25f3e892)

FD 1.2.1 - tested with spruce saplings. Gets transformed to rooted dirt. The whole line consisted of Rich Soil so this doesn't work sadly. Will do more tests to check other tree species and modded ones if necessary, let me know. 


Large trees generate podzol underneath. Maybe a mod incompatibility? Shall I add my modlist? 
![grafik](https://github.com/vectorwing/FarmersDelight/assets/106652912/c9638237-4894-4292-8a33-57831238fda5)

**Comment by vectorwing** [comment]
Small Spruce trees should not be generating Rooted Dirt underneath them... this doesn't seem like vanilla behaviour.

Could you test this again in a minimal instance (FD only)? There might be a mod changing the behavior of tree growth and forcing such blocks to generate.

**Comment by xFirefalconx** [comment]
Alright I'll investigate this situation further. Will take me a bit to find out which mod does that, I got 300+ mods in my pack as of now. I'll inform you once I found out what is going on.

**Comment by xFirefalconx** [comment]
Can confirm, it's a mod compatibility/setting issue, vanilla spruce trees don't overwrite the soil on vanilla. More updates on the situation once I found the culprit.

**Comment by xFirefalconx** [comment]
So, it is not one but multiple mods. Number yet to figure out. 

**Verdure** is part of the problem. https://www.curseforge.com/minecraft/mc-mods/verdure
I'll update you once I figured out who else is changing the behaviour here. I tested it a couple of times and this mod definitely alters the rich soil to rooted dirt. When just putting FD and Verdure alone, nothing happens though.

**Comment by xFirefalconx** [comment]
An observation I made: 
I took screenshots of both the situation when the soil gets replaced vs. when it's fine. 
There are still "replacable" tags on the block. 
Refer to the lists and screenshots I put in here:
https://github.com/xFirefalconx/Royal-Equines-Petrified-Magic/issues/23#issuecomment-1584140126
bugged: ![grafik](https://github.com/vectorwing/FarmersDelight/assets/106652912/2e189a87-8b0d-4ad5-9727-9edf6f780247)


not bugged: ![grafik](https://github.com/vectorwing/FarmersDelight/assets/106652912/16ca4c1a-a8da-48e1-a5f0-b5847acdf598)


I have a proposal regarding this, can there be a correlation between these item tags that refer to dirt and replacable and the soil getting downgraded to rooted soil? 

I have been testing multiple mod combinations the past days and there are strange things happening like 
multiple tooltip mods being part of the issue afaik but i cannot reproduce its exact outcome yet because I am still missing a mod that is core of the problem. i am desperately trying to remove parts from my modpack just to get put back to square one because for some unknown reason multiply situations chain together to build this huge mess of a cluster bug. I would also like to keep all mods I am using but I don't know what they do, why Sophisticated Storage is part of the problem, or Dynamic trees, Why beehive and anvil tooltip have a say in this. 
I could honestly use some help, I feel like it's so much to test I likely will take weeks to find the cause on my own. As you can also read in the issue I got on my modpack right now. It seems to be a really rare situation, but something is tampering with this behaviour, either by causing an issue, or overwriting important information, i don't know. I could say more if I could test with a few debug messages, but that's probably not possible. 
I'm currently at 190 (+/-) untested/not verified mods out of total 308 😕
I suspect about 5 mods now, or even more to cause this issue. I still cannot recreate it on a pack where I just put FD and the mods I suspect. Recreating the issue itself with just a fresh pack where I dump **all** 190 current mods, works. It means at least that configs don't have to do much with the issue, that's the only relief of the current armaggeddon..
Hope this info is somewhat helpful to you, I will struggle onward in hope I find the exact cause, but my hopes are growing slimmer by the day.

**Comment by xFirefalconx** [comment]
![grafik](https://github.com/vectorwing/FarmersDelight/assets/106652912/4f54c123-fd21-468a-ab87-39bdafede40d)
Apparently Verdure is the culprit here, upon disabling this the issue is gone. 
I have to see what else I can do about the buggy behaviour but at least your mod is not affected if I use it this way. 
Glad to at least have this option now.
