### ISSUE TITLE
[1.18.2 - FORGE] - Client Crash with "Create" during load.

### ISSUE THREAD

**Issue by Jusey1** [vectorwing/FarmersDelight#546]
The new version of Farmer's Delight (1.2.0) that just came out crashes with Create (version 0.5.0.d) while playing 1.18.2 FORGE version 40.1.80. The crash log itself specifically mentions "Failed to load description for particle create:soul_perimeter", which implies that it is an issue with Create itself to me BUT the crash only happens if Farmer's Delight V1.2.0 is installed. Downgrading Farmer's Delight back to V1.1.2 fixes the issue and everything works as expected and normally during load.

However, since this has something to do with the client's GUI it seems like. I assume this is due to an issue with the newly implemented Recipe Book GUIs for the cookpot and other things in 1.2.0... However, if this is just a missing issue on Create's side and this new update just simply opened up the problem, then I do apologize for posting here.

Crash log should be attached.
[crash-2022-09-20_22.07.53-client.txt](https://github.com/vectorwing/FarmersDelight/files/9612387/crash-2022-09-20_22.07.53-client.txt)

**Comment by vectorwing** [comment]
Seems to be related to a particle load with the Peculiar Bell... though it doesn't explain who exactly is failing the check. It could be revealing some bugged mod interaction via mixins.
I tried loading them up together on a lightly modded instance, but couldn't get this issue to show up, assuming this is the case:

![image](https://user-images.githubusercontent.com/5566692/191401656-fd27945c-74f5-4d81-894c-3ad11ecb553b.png)

Some quick suggestions:
- Try disabling Rubidium and/or any shaders you have;
- Try putting both mods together on a minimal instance, and see if the issue persists.

**Comment by Jusey1** [comment]
So, with Rubidium + Ruby Extras, Farmer's Delight, and Create. It loads just fine. Which means it is a three way mixin problem then. I'ma go through the crash log again and see what mixins it specifically mentions to figure out the culprit (assuming it is that).

**Comment by Jusey1** [comment]
The issue is "Corn Delight", which is the corn addon for Farmer's Delight and also has optional support for Create, which is why the three are interconnected. I also learn that the crash can still happen even without Create installed (it'll blame the particle "farmersdelight:star"). So, this is a Corn Delight issue. Most likely it just needs to update for the newer version? Which is weird cause the other FD addon works just fine.

Crash log being completely useless made this so confusing cause I don't think Corn Delight was mentioned at all in the main crash log itself, just on the mod list.

**Comment by vectorwing** [comment]
Ah, nice find! 👍 

Yeah, if it's caused by an add-on, then it's to be expected. Minor releases (such as 1.2.0) carry the chance of breaking add-ons which depend on internal code. They'll need to update some stuff in order to work again.

My suggestion, then, is to try and generate a crash log upon the addition of Corn Delight, and reporting the issue to the respective dev, so they can take a look at it.
