### ISSUE TITLE
[1.18.2] Crash on latest update (1.2.0) with Cultural Delights addon

### ISSUE THREAD

**Issue by Flugel3** [vectorwing/FarmersDelight#547]
**Description**
Crashes on launch with the cultural delights addon for farmer's delight...

**Steps to reproduce:**
Just install Cultural delights with the most recent version of Farmer's delight (1.2.0)

**Logs**
[crash-2022-09-20_22.47.11-fml.txt](https://github.com/vectorwing/FarmersDelight/files/9612534/crash-2022-09-20_22.47.11-fml.txt)

**Mod list:**
Post a list of your mods here, **Forge and Farmer's Delight versions are mandatory!**
You can generate a mod list by forcing a crash. In your game, hold F3+C for 10 seconds, then check your logs; the list of mods will be by the end.

[Modlist.txt](https://github.com/vectorwing/FarmersDelight/files/9612554/Modlist.txt)

**Screenshot:**
<img width="902" alt="Farmerdelightcrash" src="https://user-images.githubusercontent.com/78325529/191404163-91f9fed6-ea61-4c2a-946b-39f036646c02.png">

**Comment by vectorwing** [comment]
Add-ons will usually break after a minor version bump, as they might depend on internal code which might have changed.
The Cultural Delights devs are aware of it, and might work on adapting to the new version soon. Thanks for reporting, though! 👍

**Comment by Flugel3** [comment]
I'll let them know then :) Thank you.
