### ISSUE TITLE
[1.18.2] Crash at the startup

### ISSUE THREAD

**Issue by emanuele246gi** [vectorwing/FarmersDelight#549]
**Description**
After I updated to the latest version of the mod, it crashed right after I launched the game

**Steps to reproduce:**
Update to the latest version, then (probably) get my modlist and you will not be able to launch the game

**Expected behavior:**
To get at the main menu

**Logs**
(https://pastebin.com/xyV7cUMe)

**Mod list:**
It's in the crash report

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
This particle crash seems to be an issue related to Corn Delight. Due to the minor version bump, add-ons usually need to update their code in order to be compatible with the latest version.

I believe the add-on dev is already aware of it. Thank you! 👍

**Comment by emanuele246gi** [comment]
Oh okay, thank you!

**Comment by 0999312** [comment]
> Oh okay, thank you!

Corn Delight Fixed, update your version to 1.0.6-1.18.2
