### ISSUE TITLE
[1.18.2] My server says my mod version is missmatching but they're the same version

### ISSUE THREAD

**Issue by xXMolgadoGamer01Xx** [vectorwing/FarmersDelight#553]
**Description**
I'm trying to connect to my server (forge 40.1.80) with Farmer's Delight 1.2.0 but the server refuses my connection because version missmatching, but I have the same version in client and in server.

**Steps to reproduce:**
Just try to connect to a server with the forge version and the farmers delight version from above.

**Expected behavior:**
The game let's me connect to the server

**Logs**
Client side log: https://mclo.gs/wcdwhtt
Server side log: https://mclo.gs/00RFNmX

**Screenshots**
![image](https://user-images.githubusercontent.com/24871116/191883098-f35d52f7-626e-4c8d-b95f-5cecc49e131d.png)

**Mod list:**
	Mod List: 
		saturn-mc1.18.2-0.0.1.jar                         |Saturn                        |saturn                        |0.0.1               |DONE      |Manifest: NOSIGNATURE
		musictriggers-1.18.2-5.4-hf.jar                   |Music Triggers                |musictriggers                 |1.18.2-5.4          |DONE      |Manifest: NOSIGNATURE
		GlobalGameRules-1.18.1-6.0.0.5.jar                |Global GameRules              |globalgamerules               |6.0.0.5             |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0.1  |DONE      |Manifest: NOSIGNATURE
		infernal-expansion-1.18.2-2.5.0.jar               |Infernal Expansion            |infernalexp                   |2.5.0               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5.jar              |Player Animator               |playeranimator                |0.3.5               |DONE      |Manifest: NOSIGNATURE
		Architects-Palette-1.18.2-1.2.0.jar               |Architect's Palette           |architects_palette            |1.1.2               |DONE      |Manifest: NOSIGNATURE
		windowlogging-mc1.18.2_v0.0.9.jar                 |Windowlogging                 |windowlogging                 |0.0.8               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.3a.jar                               |Rubidium                      |rubidium                      |0.5.3a              |DONE      |Manifest: NOSIGNATURE
		piglinproliferation-1.0.0.jar                     |Piglin Proliferation          |piglinproliferation           |1.0.0               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE
		ExtraShieldEnchantments-1.18.2-v1.0.1.jar         |Extra Shield Enchantments     |extra_shield_enchantments     |1.0.1               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.0.8.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.0.8  |DONE      |Manifest: NOSIGNATURE
		wildbackport-1.2.3.jar                            |TheWildBackport               |wildbackport                  |1.2.3               |DONE      |Manifest: NOSIGNATURE
		MaxHealthFix-Forge-1.18.2-5.0.1.jar               |MaxHealthFix                  |maxhealthfix                  |5.0.1               |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		jeed-1.18.2-1.11.jar                              |Just Enough Effect Description|jeed                          |1.18.2-1.11         |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.2.1-1.18.2.jar                     |Bygone Nether                 |bygonenether                  |1.2.1               |DONE      |Manifest: NOSIGNATURE
		balm-3.2.0+0.jar                                  |Balm                          |balm                          |3.2.0+0             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		hedgehog-1.18.2-1.1.0.jar                         |Hedgehog                      |hedgehog                      |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		enchanting_overhauled-1.1.0.jar                   |Enchanting Overhauled         |enchanting_overhauled         |1.1.0               |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.18.2-2.4.6.jar                    |Structure Gel API             |structure_gel                 |2.4.6               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		locallooks-1.2.1-1.18.2.jar                       |Local Looks                   |locallooks                    |1.2.1               |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.18.2-Forge-2.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		volcanic_caverns-1.18.2-1.1.2.jar                 |Volcanic Caverns              |volcanic_caverns              |1.18.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		shulker_enchantments-3.0.1.jar                    |Shulker Enchantments          |shulker_enchantments          |3.0.1               |DONE      |Manifest: NOSIGNATURE
		dungeons_enhanced-1.18.2-3.2.1.jar                |Dungeons Enhanced             |dungeons_enhanced             |3.2.1               |DONE      |Manifest: NOSIGNATURE
		corail_woodcutter-1.18.2-2.3.3.jar                |Corail Woodcutter             |corail_woodcutter             |2.3.3               |DONE      |Manifest: NOSIGNATURE
		Simply Spawners 1.18.2 v1.3.jar                   |Simply Spawners               |simplyspawners                |1.3                 |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		overweightfarming-1.18.2-1.6.0-forge.jar          |Overweight Farming            |overweight_farming            |1.18.2-1.6.0-forge  |DONE      |Manifest: NOSIGNATURE
		TheWildBackportAdditions-1.18.2-1.0.2.jar         |The Wild Backport Additions   |wild_backport_additions       |1.0.0               |DONE      |Manifest: NOSIGNATURE
		architectury-4.9.84-forge.jar                     |Architectury                  |architectury                  |4.9.84              |DONE      |Manifest: NOSIGNATURE
		windswept-1.18.2-1.0.0.jar                        |Windswept                     |windswept                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		sullysmod-1.1.4-beta.jar                          |Sully's Mod                   |sullysmod                     |1.1.4-beta          |DONE      |Manifest: NOSIGNATURE
		cursery-1.18.2-2.9.jar                            |Cursery Mod                   |cursery                       |1.18.2-2.9          |DONE      |Manifest: NOSIGNATURE
		HopoBetterMineshaft-1.18.2-1.1.3b.jar             |HopoBetterMineshaft           |hopo                          |1.1.3               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.39.jar                    |GeckoLib                      |geckolib3                     |3.0.39              |DONE      |Manifest: NOSIGNATURE
		naturalist-forge-1.1.1-1.18.2.jar                 |Naturalist                    |naturalist                    |1.1.1               |DONE      |Manifest: NOSIGNATURE
		sliceanddice-1.1.0.jar                            |Create Slice & Dice           |sliceanddice                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		TradingPost-v3.2.0-1.18.2-Forge.jar               |Trading Post                  |tradingpost                   |3.2.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		justverticalslabs-1.18.2-3.2.0.3-forge.jar        |Just Vertical Slabs           |justverticalslabs             |3.2.0.3             |DONE      |Manifest: NOSIGNATURE
		depthmeter-1.18.2-1.0.0.jar                       |DepthMeter                    |depthmeter                    |1.18.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.18.2-1.4.31.jar             |Biome Makeover                |biomemakeover                 |1.18.2-1.4.31       |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
		enhanced_mushrooms-forge-4.0.1+1.18.2.jar         |Enhanced Mushrooms            |enhanced_mushrooms            |4.0.1               |DONE      |Manifest: NOSIGNATURE
		the-conjurer-1.18.2-1.1.1.jar                     |The Conjurer                  |conjurer_illager              |1.1.1               |DONE      |Manifest: NOSIGNATURE
		differentiate-1.18.2-1.0.3.jar                    |Differentiate                 |differentiate                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		Map Atlases-forge-1.18.2-2.1.0.jar                |Map Atlases                   |map_atlases                   |2.1.0               |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |DONE      |Manifest: NOSIGNATURE
		Serene Seasons-1.18.2-7.0.0.13.jar                |Serene Seasons                |sereneseasons                 |1.18.2-7.0.0.13     |DONE      |Manifest: NOSIGNATURE
		starlight-1.0.2+forge.546ae87.jar                 |Starlight                     |starlight                     |1.0.2+forge.83663de |DONE      |Manifest: NOSIGNATURE
		everycomp-1.18.2-1.5.12.jar                       |Every Compat                  |everycomp                     |1.18.2-1.5.12       |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.3.1  |DONE      |Manifest: NOSIGNATURE
		Block Swap-forge-1.18.2-1.0.1.jar                 |Block Swap                    |blockswap                     |1.0.1               |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |DONE      |Manifest: NOSIGNATURE
		allurement-1.18.2-2.0.0.jar                       |Allurement                    |allurement                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		incubation-1.18.2-2.0.2.jar                       |Incubation                    |incubation                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.18.2-4.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |4.0.0               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.18.2-5.0.0.jar                       |Berry Good                    |berry_good                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		cookielicious-1.18.2-2.4.3.jar                    |Cookielicious                 |cookielicious                 |1.18.2-2.4.3        |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.190.jar             |CraftTweaker                  |crafttweaker                  |9.1.190             |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.80-universal.jar                |Forge                         |forge                         |40.1.80             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		chalk-1.18.2-1.3.2.jar                            |Chalk                         |chalk                         |1.3.2               |DONE      |Manifest: NOSIGNATURE
		neapolitan-1.18.2-3.0.0.jar                       |Neapolitan                    |neapolitan                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.5.jar                  |Supplementaries               |supplementaries               |1.18.2-1.5.5        |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		upgrade_aquatic-1.18.2-4.0.0-beta1.jar            |Upgrade Aquatic               |upgrade_aquatic               |4.0.0               |DONE      |Manifest: NOSIGNATURE
		trade-cycling-forge-1.18.2-1.0.2.jar              |Trade Cycling                 |trade_cycling                 |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		revamped_phantoms-forge-0.2.3.jar                 |Revamped Phantoms             |revamped_phantoms             |0.2.3               |DONE      |Manifest: NOSIGNATURE
		dynamic_asset_generator-forge-1.18.2-0.6.3.jar    |DynamicAssetGenerator         |dynamic_asset_generator       |0.6.3               |DONE      |Manifest: NOSIGNATURE
		excavated_variants-forge-1.18.2-0.6.4.jar         |Excavated Variants            |excavated_variants            |0.6.4               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		pollen-forge-1.5.0+1.18.2.jar                     |Pollen                        |pollen                        |1.5.0               |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.4.1+1.18.2.jar               |Better Combat                 |bettercombat                  |1.4.1+1.18.2        |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.0.4+1.18.2.jar                 |Combat Roll                   |combatroll                    |1.0.4+1.18.2        |DONE      |Manifest: NOSIGNATURE
		trulytreasures-forge-1.18.1-2.2.3.jar             |Truly Treasures               |trulytreasures                |1.18.1-2.2.3        |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.4.jar                       |Jade                          |jade                          |5.2.4               |DONE      |Manifest: NOSIGNATURE
		ArmorPoser-forge-1.18.2-1.0.4.jar                 |Armor Poser                   |armorposer                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		enchantment_enhancements-1.18.2-1.1.0.jar         |Enchantment Enhancements      |enchantment_enhancements      |1.18.1-1.1.0        |DONE      |Manifest: NOSIGNATURE
		Oreganized_Mod-1.18.2-1.0.5.jar                   |Oreganized                    |oreganized                    |1.18.2-1.0.5        |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		personality-1.18.2-2.0.0.jar                      |Personality                   |personality                   |2.0.0               |DONE      |Manifest: NOSIGNATURE
		mmlib-1.1.3-1.18.2.jar                            |Mysterious Mountain Lib       |mmlib                         |1.1.3-1.18.2        |DONE      |Manifest: NOSIGNATURE
		corn_delight-1.0.6-1.18.2.jar                     |Corn Delight                  |corn_delight                  |1.0.6-1.18.2        |DONE      |Manifest: NOSIGNATURE
		BrewinAndChewin-1.18.2-1.0.1.jar                  |Brewin' and Chewin'           |brewinandchewin               |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.d.jar                         |Create                        |create                        |0.5.0.d             |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		brutalbosses-1.18.2-5.4.jar                       |brutalbosses mod              |brutalbosses                  |1.18.2-5.4          |DONE      |Manifest: NOSIGNATURE
		autumnity-1.18.2-3.0.0-beta3.jar                  |Autumnity                     |autumnity                     |3.0.0               |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.18.2-3.0.1.jar                |Abnormals Delight             |abnormals_delight             |3.0.1               |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		hardcorerevival-forge-1.18.2-8.0.1.jar            |Hardcore Revival              |hardcorerevival               |8.0.1               |DONE      |Manifest: NOSIGNATURE
		canary-mc1.18.2-0.0.5.jar                         |Canary                        |canary                        |0.0.5               |DONE      |Manifest: NOSIGNATURE
		global_packs-forge-1.18.2-1.12.3_forge.jar        |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.12.3_forge        |DONE      |Manifest: NOSIGNATURE
		lootr-1.18.2-0.2.21.58.jar                        |Lootr                         |lootr                         |0.2.21.58           |DONE      |Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		PuzzlesLib-v3.3.5-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.3.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		bettergolem-1.18.2-1.1.0.jar                      |Better Golem                  |bettergolem                   |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		step-1.18-1.1.0.jar                               |Step                          |step                          |1.1.0               |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.4.2-1.18.2.jar          |Domestication Innovation      |domesticationinnovation       |1.4.2               |DONE      |Manifest: NOSIGNATURE
		defaultoptions-forge-1.18.2-14.1.1.jar            |Default Options               |defaultoptions                |14.1.1              |DONE      |Manifest: NOSIGNATURE

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Hmm, that's quite strange! Do you have **more than one version of FD** in your mods folder, per chance? This can sometimes confuse Forge and cause it to load the mod wrongly.

**Comment by xXMolgadoGamer01Xx** [comment]
Nope. I only have 1 version on my server and on my client

**Comment by vectorwing** [comment]
@xXMolgadoGamer01Xx, sorry for the late reply. I wasn't able to replicate or solve the issue before.

Is the issue still happening? If so, could you submit new logs, so I can take a look?

**Comment by vectorwing** [comment]
I'm closing this issue for now. If it's still happening, feel free to reply here with the info requested above.
