### ISSUE TITLE
please solve this problem

### ISSUE THREAD

**Issue by 1123451241** [vectorwing/FarmersDelight#558]
please solve this problem I use google translator, so my words might be a little weird. I tried to connect to the server by applying this mod, but it doesn't work. Please reply.

**Comment by 1123451241** [comment]
![Minecraft 1 19 2 2022-10-01 오전 10_05_23](https://user-images.githubusercontent.com/114786709/193377255-1e4cb395-7e60-436e-9ff2-ce59d8ae889f.png)

**Comment by vectorwing** [comment]
Please provide your mod list, and whether you're playing on Forge or Fabric.

**Comment by vectorwing** [comment]
Hi, @1123451241! I'm closing this issue, as it's gotten stale.
Feel free to reply with the information I requested above (mod loader and mod list), and I'll reopen it. 👍
