### ISSUE TITLE
[1.19.2 Forge 43.1.1] Disconnect upon trying to create and join singleplayer world

### ISSUE THREAD

**Issue by Rytelus** [vectorwing/FarmersDelight#565]
**Description**
Whenever I try to create a new world, I get prompted about experimental settings and I press continue. Then I try to generate a world with default settings, but as soon as the generation screen finishes, it kicks me out with a disconnected message to the multiplayer screen. Attempting to join the new world gives a failure to access message before promptly kicking me back to the multiplayer screen.

**Steps to reproduce:**
Having these mods on causes this interaction. Removing Farmer's Delight allows me to create and join a world as normal. I've tried running it without Supplementaries, Canary, Smooth Boot, and DEUF, but the logs and issue remained the same and pointed to this mod.

**Expected behavior:**
For world to be generated with Farmer's Delight and other mods, and allow me to actually join the world.

**Logs**
[latest.log](https://github.com/vectorwing/FarmersDelight/files/9751033/latest.log)

**Mod list:**
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		radon-0.8.2.jar                                   |Radon                         |radon                         |0.8.2               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.3.jar   |EnchantmentDescriptions       |enchdesc                      |13.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		moonlight-1.19.2-2.0.32.jar                       |Moonlight Library             |moonlight                     |1.19.2-2.0.32       |DONE      |Manifest: NOSIGNATURE
		RoughlyEnoughProfessions-forge-1.19-1.1.2.jar     |Roughly Enough Professions    |roughlyenoughprofessions      |1.1.2               |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.3.5.jar              |Player Animator               |playeranimator                |0.3.5               |DONE      |Manifest: NOSIGNATURE
		smoothboot(reloaded)-mc1.19.2-1.0.4.jar           |Smooth Boot (Reloaded)        |smoothboot                    |1.0.4               |DONE      |Manifest: NOSIGNATURE
		AttributeFix-Forge-1.19.2-17.1.2.jar              |AttributeFix                  |attributefix                  |17.1.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		RoughlyEnoughItems-9.1.550.jar                    |Roughly Enough Items (REI)    |roughlyenoughitems            |9.1.550             |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.1-mc1.19.1.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.1               |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.7-8.jar                 |Flywheel                      |flywheel                      |0.6.7-8             |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.f.jar                         |Create                        |create                        |0.5.0.f             |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+11.jar                  |Clumps                        |clumps                        |9.0.0+11            |DONE      |Manifest: NOSIGNATURE
		citadel-1.12.12-1.19.jar                          |Citadel                       |citadel                       |1.12.12             |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |DONE      |Manifest: NOSIGNATURE
		REIPluginCompatibilities-forge-9.0.16.jar         |REI Plugin Compatibilities    |rei_plugin_compatibilities    |9.0.16              |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.19.2-1.6.4.jar                   |Smarter Farmers               |smarterfarmers                |1.19.2-1.6.4        |DONE      |Manifest: NOSIGNATURE
		entityculling-forge-1.5.2-mc1.19.1.jar            |EntityCulling                 |entityculling                 |1.5.1               |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.19-1.8.1.jar            |Better Third Person           |betterthirdperson             |1.8.1               |DONE      |Manifest: NOSIGNATURE
		canary-mc1.19.2-0.0.4.jar                         |Canary                        |canary                        |0.0.4               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.1.5.jar                 |Bookshelf                     |bookshelf                     |16.1.5              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		architectury-6.2.46-forge.jar                     |Architectury                  |architectury                  |6.2.46              |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.31-1.19.x.jar                |Simply Swords                 |simplyswords                  |1.31-1.19.x         |DONE      |Manifest: NOSIGNATURE
		rer-2.6.1.jar                                     |Roughly Enough Resources      |roughlyenoughresources        |2.6.1               |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.1-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		farsight-1.19.2-2.1.jar                           |Farsight mod                  |farsight_view                 |1.19.2-2.1          |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.4.4+1.19.jar                 |Better Combat                 |bettercombat                  |1.4.4+1.19          |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.1.1-universal.jar                 |Forge                         |forge                         |43.1.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Quark-3.3-371.jar                                 |Quark                         |quark                         |3.3-371             |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.2.6.jar                  |Supplementaries               |supplementaries               |1.19.2-2.2.6        |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.23.jar                    |GeckoLib                      |geckolib3                     |3.1.23              |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-2.0.4-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.5.4-1.19.1.jar          |Domestication Innovation      |domesticationinnovation       |1.5.4               |DONE      |Manifest: NOSIGNATURE
		deuf-1.19.2-1.3.jar                               |DEUF - Duplicate Entity UUID F|deuf                          |1.19.2-1.3          |DONE      |Manifest: NOSIGNATURE
	Flywheel Backend: Off
	Crash Report UUID: 17b3d5cb-688c-4977-b84a-b2d67c59b1b0
	FML: 43.1
	Forge: net.minecraftforge:43.1.1

**Comment by vectorwing** [comment]
Hmm... this still sounds like a rogue mod interaction; I was able to test FD in servers before and after release. But nothing in your mod list seems like an obvious target aside from maybe OptiFine.

I suggest running a minimal instance with only FD and nothing else, and seeing if the server lets you log in.

**Comment by Rytelus** [comment]
Thanks for responding so quickly, I followed up on your advice and was able to narrow it down after a few hours. Mind you, this an issue with singleplayer as a minor correction to your statement.

Farmer's Delight and Roughly Enough Resources seem to be the crux of the interaction as the removal of either fixes the issue. If it can't be resolved on your end, should I open an issue on their page?

The mod list now:
Cloth Config, Farmer's Delight, REI Plugin Compat, Roughly Enough Items, Roughly Enough Resources.
All the same versions as the previous log.

Logs:
[latest.log](https://github.com/vectorwing/FarmersDelight/files/9760144/latest.log)
[rei.log](https://github.com/vectorwing/FarmersDelight/files/9760145/rei.log)

**Comment by vectorwing** [comment]
Thanks for troubleshooting!

I took a gander at their issues board, and this seems to affect more mods, so there's a chance it's on their end. It seems RER causes errors when placing players if any mod registers a custom loot function. Here's one of the issues:
https://github.com/theorbtwo/RoughlyEnoughResources/issues/70

For the time being, all I can suggest is to disable RER until the issue is updated with more info.

**Comment by unilock** [comment]
If it helps, the dev of Enigmatic Legacy fixed the same issue on their end in their 1.19.2 branch:
https://github.com/Aizistral-Studios/Enigmatic-Legacy/commit/857aa211318873180761aaa01a132a43cb0ac36e

I (hackily) cherry-picked that commit into its 1.18.X branch, and it worked fine.
Maybe something similar can be done here?

**Comment by unilock** [comment]
I fixed the issue on the 1.18.2 branch by moving the `LootItemFunction` registration from `CommonSetup#registerLootItemFunctions` to a separate class (`ModLootFunctions`), which allows each class extending `LootItemConditionalFunction` (i.e. `CopyMealFunction`, `CopySkilletFunction`, and `SmokerCookFunction`) to get its respective `LootItemFunctionType`, thus appeasing Roughly Enough Resources.

My commit: https://github.com/unilock/FarmersDelight/commit/55436e92ac641c5de5c1e34f94a17fc7c5870467

I don't have much experience with registries, so the way I implemented the fix likely isn't optimal; hence why it's not an outright pull request.

**Comment by vectorwing** [comment]
@unilock, sorry for the late reply! You were correct, the problem was on FD's end. I mistakenly left `getType()` as null back then, due to how I was registering the loot functions. It has to be specified, otherwise things break.

Commit 6591911 fixes the issue on 1.18.2, and I'll port it over to 1.19 and 1.20 as well. Thank you for the help! ^^
