### ISSUE TITLE
[1.18.2] Cooking pot flings out bowls

### ISSUE THREAD

**Issue by Watersfall** [vectorwing/FarmersDelight#568]
When cooking a recipe that returns a bowl it flings it out into the world instead of putting it in the bowl slot. An example recipe is the Pasta with Meatballs recipe.

**Comment by vectorwing** [comment]
This is an intended mechanic.

When an ingredient leaves behind a container, it is flung precisely towards the opposite side of the spoon, and can be captured by a Hopper or a Basket. You can use a Hopper to re-insert the bowl at the side, to auto-serve if you prefer.

If I made them be funneled into the bowl slot, it could end up clogging it, as well as being unable to handle two ingredients with different containers (for example, a recipe using both bottle and bowl ingredients). The container flinging lets the user choose what they want to do with such items.
