### ISSUE TITLE
[1.16.5] Farmers Delight Food

### ISSUE THREAD

**Issue by Darbeze** [vectorwing/FarmersDelight#569]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

Whenever I try to eat foods from this modpack I don't get the food effect. 

All I did was eat the hamburger for example, and I believe it should've given me strength but it never does. 

Here is the screen shot of the mod list
[
![image_2022-10-19_155149564](https://user-images.githubusercontent.com/116221834/196801604-e58b1111-9ff1-488e-97f3-fa16293ef5e6.png)
](url)

Thank you for helping with the project! Your reports are appreciated!

**Comment by vectorwing** [comment]
Sandwiches and similar finger foods have lost their effects in previous updates. The only foods which provide effects are now meals (bowl and plate food items), with the exception of Melon Popsicle in 0.6.
