### ISSUE TITLE
[1.18.2] Compat request with Croptopia

### ISSUE THREAD

**Issue by Raviolibolonesa** [vectorwing/FarmersDelight#570]
can you add compability with croptopia, please? Thanks a lot!

**Comment by vectorwing** [comment]
You'll have to be more specific on what kind of compatibility. Both mods, IIRC, use similar tags on items and recipes, so things should be interchangeable.

If you have ideas for specific integrations, I suggest opening a discussion. I can look into it sometime. 👍

**Comment by Raviolibolonesa** [comment]
the compability would be like making skillet and pot meals in croptopia able to be cooked in farmer's delight pots and skillets as well, crates for every fruit and vegetable there and making croptopia knives able to collect straw as well, i think that would be all, thank you!
