### ISSUE TITLE
[1.18.2] Cakes with candles broken by a knife does not drop any cake slices

### ISSUE THREAD

**Issue by Synthestra** [vectorwing/FarmersDelight#575]
Please fill out the template below to describe your issue. Doing so **greatly** helps us understand what happened!

**Description**
Cakes with candles broken by a knife does not drop any cake slices

**Steps to reproduce:**
Break minecraft:candle_cake with any farmersdelight knife.
Only candle drops

**Expected behavior:**
sliced cakes drop.

**Mod list:**
[crash-2022-11-03_10.01.32-client.txt](https://github.com/vectorwing/FarmersDelight/files/9927258/crash-2022-11-03_10.01.32-client.txt)

**Comment by Synthestra** [comment]
Ah i see it works through right clicking with a knife. I guess it makes sense since you'd take off the candle before cutting it. I also tried right clicking with an empty hand to take off the candle, but it flickers back into a candle cake within a tick (full hunger). I don't know if this is an fd issue.

**Comment by vectorwing** [comment]
Thanks for reminding me of this. 👍 

We had previously solved the knife-slicing action, but I never went back to fix the mining action as well. It will probably require a small rewrite of my loot modifer to accomodate for candle cakes.

**Comment by edgarogh** [comment]
I just suggested changes for that in #632

**Comment by vectorwing** [comment]
Fixed on commit 514707d, should be out in the next patch. 👍
