### ISSUE TITLE
[1.18.2] Compatibility with Botany Pots is broken

### ISSUE THREAD

**Issue by xAlicatt** [vectorwing/FarmersDelight#576]
**Description**
I have tested this with minimal mods, so it's not a 3rd mod causing the issue. Seems there is some issue with the integration files since the logs show a parsing error loading the FD crop files. "Expected member drops was not found"

**Steps to reproduce:**
I am not able to add any farmer's delight crops to Botany Pots. I can add FD soils, but they do not seem to work as intended...causing the crop growing to slow to a crawl compared to regular dirt.

**Expected behavior:**
I should be able to place FD crops into Botany Pots and have them grow. FD special soils added to pots should cause crops growing to grow faster than on regular dirt.

**Logs**
Latest: https://paste.ee/p/zMQar
Debug: https://paste.ee/p/I5cRj

**Screenshots**
N/A

**Mod list:**
![image](https://user-images.githubusercontent.com/24724298/200029308-a5c8487d-ed9c-4213-8564-7321404dd5f3.png)

**Comment by vectorwing** [comment]
This is a known issue. Botany Pots integration will be fixed in the upcoming 1.2.1 release; the mod's schemas changed, and my old integration is no longer valid, but Darkhax fixed them. 👍
