### ISSUE TITLE
[Suggestion] Consistency for pumpkin pie

### ISSUE THREAD

**Issue by IlTAKlI** [vectorwing/FarmersDelight#584]
### Description

Currently the farmer's delight pies are placeable and have slices with them, Would it be possible to have the pumpkin pie follow these behavior's too for consistency?

### Mod list

N/A

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hey there! Please use the **Discussions** tab for posting suggestions. 👍
Making Pumpkin Pie placeable is something I considered before, but nothing confirmed for the time being.
