### ISSUE TITLE
1.18.2: Rope with tomato vine on doesn't drop rope when broken by running water.

### ISSUE THREAD

**Issue by MonaMoonlight** [vectorwing/FarmersDelight#585]
### Description

When breaking rope with tomato vine growing on it, either manually or by water breaking it, the rope itself does not drop as an item.

Any rope climbed by vines above the part that was broken by the water reverts to regular rope, but the part that was broken is just lost.

(Breaking just the base of the vine replaces the length of vine-climbed rope with regular rope as expected.)

### Steps to reproduce

1. Grow tomato vine until it climbs rope.
2. Break the length of rope with vine growing on it by making water flow into it.
3. Note that the rope does not drop as an item.

### Mod list

- appleskin-forge-mc1.18.2-2.4.1
- badpackets-forge-0.1.3
- cofh_core-1.18.2-9.0.0.24
- configured-2.0.0-2.28.3
- create-1.18.2-0.5.0.e
- createaddition-1.18.2-20220914a
- FarmersDelight-1.18.2-1.2.0
- flywheel-forge-1.18.2-0.6.5
- jei-1.19.2-9.7.1.255
- polymorph-forge-1.18.2-0.45
- tempad-forge-1.18.2-1.4.1
- thermal_cultivation_1.18.2-9.0.0.13
- thermal_expansion_1.18.2-9.0.0.15
- thermal_foundation_1.18.2-9.0.0.32
- thermal_innovation_1.18.2-9.0.0.14
- thermal_integration_1.18.2-9.0.0.9
- thermal_locomotion_1.18.2-9.0.0.10
- wthit-forge-4.13.4
- wthitharvestability-mc1.18.2-2.0.0

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hmm, good eye. I probably forgot to account for neighbor interactions on roped tomato vines. Tested just now, and the whole thing just vanished without a sound... 😆

![image](https://user-images.githubusercontent.com/5566692/209704689-c788a8cd-466d-4c3e-98b7-034568dfc44e.png)

Perhaps roped vines could simply be resistant to water? I'll try some stuff out later.

**Comment by vectorwing** [comment]
Doesn't seem like I can make its resistant to water based on blockstates; it's a material property, which is defined on load.

The best scenario here would be to make Tomato Vines immune to water entirely - which would include the bottom vine. Might be goofy, but at least there isn't broken behaviour. 🤷

**Comment by MonaMoonlight** [comment]
> Doesn't seem like I can make its resistant to water based on blockstates; it's a material property, which is defined on load.
> 
> The best scenario here would be to make Tomato Vines immune to water entirely - which would include the bottom vine. Might be goofy, but at least there isn't broken behaviour. 🤷

Hydroponic tomatoes and lettuce are a thing IRL, so not that goofy.

**Comment by vectorwing** [comment]
Applied on commit 97dc42a, will be out for 1.2.2 soon. Hopefully it doesn't cause *other* broken behaviors down the line. It shouldn't though, from looking at the relevant property I changed.
