### ISSUE TITLE
1.18.2 Forge : INVALID PLAYER DATA WORLD CRASH

### ISSUE THREAD

**Issue by Traverse-Joe** [vectorwing/FarmersDelight#588]
### Description

Joining World gives INVALID PLAYER DATA and returns to Title Screen

### Steps to reproduce

1. Launch Pack
2. Join World

### Mod list

https://paste.ee/p/SAdOH

### Logs

https://paste.ee/p/rEUpg

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by genesy** [comment]
happens to me too

**Comment by vectorwing** [comment]
This is a known bug with the **Roughly Enough Resources** addon. It causes login failures if any present mod registers a custom loot function. I'm unsure if it has been fixed yet, sorry. :(

**Comment by genesy** [comment]
that makes sense. but yeah no it hasn't beed fixed yet :)

**Comment by vectorwing** [comment]
Update: turns out this was on my end. I made a mistake when setting up my loot functions, which caused the error.

Fixed on commit https://github.com/vectorwing/FarmersDelight/commit/65919116d1aecbded2e4ac1429d574d6d58615f5, should be out later for 1.18, 1.19 and 1.20. 👍
