### ISSUE TITLE
KETTLE WONT GIVE ME MY HOT COCOA :(

### ISSUE THREAD

**Issue by kale808** [vectorwing/FarmersDelight#592]
I made hot cocoa in the kettle and it won’t allow me to take it out now.  The kettle just keeps whistling and it’s very obnoxious.  Any ideas on how to fix this?

**Comment by vectorwing** [comment]
Sorry, the Kettle belongs to the **Farmer's Respite** add-on; it's not an FD workstation.
If I recall correctly, you need to put a Glass Bottle in the container slot to take it out, or right-click the kettle with it. Good luck!
