### ISSUE TITLE
[1.18.2]: Crash between Biome Makeover's Itching Ivy and Farmer's Delight Rich soil 

### ISSUE THREAD

**Issue by Insane96** [vectorwing/FarmersDelight#593]
### Description

Ticking Rich soil crashes the game if Biome Makeover's Itching Ivy is on top

### Mod list

		QuarkOddities-1.18.jar                            |Quark Oddities                |quarkoddities                 |1.18                |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0.1  |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.278.jar                   |Just Enough Items             |jei                           |10.2.1.278          |DONE      |Manifest: NOSIGNATURE
		MobsPropertiesRandomness-3.6.0-mc1.18.2.jar       |Mobs Properties Randomness    |mobspropertiesrandomness      |3.6.0               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |DONE      |Manifest: NOSIGNATURE
		InsaneLib-1.5.1-mc1.18.2.jar                      |InsaneLib                     |insanelib                     |1.5.1               |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		configured-2.0.0-1.18.2.jar                       |Configured                    |configured                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.6.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.6  |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		lazydfu-1.0-1.18+.jar                             |LazyDFU                       |lazydfu                       |0.1.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.3.1  |DONE      |Manifest: NOSIGNATURE
		ProgressiveBosses-3.6.4-mc1.18.2.jar              |Progressive Bosses            |progressivebosses             |3.6.4               |DONE      |Manifest: NOSIGNATURE
		jeed-1.18.2-1.11.jar                              |Just Enough Effect Description|jeed                          |1.18.2-1.11         |DONE      |Manifest: NOSIGNATURE
		EasierVillagerTrading-forge-1.18.2-1.0.0.jar      |Easier Villager Trading       |easiervillagertrading         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.2-1.18.2.jar                        |Catalogue                     |catalogue                     |1.6.2               |DONE      |Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.18.2-4.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |4.0.0               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.18.2-5.0.0.jar                       |Berry Good                    |berry_good                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.0.jar                |Savage & Ravage               |savage_and_ravage             |4.0.0               |DONE      |Manifest: NOSIGNATURE
		carryon-1.18.2-1.17.0.8.jar                       |Carry On                      |carryon                       |1.17.0.8            |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.197.jar             |CraftTweaker                  |crafttweaker                  |9.1.197             |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.84-universal.jar                |Forge                         |forge                         |40.1.84             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |DONE      |Manifest: NOSIGNATURE
		PathToDirt-1.4.2-mc1.18.2.jar                     |Path To Dirt                  |pathtodirt                    |1.4.2               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.12.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.12       |DONE      |Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		Shields+-1.2.5-mc1.18.2.jar                       |ShieldsPlus                   |shieldsplus                   |1.2.5-mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		cofh_core-1.18.2-9.0.0.24.jar                     |CoFH Core                     |cofh_core                     |9.0.0.24            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.18.2-3.5.2.44.jar                    |Tinkers' Construct            |tconstruct                    |3.5.2.44            |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		cleancut-mc1.18.2-4.0-forge.jar                   |Clean Cut                     |cleancut                      |4.0                 |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		archers_paradox-1.18.2-3.0.0.8.jar                |Archer's Paradox              |archers_paradox               |3.0.0.8             |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		YungsBridges-1.18.2-Forge-2.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		shulker_enchantments-3.0.1.jar                    |Shulker Enchantments          |shulker_enchantments          |3.0.1               |DONE      |Manifest: NOSIGNATURE
		IguanaTweaksReborn-2.12.7-mc1.18.2.jar            |Iguana Tweaks Reborn          |iguanatweaksreborn            |2.12.7-mc1.18.2     |DONE      |Manifest: NOSIGNATURE
		goprone-1.18.2-1.7.0.jar                          |GoProne                       |goprone                       |1.18.2-1.7.0        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.e.jar                         |Create                        |create                        |0.5.0.e             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |DONE      |Manifest: NOSIGNATURE
		camera-1.18.2-1.0.5.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.5        |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		materialis-1.18.2-2.6.1.jar                       |Materialis                    |materialis                    |1.18.2-2.6.1        |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		global_packs-forge-1.18.2-1.12.3_forge.jar        |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.12.3_forge        |DONE      |Manifest: NOSIGNATURE
		architectury-4.10.86-forge.jar                    |Architectury                  |architectury                  |4.10.86             |DONE      |Manifest: NOSIGNATURE
		biomemakeover-FORGE-1.18.2-1.4.31.jar             |Biome Makeover                |biomemakeover                 |1.18.2-1.4.31       |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.5-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.5               |DONE      |Manifest: NOSIGNATURE
		EnhancedAI-1.6.3-mc1.18.2.jar                     |Enhanced AI                   |enhancedai                    |1.6.3               |DONE      |Manifest: NOSIGNATURE
		incubation-1.18.2-2.0.2.jar                       |Incubation                    |incubation                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.2    |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.18.2-0.1.2.125.jar           |Better Advancements           |betteradvancements            |0.1.2.125           |DONE      |Manifest: NOSIGNATURE
	

### Logs

https://gist.github.com/Insane96/395489cf53a596b11e8720a020e94684

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [x] I have tested this without performance or shader mods

Also reported to https://github.com/Lemonszz/Biome-Makeover/issues/182

**Comment by vectorwing** [comment]
Hmm... looking at the code in both blocks, it seems Biome Makeover is making an erroneus class cast on its Bone Meal method.
Does it also crash if you use bone meal directly on the block? Rich Soil applies bone meal to blocks above it, so the behavior would be equivalent.

**Comment by Lemonszz** [comment]
Yeah, this is a BM issue.

**Comment by vectorwing** [comment]
Ah, okay! Thanks for letting me know! 👍
