### ISSUE TITLE
(Suggestion)(1.18.2)

### ISSUE THREAD

**Issue by Gitcrafter** [vectorwing/FarmersDelight#595]
Can you add compat for Tool´s Complement´s Knifes

**Comment by edgarogh** [comment]
You should probably ask TeamCoFH to add their knives to the `forge:tools/knives` tag, this would make them compatible not only with FD, but with any other mod that uses knives.

Farmer's Delight uses this tag to determine valid knives[^source]. By the way, if you're running your own server/local world, you can add the compat too with a datapack.

[^source]: usage: https://github.com/vectorwing/FarmersDelight/blob/de251cbed351e703157411ab52182be6756d815a/src/main/java/vectorwing/farmersdelight/common/block/entity/CuttingBoardBlockEntity.java#L139
current json definition: https://github.com/vectorwing/FarmersDelight/blob/1.18.2/src/generated/resources/data/forge/tags/items/tools/knives.json

**Comment by vectorwing** [comment]
Thanks, edgarogh! Sorry for the delayed response.

Yes, Team CoFH should be able to tag their knives to grant them FD compatibility from their end. It might be easier than accounting for all knife-adding mods on my end, as they seem very far-apart. 😄

- `forge:tools/knives` is used exclusively for crafting, such as Cutting Board recipes;
- `farmersdelight:tools/knives` is used for gameplay interactions:
  - Scavenging animal drops;
  - Slicing cakes and pies;
  - Cutting straw (this tag is added in `farmersdelight:straw_harvesters`) etc;
  - This tag is also added by default to `forge:tools/knives`, making them recipe-compatible out of the box.

Hope this helps! 👍
