### ISSUE TITLE
[MC Version]: 1.18.2

### ISSUE THREAD

**Issue by Sleepybird1** [vectorwing/FarmersDelight#596]
### Description

When trying to craft large meals like chicken sandwiches they have this Red 0 with a cross in it like a barrier block but when I hover over it. It says, missing tag:salad_ingredients im not to sure how.

### Steps to reproduce

I do not have a way to reproduce it, it could be a mod conflict for some reason or I thought it was a currupt file so I tried to reinstall the mod and it didnt fix it.

### Mod list

CyclopsCore-1.18.2-1.16.0.jar                     |Cyclops Core                  |cyclopscore                   |1.16.0              |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |DONE      |Manifest: NOSIGNATURE
		tinyredstone-1.18.2-3.2.2.jar                     |Tiny Redstone                 |tinyredstone                  |1.18.2-3.2.2        |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.18.2.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.15.141.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.15.141   |DONE      |Manifest: NOSIGNATURE
		rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |DONE      |Manifest: NOSIGNATURE
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |DONE      |Manifest: NOSIGNATURE
		chiseled-1.18.2-0.5beta.jar                       |Chiseled                      |chiseled                      |0.5.0               |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.28.3_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.3              |DONE      |Manifest: NOSIGNATURE
		CTM-1.18.2-1.1.5+5.jar                            |ConnectedTexturesMod          |ctm                           |1.18.2-1.1.5+5      |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.6.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.6  |DONE      |Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |2.0.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.29.718.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.29.718  |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.18.2.1.4.3.jar                   |Guard Villagers               |guardvillagers                |1.4.3               |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.0.7-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.7               |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.5.465.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.5              |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		createfa-1.18.2-1.0.11.jar                        |CreateFoodAdditions           |createfa                      |1.18.2-1.0.11       |DONE      |Manifest: NOSIGNATURE
		konkrete_forge_1.5.3_MC_1.18-1.18.2.jar           |Konkrete                      |konkrete                      |1.5.3               |DONE      |Manifest: NOSIGNATURE
		PrettyPipes-1.12.8.jar                            |Pretty Pipes                  |prettypipes                   |1.12.8              |DONE      |Manifest: NOSIGNATURE
		mcw-bridges-2.0.5-mc1.18.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.5               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.0.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		cleancut-mc1.18.2-4.0-forge.jar                   |Clean Cut                     |cleancut                      |4.0                 |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-5.1.14+1.18.2.jar     |Repurposed Structures         |repurposed_structures         |5.1.14+1.18.2       |DONE      |Manifest: NOSIGNATURE
		CommonCapabilities-1.18.2-2.8.2.jar               |CommonCapabilities            |commoncapabilities            |2.8.2               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.18.2-16.0.0.109-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.18.2-16.0.0.109   |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.7-mc1.18.2.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.7               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.6-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |DONE      |Manifest: NOSIGNATURE
		pamhc2foodextended-1.18.2-1.0.5.jar               |Pam's HarvestCraft 2 - Food Ex|pamhc2foodextended            |1.0                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.18.2-1.2.5a.jar                        |Oculus                        |oculus                        |1.2.5a              |DONE      |Manifest: NOSIGNATURE
		collective-1.18.2-5.16.jar                        |Collective                    |collective                    |5.16                |DONE      |Manifest: NOSIGNATURE
		workers-1.18.2-1.5.2.jar                          |Workers Mod                   |workers                       |1.5.2               |DONE      |Manifest: NOSIGNATURE
		IntegratedTunnels-1.18.2-1.8.16.jar               |IntegratedTunnels             |integratedtunnels             |1.8.16              |DONE      |Manifest: NOSIGNATURE
		bettervillage-forge-1.18.2-2.0.0.jar              |Better village                |bettervillage                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18.2-1.8.1.jar          |Better Third Person           |betterthirdperson             |1.8.1               |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.1-mc1.18.2-forge.jar                |Macaw's Roofs                 |mcwroofs                      |2.2.1               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.0.2-mc1.18.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.2               |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-28.jar                              |FastLeafDecay                 |fastleafdecay                 |28                  |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.2    |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.18.2-10.0.3.jar             |DarkPaintings                 |darkpaintings                 |10.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-lights-1.0.4-mc1.18.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               |DONE      |Manifest: NOSIGNATURE
		pamhc2trees-1.18.2-1.0.3.jar                      |Pam's HarvestCraft 2 - Trees  |pamhc2trees                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		rechiseled-1.0.10a-mc1.18.jar                     |rechiseled                    |rechiseled                    |1.0.10a             |DONE      |Manifest: NOSIGNATURE
		oculus-flywheel-compat-1.18.2-0.1.7-BETA.jar      |Oculus Flywheel Compat        |irisflw                       |1.18.2-0.1.7-BETA   |DONE      |Manifest: NOSIGNATURE
		treeharvester_1.18.2-5.9.jar                      |Tree Harvester                |treeharvester                 |5.9                 |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.255.jar                          |Just Enough Items             |jei                           |9.7.1.255           |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.18.2-3.0.0.jar              |Library ferret                |libraryferret                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.5.465.jar                    |Mekanism                      |mekanism                      |10.2.5              |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.4-mc1.18.2.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.4               |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+15.jar                  |Clumps                        |clumps                        |8.0.0+15            |DONE      |Manifest: NOSIGNATURE
		PrettyPipesFluids-1.18.2-1.1.0.jar                |Pretty Fluid Pipes            |ppfluids                      |1.18.2-1.1.0        |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.5.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.5      |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.2.0.jar                        |Artifacts                     |artifacts                     |1.18.2-4.2.0        |DONE      |Manifest: NOSIGNATURE
		configured-2.0.0-1.18.2.jar                       |Configured                    |configured                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		compactmachines-4.5.0.jar                         |Compact Machines 4            |compactmachines               |4.5.0               |DONE      |Manifest: NOSIGNATURE
		tinypipes-2.0.3.jar                               |Tiny Pipes                    |tinypipes                     |2.0.3               |DONE      |Manifest: NOSIGNATURE
		Terralith_v2.2.2.jar                              |Terralith                     |terralith                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.79-universal.jar                |Forge                         |forge                         |40.1.79             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mcw-paths-1.0.1-mc1.18.2.jar                      |Macaw's Paths and Pavings     |mcwpaths                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.13.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.13       |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.18.2-9.1.0.27.jar                     |CoFH Core                     |cofh_core                     |9.1.0.27            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.18.2-9.1.0.34.jar            |Thermal Series                |thermal                       |9.1.0.34            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_integration-1.18.2-9.1.0.10.jar           |Thermal Integration           |thermal_integration           |9.1.0.10            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_innovation-1.18.2-9.1.0.15.jar            |Thermal Innovation            |thermal_innovation            |9.1.0.15            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.18.2-9.1.0.18.jar             |Thermal Expansion             |thermal_expansion             |9.1.0.18            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TConstruct-1.18.2-3.5.2.40.jar                    |Tinkers' Construct            |tconstruct                    |3.5.2.40            |DONE      |Manifest: NOSIGNATURE
		voicechat-forge-1.18.2-2.3.16.jar                 |Simple Voice Chat             |voicechat                     |1.18.2-2.3.16       |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.18.2-1.0.6.jar               |Sound Physics Remastered      |sound_physics_remastered      |1.18.2-1.0.6        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		The_Wild_Update_Mod_V1.3_Minecraft_1.18.jar       |The Wild Update 1.19 Mod      |the_wild_update               |1.3                 |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.6.jar                       |Jade                          |jade                          |5.2.6               |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-11.6.5.jar              |Applied Energistics 2         |ae2                           |11.6.5              |DONE      |Manifest: NOSIGNATURE
		pamhc2crops-1.18.2-1.0.5.jar                      |Pam's HarvestCraft 2 - Crops  |pamhc2crops                   |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |DONE      |Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.e.jar                         |Create                        |create                        |0.5.0.e             |DONE      |Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.31.jar                          |Mantle                        |mantle                        |1.9.31              |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.16.2_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.16.2             |DONE      |Manifest: NOSIGNATURE
		IntegratedDynamics-1.18.2-1.11.13.jar             |IntegratedDynamics            |integrateddynamics            |1.11.13             |DONE      |Manifest: NOSIGNATURE
		pamhc2foodcore-1.18.2-1.0.3.jar                   |Pam's HarvestCraft 2 - Food Co|pamhc2foodcore                |1.0.1               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.18.2-FORGE-2.1.0.jar                  |Croptopia                     |croptopia                     |2.1.0               |DONE      |Manifest: NOSIGNATURE
		thermal_cultivation-1.18.2-9.1.0.14.jar           |Thermal Cultivation           |thermal_cultivation           |9.1.0.14            |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		polymorph-forge-1.18.2-0.45.jar                   |Polymorph                     |polymorph                     |1.18.2-0.45         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		[1.18.2] SecurityCraft v1.9.3.1.jar               |SecurityCraft                 |securitycraft                 |1.9.3.1             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		fancymenu_forge_2.12.9_MC_1.18.2.jar              |FancyMenu                     |fancymenu                     |2.12.9              |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		largemeals-1.18.2-2.0.jar                         |Large Meals                   |largemeals                    |1.18.2-2.0          |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.2-1.2.115-universal.jar    |Chisels & bits                |chiselsandbits                |1.2.115             |DONE      |Manifest: NOSIGNATURE
		createaddition-1.18.2-20221117a.jar               |Create Crafts & Additions     |createaddition                |1.18.2-20221117a    |DONE      |Manifest: NOSIGNATURE
		PresenceFootsteps-1.18.2-1.5.0-beta2-forge.jar  

### Logs

https://pastebin.com/Zg6LPrza
[crash-2022-11-26_22.13.03-client.txt](https://github.com/vectorwing/FarmersDelight/files/10097123/crash-2022-11-26_22.13.03-client.txt)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hmm... This sounds like another mod is trying (but failing) to add items to this tag, or doing something which is breaking it during world load.

When entering a world, the logs will usually show datapack errors, which could help find out the cause. Could you boot up your world, and then send the `latest.log` here?

**Comment by vectorwing** [comment]
Hi @Sleepybird1, is the issue still happening? If so, please send the log I requested, as it's most likely another mod registering their tags wrongly.

**Comment by OgLemons** [comment]
> Hmm... This sounds like another mod is trying (but failing) to add items to this tag, or doing something which is breaking it during world load.
> 
> When entering a world, the logs will usually show datapack errors, which could help find out the cause. Could you boot up your world, and then send the `latest.log` here?

I seem to be having the same issue but I will supply what I can to help as it looks like op has stopped replying.
I am running a different pack on a server but it is the same issue with soup what logs would you like me to provide?

**Comment by vectorwing** [comment]
Both server logs and a client's latest.log should suffice; one of them should report erroneous tag registration.
Also, chances are a food mod or add-on to FD might be causing it, so disabling them temporarily might help spot the issue too.

**Comment by OgLemons** [comment]
> Both server logs and a client's latest.log should suffice; one of them should report erroneous tag registration. Also, chances are a food mod or add-on to FD might be causing it, so disabling them temporarily might help spot the issue too.

Sweet will grab them, we also have farmers delight could that be the reason?
Server: [latest.log](https://github.com/vectorwing/FarmersDelight/files/10719133/latest.log)
Client: [latest.log](https://github.com/vectorwing/FarmersDelight/files/10719137/latest.log)

**Comment by vectorwing** [comment]
Found the problem:

```
[13Feb2023 18:38:43.910] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:cactus_plants as it is missing following references: #forge:cactus_plants/barrelcactus (from pamhc2crops-1.18.2-1.0.5.jar), 
	#forge:cactus_plants/nopales (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.912] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:leafyvegetables/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.936] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:salad_ingredients/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.937] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:salad_ingredients as it is missing following references: #forge:salad_ingredients/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.938] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:vegetables/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.946] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:leafyvegetables as it is missing following references: #forge:leafyvegetables/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
[13Feb2023 18:38:43.948] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:vegetables as it is missing following references: #forge:vegetables/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
```

Pam's HC2 Crops module is having issues registering items to certain tags, causing them to fail loading. From a quick check, 1.0.5 seems to be the latest version, so there might not be a fix yet.

I suggest forwarding this issue to the Harvestcraft 2 issue board, or temporarily disabling the module until it's fixed. Thank you for the logs btw, it helped a lot! 👍

**Comment by OgLemons** [comment]
> Found the problem:
> 
> ```
> [13Feb2023 18:38:43.910] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:cactus_plants as it is missing following references: #forge:cactus_plants/barrelcactus (from pamhc2crops-1.18.2-1.0.5.jar), 
> 	#forge:cactus_plants/nopales (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.912] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:leafyvegetables/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.936] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:salad_ingredients/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.937] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:salad_ingredients as it is missing following references: #forge:salad_ingredients/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.938] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:vegetables/bokchoy as it is missing following references: pamhc2crops:bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.946] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:leafyvegetables as it is missing following references: #forge:leafyvegetables/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> [13Feb2023 18:38:43.948] [Worker-Main-22/ERROR] [net.minecraft.tags.TagLoader/]: Couldn't load tag forge:vegetables as it is missing following references: #forge:vegetables/bokchoy (from pamhc2crops-1.18.2-1.0.5.jar)
> ```
> 
> Pam's HC2 Crops module is having issues registering items to certain tags, causing them to fail loading. From a quick check, 1.0.5 seems to be the latest version, so there might not be a fix yet.
> 
> I suggest forwarding this issue to the Harvestcraft 2 issue board, or temporarily disabling the module until it's fixed. Thank you for the logs btw, it helped a lot! 👍

Interesting, I see, glad I could help! How would I go about contacting them, I still don't even know how I got here.

**Comment by Traehgniw** [comment]
This was causing a major issue in a modpack I play - the issue ONLY occurs with the latest version of Pam's HC2 Crops. Go back a version and it's fixed. 

Issues with Pam's get reported in their discord at https://discord.gg/DJMfsHH

**Comment by OgLemons** [comment]
> This was causing a major issue in a modpack I play - the issue ONLY occurs with the latest version of Pam's HC2 Crops. Go back a version and it's fixed.
> 
> Issues with Pam's get reported in their discord at https://discord.gg/DJMfsHH

Oh that's really good to know thank you!!
