### ISSUE TITLE
Please fix Crafttweaker support for 1.18.2/1.19.2

### ISSUE THREAD

**Issue by Gitcrafter** [vectorwing/FarmersDelight#601]
Can you please fix the Crafttweaker support for 1.18.2, cause it is giving me this error, despite doing everyting like the example on the Crafttweaker wiki

![2022-12-01_15 02 52](https://user-images.githubusercontent.com/81863925/205082948-305940e5-49c7-4d7c-98d4-b34f106488cb.png)

**Comment by vectorwing** [comment]
CT support was previously disabled during the 1.18 ports, as the mod hadn't updated yet. I forgot to re-enable it later, as the contribution was done by different devs.

The upcoming 1.2.1 version should re-enable all CT support; I'll let you know here once it's released. 👍

**Comment by Gitcrafter** [comment]
Thanks for telling me

**Comment by Gitcrafter** [comment]
I recently switched to 1.19.2, please add Crafttweaker support for that version too

**Comment by vectorwing** [comment]
@Gitcrafter, 1.2.1 has been released a while ago with re-enabled CT support. Sorry, I forgot to update you about it! 😅

**Comment by Gitcrafter** [comment]
no problem, I got the update a while ago during a regular check for mod updates, but still thanks for telling me regardless
