### ISSUE TITLE
[1.19.2]: Can't get Crop Rotation advancement

### ISSUE THREAD

**Issue by dher383** [vectorwing/FarmersDelight#608]
### Description

When I try to plant all 18 crops, only 17 records. Later, I found out that it didn't record tomato crops. This isn't a crash, so there's no crash report.
I'm sorry about my bad English.

### Steps to reproduce

1.plant all 18 crops that the advancement require
2.found that only 17 were recorded
3.Later, I found that the advancement was not recording tomato crops

### Mod list

client-1.19.2-20220805.130853-srg.jar
FarmersDelight-1.19-1.2.0.jar
forge-1.19.2-43.2.0-universal.jar

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Yup, I forgot to update it to ask for `budding_tomatoes`, as you can't directly plant `tomatoes` anymore. :x

Thanks for documenting it. Should be fixed in 1.2.1 soon. 👍

**Comment by dher383** [comment]
Good to know. Also, thank you for making this awesome mod.

**Comment by PayWithBitcoin** [comment]
Is there a ETA for a Version with a fix for this? I currently play on a modpack Server (1.19.2) and all players have this issue.

> Yup, I forgot to update it to ask for `budding_tomatoes`, as you can't directly plant `tomatoes` anymore. :x
> 
> Thanks for documenting it. Should be fixed in 1.2.1 soon. 👍

**Comment by vectorwing** [comment]
Sorry, I took a hiatus after this. I'm currently wrapping up a few bugs and translations for 1.2.1, so it should be released soon.
