### ISSUE TITLE
[MC Version]: 

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#609]
### Description

I downloaded the mod alone and with other mods, and in both cases the game crashed.
I play through tlauncher, and when I run the game with te mod(s), it just shows a crash report. I tried to test the game without the mod, and it worked, so I don't know what to do to resolve the problem with the mod. 

### Steps to reproduce

1 - downloaded the mod in curseforge
2 - put it in the mod's paste 
3 - join the game and see the crash report

### Mod list

alex's mobs - 1.21.0
apple skin - 2.4.2
mr. crayfish's furniture - 7.0.0
citadel - 2.1.0
farmer's delight - 1.1.2 (I tested with the 1.2 version too, it don't work)
jei - 11.5.0.292
macaw doors - 1.0.7
macaw fences - 1.0.7
macaw furniture - 3.0.2
macaw windows - 2.1.1
moonlight - 2.1.20
nether's delight - 3.0
twilight forest - 4.2.333
xaeros minimap - 22.17.0

### Logs

https://mclo.gs/4KUyQEZ

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by Knightwalker123** [comment]
I am also getting this same issue, and honestly have no clue how to fix it

**Comment by vectorwing** [comment]
According to your logs, Farmer's Delight was not included or loaded in the **server**'s modlist, thus causing the add-on Nether's Delight to fail loading. Please check with your server owner if FD is actually downloaded on the server.

Unrelated: I strongly advise not using TLauncher. It's known for containing malware. :P

**Comment by vectorwing** [comment]
I'll be closing this issue, as it's gotten stale. If your server owner is sure FD is actually installed and the issue persists, feel free to reply here. 👍
