### ISSUE TITLE
Comfort change has not been properly documented

### ISSUE THREAD

**Issue by Cinderheart** [vectorwing/FarmersDelight#612]
### Description

The changes to Comfort have gone through fine, however the game still says it gives immunity to slowness, hunger, and weakness. That is what JEED says, and it is what the official Farmer's Delight Wiki (on github) still says.

### Mod list

My mod list is not relevant here, as this is an issue around the mod rather than with the mod itself.

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
True, I haven't updated the wiki in a long while. Will update the text later. 👍

JEED, however, is not maintained by me, nor is the info pulled from FD's files; the mod itself holds these langs. You might need to pass this issue over to JEED's repository instead.

**Comment by Cinderheart** [comment]
Huh, I thought JEED pulled from internal comments. Good to know. Thank you for the update!

**Comment by vectorwing** [comment]
Updated the Effects page on the wiki with new info, and some images.
https://github.com/vectorwing/FarmersDelight/wiki/Effects
