### ISSUE TITLE
Add Cutting Board recipes for Deployer from Create

### ISSUE THREAD

**Issue by DmitryScaletta** [vectorwing/FarmersDelight#614]
### Description

If Create is installed add all Cutting Board recipes for Deployer (if Depot or Belt is underneath).

![image](https://user-images.githubusercontent.com/5096735/210785688-4a62f86f-aa3f-4791-ad3b-88a5ad2344ca.png)

**Comment by edgarogh** [comment]
I'm willing to implement that if it gets approved.

**Comment by vectorwing** [comment]
To do this for every potential cutting recipe, I would have to make a dynamic implementation rather than a list of .json recipes, causing FD to depend on Create. It's not currently in the plans, though you can still use a timed deployer to use tools against the Cutting Board.

**Comment by edgarogh** [comment]
That makes sense, less dependencies is always better. Thanks for replying.

**Comment by RaymondBlaze** [comment]
I totally agree vectorwing's point on not introducing new hard dependencies for FD, especially when it comes to an independent, huge, frequently updated mod like Create.

There exist mods that automates the Cutting Board recipes with Create: one is [**Create: Slice and Dice**](https://github.com/PssbleTrngle/SliceAndDice) which introduced a new machine for the work, the other one is [**Create: Central Kitchen**](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen) which does exactly what you're looking for while providing more compatibilities between FD and Create.

I hope the information above is helpful. Feel free to open feature requests about FD & Create in [Create: Central Kitchen's issues](https://github.com/DragonsPlusMinecraft/CreateCentralKitchen/issues) :)

**Comment by vectorwing** [comment]
Yeah, those add-ons seem to accomplish that dynamic recipe much nicer. They're valid recommendations for now! 👍
