### ISSUE TITLE
[1.19.2] Crash when using Cooking Pot

### ISSUE THREAD

**Issue by mocksonline** [vectorwing/FarmersDelight#619]
### Description

forge: 43.2.1
arclight: Horn 1.0.1 (https://github.com/IzzelAliz/Arclight)

crashing when using cooking pot

can not reproduce in minimal instance

### Steps to reproduce

use the cooking pot

### Mod list

Mod List: 
		[ʥ      ]Festive_Delight_1.0_1.19.2.jar           |Festive Delight               |festive_delight               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		[    GUI]Public+GUI+Announcement-forge-1.19.2-4.3.|Public GUI Announcement       |publicguiannouncement         |4.3.2               |DONE      |Manifest: NOSIGNATURE
		[JEI]jei-1.19.2-forge-11.5.0.297.jar              |Just Enough Items             |jei                           |11.5.0.297          |DONE      |Manifest: NOSIGNATURE
		[ ȼ۽   ]ProjectE-1.19.2-PE1.0.1B.jar              |ProjectE                      |projecte                      |1.0.1B              |DONE      |Manifest: NOSIGNATURE
		[   ˳   ]cookingforblockheads-forge-1.19.2-13.3.0.|CookingForBlockheads          |cookingforblockheads          |13.3.0              |DONE      |Manifest: NOSIGNATURE
		artifacts-1.19.2-5.0.1.jar                        |Artifacts                     |artifacts                     |1.19.2-5.0.1        |DONE      |Manifest: NOSIGNATURE
		[     ļ ]SereneSeasons-1.19-8.0.0.19.jar          |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		[ʱװ]CustomPlayerModels-1.19-0.6.2a.jar            |Customizable Player Models    |cpm                           |0.6.2a              |DONE      |Manifest: NOSIGNATURE
		zetter-0.19.1-1.19.2-rc.jar                       |Zetter                        |zetter                        |0.19.1-1.19.2-rc    |DONE      |Manifest: NOSIGNATURE
		[ǰ  ]balm-4.5.3.jar                               |Balm                          |balm                          |4.5.3               |DONE      |Manifest: NOSIGNATURE
		[        ]PineappleDelight-1.19.2-1.0.1.jar       |Pineapple Delight             |pineapple_delight             |1.0                 |DONE      |Manifest: NOSIGNATURE
		VideoPlayer-0.4-BETA-1.19.jar                     |VideoPlayer                   |videoplayer                   |0.4                 |DONE      |Manifest: NOSIGNATURE
		Display+Case-forge-1.19-1.0.3.jar                 |Display Case Mod              |display_case                  |1.0.3               |DONE      |Manifest: NOSIGNATURE
		[ǰ  ]cloth-config-8.2.88-forge.jar                |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.1-universal.jar                 |Forge                         |forge                         |43.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		corpse-1.19.2-1.0.0.jar                           |Corpse                        |corpse                        |1.19.2-1.0.0        |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.19.2-2.1.54-release.jar           |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.2       |DONE      |Manifest: NOSIGNATURE
		tectonic-mod-mc1.19-v1.1.3.jar                    |Tectonic                      |tectonic                      |1.1.3               |DONE      |Manifest: NOSIGNATURE
		server-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: NOSIGNATURE
		[CoFh    ]cofh_core-1.19.2-10.0.2.33.jar          |CoFH Core                     |cofh_core                     |10.0.2.33           |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		lucky-block-forge-1.19.2-13.0.jar                 |Lucky Block                   |lucky                         |1.19.2-13.0         |DONE      |Manifest: NOSIGNATURE
		[ũ      ]FarmersDelight-1.19-1.2.0.jar            |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		nekoration-1.19.2-1.8.1.jar                       |Nekoration                    |nekoration                    |1.8.1               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.11.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.11.0+1.19         |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_1.19_1.1.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		FancyVideo-API-forge-2.2.0.1.jar                  |FancyVideo API                |fancyvideo_api                |2.2.0.1             |DONE      |Manifest: NOSIGNATURE
		extragolems-19.2.4.jar                            |Extra Golems                  |golems                        |19.2.4              |DONE      |Manifest: NOSIGNATURE
		[ǰ  ]flywheel-forge-1.19.2-0.6.8.jar              |Flywheel                      |flywheel                      |0.6.8-13            |DONE      |Manifest: NOSIGNATURE
		[  е    ]create-1.19.2-0.5.0.g.jar                |Create                        |create                        |0.5.0.g             |DONE      |Manifest: NOSIGNATURE
		createdeco-1.2.11-1.19.2.jar                      |Create Deco                   |createdeco                    |1.2.11-1.19.2       |DONE      |Manifest: NOSIGNATURE
		[ǰ  ][  Ʒ  ]curios-forge-1.19.2-5.1.1.0.jar       |Curios API                    |curios                        |1.19.2-5.1.1.0      |DONE      |Manifest: NOSIGNATURE
		[ǰ  ][       ֲ ]Patchouli-1.19.2-77.jar           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.1+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.1+1.19.2       |DONE      |Manifest: NOSIGNATURE
		FramedBlocks-6.6.2.jar                            |FramedBlocks                  |framedblocks                  |6.6.2               |DONE      |Manifest: NOSIGNATURE
		[ǰ  ]architectury-6.4.62-forge.jar                |Architectury                  |architectury                  |6.4.62              |DONE      |Manifest: NOSIGNATURE
		[ǰ  ][FTB  ]ftb-library-forge-1902.3.11-build.166.|FTB Library                   |ftblibrary                    |1902.3.11-build.166 |DONE      |Manifest: NOSIGNATURE
		[ǰ  ][  Ʒ      ]item-filters-forge-1902.2.9-build.|Item Filters                  |itemfilters                   |1902.2.9-build.46   |DONE      |Manifest: NOSIGNATURE
		[ǰ  ][ Ŷ ]ftb-teams-forge-1902.2.11-build.87.jar  |FTB Teams                     |ftbteams                      |1902.2.11-build.87  |DONE      |Manifest: NOSIGNATURE
		[       о]ferritecore-5.0.3-forge.jar             |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		create_crystal_clear-0.1.2e-1.19.2.jar            |Create: Crystal Clear         |create_crystal_clear          |1.19.2 - 0.1.1e     |DONE      |Manifest: NOSIGNATURE
		[       ]fastfooddelight-1.19-1.2.3.jar           |https://github.com/akaneoMT/Fa|fastfooddelight               |1.19-1.2.3          |DONE      |Manifest: NOSIGNATURE
		arclight-1.19.2-1.0.1-0550c6cd.jar                |Arclight Mod                  |arclight                      |1.19.2-1.0.1-0550c6c|DONE      |Manifest: NOSIGNATURE
		asynclocator-1.19.2-1.2.0.jar                     |Async Locator                 |asynclocator                  |1.19.2-1.2.0        |DONE      |Manifest: NOSIGNATURE
		expandability-forge-7.0.0.jar                     |ExpandAbility                 |expandability                 |7.0.0               |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.0.1+1.19.2.jar                 |Vein Mining                   |veinmining                    |1.0.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		[  е        ]createaddition-1.19.2-20221220a.jar  |Create Crafts & Additions     |createaddition                |1.19.2-20221220a    |DONE      |Manifest: NOSIGNATURE
		[ѭ  ]Cyclic-1.19.2-1.7.14.jar                     |Cyclic                        |cyclic                        |1.19.2-1.7.14       |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
	Crash Report UUID: b139397c-bcc3-4597-917d-4e8572e12944
	FML: 43.2
	Forge: net.minecraftforge:43.2.1
	FramedBlocks BlockEntity Warning: Not applicable
	Arclight Release: Horn
	Arclight: 
   Running: Arclight version arclight-1.19.2-1.0.1-0550c6cd (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) false

### Logs

https://pastebin.com/8Bbc2E68

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Looking into the Arclight source code, it seems to be overwriting quite a few things in the RecipeManager, in a way that breaks FD's RecipeManager accessor.

Does this crash happen exclusively with an Arclight server?

**Comment by vectorwing** [comment]
Yeah... looking a bit more at Arclight's code, I'm afraid this is an incompatibility. :(

Arclight replaces most of the RegistryManager using unsafe mixin methods like `@Overwrite`, which breaks other mods trying to utilize it. There isn't much I can do here.
