### ISSUE TITLE
[MC Version]: 1.18.2, cannot spawn rice in swamp

### ISSUE THREAD

**Issue by Sam-Chai** [vectorwing/FarmersDelight#622]
### Description

Farmer's delight's wild rice cannot spawn in minecraft:swamp biome.

### Steps to reproduce

1. Spawn a world
2. /locatebiome minecraft:swamp
3. I don't see any wild rice in swamp biome.

### Mod list

- This mod
- Tectonic terrain mod

### Logs

no speical logs. Just don't spawn wild rice

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Sorry for the late reply, @Sam-Chai!

There seems to be an ongoing issue regarding FD's world generation and biomes, either within a modded biome or when vanilla biomes suffer extensive generation changes (which I presume Tectonic is doing). I'll take a look later and see if something can be identified.

**Comment by vectorwing** [comment]
I made an instance with FD and Tectonic to test this out, and I was able to find all wild crops within vanilla biomes, at least. It could be that you got unlucky with your test worlds:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/b19c34e5-632e-4315-8abd-20916b26d7fc)

I did notice, however, that they don't seem to be spawning within Tectonic biomes. On 1.18, FD applies wild crops to biomes based on `BiomeCategory`, which I presume some mods aren't using to define their biomes. I'll need to test this a bit more.

**Comment by vectorwing** [comment]
Figured out the problem: Tectonic does not tag its biomes as `forge:is_overworld`. And it seems many biome mods don't either.

I added such a check to prevent wild crops from showing up in other dimensions (Nether, End etc), because some mods add biomes with dirt to them. But it seems this solution causes a different problem.

I'll investigate a better way to check for this condition.

**Comment by vectorwing** [comment]
Fixed on commit 2daa6e5, should be out in the 1.2.2 patch. 👍
