### ISSUE TITLE
[1.19.2]: Wild Cabbage crop feature checks for vanilla sand block, instead of sand tag

### ISSUE THREAD

**Issue by ManaStar** [vectorwing/FarmersDelight#623]
### Description

As the title says, the wild cabbage crop checks for minecraft's sand block below it for placement instead of the sand block tag. This is inconsistent with the sandy shrub feature which checks for the sand tag.

### Mod list

N/A

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
I think that I originally did it like that because it's a beach plant, so it could never spawn on Red Sand. But some mods might introduce modded beches with custom sand, so this would make sense.

Will take a look later.

**Comment by vectorwing** [comment]
Thinking a bit more, yeah, it doesn't make much sense to be so restrictive on which sands a beach crop can spawn in, since they check for the biome as well. I'll change the feature to use tags in a future patch to 1.19 and 1.20 soon. 👍

**Comment by vectorwing** [comment]
Updated on commit 7879cef, should be out for 1.2.2 later.
