### ISSUE TITLE
1.18.2 Cannot cut wheat dough

### ISSUE THREAD

**Issue by Berkmine** [vectorwing/FarmersDelight#625]
The game says it is non cuttable with knife shift clicked in the cutting board and when I put the wheat dough on the cutting board and right click it with a iron knife the game says use another tool.

**Comment by vectorwing** [comment]
This might be the issue with Farmer's Compats, where the knife tag was broken. Some users reported that the board was saying "Maybe with a different tool..." when it happened.

@Berkmine, try checking JEI for Raw Pasta's recipe; if it looks similar to the screenshot below, it could be that.

![image](https://user-images.githubusercontent.com/5566692/235521689-1fa9547f-76d9-45bf-8c7c-aa379471719e.png)

**Comment by vectorwing** [comment]
@Berkmine, I'll be closing this issue for now, as it's gotten stale. Feel free to reply to my question above, and I'll reopen it if needed.
