### ISSUE TITLE
1.19.2 Forge: glow berry custard can be eaten even with full hunger

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#627]
### Description

glow berry custard can be eaten even with full hunger

=
### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is intentional, so that you can trigger the Glow effect whenever you want.

**Comment by thelegitdolt** [comment]
mmmm
