### ISSUE TITLE
Server Watch Dog Crash due to Farmer Delight's task

### ISSUE THREAD

**Issue by emibanana** [vectorwing/FarmersDelight#630]
Server suddenly freeze, with no obvious sign before it's crashing (people are doing normal thing), but we finally figured out it's farmer's delight, because it show up both in crash log and in spark profiler, it shows that farmer's delight is keep trying to write/read an NBT data, to something.

This also make sense that why someone on the server sometime got disconnected due to "NBT data too large" error.

Crash log: https://mclo.gs/3bJUxi2

spark profiler (before the crash): https://spark.lucko.me/iCRjziLlhp

you can see farmer delight is still constantly using a lot of server resource (CPU)

**Comment by SHXRKIEgg** [comment]
I believe this is actually caused by Brewin and Chewin but the dev can comment on this to let us know

**Comment by vectorwing** [comment]
Sorry for the long delay! I was on hiatus before.

You seem to be using the Fabric version of FD, so I'm unable to help out with the issue. :(
Please forward your issue to this board instead: https://github.com/newhoryzon/farmers-delight-fabric/issues
