### ISSUE TITLE
[MC Version]: 1.19.2 Unable to connect to server

### ISSUE THREAD

**Issue by Ahydul** [vectorwing/FarmersDelight#638]
### Description

Using Farmer's Delight 1.2 I'm unable to connect to a server (with the same mod).
I've tested with forge 43.2.0, 43.2.3 and 43.2.4.

![image](https://user-images.githubusercontent.com/48711356/218304006-485f78ed-d874-46df-b94c-ab7985ca719e.png)

### Steps to reproduce

Connect to a localhost server.

### Mod list

Farmer's Delight 1.19-1.2.0
Forge 43.2.0 ( and 43.2.3, 43.2.4)

### Logs

Client: https://pastebin.com/3DjZu5rR
Server: nothing important

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [x] I have tested this without performance or shader mods

**Comment by gabmontes** [comment]
@Ahydul I'm having the same problem. How did you got around this?
