### ISSUE TITLE
[1.19.2] Stuffed pumpkins aren't compostable

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#639]
### Description

Stuffed pumpkins cannot be composted.

Given that they are composed entirely of compostable materials, I believe they should be compostable

### Steps to reproduce

1. Right click a stuffed pumpkin on a composter
2. it doesn't work

### Mod list

Farmer's Delight 1.2.0

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by thelegitdolt** [comment]
Here are some other things that should be compostable.

- kelp roll
- Sliced kelp roll
- Sandy Shrubs
- Yeah that's it i think

**Comment by vectorwing** [comment]
It seems I mistakenly registered the Stuffed Pumpkin **serving** instead of the full item, due to how I named them in code. 🤦

I'll correct this one and add the items you mentioned, as they're indeed fully vegetable.

**Comment by vectorwing** [comment]
Fixed on commit 0e3c0d3, will be ported over to 1.19 later.
