### ISSUE TITLE
Shears being dropped by dispenser

### ISSUE THREAD

**Issue by SwagRabbit** [vectorwing/FarmersDelight#64]
If shears are in a dispenser and it is activated, shears will be dropped by the dispenser instead of being used. 

In version 0.2.1 in minecraft 1.15.2

**Comment by vectorwing** [comment]
Can confirm. A sad consequence of how dispenser behaviors are registered.

I tried adding a _new_ one for Shears if they're facing the Cutting Board, but the registry dislikes dealing with more than one behaviour, causing it to cancel out the vanilla one.

I'm looking into a workaround, but honestly, I might just remove the behavior from shears for now. All it does is process saddles anyway. x)

**Comment by vectorwing** [comment]
@LordGrimmauld fixed it, and improved the dispenser registering on commit f9fcb30.
