### ISSUE TITLE
[Enhancement] - Make rabbits follow you when holding a Cabbage.

### ISSUE THREAD

**Issue by Crabanutij** [vectorwing/FarmersDelight#643]
Similar to carrots and flowers.

**Comment by 3gl1** [comment]
pretty funny
*also cabbage leaf

**Comment by vectorwing** [comment]
Hmm, true, Rabbits would enjoy some cabbage. I took a gander at how their temptations are implemented, and theirs is a bit worse/inconsistent compared to Pigs and Chickens, so I'll have to sit down to make this work. Might leave it in the backlog for now.

**Comment by vectorwing** [comment]
Added on commit 3532f6c, should be out in 1.2.2 soon.
