### ISSUE TITLE
[MC Version]: 1.19.3

### ISSUE THREAD

**Issue by Fontainianwaters** [vectorwing/FarmersDelight#644]
### Description

When I try to load this mod in the forge 1,19 latest download the game doesn't load properly. It says that there is an error with "void net" something. I attached the log here
[crash-2023-02-21_19.00.30-fml.txt](https://github.com/vectorwing/FarmersDelight/files/10795827/crash-2023-02-21_19.00.30-fml.txt)

### Mod list

farmer's delight
mr.crayfish furniture mod

### Logs

https://mclo.gs/5kfQKDU

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is because Farmer's Delight isn't out for 1.19.3 yet. This version changes how creative tabs work, so I have to update it first.
