### ISSUE TITLE
[1.19.2] Cooking Pot and dough recipe does not use the forge:buckets/water tag

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#646]
### Description

This means it is impossible to craft cooking pots with water buckets added by other mods, like Windswept's wooden buckets. 

### Mod list

Forge 
Farmer's Delight 

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
That doesn't seem to be an official Forge tag... Is that a commonly used "unofficial tag" amidst mods with custom buckets?

**Comment by thelegitdolt** [comment]
Yes! Abnormals and windswept definitely both use it.

**Comment by thelegitdolt** [comment]
I didn't know it wasn't an official tag though. Upon further inspection, it's apparently something from blueprint, and Abnormals Delight apparently changes the cooking pot and dough recipe themself to use the tag, so you probably don't have to go out of your way to do this
