### ISSUE TITLE
[MC Version]: 1.19.2

### ISSUE THREAD

**Issue by 3gl1** [vectorwing/FarmersDelight#647]
### Description

knifes are useless
![2023-02-24_21 14 31](https://user-images.githubusercontent.com/126273058/221338373-7d0e3afe-d440-4504-8287-78d576dc2582.png)
![2023-02-24_21 16 11](https://user-images.githubusercontent.com/126273058/221338375-5d1d94f6-41f0-4bdf-a526-be2324bcc51f.png)
problem with forge tags

### Steps to reproduce

1) get forge 43.2.0
2) look in the JEI menu (cutting table)

### Mod list

jei
farmer's delight
create
and many more (i'll leave a list later)

full list:
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		frozen_delight_1.3.0_forge_1.19.2.jar             |Frozen Delight (By NoCube)    |frozen_delight                |1.3.0               |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.19-6.2.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.2          |DONE      |Manifest: NOSIGNATURE
		mowlib-0.2.41.jar                                 |MowLib                        |mowlib                        |0.2.41              |DONE      |Manifest: NOSIGNATURE
		lore-1.19.2-1.0.jar                               |Lore                          |lore                          |1.0                 |DONE      |Manifest: NOSIGNATURE
		createbigcannons-1.19.2-beta-0.5.b.jar            |Create Big Cannons            |createbigcannons              |1.19.2-beta-0.5.b   |DONE      |Manifest: NOSIGNATURE
		create_misc_and_things_1.19.2_2.0.jar             |create: things and misc       |create_things_and_misc        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		open-parties-and-claims-forge-1.19.2-0.16.6.jar   |Open Parties and Claims       |openpartiesandclaims          |0.16.6              |DONE      |Manifest: NOSIGNATURE
		focusedbooks-0.1.1.jar                            |Focused Books                 |focusedbooks                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1011.jar                  |Just Enough Items             |jei                           |11.6.0.1011         |DONE      |Manifest: NOSIGNATURE
		giacomos_bookshelf1.3.3-1.19.2.jar                |Giacomo's bookshelves Mod     |giacomos_bookshelf            |1.3.3               |DONE      |Manifest: NOSIGNATURE
		paperbooks-1.19.2-3.0.jar                         |Paper Books                   |paperbooks                    |3.0                 |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.19.2-3.0.0.jar              |Library ferret                |libraryferret                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		kffmod-3.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.10.0              |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.8.a.jar                 |Flywheel                      |flywheel                      |0.6.8.a             |DONE      |Manifest: NOSIGNATURE
		alloyed-1.19.2-v1.5.jar                           |Create: Alloyed               |alloyed                       |1.19.2              |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.2.2.jar                   |Curios API                    |curios                        |1.19.2-5.1.2.2      |DONE      |Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.i.jar                         |Create                        |create                        |0.5.0.i             |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.1.0_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.1.0              |DONE      |Manifest: NOSIGNATURE
		create-stuff-additions1.19.2_v2.0.2a.jar          |Create Stuff & Additions      |create_sa                     |2.0.2               |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-6.48.jar                        |Collective                    |collective                    |6.48                |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.1-1.19.jar                            |Citadel                       |citadel                       |2.1.1               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.16.jar               |Traveler's Backpack           |travelersbackpack             |8.2.16              |DONE      |Manifest: NOSIGNATURE
		nocube's_farmers_compats_1.0.0_Forge_1.19.2.jar   |Farmer's Compats (by NoCube)  |nocubes_farmer_compats        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		create_central_kitchen-1.19.2-for-create-0.5.0.i-1|Create: Central Kitchen       |create_central_kitchen        |1.2.0               |DONE      |Manifest: NOSIGNATURE
		bettervillage-forge-1.19.2-2.0.0.jar              |Better village                |bettervillage                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.2-2.7.28.jar                   |Gobber 2                      |gobber2                       |2.7.28              |DONE      |Manifest: NOSIGNATURE
		create-confectionery1.19.2_v1.0.8.jar             |Create Confectionery          |create_confectionery          |1.0.8               |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.19.2-1.1.2.jar                |Create: Dragon Lib            |create_dragon_lib             |1.1.2               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre35-1.19.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre35         |DONE      |Manifest: NOSIGNATURE
		Steam_Rails-1.19.2-1.1.1.jar                      |Create: Steam 'n Rails        |railways                      |1.19.2-1.1.1        |DONE      |Manifest: NOSIGNATURE
		moredragoneggs-3.2.jar                            |More Dragon Eggs              |moredragoneggs                |3.2                 |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.1.35.jar             |CraftTweaker                  |crafttweaker                  |10.1.35             |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		FORGE-blanced_crates1.7.0-1.19.2.jar              |Balanced Crates               |balanced_crates               |1.7.0               |DONE      |Manifest: NOSIGNATURE
		frozenup-1.19.2-2.1.2-forge.jar                   |Frozen Up                     |frozenup                      |2.1.2-forge         |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		tl_skin_cape_forge_1.19_1.19.2-1.27.jar           |TLSkinCape                    |tlskincape                    |1.27                |DONE      |Manifest: 19:f5:ce:44:81:0c:e4:22:05:5e:73:c5:a8:cd:de:f3:c8:cf:a9:b3:01:70:40:a0:ee:2d:50:7a:1c:3d:1c:8a
		sliceanddice-2.0.1.jar                            |Create Slice & Dice           |sliceanddice                  |2.0.1               |DONE      |Manifest: NOSIGNATURE
		NekosEnchantedBooks-1.19-1.8.0.jar                |Neko's Enchanted Books        |nebs                          |1.8.0               |DONE      |Manifest: NOSIGNATURE
		createaddition-1.19.2-20230202b.jar               |Create Crafts & Additions     |createaddition                |1.19.2-20230202b    |DONE      |Manifest: NOSIGNATURE
total 44 mods

### Logs

[latest.log](https://github.com/vectorwing/FarmersDelight/files/10833468/latest.log)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is a common issue when using mods or add-ons which implement new knives. One of those mods is not registering their items in the `tools/knives` tag correctly, thus making it fail to load.

Please provide your `latest.log`, as it will contain a message saying which mod failed to register the tag.

**Comment by 3gl1** [comment]
> This is a common issue when using mods or add-ons which implement new knives. One of those mods is not registering their items in the `tools/knives` tag correctly, thus making it fail to load.
> 
> Please provide your `latest.log`, as it will contain a message saying which mod failed to register the tag.

ok
farmer compats is buggy
