### ISSUE TITLE
[SUGGESTION]: Data driven Recipe Book Tabs

### ISSUE THREAD

**Issue by Reshirou** [vectorwing/FarmersDelight#653]
Having the ability to make extra tabs for the recipe book,
like "Nether Meals", "Alex's Meals", "Vegetarian Meals", etc,
would be very helpful for addon makers and modpack makers alike.

**Comment by vectorwing** [comment]
Recipe categories are registered on game load, rather than world load, and are populated through in-code references. This prevents me from making the categores themselves data-driven. :(

The best I could look into are configs, but those would have to be very robust to make it work.
