### ISSUE TITLE
[1.19.2]: It is possible to plant wild potatoes, onions, and carrots on sand

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#656]
### Description

Wild Potatoes, onions, and carrots, are plantable on sand. I think this is kind of weird, as they never spawn on sand and other small flowers are not plantable on sand. 

### Steps to reproduce

1. Right click wild potatoes, onions, and carrots on a sand
2. Notice that you are able to place it.

### Mod list

Farmer's Delight
JEI

### Logs

Not necessary

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Wild Crops all inherit the same block class for simplicity, which lets them be planted on any sediment if needed. I guess we can chalk it up to them being hardy plants...? 😆

**Comment by vectorwing** [comment]
I'll mark this one up as intentional, as it doesn't cause much problems. Sorry, Dolt!
