### ISSUE TITLE
[Suggestion]: Add the ability to change recipes for the cooking pot and cutting board

### ISSUE THREAD

**Issue by RandomGuy91** [vectorwing/FarmersDelight#657]
### Description

Maybe use datapack-driven recipes or at least a config option or something? IDK 

### Mod list

N/A

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Not sure what you're referring to here... FD's cooking and cutting recipes are already datapack-based from the start; you should be able to override any of them, and add new ones, with a custom datapack.

If you ran into issues setting up a recipe datapack, I might be able to help. Usually the game's logs will report datapack loading failures, and indicate what went wrong; you can send them here if you'd like!

**Comment by RandomGuy91** [comment]
Oh, sorry I looked online and saw someone wondering abut that and figured it was still true but ig I needed to look around more. 
Thx for letting me know

**Comment by vectorwing** [comment]
For general datapack setup, the wiki tutorial is a good start:
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

For the .json syntax on cooking and cutting recipes, see here:
https://github.com/vectorwing/FarmersDelight/wiki/Cooking-Pot-Recipes
https://github.com/vectorwing/FarmersDelight/wiki/Cutting-Board-Recipes

To override an existing recipe, you must add a new .json with that recipe's exact name and path, rewriting it according to your new goals, and add it to a custom datapack. The previous recipe will be overridden.
