### ISSUE TITLE
[1.15.2] Server crash seemingly related to rich soil

### ISSUE THREAD

**Issue by 00-Steven** [vectorwing/FarmersDelight#66]
**Description**
Server crashes upon someone joining the server, unsure why exactly.
Did this get fixed in the 0.2.2 update or?

**Steps to reproduce:**
I'm unsure as to what exactly caused it, as it happened upon a player joining the server.
As to something related, we did have rich soil in the loaded area back from before the remapping.

**Expected behavior:**
I, uhh, expected the server to not crash upon someone joining.

**Mod List&Crash Log:**
https://pastebin.com/VUYnNJ87

**Comment by mallrat208** [comment]
Yep, that was one of the fixes in 0.2.2

**Comment by 00-Steven** [comment]
Ah nice, thanks
