### ISSUE TITLE
[1.19.2]: When right clicking a cutting board with a tool in display with an item displays the "No reason to cut this thingy..." tooltip

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#660]
### Description

Tools in display (that is, tools that are shift-right clicked on the cooking board) are usually placed for decoration. Therefore, it seems extraneous to display the tooltip in those cases.

### Steps to reproduce

1. Place cutting board
2. Shift-right click a tool onto it
3. Right click the board with any item

The tooltip will show up.

### Mod list

Farmer's Delight

### Logs

Not necessary

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by 3gl1** [comment]
To cut the food, you need to put THE FOOD on the CUTTING BOARD, and the KNIFE must be IN YOUR HAND

**Comment by thelegitdolt** [comment]
Que

**Comment by vectorwing** [comment]
> To cut the food, you need to put THE FOOD on the CUTTING BOARD, and the KNIFE must be IN YOUR HAND

They meant that you can still see the hint message when using items against a "carved tool", whose main purpose is to be a display item. Such items usually would not be cuttable, so I see the point here.

I suppose I could add some check to prevent processing checks if the tool is "carved"...

**Comment by vectorwing** [comment]
Applied on commit 07a505c. Should hopefully not cause issues. 😄
