### ISSUE TITLE
[1.19.2]: Mangrove Cabinet is untagged

### ISSUE THREAD

**Issue by gigawhip** [vectorwing/FarmersDelight#662]
### Description

Other cabinets have the `cabinets/wooden` tag, and the `cabinet` tag inherits from that. The Mangrove Cabinet has neither tag.

### Mod list

Forge 43.2.0
FarmersDelight-1.19-1.2.0.jar

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [x] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Fixed on pull request #611 by brnbrd, should be out in the next patch.
