### ISSUE TITLE
1.19.2: Stove is not making ambient sound

### ISSUE THREAD

**Issue by MythrilBagels** [vectorwing/FarmersDelight#663]
### Description

The Stove block does not make any passive ambient sound.
When lit, one would expect the stove to make sound, similar to the campfire block.
I feel like it used to make sound in previous versions, but I may be wrong.

### Steps to reproduce

1. Place down a Stove block
Observe as the Stove does not make any ambient sounds.

### Mod list

Forge 1.19.2 - 43.2.4
Farmer's Delight 1.19 - 1.2.0

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Fixed on commit 69ec25d. I forgot to change a `Random` to `RandomSource` and the game forgot my method existed. 😞
