### ISSUE TITLE
[1.19.2]: Vanilla eggs not compatiable in recipes

### ISSUE THREAD

**Issue by ExVonica** [vectorwing/FarmersDelight#665]
### Description

When trying to use vanilla eggs to create recipes, it does not work. For example, when the skillet is put on the stove then you try to cook an egg (to make fried egg) it says this item isn't cookable. It also doesn't allow other recipes, such as roast chicken, to be created with vanilla eggs.w
![Fry egg Bug](https://user-images.githubusercontent.com/128937714/227744523-c3199938-3603-4938-b448-27e031c79809.png)

### Steps to reproduce

When trying to fry an egg)
1. Set up stove with skillet and make sure it is on
2. Right click with egg in hand

When creating roast chicken)
1. Gather items needed
2. Place in crafting bench

### Mod list

Mod List: 
		YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        |YUNG's Better Dungeons        |betterdungeons                |1.19.2-Forge-3.2.2  |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v4.3.3-1.19.2-Forge.jar                 |Easy Magic                    |easymagic                     |4.3.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.19.2-forge-11.6.0.1013.jar                  |Just Enough Items             |jei                           |11.6.0.1013         |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.8.0-1.19.2.jar                    |Goblin Traders                |goblintraders                 |1.8.0               |DONE      |Manifest: NOSIGNATURE
		Strawgolem-forge-1.19.2-2.0.0-beta.5.jar          |Straw Golem                   |strawgolem                    |2.0.0-beta.5        |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.3.1.jar                 |Waystones                     |waystones                     |11.3.1              |DONE      |Manifest: NOSIGNATURE
		CTM-1.19.2-1.1.6+8.jar                            |ConnectedTexturesMod          |ctm                           |1.19.2-1.1.6+8      |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.0.3+1.19.2.jar                   |Comforts                      |comforts                      |6.0.3+1.19.2        |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.19.2-8.1.0.24.jar                 |Serene Seasons                |sereneseasons                 |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.9.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.9  |DONE      |Manifest: NOSIGNATURE
		Decorative+Blocks-forge-1.19.2-3.0.0.jar          |Decorative Blocks             |decorative_blocks             |3.0.0               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.2.18.jar                |Bookshelf                     |bookshelf                     |16.2.18             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		takesapillage-1.0.3-1.19.2.jar                    |It Takes A Pillage            |takesapillage                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.2.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.2.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.19.2-6.1.2.jar                        |Blueprint                     |blueprint                     |6.1.2               |DONE      |Manifest: NOSIGNATURE
		boatload-1.19.2-4.2.1.jar                         |Boatload                      |boatload                      |4.2.1               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.19-5.0.1.jar                       |Buzzier Bees                  |buzzier_bees                  |5.0.1               |DONE      |Manifest: NOSIGNATURE
		environmental-1.19.2-3.0.0.jar                    |Environmental                 |environmental                 |3.0.0               |DONE      |Manifest: NOSIGNATURE
		ShieldExpansion-1.19.2-1.1.5.jar                  |Shield Expansion              |shieldexp                     |1.1.5               |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.7-universal.jar                 |Forge                         |forge                         |43.2.7              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		revampedwolf-1.19.2-2.1.0.jar                     |RevampedWolf                  |revampedwolf                  |1.19.2-2.1.0        |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.2.35.jar                 |Supplementaries               |supplementaries               |1.19.2-2.2.35       |DONE      |Manifest: NOSIGNATURE
		structure_gel-1.19.2-2.7.1.jar                    |Structure Gel API             |structure_gel                 |2.7.1               |DONE      |Manifest: NOSIGNATURE
		chipped-forge-1.19.2-2.1.2.jar                    |Chipped                       |chipped                       |2.1.2               |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		upgrade_aquatic-1.19.2-5.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |5.0.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.3.jar                |More Villagers                |morevillagers                 |4.0.3               |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.136.jar           |TerraBlender                  |terrablender                  |2.0.1.136           |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.2.16-forge.jar                 |Moonlight Library             |moonlight                     |1.19.2-2.2.16       |DONE      |Manifest: NOSIGNATURE
		smarterfarmers-1.19.2-1.7.1.jar                   |Smarter Farmers               |smarterfarmers                |1.19.2-1.7.1        |DONE      |Manifest: NOSIGNATURE
		dungeons_plus-1.19.2-1.3.0.jar                    |Dungeons Plus                 |dungeons_plus                 |1.3.0               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.10.0+1.19.jar                  |SpectreLib                    |spectrelib                    |0.10.0+1.19         |DONE      |Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |DONE      |Manifest: NOSIGNATURE
		atmospheric-1.19.2-5.0.0.jar                      |Atmospheric                   |atmospheric                   |5.0.0               |DONE      |Manifest: NOSIGNATURE
		kffmod-3.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.11.0              |DONE      |Manifest: NOSIGNATURE
		CNB-1.19-1.5.2.jar                                |Creatures and Beasts          |cnb                           |1.5.2               |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.19.2-4.0.2.jar                |Abnormals Delight             |abnormals_delight             |4.0.2               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.19.2-Forge-3.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.19.2-Forge-3.1.0  |DONE      |Manifest: NOSIGNATURE
		DiagonalFences-v4.2.3-1.19.2-Forge.jar            |Diagonal Fences               |diagonalfences                |4.2.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		villagertools-1.19-1.0.3.jar                      |villagertools                 |villagertools                 |1.19-1.0.3          |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		backpacked-2.1.10-1.19.jar                        |Backpacked                    |backpacked                    |2.1.10              |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.19.2-1.1.23.jar            |Resourceful Lib               |resourcefullib                |1.1.23              |DONE      |Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		Adorn-3.8.1+1.19.2-forge.jar                      |Adorn                         |adorn                         |3.8.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v4.3.12-1.19.2-Forge.jar               |Puzzles Lib                   |puzzleslib                    |4.3.12              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13.jar |Oh The Biomes You'll Go       |byg                           |2.0.0.13            |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		letmedespawn-1.18.x-1.19.x-forge-1.0.3.jar        |Let Me Despawn                |letmedespawn                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE
		NekosEnchantedBooks-1.19-1.8.0.jar                |Neko's Enchanted Books        |nebs                          |1.8.0               |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.19.2-13.1.5.jar             |DarkPaintings                 |darkpaintings                 |13.1.5              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		BetterAdvancements-1.19.2-0.2.2.147.jar           |Better Advancements           |betteradvancements            |0.2.2.147           |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: e169a7c9-d5c5-4109-861c-737c3222b86c

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This seems to be an issue with **Abnormals Delight**: it attempts to disable Environmental's egg smelting recipes, but fails, causing both recipes to not be loaded: https://github.com/team-abnormals/abnormals-delight/issues/65

Since this is on the addon's end, I suggest following its issue board for updates, or temporarily disabling it.
