### ISSUE TITLE
[1.19.2]: Double Tatami Mats can be placed where they cannot survive

### ISSUE THREAD

**Issue by thelegitdolt** [vectorwing/FarmersDelight#670]
### Description

Tatami mats are placeable even if one of their blocks would end up on top of air. In this case, they will break themselves instantly. 

https://user-images.githubusercontent.com/50085439/229938900-4e4a18bb-862b-4ac1-a6d1-7247be9482d2.mov

### Steps to reproduce

See video

### Mod list

Farmer's Delight

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Although this kinda solves itself (it breaks, rather than staying in place), it's probably better to just prevent placement indeed.
