### ISSUE TITLE
[1.19.2]: Quark Deletes Items That In The Farmer's Delight Cabinet 

### ISSUE THREAD

**Issue by Blunder-G** [vectorwing/FarmersDelight#671]
### Description

When clicking "Sort" button in a Cabinet, all slots delete except the first slot

### Steps to reproduce

1. Install Quark 3.4-396 (Latest Version)
2. Farmer's Delight 1.2.0 (Latest Version)
3. Place Cabinet
4. Put Items in the Cabinet
5. Click "Sort" button on the top right corner

### Mod list

[modlist.txt](https://github.com/vectorwing/FarmersDelight/files/11169492/modlist.txt)

Forge: 43.2.8

### Logs

[latest.log](https://github.com/vectorwing/FarmersDelight/files/11169502/latest.log)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by Blunder-G** [comment]
https://github.com/VazkiiMods/Quark/issues/4134

**Comment by vectorwing** [comment]
Oof... yeah, this seems to be on Quark's end, given Vazkii's tagging on the mentioned issue. I'll keep this open, in case it's an issue with how I implemented the container, but it's best to follow the other issue for updates.

**Comment by vectorwing** [comment]
This seems to also affect some of Quark's containers, so it's likely not implementation-based. I'll close this issue for now; follow the one above in Quark's board for updates. 👍
