### ISSUE TITLE
[MC 1.19.2] Is there Biomes on Plenty Compatability?

### ISSUE THREAD

**Issue by NovaViper** [vectorwing/FarmersDelight#675]
Hey I'm wondering if there's compatability for Biomes O Plenty's biomes? I haven't been able to find any of the wild crops with the mod installed

**Comment by vectorwing** [comment]
There might currently be a problem in regards to generating wild crops in modded biomes. I'll have to sit down and check what's going on later.

**Comment by vectorwing** [comment]
Figured out the problem: FD filtered wild crop spawning to biomes tagged as `forge:is_overworld`, which BoP does not use. Instead, it uses sub-tags speficying overworld per biome tag.

I'm adding a different check to prevent non-Overworld generation, and it's working properly with BoP in my tests.

**Comment by vectorwing** [comment]
Fixed on commit 2daa6e5, should be out in the 1.2.2 patch. 👍
