### ISSUE TITLE
[1.19.2]: Minced Beef disappears after Bulk Smoked using the Create Mod

### ISSUE THREAD

**Issue by nicode3141** [vectorwing/FarmersDelight#678]
### Description

When minced beef is cooked using the Bulk Smoking Process in the Create Mod, the miced beef disappers when it should be turned into the Beef Patty.

### Steps to reproduce

Bulk Smoke the miced beef patty via a Fan which behind Lava.

### Mod list

Create Mod,
Farmers Delight
[Modpack]: Create Flavored

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Your setup is incorrect: to smoke food, you **must** specifically use a Campfire; if you use Lava (as described in your steps), it will destroy any food item on its stream.

Just tested locally, and it's working normally. 👍

![image](https://user-images.githubusercontent.com/5566692/235333781-515a60fd-47ef-4f38-96b1-ba7358f5a564.png)
