### ISSUE TITLE
Stove Ticking error

### ISSUE THREAD

**Issue by madbrad21** [vectorwing/FarmersDelight#68]
It appears while cooking on a stove (in this case I was cooking potatoes) a ticking error occurs. I believe it happens just before the item becomes the cooked variant as it did not occur right off. This was on a server using the Valhelsia 3 modpack, minecraft version 1.16.1, Mod version 0.2.1

Pastebin: https://pastebin.com/N5QffRyg

**Comment by vectorwing** [comment]
Hello! This issue has been fixed in version 0.2.2 of the mod. You can download it manually here, for now:
https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files

Sorry for the trouble! ^^
