### ISSUE TITLE
Egg Crate

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#681]
### Description

Please add this. All the other food items have a compacting recipe, why not eggs?

### Mod list

this one

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hey there! This board is for issues with the mod; please send feature suggestions to the **Discussions** tab instead. 👍

Crates are a feature inspired by Quark, so I chose to keep it only for vegetables for now. More crates could come someday, but it's not a priority at the moment.
