### ISSUE TITLE
[1.19.2]: Canvas Signs incompatible with Create's Display Link

### ISSUE THREAD

**Issue by p3lim** [vectorwing/FarmersDelight#682]
### Description

Canvas signs are not compatible display targets for the Create Display Link.  
Adding the "minecraft:signs" tag to the canvas blocks does not solve this as Create specifically targets `BlockEntityType.SIGN`:
https://github.com/Creators-of-Create/Create/blob/9c8df2ff2742176ff82fb9b6b27f1c9b37110bf5/src/main/java/com/simibubi/create/content/logistics/block/display/AllDisplayBehaviours.java#L234

Not sure if this can be solved on FD's end.

### Steps to reproduce

1. Place Canvas Sign
2. Right-click it with a Display Link from the Create mod
3. Place the display link on a compatible block(-entity)

Result:
![image](https://user-images.githubusercontent.com/26496/233799613-06930aae-0763-4391-80cf-83e3475f861c.png)

### Mod list

Forge 43.2.4
FarmersDelight 1.2.0
Create 0.5.0i

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by p3lim** [comment]
Sidenote; would be cool if hanging signs and sign posts could be valid display targets too, but that'd probably require extra work since they have more/less lines than a sign has.

**Comment by vectorwing** [comment]
Yeah, Canvas Signs use their own custom block entity type, so they're not included in that default.

I might need to explicitly add such integrations; I'll consult with the Create team later and see how it's done.

**Comment by vectorwing** [comment]
After talking with the Create team, they said they are working on it from their end. Keep an eye for future patches. 👍
