### ISSUE TITLE
1.18.2 Pigs wont eat corn 

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#693]
### Description

Was this intentional? it seems like they should

### Mod list

this one

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Corn is not an item from Farmer's Delight; it was probably added by another mod or add-on. The ability for pigs to eat it would have to be added by the mod which adds it.

**Comment by Aceplante** [comment]
Ah, I just realized Cultural delight was not made by you.
