### ISSUE TITLE
Pasta cooking does not show up in recipe book 1.18.2

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#699]
### Description

title. The cooking recipe of wheat/egg into pasta does not show up in the recipe book

### Mod list

this one

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Raw Pasta is a cutting recipe, made by cutting Wheat Dough with a Knife. It won't show up in the recipe book. 😉

JEI can display cutting recipes, so I recommend checking through it: Here's the most recent recipe:
![image](https://user-images.githubusercontent.com/5566692/235333048-a11b0d5a-c749-427a-bbc0-439801f10b5d.png)

**Comment by Aceplante** [comment]
Ah, this was also a cultural delights feature apologies. I didnt notice at the time i reported but Ill be sure to check now
