### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by JurajVajda** [vectorwing/FarmersDelight#705]
### Description

Question about the MIT license. Is that for the code, media/textures or both?

### Mod list

N/A

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [x] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
It currently applies to all parts of the project, including code and assets.

That said, for assets in specific, I'd prefer if usage was kept derivative (basing new assets from the ones on FD) if using them on a new project.

**Comment by JurajVajda** [comment]
Would it possible to mention this in the license file? Currently it doesnt say to what part of the project is the license applied. Thanks for the answer though i would definitely look towards derivates

**Comment by vectorwing** [comment]
I can only change the license for the whole project if I consult every past contributor for approval. Otherwise, changes would only "apply" to additions after the fact.

My preference above is mostly a formality outside the license, when people ask me for permissions directly. I might include it in a FAQ or something. 👍

**Comment by JurajVajda** [comment]
I am not asking to change the license. Just adding this (or similar) line to it (or readme) "license for code and assets see license txt."

**Comment by vectorwing** [comment]
Perhaps it could work on the README.md, I agree. I'll revisit it sometime. 👍
