### ISSUE TITLE
[1.19.2]: Add modded logs from Biomes You'll Go and Ars Nouveau to bark recipe

### ISSUE THREAD

**Issue by shannonr** [vectorwing/FarmersDelight#707]
### Description

When you use the Cutting board and Axe you can't use logs from Biomes You'll Go or Ars Nouveau to get bark and stripped logs. It just tells you it doesn't seem cuttable...
It would be wonderful if this compatibility could be added.

### Steps to reproduce

Place cutting board, put a log from Ars or BYG on there and right click with an axe.

### Mod list

The server modpack is Cottage Witch 
https://www.curseforge.com/minecraft/modpacks/cottage-witch
https://pastebin.com/xPMZbinL

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by Lethosos** [comment]
Toss this in.

https://github.com/Lethosos/Choppers-Delight

I don't have Ars Noveau in it, though. But I'll look it up for you.

**Comment by Lethosos** [comment]
It took me a while as I forgot about the changes Vector did to the chopping board recipes. Took the time to update the whole datapack. Both Ars Nouveau and Biomes You Go have been updated and functional; if you're running 1.19, just change the pack format number to 10.

https://github.com/Lethosos/Choppers-Delight/tree/1.18

**Comment by shannonr** [comment]
Thank you so much, this is amazing 💚
