### ISSUE TITLE
[1.15] Cooking Pot makes bowls vanish

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#71]
**Description**
If you right click on the cooking pot with a bowl on hand, the bowl will disappear

**Steps to reproduce:**
1- Hold an empty bowl on hand
2- Interact with Cooking Pot, opening the GUI
3- Bowl on hand is now an empty slot

**Expected behavior:**
Open the Cooking Pot GUI so that I can insert a bowl

**Mod list:**
FD Version: 0.2.2
Forge Version: 31.2.30

**Comment by vectorwing** [comment]
Can confirm it happens on both versions. I'll take a look, together with some code cleanups.

**Comment by vectorwing** [comment]
Fixed on commit 4fa0735. It was affecting whichever item was the previous valid container.
