### ISSUE TITLE
[MC Version]: 1.19.2 Cooking pot infinite bowls glitch

### ISSUE THREAD

**Issue by NcredibleDark** [vectorwing/FarmersDelight#711]
### Description

Cooking Pot drops empty wooden bowls out of nowhere every time a meal has been cooked and is stored in the pot. 

### Steps to reproduce

Cook for example fish stew: 
Put Salmon slice, tomato sauce, onions in the pot.
Don't put bowls in to collect the food. 
Watch the cooking pot drop empty bowls out of nowhere, when a meal is stored in it, although there are no bowls in it. 

### Mod list

1.19.2 Bmc3 
https://www.curseforge.com/minecraft/modpacks/better-mc-new

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is intended behavior; the bowls are from the **Tomato Sauce** you put in the input slots.

Whenever the Cooking Pot has leftover containers from its ingredients, they are tossed out the top, so they don't clog other slots. From there, you can choose to either:
- Place a Hopper or Basket to collect those containers;
- Put a Hopper pointing to the side of the Cooking Pot, so it will reinsert them into the Container slot, auto-serving meals.
