### ISSUE TITLE
[1.18.2]: Lily Pads can be placed on Rich Soil

### ISSUE THREAD

**Issue by LaGz4643** [vectorwing/FarmersDelight#715]
### Description

Lily Pads can be placed on top of Rich Soil blocks.
This bug probably affects the 1.19.2 version of Farmer's Delight as well but I have not tested it.

### Steps to reproduce

1. Place a Rich Soil block.
2. Try to place a Lily Pad on top of the Rich Soil.

### Mod list

Forge 40.2.0
Farmer's Delight 1.2.1

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Seems I have to be more restrictive with which plant types Rich Soil accepts. Thanks for noticing!
