### ISSUE TITLE
[1.19.2]: Breaking rice causes a crash

### ISSUE THREAD

**Issue by LONGACAT** [vectorwing/FarmersDelight#717]
### Description

Braking a rice plant causes a crash on the client. Addditionally, trying to join the server back results in the exact same crash.

Other players can go to the rice just fine, but when they touch it they get crashed and prevented from joining as well.

### Steps to reproduce

1. Host a server
2. Join it using a client
3. Ty breaking a rice plant (no idea if it has to be fully grown)
4. Minecraft crashes
5. Join the server again
6. Minecraft crashes before you load into the world

### Mod list

```
AutoRegLib-1.8.2-55.jar
BetterAdvancements-1.19.2-0.3.0.148.jar
BetterF3-4.0.0-Forge-1.19.2.jar
BiomesOPlenty-1.19.2-17.1.2.544.jar
Bookshelf-Forge-1.19.2-16.2.18.jar
BorderlessWindow-1.19.1-1.5.2.jar
Clumps-forge-1.19.2-9.0.0+14.jar
Controlling-forge-1.19.2-10.0+7.jar
CosmeticArmorReworked-1.19.2-v1a.jar
CullLessLeaves-Reforged-1.0.5.jar
Delightful-1.19-3.1.3.jar
Dimensional-Threading-Reforged-1.19.2-1.2.8.jar
DrawersTooltip-1.19.2-forge-6.0.2.jar
DungeonCrawl-1.19-2.3.12.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar
EnhancedBlockEntities-Reforged-1.19.2-0.7.3.jar
FarmersDelight-1.19-1.2.1.jar
FarmersRespite-1.19-2.0.jar
FastFurnace-1.19.2-7.0.0.jar
FastWorkbench-1.19.2-7.1.2.jar
ImmediatelyFastReforged-1.19.2-1.1.12.jar
ItalianDelight-1.19.2 1.5-MAR_FIX.jar
MouseTweaks-forge-mc1.19-2.23.jar
NoChatReports-FORGE-1.19.2-v1.5.1.jar
Placebo-1.19.2-7.1.8.jar
Quark-3.4-399.jar
StorageDrawers-1.19-11.1.2.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
TextruesRubidiumOptions-1.0.5-mc1.19.2.jar
TravelersTitles-1.19.2-Forge-3.1.2.jar
YungsApi-1.19.2-Forge-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar
appleskin-forge-mc1.19-2.4.2.jar
architectury-6.5.82-forge.jar
badpackets-forge-0.2.1.jar
balm-forge-1.19.2-4.5.7.jar
brrp-forge-0.9.0-1.19.2.jar
capes-1.5.2+1.19.2-forge.jar
chat_heads-0.10.14-forge-1.19.2.jar
clear-skies-forge-mc119-2.0.95.jar
cloth-config-8.2.88-forge.jar
collective-1.19.2-6.53.jar
comforts-forge-6.0.5+1.19.2.jar
configured-2.1.1-1.19.2.jar
connectedness-2.0.1a.jar
constructionwand-1.19.2-2.10.jar
dungeons_enhanced-1.19.2-4.1.jar
dungeons_plus-1.19.2-1.3.1.jar
durabilityviewer-1.19.1-forge42.0.1-1.10.jar
entityculling-forge-1.6.1-mc1.19.2.jar
explorify-forge-1.19-1.3.0.jar
farsight-1.19.2-2.1.jar
ftb-library-forge-1902.3.18-build.208.jar
ftb-ultimine-forge-1902.4.0-build.77.jar
ftbbackups2-forge-1.19.2-1.0.18.jar
hiddenrecipebook-1.19.2-4.0.jar
jeed-1.19.2-2.1.2.jar
jei-1.19.2-forge-11.6.0.1015.jar
journeymap-1.19.2-5.9.7-forge.jar
justzoom_forge_1.0.1-1_MC_1.19.jar
konkrete_forge_1.6.1_MC_1.19-1.19.2.jar
kotlinforforge-3.12.0-all.jar
light-overlay-7.0.1-forge.jar
lightspeed-1.19.2-1.0.4.jar
lootr-1.19-0.4.23.60.jar
no-telemetry-1.7.0.jar
polylib-forge-1900.0.2-build.73.jar
polymorph-forge-0.46.1+1.19.2.jar
reforgium-1.0.12a.jar
rubidium-0.6.2a.jar
rubidium-extra-0.4.17+mc1.19.2-build.71.jar
rubidium_extras-1.19.2_v1.3.2.jar
seamless-1.1.0-forge-1.19.2.jar
sophisticatedbackpacks-1.19.2-3.18.45.819.jar
sophisticatedcore-1.19.2-0.5.54.261.jar
sophisticatedstorage-1.19.2-0.7.8.366.jar
starlight-1.1.1+forge.cf5b10b.jar
structure_gel-1.19.2-2.7.2.jar
waystones-forge-1.19.2-11.4.0.jar
wthit-forge-5.15.5.jar
wthitharvestability-mc1.19.2-2.1.0.jar
```

### Logs

Crash when breaking the rice: [crash-2023-05-16_13.41.58-client.txt](https://github.com/vectorwing/FarmersDelight/files/11487439/crash-2023-05-16_13.41.58-client.txt)
Crash when trying to join the server again: [crash-2023-05-16_13.44.13-client.txt](https://github.com/vectorwing/FarmersDelight/files/11487440/crash-2023-05-16_13.44.13-client.txt)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Hmm... this is a really odd crash, as it doesn't even seem to be occurring from FD's classes. It looks like something else accessed the rice panicle's coordinate wrongly for its properties and shape.

After asking for some help, it could have been caused by performance and shader mods. @LONGACAT Could you and your players please test your steps again, while disabling all performance mods? For example: Rubidium, Reforged, OF, Iris etc.

**Comment by vectorwing** [comment]
Quick addendum: it could happen that this particular chunk crash is resolved after disabling, testing and re-enabling those mods, as those interactions tend to be very sporadic and random. So it's worth testing without them for that too.

**Comment by vectorwing** [comment]
Hey @LONGACAT, are you still having this issue? Were you able to run the test above?

**Comment by vectorwing** [comment]
I'm closing this issue, as it's become stale. If you're still having this issue @LONGACAT, feel free to reply here and I'll reopen it.
