### ISSUE TITLE
[MC Version]: 1.18.2 // empty forge tags

### ISSUE THREAD

**Issue by AresRedwod** [vectorwing/FarmersDelight#720]
### Description

empty forge tag in recipe:
chicken soup
vegetable soup
pumpkin soup
mixed salat
chicken sandwich...
everything with the tag vegetables or salad i think

### Mod list

Forge 40.2.1 , farmer's delight latest 1.18.2 version

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by AresRedwod** [comment]
ok the problem is pam's harvest craft 2 T.T is there a way to fix this?

**Comment by vectorwing** [comment]
I believe this is a known issue, currently.

Due to the error being in HC2's tag datapacks, it would have to be fixed on their end, or with a custom datapack which edits their implementation. I suggest forwarding this issue to the HC2 team with the details you found.
