### ISSUE TITLE
[MC !.19.2]: Cutting Board item rendering

### ISSUE THREAD

**Issue by Ross2750** [vectorwing/FarmersDelight#721]
### Description

When you put any item in cutting board the item renders vertically but if you put cutting board in a cutting board it renders correctly
![2023-05-26_17 57 31](https://github.com/vectorwing/FarmersDelight/assets/122451270/be6e73c0-15a0-4343-b539-8d114bcaa565)
![2023-05-26_17 56 52](https://github.com/vectorwing/FarmersDelight/assets/122451270/ec254592-5b70-41da-8a2b-61d05679bf32)

### Steps to reproduce

Put any item in cutting board except to cutting board

### Mod list

[Mod List.txt](https://github.com/vectorwing/FarmersDelight/files/11574131/Mod.List.txt)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is a Forge bug. Please update to a Forge version higher than 43.2.0 to fix it. 👍

**Comment by Ross2750** [comment]
> This is a Forge bug. Please update to a Forge version higher than 43.2.0 to fix it. 👍

but i use forge 43.2.0

**Comment by MythrilBagels** [comment]
"Higher than..."
It doesn't work with 43.2.0, thats the issue.

**Comment by thelegitdolt** [comment]
thanks bagels
