### ISSUE TITLE
[1.19.2]: Chance to crash on world creation

### ISSUE THREAD

**Issue by SiverDX** [vectorwing/FarmersDelight#735]
### Description

Might happen if you spawn in a biome which matches the condition for this to spawn?
Did not occur yet when I created large biome worlds
(Only happened once so far)

``` log
[08Jun2023 10:22:15.474] [Server thread/ERROR] [net.minecraft.util.thread.BlockableEventLoop/FATAL]: Error executing task on Chunk source main thread executor for minecraft:overworld
net.minecraft.ReportedException: Exception generating new chunk
	at net.minecraft.server.level.ChunkMap.m_214912_(ChunkMap.java:634) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:535) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:543) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:1762) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:1658) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:179) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:5049) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.PlayerRespawnLogic.m_183928_(PlayerRespawnLogic.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.PlayerRespawnLogic.m_183932_(PlayerRespawnLogic.java:64) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.MinecraftServer.m_177896_(MinecraftServer.java:399) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:338) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:300) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.client.server.IntegratedServer.m_7038_(IntegratedServer.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:625) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalStateException: Trying to access unbound value 'ResourceKey[minecraft:worldgen/placed_feature / farmersdelight:patch_wild_tomatoes]' from registry Registry[ResourceKey[minecraft:root / minecraft:worldgen/placed_feature] (Stable)]
	at net.minecraft.core.Holder$Reference.m_203334_(Holder.java:151) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at com.alcatrazescapee.cyanide.codec.FeatureCycleDetector.buildFeaturesPerStep(FeatureCycleDetector.java:73) ~[cyanide-forge-1.19.2-3.0.1.jar%23541!/:3.0.1]
	at net.minecraft.world.level.biome.FeatureSorter.handler$flh000$buildFeaturesPerStepWithAdvancedCycleDetection(FeatureSorter.java:529) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.world.level.biome.FeatureSorter.m_220603_(FeatureSorter.java) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at com.teamabnormals.blueprint.common.world.modification.ModdedBiomeSlicesManager.lambda$onServerAboutToStart$3(ModdedBiomeSlicesManager.java:108) ~[blueprint-1.19.2-6.1.2.jar%23498!/:6.1.2]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.0.1-jre.jar%23116!/:?]
	at net.minecraft.world.level.chunk.ChunkGenerator.m_213609_(ChunkGenerator.java:397) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223313_(ChunkStatus.java:145) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%23121!/:?]
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.19.2-20220805.130853-srg.jar%23767!/:?]
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?]
```

### Mod list

- maenchants-1.19.2-6.0.0.jar                       
- saturn-mc1.19.2-0.0.4.jar                         
- dynamiclightsreforged-1.19.2_v1.4.0.jar           
- adaptive_performance_tweaks_core_1.19.2-6.9.1.jar 
- YungsBetterDungeons-1.19.2-Forge-3.2.2.jar        
- EasyAnvils-v4.0.11-1.19.2-Forge.jar               
- Revised Phantoms 1.0.4 - 1.19.2.jar               
- Ulterlands v1.2.1 _ 19.jar                        
- player-animation-lib-forge-1.0.2.jar              
- botarium-forge-1.19.2-1.8.2.jar                   
- majruszs-difficulty-1.19.2-1.7.5.jar              
- Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar   
- rubidium-0.6.2a.jar                               
- modernfix-mc1.19.2-forge-3.7.1.jar                
- VillagersPlus_1.2_(FORGE)_for_1.19.2.jar          
- YungsApi-1.19.2-Forge-3.8.9.jar                   
- MaxHealthFix-Forge-1.19.2-8.0.1.jar               
- extrapotions-1.19.2-1.5.jar                       
- upgradednetherite_items-1.19.2-4.1.0.1-release.jar
- toolleveling-forge-1.19.2-1.4.1.jar               
- opulence-1.19.2-0.2.0.jar                         
- Apotheosis-1.19.2-6.2.1.jar                       
- clickadv-1.19.2-3.0.jar                           
- PickUpNotifier-v4.2.4-1.19.2-Forge.jar            
- balm-forge-1.19.2-4.5.7.jar                       
- dynview-1.19.1-2.9.jar                            
- JustEnoughResources-1.19.2-1.2.2.200.jar          
- chat_heads-0.10.14-forge-1.19.2.jar               
- YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar
- cloth-config-8.2.88-forge.jar                     
- iterpg-0.4.2a.jar                                 
- geophilic‐1.19-2.0.0b.jar                         
- upgradednetherite-1.19.2-5.1.0.9-release.jar      
- novillagerdm-1.19-4.0.0.jar                       
- structure_gel-1.19.2-2.7.2.jar                    
- explorations-forge-1.19.2-1.5.1.jar               
- morevillagers-forge-1.19-4.0.3.jar                
- explorify-forge-1.19-1.3.0.jar                    
- ColaMixinConfig-v1.0.2.jar                        
- dungeons_plus-1.19.2-1.3.1.jar                    
- UnusualEnd1.19.2_V1.4.3.jar                       
- supermartijn642corelib-1.1.9a-forge-mc1.19.2.jar  
- resourcefulconfig-forge-1.19.2-1.0.20.jar         
- TextruesRubidiumOptions-1.0.5-mc1.19.2.jar        
- spark-1.10.37-forge.jar                           
- Philips-Ruins1.19.2-6.0.jar                       
- curiouslanterns-1.19.2-1.3.3.jar                  
- lightspeed-1.19.2-1.0.4.jar                       
- curios-forge-1.19.2-5.1.4.1.jar                   
- corail_woodcutter-1.19.2-2.5.2.jar                
- oculus-mc1.19.2-1.2.8a.jar                        
- reforgium-1.0.12a.jar                             
- bettervillage-forge-1.19.2-3.1.0.jar              
- queen_bee-3.0.1-1.19.2.jar                        
- antighost-1.19.1-forge42.0.1-1.1.3.jar            
- dragon_enchants-1.0.4-1.19.2.jar                  
- soulfired-1.19.2-3.1.0.0-final-forge.jar          
- pluto-mc1.19.2-0.0.9.jar                          
- brrp-forge-0.9.0-1.19.2.jar                       
- Masik'sPuzzleDungeon-forge-1.19.2-v1.0.7.1.jar    
- unsafe-world-random-access-detector-1.1.0+forge.ja
- EasyShulkerBoxes-v4.4.1-1.19.2-Forge.jar          
- YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar      
- BetterModsButton-v4.2.1-1.19.2-Forge.jar          
- sliceanddice-forge-2.2.0.jar                      
- vitalize-forge-1.19.2-1.1.1.jar                   
- Kiwi-1.19.1-forge-8.3.4.jar                       
- clienttweaks-forge-1.19.2-8.1.2.jar               
- StylishEffects-v4.3.4-1.19.2-Forge.jar            
- adaptive_performance_tweaks_spawn_1.19.2-6.9.0.jar
- Fastload-Reforged-3.3.7+1.19.2.jar                
- shieldmechanics-1.19.2-3.5.jar                    
- tia-1.19.2-1.0-forge.jar                          
- Block_Swapper-1.19-1.1.jar                        
- Nameless Trinkets-1.19.2-1.6.11.jar               
- VisualWorkbench-v4.2.4-1.19.2-Forge.jar           
- AttributeFix-Forge-1.19.2-17.2.6.jar              
- Pehkui-3.7.5+1.19.2-forge.jar                     
- libraryferret-forge-1.19.2-4.0.0.jar              
- goblintraders-1.8.0-1.19.2.jar                    
- caelus-forge-1.19.2-3.0.0.6.jar                   
- Kobolds-2.6.6.jar                                 
- carpeted-1.19.2-1.4.jar                           
- fullstackwatchdog-1.0.1+1.19.2-forge.jar          
- dungeonnowloading-18.2-1.19.2.jar                 
- mobhealthbar-forge-1.19-41.0.100-2.1.1.jar        
- integrated_api_forge-1.2.7+1.19.2.jar             
- NaturesCompass-1.19.2-1.10.0-forge.jar            
- starlight-1.1.1+forge.cf5b10b.jar                 
- additional_lights-1.19-2.1.6.jar                  
- davespotioneering-1.19.2-1.1.5.jar                
- catalogue-1.7.0-1.19.2.jar                        
- JeiTweaker-forge-1.19.2-4.0.12.jar                
- dismountentity-1.19.2-3.0.jar                     
- memoryleakfix-forge-1.17+-1.0.0.jar               
- CraftTweaker-forge-1.19.2-10.1.44.jar             
- rubidium_extras-1.19.2_v1.3.2.jar                 
- forge-1.19.2-43.2.11-universal.jar                
- extractinator-forge-1.19.2-2.1.0.jar              
- Log-Begone-Forge-1.19-1.0.6.jar                   
- idas_forge-1.7.4+1.19.2.jar                       
- SpikySpikes-v4.0.8-1.19.2-Forge.jar               
- client-1.19.2-20220805.130853-srg.jar             
- cofh_core-1.19.2-10.2.1.40.jar                    
- smoothchunk-1.19.1-2.0.jar                        
- MobPC-1.19-1.0.0.jar                              
- emi-1.0.2+1.19.2+forge.jar                        
- usefulspyglass-forge-1.19.2-0.3.0.jar             
- bettercombat-forge-1.7.1+1.19.jar                 
- commonality-1.19.2-4.2.1.jar                      
- majrusz-library-1.19.2-4.2.0.jar                  
- enchsort-1.19.2-1.1.5-all.jar                     
- spectrelib-forge-0.11.0+1.19.jar                  
- domum_ornamentum-1.19-1.0.83-ALPHA-universal.jar  
- betterfpsdist-1.19.2-1.8.jar                      
- kffmod-3.12.0.jar                                 
- notenoughanimations-forge-1.6.2-mc1.19.2.jar      
- flywheel-forge-1.19.2-0.6.8.a-14.jar              
- ecologics-forge-1.19.2-2.1.11.jar                 
- Xaeros_Minimap_23.4.4_Forge_1.19.1.jar            
- rubidium-extra-0.4.17+mc1.19.2-build.71.jar       
- aquacombat-1.1.0.jar                              
- polymorph-forge-0.46.1+1.19.2.jar                 
- JustEnoughProfessions-forge-1.19.2-2.0.2.jar      
- AutoRegLib-1.8.2-55.jar                           
- LeaveMyBarsAlone-v4.0.0-1.19.2-Forge.jar          
- almostunified-forge-1.19.2-0.4.4.jar              
- DoubleSlabs-1.19-6.1.0.jar                        
- canary-mc1.19.2-0.2.4.jar                         
- global_packs-forge-1.19.2-1.14.4_forge.jar        
- ImmediatelyFastReforged-1.19.2-1.1.12.jar         
- FastFurnace-1.19.2-7.0.0.jar                      
- Sculk_Expansion_v1.0.1.jar                        
- appleskin-forge-mc1.19-2.4.2.jar                  
- upgradednetherite_ultimate-1.19.2-4.1.0.4-release.
- PuzzlesLib-v4.4.0-1.19.2-Forge.jar                
- Aquaculture-1.19.2-2.4.8.jar                      
- rebind_narrator-forge-1.19.2-2.0.1.jar            
- goated-1.19.2-1.3.1.jar                           
- CosmeticArmorReworked-1.19.2-v1a.jar              
- chunksending-forge-1.19-2.5.jar                   
- Sculked V1.4.1.jar                                
- deuf-1.19.2-1.3.jar                               
- pots_and_mimics_rpg_1.0.0_forge_1.19.2.jar        
- TreeChop-1.19.2-forge-0.17.8a.jar                 
- notenoughcrashes-4.2.1+1.19.2-forge.jar           
- Trial and Error modifications-1.0.jar             
- wandering-bags-1.19.2-2.0.6.jar                   
- YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar       
- netherportalfix-forge-1.19-10.0.1.jar             
- SpelunkingBags1.19_V1.0.2.jar                     
- DistinguishedPotions-v4.0.1-1.19.2-Forge.jar      
- PalladiumCore-forge-1.19.2-1.2.3.4-forge.jar      
- vc_gliders-1.0.2-forge.jar                        
- wildberries-1.1.3[forge-1.19.2].jar               
- naturalist-forge-3.0.3a-1.19.2.jar                
- YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar  
- connectivity-1.19.2-4.2.jar                       
- auditory-0.0.5-1.19.2.jar                         
- sophisticatedcore-1.19.2-0.5.68.306.jar           
- structureessentials-1.19.2-2.8.jar                
- connectedness-2.0.1a.jar                          
- piglinproliferation-1.19.2-1.0.3.jar              
- XaerosWorldMap_1.30.3_Forge_1.19.1.jar            
- Controlling-forge-1.19.2-10.0+7.jar               
- Placebo-1.19.2-7.2.0.jar                          
- citadel-2.1.4-1.19.jar                            
- Bookshelf-Forge-1.19.2-16.3.20.jar                
- forgery-3.2.7+1.19.jar                            
- sophisticatedbackpacks-1.19.2-3.18.50.847.jar     
- create_dragon_lib-1.19.2-1.2.1.jar                
- relics-1.19.2-0.4.6.jar                           
- takesapillage-1.0.3-1.19.2.jar                    
- jeed-1.19.2-2.1.3.jar                             
- mermod-forge-1.11.jar                             
- tooltipscroller-1.19.2-1.0.0.jar                  
- firearrows-1.19.2-11-forge.jar                    
- cameraoverhaul-1.0-1.19.2.jar                     
- dummmmmmy-1.19.2-1.7.1.jar                        
- absentbydesign-1.19-1.7.0.jar                     
- AirHop-v4.2.1-1.19.2-Forge.jar                    
- EnemyExpansion1.13-1.19.2.jar                     
- ArcaneLanterns-v4.0.0-1.19.2-Forge.jar            
- mcw-bridges-2.0.7-mc1.19.2forge.jar               
- FarmersDelight-1.19-1.2.1.jar                     
- entity_model_features_forge_1.19.2-0.2.9.jar      
- entity_texture_features_forge_1.19.2-4.4.4.jar    
- AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar          
- betterspawnercontrol-1.19.2-4.0.jar               
- Trajectory Preview-4.5.1-1.19.jar                 
- projectvibrantjourneys-1.19.2-5.1.0.jar           
- endrem_forge-5.2.1-R-1.19.X.jar                   
- Boat-Item-View-Forge-1.19.x-0.0.4.jar             
- JER-Integration-4.4.0.jar                         
- born_in_chaos_[Forge]1.19.2_1.5.jar               
- dungeons_enhanced-1.19.2-4.1.jar                  
- modelfix-1.8.jar                                  
- CNB-1.19-1.5.4.jar                                
- L_Enders_Cataclysm-0.84-1.19.2.jar                
- Patchouli-1.19.2-77.jar                           
- SpitItOut-1.19.4-1.0.0.jar                        
- collective-1.19.2-6.53.jar                        
- spyglass_improvements-1.4+mc1.19+forge.jar        
- Gothic_RPG_1.0.1_Forge_1.19.2.jar                 
- EnigmaticLegacy-2.26.5.jar                        
- resourcefullib-forge-1.19.2-1.1.24.jar            
- spirit-forge-1.19.2-2.2.6.jar                     
- InventoryProfilesNext-forge-1.19-1.10.2.jar       
- BoatBreakFix-Universal-1.0.11.jar                 
- architectury-6.5.85-forge.jar                     
- seamless-1.3.0-forge-1.19.2.jar                   
- ToolKit-forge-2.3.8-build.18+mc1.19.2.jar         
- furnish-23-forge.jar                              
- EnhancedBlockEntities-Reforged-1.19.2-0.7.3.jar   
- biomancy-forge-1.19.2-2.0.53.2.jar                
- jei-1.19.2-forge-11.6.0.1015.jar                  
- sullysmod-2.3.1-beta.jar                          
- geckolib-forge-1.19-3.1.40.jar                    
- adaptive_performance_tweaks_items_1.19.2-6.8.0.jar
- HopoBetterMineshaft-[1.19-1.19.3]-1.1.6.jar       
- Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        
- observable-3.3.1.jar                              
- DragonSurvival-1.19.2-1.5.42.jar                  
- TradingPost-v4.2.0-1.19.2-Forge.jar               
- BetterAdvancements-1.19.2-0.3.0.148.jar           
- majruszs-accessories-1.19.2-1.1.5.jar             
- PortableHole-v4.0.0-1.19.2-Forge.jar              
- xtraarrows-2.4.3-forge-mc1.19.2.jar               
- trashslot-forge-1.19-12.0.2.jar                   
- Grass_Overhaul-Forge-23.05.28_MC1.19.2.jar        
- Reaper-1.0.4.jar                                  
- oculus-flywheel-compat-1.19.2-0.1.8-BETA.jar      
- blueflame-1.19.2-0.1.0.2.jar                      
- sophisticatedstorage-1.19.2-0.8.26.443.jar        
- xlpackets-1.18.2-2.1.jar                          
- SpawncapControlUtility-1.19-41.1.2.0.jar          
- obscure_api-15.jar                                
- aquamirae-6.API15.jar                             
- ensorcellation-1.19.2-4.2.0.14.jar                
- create-1.19.2-0.5.1.b.jar                         
- create_crystal_clear-0.2.1-1.19.2.jar             
- waystones-forge-1.19.2-11.4.0.jar                 
- Structory_1.19.3_v1.3.1a.jar                      
- FastSuite-1.19.2-4.1.0.jar                        
- artifacts-1.19.2-5.0.2.jar                        
- configured-2.1.1-1.19.2.jar                       
- Decorative Blocks-forge-1.19.2-3.0.0.jar          
- PermanentSponges-v4.0.0-1.19.2-Forge.jar          
- make_bubbles_pop-0.1.0.jar                        
- fastentitytransfer-forge-1.19.x-1.1.3.jar         
- lazydfu-1.19-1.0.2.jar                            
- cyanide-forge-1.19.2-3.0.1.jar                    
- YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar   
- HopoBetterUnderwaterRuins-[1.19-1.19.3]-1.1.1.jar 
- ExplorersCompass-1.19.2-1.3.1-forge.jar           
- netherdepthsupgrade-3.0.0-1.19.2.jar              
- farsight-1.19.2-2.1.jar                           
- Terralith_1.19.3_v2.3.8.jar                       
- blueprint-1.19.2-6.1.2.jar                        
- savage_and_ravage-1.19.2-5.0.4.jar                
- clayworks-1.19.2-2.0.1.jar                        
- allurement-1.19.2-3.1.0.jar                       
- buzzier_bees-1.19-5.0.1.jar                       
- miningmaster-1.19.2-4.0.0.jar                     
- adaptive_performance_tweaks_player_1.19.2-6.8.0.ja
- toofast-1.19-0.2.2.4.jar                          
- libIPN-forge-1.19-3.0.1.jar                       
- EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  
- dynamic_asset_generator-forge-1.19.2-1.2.0.jar    
- radiantgear-forge-2.0.1+1.19.2.jar                
- moonlight-1.19.2-2.2.37-forge.jar                 
- spelunkery-1.19.2-0.2.2-forge.jar                 
- smarterfarmers-1.19.2-1.7.1.jar                   
- ToolBelt-1.19.2-1.19.7.jar                        
- Jade-1.19.1-forge-8.8.1.jar                       
- additionaladditions-5.1.0.jar                     
- HopoBetterRuinedPortals-[1.19-1.19.3]-1.3.3.jar   
- enchantment_enhancements-1.19.2-1.6.1.jar         
- CullLessLeaves-Reforged-1.0.5.jar                 
- CreativeCore_FORGE_v2.9.3_mc1.19.2.jar            
- rottencreatures-forge-1.19.2-1.0.1.jar            
- betterstats-2.2.2+1.19.2.jar                      
- tcdcommons-2.2+1.19.2.jar                         
- BarteringStation-v4.0.3-1.19.2-Forge.jar          
- CITResewn-1.1.1.jar                               
- Quark-3.4-402.jar                                 
- supplementaries-1.19.2-2.3.17.jar                 
- mutil-1.19.2-5.1.0.jar                            
- brutalbosses-1.19.2-6.3.jar                       
- create-stuff-additions1.19.2_v2.0.3b.jar          
- FastWorkbench-1.19.2-7.1.2.jar                    
- NoSeeNoTick-1.19.2-1.0.0.jar                      
- irons_spellbooks-1.19.2-1.1.3.jar                 
- DiagonalFences-v4.2.5-1.19.2-Forge.jar            
- invhud.forge.1.19-3.4.7.jar                       
- upgradedcore-1.19.2-4.1.0.1-release.jar           
- raised-forge-1.19.2-1.2.2.jar                     
- Wabi-Sabi-Structures-1.1.2-Forge.jar              
- BetterTridents-v4.0.2-1.19.2-Forge.jar            
- hunterillager-1.19.2-8.0.0.jar                    
- mvs-3.2-1.19.2.jar                                
- creeperoverhaul-2.0.9-forge.jar                   
- ferritecore-5.0.3-forge.jar                       
- SoL-Carrot-1.19.2-1.14.0.jar                      
- apexcore-1.19.2-7.3.1.jar                         
- fantasyfurniture-1.19.2-6.7.0.jar                 
- charmofundying-forge-6.2.0+1.19.2.jar             
- BetterF3-4.0.0-Forge-1.19.2.jar                   
- majruszs-enchantments-1.19.2-1.8.2.jar            
- expandability-7.0.0.jar                           
- MobLassos-v4.0.0-1.19.2-Forge.jar                 
- create_enchantment_industry-1.19.2-for-create-0.5.
- OverflowingBars-v4.0.1-1.19.2-Forge.jar           
- UndeadUnleashed-1.0.3-1.19.2.jar                  
- createaddition-1.19.2-20230527a.jar               
- PresenceFootsteps-1.19.2-1.6.4.1-forge.jar        

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
That's a really long mod list... 😅

Logs don't seem to point out any specific culprit. I asked around a bit, and the "unbound value" error would likely happen if someone was creating such value after the server started.

Has this error happened again on any world generation? @SiverDX

**Comment by vectorwing** [comment]
Yeah... looking a bit more at Arclight's code, I'm afraid this is an incompatibility. :(

Arclight replaces most of the RegistryManager using unsafe mixin methods like `@Overwrite`, which breaks other mods trying to utilize it. There isn't much I can do here.

**Comment by SiverDX** [comment]
Arclight?

Do you mean this: https://github.com/IzzelAliz/Arclight?

Not using that, it was a Singeplayer world using the Prism Launcher

So far it has happened only once but that one time was the first time I created a non-large world

**Comment by vectorwing** [comment]
> Arclight?
> 
> Do you mean this: https://github.com/IzzelAliz/Arclight?
> 
> Not using that, it was a Singeplayer world using the Prism Launcher
> 
> So far it has happened only once but that one time was the first time I created a non-large world

Oops, I replied to the wrong issue. My bad! ^^

**Comment by vectorwing** [comment]
> So far it has happened only once but that one time was the first time I created a non-large world

@SiverDX, just to make sure: have you tried creating more normal worlds after this first error? Given the abundance of mods in your list, it could be that something is interfering during world gen. I haven't been able to replicate this error on a minimal instance, either.

The stacktrace mentions some other mods, but they don't seem like they would do anything to unbind or wrongly load a placed feature. Not sure what could cause it, but if it was a one-off error which can't be replicated, it could be sporadic.

**Comment by SiverDX** [comment]
Created some more worlds but it did not happen again, so it's kinda rare I guess
Since I removed / added mods in the mean time it's also possible that the issue cannot occur anymore

So this is more of a "this can happen for some reason at some point in time maybe" kind of thing
Probably not really worth investing much time into it

**Comment by vectorwing** [comment]
Ah, I see. 👍

I'll close the issue, then, at least until a similar error occurs again with reproducible steps. Thanks for the report, though! ^^
