### ISSUE TITLE
1.18.2 forge pigs dont eat onions?

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#737]
### Description

I feel like they should

### Steps to reproduce

obtain an onion
right click a pig with it

### Mod list

n/a

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
This is intentional.

Onions are actually harmful to pigs in real life. Feeding it to them frequently can cause a specific type of anemia in them.

**Comment by Aceplante** [comment]
Then perhaps do something similar to what cookies do to parrots?

**Comment by vectorwing** [comment]
I suppose that would be more educational than denying the action. There's probably some way to do it with Forge events; I'll think about it. 👍
