### ISSUE TITLE
[Suggestion] Add the storage_block tag to the food item crates

### ISSUE THREAD

**Issue by ffuentesm** [vectorwing/FarmersDelight#738]
The idea is to add the storage_block tag to the food crates as they are mechanically storage blocks.
This would help unify some duplicated recipes, such as the food crates from Thermal and Quark.

**Comment by Brokensweet** [comment]
How can you download this I have tried so many times

**Comment by ffuentesm** [comment]
> How can you download this I have tried so many times

What do you mean? Can you elaborate?

**Comment by vectorwing** [comment]
`storage_blocks` is a Forge tag, right? I see it also has sub-folders to it.

I'll take a look later at how Quark and Thermal Cultivation are handling it, just to make sure I dont mess it up. Sounds like a reasonable tag to use.
