### ISSUE TITLE
[MC Version]: 1.19.4

### ISSUE THREAD

**Issue by AceBurnn** [vectorwing/FarmersDelight#740]
### Description

When opening minecraft on 1.19.4 forge 45.1.2 it says that:
: Farmer's delight (farmersdelight) has failed to load correctly

net.minecraft.world.item.creativemodetab.<init>(java.lang.string)'

java.lang.nosuchmethoderror : Void
![logetc](https://github.com/vectorwing/FarmersDelight/assets/137231037/1f78e66e-c320-4fec-80b8-0a3b70115553)

(btw im creating an aternos server and its saying that farmer's delight is causing a fatal error)

### Mod list

![mods1](https://github.com/vectorwing/FarmersDelight/assets/137231037/ec430838-7818-4d85-91f2-c4e847bb8bb5)

### Logs

[crashlog.txt](https://github.com/vectorwing/FarmersDelight/files/11807996/crashlog.txt)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/11808001/latest.log)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Farmer's Delight is not available for 1.19.4; due to the Creative Tab changes, you can't use 1.2.1 on it.
A 1.20 port is ongoing, but I have no plans to port to 1.19.4. Sorry for the trouble. ^^
