### ISSUE TITLE
[MC Version]: 1.19.2

### ISSUE THREAD

**Issue by Jaitnium** [vectorwing/FarmersDelight#742]
### Description

Farmer's Delight overwrites Create's "Dough" with its "Wheat Dough". This makes Dough unobtainable, and all of its associated recipes uncraftable (eg. Dough + Lime Dye = Slime Balls).

### Steps to reproduce

1. Acquire 3 Wheat Flour, 1 Water Bucket, and a Lime Dye
2. Open your inventory and use the ingredients to craft "Wheat Dough"
3. Try to craft a Slime Ball with the Wheat Dough and Lime Dye.

### Mod list

[latest.log](https://github.com/vectorwing/FarmersDelight/files/11855870/latest.log)

### Forge

- [X] I am using the Forge version of Farmer's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I have tested this without performance or shader mods

**Comment by vectorwing** [comment]
Create's Dough has a different recipe than FD's, which uses the mod's Wheat Flour item:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/82efdf43-e015-4c7a-9fe6-3e55a790f256)

It can also be made by bulk-washing Wheat Flour.

I was able to craft both kinds of dough in an instance with both mods installed. Farmer's Delight consults the `forge:dough` tag for dough uses, which includes Create's dough item. The difference here is that Create's Slimeball recipe does not utilize the `forge:dough` tag, requiring specifically the usage of `create:dough`.

If the things above don't apply to your instance, you might be playing a modpack which modified those recipes.
