### ISSUE TITLE
[Suggestion/Integration idea] "Or" chance based processing when cutting or loot table processing.

### ISSUE THREAD

**Issue by Darkmega18** [vectorwing/FarmersDelight#749]
I'm currently fiddling with some recipes to do farmers delight styled breakdowns and stripping for bark for the other mods which add types of wood etc in my modpack in 1.19.2.
However I've come upon autumnity which has a log stripping logic where there seems to be around a third chance that the stripped log will become "sappy" rather than plain, the sap then being harvested by a bottle afterwards.

I could make a processing recipe, but it would mean it has to go one way or the other. Because I can't tell it to give me EITHER the sappy or nonsappy stripped log, only one or the other. and if I do a chance to do sappy and chance to do nonsappy together theres a chance I'll get none or both along with my bark. (also making the sap always pop out will make it somewhat op).

Is there a chance you can implement this kind of mechanic (or I just don't know it exists)? or even like, make something thats processed drop out a loot table or something? cause then I could just do up a loot table for it to spit out the log instead.

**Comment by thelegitdolt** [comment]
plz do this omg plz plz plz plz plz

**Comment by thelegitdolt** [comment]
plz

**Comment by Darkmega18** [comment]
Hahaha. thanks for your support, dolt. :)
