### ISSUE TITLE
[1.19.2]: Unable to join Plugin Server

### ISSUE THREAD

**Issue by Dr-WeiAL** [vectorwing/FarmersDelight#752]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.1

### Forge version

43.2.14

### Description

Error entering Plugin Server when using Farmer's Delight
The only thing I found in my modpack that causes this problem is Farmer's Delight

Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 12)

![image](https://github.com/vectorwing/FarmersDelight/assets/47446553/84d8eaeb-7562-4e78-9fdd-b085e58a2518)

### Steps to reproduce

1. Start the server with paper or purpur server core
2. Join the server using a client with Farmer's Delight
3. Unable to access the server

### Mod list

Farmer's Delight

### Logs

client: https://pastebin.com/iusjx76a
server: https://pastebin.com/j7JJa3QD

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Farmer's Delight is a **client + server** mod; both sides must have it installed.

From a quick lookup, it seems PaperMC is incompatible with Forge, so what you're trying here won't work. In order to run a modded server, you'll need to install Forge on it, as well as any client+server mods.

**Comment by Dr-WeiAL** [comment]
Uh, no, I have many client + server mods in my modpack, only Farmer's Delight has this problem, I connect to Paper or Purpur just to use BungeeCord, but with Farmer's Delight installed I can't join the Lobby server!
