### ISSUE TITLE
Incompatibility with create:broken bad

### ISSUE THREAD

**Issue by Speedybluegames** [vectorwing/FarmersDelight#753]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.1

### Forge version

43.2.14

### Description

kelp and rice become unplantable when both mods are installed

### Mod list

I already fixed i by removing C:BB so i can't get the actual mod list srry

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Did a quick local test, and it seems this bug is caused exclusively by Create: Broken Bad, regardless of whether Farmer's Delight is installed or not. It seems to be preventing placement of things underwater, and/or through fluids.

Please forward this issue to the addon's repository instead. 👍
