### ISSUE TITLE
Loot Table Crash

### ISSUE THREAD

**Issue by Peach774** [vectorwing/FarmersDelight#762]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2

### Forge version

47.1.1

### Description

I opened a loot chest near a nether portal ruin and my game crashed

### Steps to reproduce

1. Find a loot chest that will have a farmer's delight item in it or can have one in it.
2. Try and open it
3. Crash

### Mod list

Included in crash report

### Logs

[crash-2023-07-11_21.56.02-server.txt](https://github.com/vectorwing/FarmersDelight/files/12023885/crash-2023-07-11_21.56.02-server.txt)
[debug.log](https://github.com/vectorwing/FarmersDelight/files/12023890/debug.log)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/12023892/latest.log)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
That was fast...

It seems that I misunderstood the 1.20 changes to Forge's Loot Modifiers. It's calling itself repeatedly. I'll take a look at it.

**Comment by vectorwing** [comment]
Fixed on hotfix 1.2.2a, should be out in a few minutes. Please update when it becomes available. 👍
