### ISSUE TITLE
1.20.1  crashing game

### ISSUE THREAD

**Issue by annam12345** [vectorwing/FarmersDelight#768]
I left a comment on cuseforge about the updated version of this mod crashing my game. You asked for the game log and I feel like a bit of a noob here but I can't find any crash report for it because the game isn't opening enough to fully crash (hope that makes sense), but I did find this log that I think has the error in it. https://pastebin.com/gb3RXFp2 
I think it's saying I have the wrong version of forge but I've added a screenshot to show I have
 the correct version. I'm so stumped haha 
![Screen Shot 2023-07-13 at 5 27 29 pm](https://github.com/vectorwing/FarmersDelight/assets/93758345/9a0abc66-81ba-4f8a-adc1-83e979c147f1)

**Comment by vectorwing** [comment]
Hey there! ^^

Yeah, it seems like your instance got confused over which Forge version you have. The launcher button claims it's on 47.1.0, but the log reports it's on 46.0.14 instead. There's a chance the instance was renamed, but is still on 1.20 with 46.0.14 installed.

Try running the 47.1.0 executable again, and if there is an option, select "Repair". If it doesn't work, try removing and creating a new instance.

**Comment by Jowonny** [comment]
I've been having this issue also using Forge-47.0.45 with version 1.2.2a - 1.20+ and version 1.2.2 - 1.20+
Attached is the crash log of the 1.2.2a version:
https://gist.github.com/Jowonny/7191391eeba0454db2b4e3f5e367b5a3

Great mod btw vector, me and my friends really like it :)

**Comment by annam12345** [comment]
Thank you for responding @vectorwing 

I'm not actually sure how to run the executable or create a new instance, I'm still fairly new to modding haha. How would I go about doing this? 

I've tried everything I can think of, removing the old forge installation (46.0.14 and 47.1.0) and completely installing a new 47.1.0 version but it still won't open with this mod. I don't think it's just the forge because every other 1.20.1 mod I have is working perfectly fine.

**Comment by vectorwing** [comment]
> I've been having this issue also using Forge-47.0.45 with version 1.2.2a - 1.20+ and version 1.2.2 - 1.20+ Attached is the crash log of the 1.2.2a version: https://gist.github.com/Jowonny/7191391eeba0454db2b4e3f5e367b5a3
> 
> Great mod btw vector, me and my friends really like it :)

Thanks! FD requires 47.1.0 at minimum, so 47.0.45 won't work. The crash seems related to Iris, rather than FD, so I recommend either updating or disabling it to troubleshoot.

**Comment by vectorwing** [comment]
> Thank you for responding @vectorwing
> 
> I'm not actually sure how to run the executable or create a new instance, I'm still fairly new to modding haha. How would I go about doing this?
> 
> I've tried everything I can think of, removing the old forge installation (46.0.14 and 47.1.0) and completely installing a new 47.1.0 version but it still won't open with this mod. I don't think it's just the forge because every other 1.20.1 mod I have is working perfectly fine.

@annam12345, from your paragraph, I assume those are the steps you tried:

1. Uninstall the previous Forge instance;
2. Run the installer for 47.1.0;
3. Add mods, FD included, then run.

If you did this and it still didn't run, please share that session's logs here so I can take a look.

**Comment by annam12345** [comment]
@vectorwing Yeah those are the steps I did and I just did them all again to see if it worked this time and the game still won't open. Not sure which log has the information you need so I've got 2 for you to look at. 

https://pastebin.com/raYuNfXT 
https://pastebin.com/pngvvvZF

Thanks for looking at this again

**Comment by vectorwing** [comment]
Hello, @annam12345! I'm sorry for the long delay with this reply. This got lost between my breaks and other issues. 😓
Are you still facing this issue, or has it been resolved in your latest instances?

**Comment by vectorwing** [comment]
I'm closing this issue, as it's gotten stale.
