### ISSUE TITLE
Opening loot chests crashes the game

### ISSUE THREAD

**Issue by Mrnar1s** [vectorwing/FarmersDelight#774]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2a

### Forge version

47.1.4

### Description

opening or breaking a loot chest from a ruined portal or an end city crashes the game, loot chests from a nether fortress work normally, i haven't tried any other loot chests.

### Steps to reproduce

1. find ruined portal in the overworld
2. open or break the loot chest on the ruined portal
3. game crashes

### Mod list

client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1
FarmersDelight-1.20.1-1.2.2.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.2 
forge-1.20.1-47.1.4-universal.jar                 |Forge                         |forge                         |47.1.4 

### Logs

https://pastebin.com/x4YasaEQ

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Duplicate issue. Please update to 1.2.2a to fix it; according to your logs, you haven't actually updated to it yet.

**Comment by Mrnar1s** [comment]
you're right, i was sure i downloaded the most current version but ig i didnt
