### ISSUE TITLE
1.2.2 version not working on 1.20

### ISSUE THREAD

**Issue by andreinightfall** [vectorwing/FarmersDelight#775]
### Minecraft version

1.20

### Farmer's Delight version

1.2.2

### Forge version

46.0.14

### Description

Game crashes when trying to start forge 1.20 (fml 46.0.14). It says the mod requires forge version 47.1.0 at least but that's not for 1.20, that's for 1.20.1 since the latest 1.20 forge version is the one I'm currently using. Will there be any fix for that? or the mod remains on 1.20.1 only? Also, great job on this project, vectorwing!

### Mod list

BiomesOPlenty-1.20-18.0.0.559
CraftTweaker-forge-1.20-13.0.4
FarmersDelight-1.20.1-1.2.2
TerraBlender-forge-1.20-3.0.0.163

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Yes, FD is for 1.20.1 only, due to it fixing Forge bugs which affected the mod.
You should be able to play any 1.20 mod in 1.20.1, as well, so it's worth the update. 👍

**Comment by vectorwing** [comment]
I now realize I wrongly marked it as compatible on Curseforge. Fixed, sorry! 😅
