### ISSUE TITLE
Missing Forge tags - Error tag

### ISSUE THREAD

**Issue by camoscout** [vectorwing/FarmersDelight#777]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.2

### Forge version

43.2.11

### Description

I made a custom modpack for my friends and I to play on a server together, and I have added a lot of different mods. I liked Farmers delight, so I added it. I also added a lot of "food" like mods together. My friend noticed that we cant craft majority of recipes that use the 'forge:milk' tag. For almost every farmers delight crafting (and most addons) it says is _"Empty Tag Forge:milk"_ I did some research, and it could be a JEI error, or another mod is messing with it. I have no idea what anything is, and I was told to post this here.

I primarily want to know which mod to remove to resolve this issue, secondly if someone is able to help me or to fix this issue.
The latter is preferred.

### Steps to reproduce

cant craft most things with either the milk bucket or the bottled milk. I remember seeing a few errors with mushrooms.

Cant craft the pie curst as an example

### Mod list

3dskinlayers-forge-1.5.2-mc1.19.1.jar.client	
[1.19.2-forge]-Epic-Knights-8.1.jar	
ActuallyUsefulSmithingTable-4.1.0.jar	
adaptive_performance_tweaks_core_1.19.2-6.9.1.jar	
adaptive_performance_tweaks_mods_1.19.2-6.5.2.jar	
additional_lights-1.19-2.1.6.jar	
additionaladditions-5.1.0.jar	
AdditionalBanners-Forge-1.19.2-10.1.7.jar	
AdditionalEnchantedMiner-1.19.2-1192.2.0.jar	
additionalweapon-2.0.0-1.19.2.jar	
AdvancedCompas-forge-1.19.2-1.2.14.jar	
AdvancementPlaques-1.19.2-1.4.7.jar	
AE2WTLib-12.9.5.jar	
AI-Improvements-1.19.2-0.5.2.jar	
Alexs Armoury v1.4.1-1.19.2.jar	
alexsdelight-1.4.1.jar	
alexsmobs-1.21.1.jar	
Amplified_Nether_1.19.3_v1.2.1.jar	
antighost-1.19.1-forge42.0.1-1.1.3.jar.client	
appleskin-forge-mc1.19-2.4.2.jar	
Applied-Mekanistics-1.3.4.jar	
appliedenergistics2-forge-12.9.5.jar	
aquatictorches-1.19-1.1.0.jar	
architectury-6.5.85-forge.jar	
AttributeFix-Forge-1.19.2-17.2.7.jar	
automobility-0.4.2+1.19.2-forge.jar	
AutoRegLib-1.8.2-55.jar	
balm-forge-1.19.2-4.5.7.jar	
bedspreads-forge-6.0.0+1.19.2.jar	
Better Fishing Rods 1.0.0 - 1.19.2.jar	
BetterAdvancements-1.19.2-0.2.2.142.jar.client	
BetterAnimationsCollection-v4.0.5-1.19.2-Forge.jar.client	
bettercombat-forge-1.7.1+1.19.jar	
BetterF3-4.0.0-Forge-1.19.2.jar.client	
betterstats-2.2.2+1.19.2.jar.client	
BetterThanMending-1.7.2.jar	
BetterThirdPerson-Forge-1.19-1.9.0.jar.client	
bettervillage-forge-1.19.2-3.1.0.jar	
blueprint-1.19.2-6.1.2.jar	
Boat-Item-View-Forge-1.19.x-0.0.4.jar	
boatload-1.19.2-4.2.1.jar	
Bookshelf-Forge-1.19.2-16.3.20.jar	
Botania-1.19.2-440-FORGE.jar	
BuriedWrecks-1.19.2-2.0.0.jar	
capes-1.5.2+1.19.2-forge.jar	
carryon-forge-1.19.2-2.0.5.17.jar	
cfm-7.0.0-pre35-1.19.2.jar	
cgm-1.3.4-1.19.2.jar	
chalk-1.19.2-1.6.0.jar	
chat_heads-0.10.16-forge-1.19.2.jar.client	
ChickenChunks-1.19.2-2.9.4.97-universal.jar	
Chimes-v2.0.0-1.19.2.jar
chisels-and-bits-forge-1.3.135.jar	
Chunk Pregenerator-1.19-4.3.0.jar
chunksending-forge-1.19-2.5.jar	
Chunky-1.3.38.jar	
citadel-2.1.4-1.19.jar	
clickadv-1.19.2-3.0.jar	
clienttweaks-forge-1.19.2-8.1.2.jar.client	
cloth-config-8.3.103-forge.jar	
Clumps-forge-1.19.2-9.0.0+14.jar	
CodeChickenLib-1.19.2-4.3.1.481-universal.jar	
cofh_core-1.19.2-10.2.1.40.jar	
collective-1.19.2-6.65.jar	JAR File	
collectorsreap-1.19-1.2.3.jar	
comforts-forge-6.0.5+1.19.2.jar	
configured-2.1.1-1.19.2.jar	
Controlling-forge-1.19.2-10.0+7.jar.client	
convenientcurioscontainer-1.12-1.19.2.jar	
corpse-1.19.2-1.0.0.jar	
crafting-on-a-stick-1.19.2-1.0.5.jar	
craftingtweaks-forge-1.19.2-15.1.7.jar	
CraftTweaker-forge-1.19.2-10.1.46.jar	
Create Train Additions 0.3.0-1.19.2.jar	
create-1.19.2-0.5.1.b.jar	
create-confectionery1.19.2_v1.0.9.jar	
create-stuff-additions1.19.2_v2.0.3b.jar	
create_central_kitchen-1.19.2-for-create-0.5.1.b-1.3.8.jar	
create_enchantment_industry-1.19.2-for-create-0.5.1.b-1.2.5.jar	
create_misc_and_things_ 1.19.2_3.0.jar	
createaddition-1.19.2-20230623a.jar	
createdeco-1.3.3-1.19.2.jar	
CreateTweaker-1.19.2-3.0.0.6.jar	
CullLessLeaves-Reforged-1.0.5.jar	
curios-forge-1.19.2-5.1.4.1.jar	
deeperdarker-forge-1.1.6-forge.jar
DefaultSettings-1.19.2-4.0.5-Forge.jar	
Delightful-1.19.2-3.3.jar	
DiagonalFences-v4.2.5-1.19.2-Forge.jar	
domesticationinnovation-1.6.1-1.19.2.jar	
dummmmmmy-1.19.2-1.7.1.jar	
durabilitytooltip-1.1.4-forge-mc1.19.jar	
DustrialDecor-1.3.3-1.19.2.jar
EasyAnvils-v4.0.11-1.19.2-Forge.jar	
EasyMagic-v4.3.3-1.19.2-Forge.jar	
eatinganimation-1.19-3.2.0.jar.client	
ecologics-forge-1.19.2-2.1.11.jar
EdivadLib-1.19.2-1.2.0.jar
effective_fg-1.3.4.jar	
EnchantingInfuser-v4.2.2-1.19.2-Forge.jar	
EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar.client	
EnchantWithMob-1.19.2-7.8.2.jar	
EnderStorage-1.19.2-2.10.1.181-universal.jar	
endsdelight-1.19.2-1.2.jar	
Engineers Delight 1.19.2 B.1.1.jar
engineersdecor-1.19.2-forge-1.3.28.jar	
Entity_Collision_FPS_Fix-forge-1.19-2.0.0.0.jar	
entity_texture_features_forge_1.19.2-4.4.4.jar.client	
entityculling-forge-1.6.1-mc1.19.2.jar.client	
epicsamurai-0.0.14-1.19.2-forge.jar	
ExperienceBugFix-1.19-1.41.2.3.jar	
ExplorersCompass-1.19.2-1.3.0-forge.jar	
ExtremeReactors2-1.19.2-2.0.64.jar	
FarmersDelight-1.19.2-1.2.2.jar	
FarmersRespite-1.19-2.0.jar	
farsight-1.19.2-2.1.jar.client	
FastLeafDecay-30.jar	
Fastload-Reforged-8.2.1+1.19.2.jar	
FastWorkbench-1.19.2-7.1.4.jar	
Female-Gender-Mod-forge-1.19.1-3.0.1.jar	
fireproofboats-1.19.2-1.0.0.jar	
FluxNetworks-1.19.2-7.1.4.13.jar	
flywheel-forge-1.19.2-0.6.8.a.jar	
forgetmechunk-(forge)-mc1.19.2-0.0.1.jar	
FpsReducer2-forge-1.19.2-2.1.jar.client	
FramedBlocks-6.8.4.jar	
framework-0.4.2-1.19.2.jar	
FriendlyFire-Forge-1.19.2-14.0.4.jar
friendsandfoes-beekeeperhut-forge-mc1.19.2-1.2.0.jar	
friendsandfoes-forge-mc1.19.2-1.8.5.jar	
frozen_delight_1.3.2_forge_1.19.2.jar	
FruitTrees-1.19.2-forge-6.3.0.jar	
ftb-essentials-1902.1.10-build.47.jar	
ftb-library-forge-1902.4.0-build.232.jar	
fuelgoeshere-1.19.2-0.1.0.0.jar	
GameMenuModOption-1.19-1.18.jar.client	
geckolib-forge-1.19-3.1.40.jar	
getittogetherdrops-forge-1.19.2-1.3.jar	
guardvillagers-1.19.2-1.5.6.jar	
HammerLib-1.19.2-19.3.57.jar	
hiddenrecipebook-1.19.2-4.0.jar.client	
Highlighter-1.19.1-1.1.4.jar.client
Iceberg-1.19.2-forge-1.1.4.jar	
idas_forge-1.7.6+1.19.2.jar	
IKnowWhatImDoing-5.1.1-forge.jar.client	
illuminations-forge-1.19.2-1.10.9.20.jar	
immersive_aircraft-0.5.1+1.19.2-forge.jar	
immersive_weathering-1.19.2-1.2.9-forge.jar	
ImmersiveEngineering-1.19.2-9.2.2-165.jar	
industrial-foregoing-1.19.2-3.3.2.3-5.jar	
infusedfoods-1.19.2-7.2.0.jar	
integrated_api_forge-1.2.7+1.19.2.jar	
invhud.forge.1.19-3.4.7.jar.client	
ItalianDelight-1.19.2 1.5-MAR_FIX.jar	
ItShallNotTick-1.0.11-build.35.jar	
Jade-1.19.1-forge-8.8.1.jar	
JadeAddons-1.19.2-forge-3.5.0.jar	
jamd-forge-2.0.5-build.12+mc1.19.2.jar	
javd-forge-4.0.1-build.2+mc1.19.2.jar	
JCPlugin-1.17.x-1.20.x-4.0.4-Forge.jar	
jecalculation-forge-1.19.2-4.0.2.jar	
jeed-1.19.2-2.1.4.jar	
jei-1.19.2-forge-11.6.0.1016.jar	
jeimultiblocks-1.19.2-0.0.3.jar	
JRFTL [1.19.1]-1.4.3.jar	
jumbofurnace-1.19.2-3.0.0.0.jar	
JustARaftMod-1.19-2.0.0.jar	
JustEnoughProfessions-forge-1.19.2-2.0.2.jar	
JustEnoughResources-1.19.2-1.2.2.200.jar	
keebszs_battle_towers-0.5.0-1.19.x.jar	
Kiwi-1.19.1-forge-8.3.4.jar	
kotlinforforge-3.12.0-all.jar	
layered_snowfall-1.0.0 - 1.18.2.jar
LeaveMyBarsAlone-v4.0.0-1.19.2-Forge.jar	
libraryferret-forge-1.19.2-4.0.0.jar	
LibX-1.19.2-4.2.8.jar	
limitedchunks-1.19.2-2.4.jar	
lootr-1.19-0.4.24.62.jar
lostcities-1.19-6.0.17.jar	
MagnumTorch-v4.2.2-1.19.2-Forge.jar
mahoutsukai-1.19.2-v1.34.52.jar	
MaxHealthFix-Forge-1.19.2-8.0.1.jar	
mcjtylib-1.19-7.2.5.jar	
Mekanism-1.19.2-10.3.9.13.jar	
MekanismAdditions-1.19.2-10.3.9.13.jar	
MekanismGenerators-1.19.2-10.3.9.13.jar	
MekanismTools-1.19.2-10.3.9.13.jar
memoryleakfix-forge-1.17+-1.0.0.jar	
merequester-1.19.2-1.1.2.jar	
miners_delight-1.19.2-1.1.1.jar	
mining_dimension-1.19.2-1.0.0.jar	
modelfix-1.8.jar	
modnametooltip-1.19-1.19.0.jar.client	
moonlight-1.19.2-2.2.43-forge.jar	
MoreMekanismProcessing-1.19.2-3.0.jar	
moreminecarts-1.5.7.jar	
moreoverlays-1.21.9-mc1.19.2.jar.client	
morevillagers-forge-1.19-4.0.3.jar	
MouseTweaks-forge-mc1.19-2.23.jar.client	
Mushroom_Villagers1.19.2.jar	
mvs-3.2-1.19.2.jar	
NaturesCompass-1.19.2-1.10.0-forge.jar	
NekosEnchantedBooks-1.19-1.8.0.jar.client	
NethersDelight-1.19-3.0.jar	
no_nv_flash-1.19.2-1.5.0.3.jar	
nocube's_better_blast_furnace_1.0.0_Forge_1.19.2.jar	
notenoughanimations-forge-1.6.2-mc1.19.2.jar.client	
notenoughwands-1.19-5.0.2.jar	
Notes-1.19.2-1.2.5.jar.client	
nounusedchunks-1.3.jar
Nullscape_1.19.3_v1.2.1a.jar	
NyfsQuiver-1.19.2-0.7.4.jar	
nzgExpansion-1.2.2-1.19.2.jar	
obsidianequipment-forge-1.19.2-v1.0.5.jar	
oculus-flywheel-compat-1.19.2-0.2.1.jar	
oculus-mc1.19.2-1.6.4.jar.client	
paladin-furniture-mod-1.1.1-forge-mc1.19.jar	
Patchouli-1.19.2-77.jar	
Placebo-1.19.2-7.3.0.jar
player-animation-lib-forge-1.0.2.jar
postalpigeons-1.2.0.jar
Powah-4.0.10.jar	
ProjectE-1.19.2-PE1.0.1B.jar	
ProjectExpansion-1.19.2-1.0.8.jar	
PuzzlesLib-v4.4.3-1.19.2-Forge.jar	
Quark-3.4-405.jar	
QuarkOddities-1.18.jar	
reap-1.19.2-1.0.0.jar	
reds-more-structures-1.0.7-common.jar	
revampedwolf-1.19.2-4.0.0.jar	
Rex's-AdditionalStructures-1.19.x-(v.4.0.3).jar	
rftoolsbase-1.19-4.1.7.jar	JAR File	
rftoolsbuilder-1.19-5.2.8.jar	
rftoolscontrol-1.19-6.1.4.jar	
rftoolsdim-1.19.2-9.1.7.jar	
rftoolspower-1.19-5.1.2.jar	
rftoolsstorage-1.19-4.1.2.jar	
rftoolsutility-1.19-5.1.7.jar	
riverredux-0.3.0+forge.jar	
rubidium-0.6.2b.jar.client	
rubidium_extras-1.19.2_v1.4.3.jar	
savage_and_ravage-1.19.2-5.0.4.jar	
ScalableCatsForce-2.13.10-build-10-with-library.jar	
SelectablePainting-1.19.2-2.0.3.jar	
SereneSeasons-1.19.2-8.1.0.24.jar	
ShieldExpansion-1.19.2-1.1.6.jar
shulkerboxtooltip-forge-3.2.2+1.19.2.jar
shutupexperimentalsettings-1.0.5.jar.client
simpleplanes-1.19.2-5.2.2.jar	
SimpleStorageNetwork-1.19.2-1.7.0.jar	
sit-1.19-1.3.3.jar	
sliceanddice-forge-2.2.0.jar	
smallships-forge-1.19.2-2.0.0-a2.3.jar
smoothchunk-1.19.1-2.0.jar	
snowundertrees-1.19.2-1.3.1.jar	
SolarFluxReborn-1.19.2-19.3.10.jar	
SolarGeneration-1.19.2-5.2.1.jar	
sophisticatedbackpacks-1.19.2-3.18.55.889.jar	
sophisticatedcore-1.19.2-0.5.81.377.jar	
sophisticatedstorage-1.19.2-0.8.38.555.jar	
stackrefill-1.19.2-4.0.jar	
starlight-1.1.1+forge.cf5b10b.jar	
Steam_Rails-1.4.3+forge-mc1.19.2.jar	
StrawStatues-v4.0.10-1.19.2-Forge.jar	
supermartijn642configlib-1.1.7-forge-mc1.19.jar	
supermartijn642corelib-1.1.10-forge-mc1.19.2.jar	
supplementaries-1.19.2-2.3.20.jar	
TerraBlender-forge-1.19.2-2.0.1.136.jar	
Terralith_1.19.3_v2.3.8.jar	
TextruesRubidiumOptions-1.0.5-mc1.19.2.jar.client	
thermal_dynamics-1.19.2-10.2.1b.14.jar	
thermal_expansion-1.19.2-10.2.0.21.jar	
thermal_foundation-1.19.2-10.2.0.47.jar	
thermal_innovation-1.19.2-10.2.0.18.jar	
thermal_integration-1.19.2-10.2.0.17.jar	
thermal_locomotion-1.19.2-10.2.0.14.jar	
ThisRocks-1.19.2-1.2.4.jar	
titanium-1.19.2-3.7.3-27.jar	
toms_storage-1.19-1.5.8.jar	
ToolBelt-1.19.2-1.19.7.jar	JAR File	
TradingPost-v4.2.0-1.19.2-Forge.jar	
twilightforest-1.19.2-4.2.1518-universal.jar	
upgrade_aquatic-1.19.2-5.0.0.jar	
usefulspyglass-forge-1.19.2-0.3.0.jar	
veinmining-forge-1.1.1+1.19.2.jar	
VisualWorkbench-v4.2.4-1.19.2-Forge.jar	
voicechat-forge-1.19.2-2.4.13.jar	
waveycapes-forge-1.3.2-mc1.19.2.jar.client	
waystones-forge-1.19.2-11.4.1.jar
WWOO-FORGE-3.1.9+1.19.x.jar
Xaeros_Minimap_23.5.0_Forge_1.19.1.jar	
XaerosWorldMap_1.30.6_Forge_1.19.1.jar	
xercapaint-1.19.2-1.0.1.jar	
xptome-1.19-2.1.7.jar
YungsApi-1.19.2-Forge-3.8.9.jar	
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar	
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar	
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar	
YungsBetterNetherFortresses-1.19.2-Forge-1.0.5.jar	
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar	
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar	
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar	
YungsBridges-1.19.2-Forge-3.1.0.jar	
YungsExtras-1.19.2-Forge-3.1.0.jar	
ZeroCore2-1.19.2-2.1.35.jar

### Logs

I just used the lastest log

https://mclo.gs/PW89wlp

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by camoscout** [comment]
Update! I found the problem, a support agent from Apex hosting helped me. Forzen Delight is causing the tag error. I am going to message the creator or make a post on the github if it exists.

**Comment by vectorwing** [comment]
Sorry for the delay! 😅

Yeah, the logs have many errors related to Frozen Delight. At first it didn't seem like they were affecting the milk tags, but it seems that was the cause in the end. Good to know you resolved it! 👍

**Comment by camoscout** [comment]
Yeah I did post a comment on the frozen delight mod on curse forge. hopefully it gets fixed. He has a lot of other add on mods.
