### ISSUE TITLE
Infinite Restart after install on Nitrado Server

### ISSUE THREAD

**Issue by JaySogga** [vectorwing/FarmersDelight#778]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2a - 1.20.1

### Forge version

47.0.35

### Description

When adding this mod to my servers mod folder, the server refuses to remain in the active status.  I'm not knowledgeable enough to know if there is an issue regarding Nitrado, and a support ticket has been sent.  The issue stops once i remove the mod from the mod folder and restart the server.  Has anyone else had this issue?

### Steps to reproduce

1. Added the singular mod to my desktop's downloads folder
2. Uploaded said mod file to the "mods" folder of the server
3. Saved and restarted server.
4. Server starts, then stops, then starts (refuses to show up in server lists in game, despite launching through forge with the same mods installed on my end)

### Mod list

Create (newest version 1.20.1)
Farmer's Delight (newest version 1.20.1)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Please post your server logs here, so I can take a look on any potential error messages.

Also, FD 1.2.2 requires Forge 47.1.0; there's a chance the server is rejecting it because of that.

**Comment by JaySogga** [comment]
> Please post your server logs here, so I can take a look on any potential error messages.
> 
> Also, FD 1.2.2 requires Forge 47.1.0; there's a chance the server is rejecting it because of that.

**Begin Logs**
Tue 18 Jul 2023 11:05:23 AM UTC mcrotherpacks Server restart via Restart-file or Webinterface requested
Tue 18 Jul 2023 11:05:42 AM UTC - Changed char § to \u00A7 in file server.properties
2023-07-18 17:14:48 Creating a backup ...
2023-07-18 17:15:29 Server restart requested (NITRAPI)
Tue 18 Jul 2023 05:15:37 PM UTC mcrotherpacks Server restart via Restart-file or Webinterface requested
Tue 18 Jul 2023 05:15:54 PM UTC - Changed char § to \u00A7 in file server.properties
2023-07-18 17:18:17 Server stop requested (Webinterface)
2023-07-18 17:18:54 Server restart requested (Webinterface)
Tue 18 Jul 2023 05:19:01 PM UTC mcrotherpacks Server restart via Restart-file or Webinterface requested
2023-07-18 17:21:18 Server restart requested (Webinterface)
Tue 18 Jul 2023 05:21:24 PM UTC mcrotherpacks Server restart via Restart-file or Webinterface requested
Tue 18 Jul 2023 05:21:42 PM UTC - Changed char § to \u00A7 in file server.properties

**Comment by vectorwing** [comment]
Sorry, those are the wrong logs. You can find your `latest.log` inside the `logs` folder of your server instance.

**Comment by JaySogga** [comment]
[latest.log](https://github.com/vectorwing/FarmersDelight/files/12096446/latest.log)

**Comment by vectorwing** [comment]
Given that FD 1.2.2+ won't boot if Forge is under version 47.1.0, your server may be failing to boot because of it. Then, after it fails, it attempts to restart itself repeatedly, thus wiping latest.log.

Please update:
- Forge to at least 47.1.0;
- Farmer's Delight to 1.2.3.

Feel free to reopen if this doesn't fix the issue. 👍
