### ISSUE TITLE
unable to obtain tree bark

### ISSUE THREAD

**Issue by quasarjar** [vectorwing/FarmersDelight#779]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2

### Forge version

0.229.3.11469

### Description

unable to obtain tree bark when right clicking with axe, only strips log

### Steps to reproduce

1. find or place log
2. right click with axe

### Mod list

farmers delight, biomes o plenty, cooking for blockheads, origins

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Tree Bark is obtained by cutting logs in a **Cutting Board**, not within the world. Like so:

![image](https://github.com/vectorwing/FarmersDelight/assets/5566692/ceae1ea3-2589-413e-a884-88850af130cf)

This was done to not spam non-FD players with Tree Bark when decorating their builds.

**Comment by quasarjar** [comment]
omg my bad thank you so much tho
