### ISSUE TITLE
1.20.1 Crashing With A Mixin Error

### ISSUE THREAD

**Issue by Ax3dGaming** [vectorwing/FarmersDelight#782]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2a

### Forge version

47.1.0

### Description

I'm making a farmer's delight addon, and when I try to boot up my game, I have a crash which says:
Mixin apply failed farmersdelight.mixins.json:KeepRichSoilGiantTreeMixin

### Mod list

My mod, farmer's delight

### Logs

https://pastebin.com/a5GP2SRV

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
I'll admit to not being very familiar with setting up an add-on environment and dependencies 😅, but another user was assisted for a similar issue in our Discord before.

Please try following Step 1 of this guide, and then regenerate IntelliJ or Eclipse runs, depending on your IDE:
https://github.com/SpongePowered/Mixin/wiki/Mixins-on-Minecraft-Forge#step-1---adding-the-mixingradle-plugin

**Comment by Ax3dGaming** [comment]
It works now thanks you for your reply !
