### ISSUE TITLE
[1.19.2] Cannot craft shepard's pie

### ISSUE THREAD

**Issue by BobidaHombre** [vectorwing/FarmersDelight#784]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.1

### Forge version

43.2.0

### Description

	Cannot craft shepar's pie. I do everything exactly as in wikis or YouTube tutorial and it's not working

### Steps to reproduce

![image](https://github.com/vectorwing/FarmersDelight/assets/63858995/591797e7-e046-4946-93c0-18d337e2fa0c)

### Mod list

client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.1.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.1          |DONE      |Manifest: NOSIGNATURE
		frozen_delight_1.3.2_forge_1.19.2.jar             |Frozen Delight (by NoCube)    |frozen_delight                |1.3.2               |DONE      |Manifest: NOSIGNATURE
		elytraslot-forge-6.1.1+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.1.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.19.2-2.0.6.jar                |Handcrafted                   |handcrafted                   |2.0.6               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		galosphere_delight_1.1.0_forge_1.19.2.jar         |Galosphere Delight (by NoCube)|galosphere_delight            |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		resourcefullib-forge-1.19.2-1.1.24.jar            |Resourceful Lib               |resourcefullib                |1.1.24              |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |DONE      |Manifest: NOSIGNATURE
		ItalianDelight-1.19.2+1.5-MAR_FIX.jar             |Italian Delight               |italian_delight               |1.2                 |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.3+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.3+1.19.2       |DONE      |Manifest: NOSIGNATURE
		charmofundying-forge-6.2.0+1.19.2.jar             |Charm of Undying              |charmofundying                |6.2.0+1.19.2        |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.0.jar                     |FallingTree                   |fallingtree                   |3.10.0              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |DONE      |Manifest: NOSIGNATURE
		Gobber_Delight_1.1.1_Forge_1.19.2.jar             |Gobber Delight (by NoCube)    |gobberdelight                 |1.1.1               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.5.0_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.5.0              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.19.2-11.4.0.jar                 |Waystones                     |waystones                     |11.4.0              |DONE      |Manifest: NOSIGNATURE
		veinmining-forge-1.1.1+1.19.2.jar                 |Vein Mining                   |veinmining                    |1.1.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-6.61.jar                        |Collective                    |collective                    |6.61                |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.30.6_Forge_1.19.1.jar            |Xaero's World Map             |xaeroworldmap                 |1.30.6              |DONE      |Manifest: NOSIGNATURE

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This is caused by **Frozen Delight**. You forgot to install the mod [Frozen Up!](https://legacy.curseforge.com/minecraft/mc-mods/frozen-up), which Frozen Delight is also an add-on for, so it fails to load several ID's, breaking tags in the process.

Frozen Delight *should* be specifying Frozen Up! as a hard-dependency, though, so this is a bug on the add-on's side. I suggest reporting this to the creator.
