### ISSUE TITLE
Farmer's Delight crashes Minecraft with error code 255

### ISSUE THREAD

**Issue by kedamono** [vectorwing/FarmersDelight#786]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.2

### Forge version

43.2.14

### Description

After installing Farmer's Delight 1.2.2, when I try to launch Minecraft, the game crashes with error code 255.  I've tried an instance of Minecraft with nothing but Farmer's Delight and several of the Delight add-on mods and get the same results.

### Steps to reproduce

1. Install Farmer's Delight 1.2.2 using CurseForge.
2. Click Play to load profile in the Minecraft Launcher.
3. Click Play in the Launcher to start a game session.

Result: Game tries to start, but crashes with error code 255.

### Mod list

TreeChop-1.19.2-forge-0.17.8a.jar                 |HT's TreeChop                 |treechop                      |0.17.8a             |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.7-forge-mc1.19.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.7               |COMMON_SET|Manifest: NOSIGNATURE
		ColourfulLlamas-1.19.2-1.6.jar                    |Colourful Llamas              |colourfulllamas               |1.19.2-1.6          |COMMON_SET|Manifest: NOSIGNATURE
		deepslatecutting-forge-1.5.0.jar                  |DeepslateCutting              |deepslatecutting_forge        |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		naturalist-forge-3.0.4-1.19.2.jar                 |Naturalist                    |naturalist                    |3.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.82.382.jar           |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.82.382   |COMMON_SET|Manifest: NOSIGNATURE
		kleeslabs-forge-1.19.2-12.3.0.jar                 |KleeSlabs                     |kleeslabs                     |12.3.0              |COMMON_SET|Manifest: NOSIGNATURE
		hourglass-1.19.1-1.2.1.1.jar                      |Hourglass                     |hourglass                     |1.19.1-1.2.1.1      |COMMON_SET|Manifest: NOSIGNATURE
		Neat-1.19-32.jar                                  |Neat                          |neat                          |1.19-32             |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.19.2-10.0.6.1-build.0897.jar     |ForgeEndertech                |forgeendertech                |10.0.6.1            |COMMON_SET|Manifest: NOSIGNATURE
		golemsarefriends-1.19.2-0.1.0.1.jar               |Golems Are Friends Not Fodder |golemsarefriends              |1.19.2-0.1.0.1      |COMMON_SET|Manifest: NOSIGNATURE
		ResourcefulTools-Forge-1.19.2-1.5.11.jar          |Resourceful Tools             |resourceful_tools             |1.5.11              |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.19.2-13.3.2.jar      |CookingForBlockheads          |cookingforblockheads          |13.3.2              |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |COMMON_SET|Manifest: NOSIGNATURE
		lootintegrations-1.19.2-3.1.jar                   |Lootintegrations mod          |lootintegrations              |1.19.2-3.1          |COMMON_SET|Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.9.jar                   |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.9  |COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.6.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.6        |COMMON_SET|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.18.55.889.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.18.55.889  |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19.2-1.5.6.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.6        |COMMON_SET|Manifest: NOSIGNATURE
		Rex's-AdditionalStructures-1.19.x-(v.4.0.3).jar   |Additional Structures         |additionalstructures          |4.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.5.7.jar                       |Balm                          |balm                          |4.5.7               |COMMON_SET|Manifest: NOSIGNATURE
		dynview-1.19.1-2.9.jar                            |Dynamic view distance         |dynview                       |2.3                 |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.2.2.200.jar          |Just Enough Resources         |jeresources                   |1.2.2.200           |COMMON_SET|Manifest: NOSIGNATURE
		Paraglider-1.19.2-1.7.0.5.jar                     |Paraglider                    |paraglider                    |1.7.0.5             |COMMON_SET|Manifest: NOSIGNATURE
		mushroom delight.jar                              |mushroom delight              |mushroom_delight              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		sushimod-forge-1.19.2-v1.0.4.jar                  |Sushi Mod                     |sushimod                      |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		durabilitytooltip-1.1.4-forge-mc1.19.jar          |Durability Tooltip            |durabilitytooltip             |1.1.4               |COMMON_SET|Manifest: NOSIGNATURE
		stylecolonies-1.0.3.jar                           |stylecolonies mod             |stylecolonies                 |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.19.2-1.0.0.jar                           |Corpse                        |corpse                        |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		FarmersDelight-1.19.2-1.2.2.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.2        |COMMON_SET|Manifest: NOSIGNATURE
		CroptopiaAdditions-1.19.2-FORGE-2.0.FINAL.jar     |Croptopia Additions           |croptopia_additions           |2.0.0.              |COMMON_SET|Manifest: NOSIGNATURE
		repurposed_structures_forge-6.3.24+1.19.2.jar     |Repurposed Structures         |repurposed_structures         |6.3.24+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		chefs-delight-1.0.2-forge-1.19.2.jar              |Chefs Delight                 |chefsdelight                  |1.0.2-forge-1.19.2  |COMMON_SET|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.13_mc1.19.2.jar          |Ambient Sounds                |ambientsounds                 |5.2.13              |COMMON_SET|Manifest: NOSIGNATURE
		mining_dimension-1.19.2-1.0.0.jar                 |Mining World                  |mining_dimension              |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		YungsBridges-1.19.2-Forge-3.1.0.jar               |YUNG's Bridges                |yungsbridges                  |1.19.2-Forge-3.1.0  |COMMON_SET|Manifest: NOSIGNATURE
		zmedievalmusic-1.19.2-2.0.jar                     |medievalmusic mod             |medievalmusic                 |1.19.2-2.0          |COMMON_SET|Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.19.2-1.0.20.jar         |Resourcefulconfig             |resourcefulconfig             |1.0.20              |COMMON_SET|Manifest: NOSIGNATURE
		Philips-Ruins1.19.2-6.8.jar                       |Philip's Ruins                |philipsruins                  |6.8                 |COMMON_SET|Manifest: NOSIGNATURE
		corail_woodcutter_extension_byg-1.19.2-1.0.3.jar  |Corail Woodcutter: Extension B|corail_woodcutter_extension_by|1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.1.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.1      |COMMON_SET|Manifest: NOSIGNATURE
		tetra-1.19.2-5.3.1.jar                            |Tetra                         |tetra                         |5.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		tetranomicon-1.4.2-1.19.2.jar                     |Tetranomicon                  |tetranomicon                  |1.4.2-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		corail_woodcutter-1.19.2-2.5.2.jar                |Corail Woodcutter             |corail_woodcutter             |2.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		blockui-1.19-0.0.69-ALPHA.jar                     |UI Library Mod                |blockui                       |1.19-0.0.69-ALPHA   |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.19.2-6.65.jar                        |Collective                    |collective                    |6.65                |COMMON_SET|Manifest: NOSIGNATURE
		storageracks-1.19.2-1.1.4.jar                     |Storage Racks                 |storageracks                  |1.19.2-1.1.4        |COMMON_SET|Manifest: NOSIGNATURE
		ftb-ultimine-forge-1902.4.1-build.90.jar          |FTB Ultimine                  |ftbultimine                   |1902.4.1-build.90   |COMMON_SET|Manifest: NOSIGNATURE
		overgrowth-1.19.2-1.1.8.jar                       |overgrowth mod                |overgrowth                    |1.19.2-1.1.8        |COMMON_SET|Manifest: NOSIGNATURE
		passiveshield-1.19.2-3.2.jar                      |Passive Shield                |passiveshield                 |3.2                 |COMMON_SET|Manifest: NOSIGNATURE
		With_Thursday-R5.1(5.0FIX)-1.19.2.jar             |with_thursday                 |with_thursday                 |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.19-1.10.6.jar       |Inventory Profiles Next       |inventoryprofilesnext         |1.10.6              |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |COMMON_SET|Manifest: NOSIGNATURE
		letsdo-api-forge-1.1.0.jar                        |Lets Do Api                   |doapi                         |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		letsdo-vinery-forge-1.3.7.jar                     |Vinery                        |vinery                        |1.3.7               |COMMON_SET|Manifest: NOSIGNATURE
		JAMD-Forge-2.1.2+mc1.19.2.jar                     |Just Another Mining Dimension |jamd                          |2.1.2+mc1.19.2      |COMMON_SET|Manifest: NOSIGNATURE
		betterwithminecolonies-1.19-1.18.19.jar           |Better With Minecolonies      |betterwithminecolonies        |1.19++-1.18.19      |COMMON_SET|Manifest: NOSIGNATURE
		beer_craft-1.19.2-1.0.0.jar                       |Beer Craft                    |beer_craft                    |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Enhanced-Farming-1.19.2-1.5.3.jar                 |Enhanced Farming              |enhancedfarming               |1.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		woodenshears-1.19-1.3.0.0.jar                     |Wooden Shears                 |woodenshears                  |1.19-1.3.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		Towns-and-Towers-v.1.10-_FORGE-1.19.2_.jar        |Towns and Towers              |t_and_t                       |1.10                |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-30.jar                              |FastLeafDecay                 |fastleafdecay                 |30                  |COMMON_SET|Manifest: NOSIGNATURE
		TofuCraftReload-1.19.2-2.10.2.1.jar               |TofuCraftReload               |tofucraft                     |1.19.2-2.10.2.1     |COMMON_SET|Manifest: NOSIGNATURE
		maturidelight-1.19.2-0.1.0.jar                    |MaturiDelight                 |maturidelight                 |1.19.2-0.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		tofudelight-1.19.2-1.0.1.jar                      |TofuDelight                   |tofudelight                   |1.19.2-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		Festive_Delight_1.0_1.19.2.jar                    |Festive Delight               |festive_delight               |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		trashslot-forge-1.19-12.0.2.jar                   |TrashSlot                     |trashslot                     |12.0.2              |COMMON_SET|Manifest: NOSIGNATURE
		ftb-library-forge-1902.4.1-build.236.jar          |FTB Library                   |ftblibrary                    |1902.4.1-build.236  |COMMON_SET|Manifest: NOSIGNATURE
		TheFenceUnleashed-1.0.2-1.19.2-1.1.jar            |The Fence Unleashed           |fency                         |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		culturaldelights-1.19.2-0.15.4.jar                |Cultural Delights             |culturaldelights              |0.15.4              |COMMON_SET|Manifest: NOSIGNATURE
		harvestwithease-1.19.2-6.0.1.4-final-forge.jar    |Harvest with ease             |harvestwithease               |6.0.1.4-final       |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1016.jar                  |Just Enough Items             |jei                           |11.6.0.1016         |COMMON_SET|Manifest: NOSIGNATURE
		Nameless Trinkets-1.19.2-1.7.3.jar                |Nameless Trinkets             |nameless_trinkets             |1.19.2-1.7.3        |COMMON_SET|Manifest: NOSIGNATURE
		The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar       |The Graveyard                 |graveyard                     |2.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.19.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		goblintraders-1.8.0-1.19.2.jar                    |Goblin Traders                |goblintraders                 |1.8.0               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |COMMON_SET|Manifest: NOSIGNATURE
		numismaticoverhaul-1.19.2-1.0.4.jar               |Numismatic Overhaul Reforged  |numismaticoverhaul            |1.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		forgivingworld-1.19.2-4.0.jar                     |Forgiving world mod           |forgivingworld                |1.19.2-4.0          |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-6.0.5+1.19.2.jar                   |Comforts                      |comforts                      |6.0.5+1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.19.2-1.10.0-forge.jar            |Nature's Compass              |naturescompass                |1.19.2-1.10.0-forge |COMMON_SET|Manifest: NOSIGNATURE
		copper-mod-1.19.2.jar                             |Copper Armor & Tools          |copperarmorandtools           |1.19.2              |COMMON_SET|Manifest: NOSIGNATURE
		starlight-1.1.1+forge.cf5b10b.jar                 |Starlight                     |starlight                     |1.1.1+forge.a3aea74 |COMMON_SET|Manifest: NOSIGNATURE
		ExplorersCompass-1.19.2-1.3.0-forge.jar           |Explorer's Compass            |explorerscompass              |1.19.2-1.3.0-forge  |COMMON_SET|Manifest: NOSIGNATURE
		farsight-1.19.2-2.1.jar                           |Farsight mod                  |farsight_view                 |1.19.2-2.1          |COMMON_SET|Manifest: NOSIGNATURE
		pineapple_delight-Forge-1.19.2-1.0.6-Fix1.jar     |Pineapple Delight             |pineapple_delight             |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		PackingTape-1.19-0.14.0.jar                       |Packing Tape                  |packingtape                   |0.14.0              |COMMON_SET|Manifest: NOSIGNATURE
		CoffeeDelight-Forge-1.19.2-1.3.jar                |Coffee Delight                |coffee_delight                |1.3                 |COMMON_SET|Manifest: NOSIGNATURE
		panorama-1.3.0 - 1.19.2.jar                       |Panorama                      |panorama                      |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		beehive-tooltips-forge-1.5.0.jar                  |Beehive Tooltips              |beehivetooltips               |1.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.2.14-universal.jar                |Forge                         |forge                         |43.2.14             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		wso16-forge-1.1.jar                               |Why stacks of 16?             |wso16                         |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.19.2-15.1.8.jar            |CraftingTweaks                |craftingtweaks                |15.1.8              |COMMON_SET|Manifest: NOSIGNATURE
		tetrasdelight-1.19.2-1.jar                        |Tetra's Delight               |tetrasdelight                 |1.19.2-1            |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		smoothchunk-1.19.1-2.0.jar                        |Smoothchunk mod               |smoothchunk                   |1.19.1-2.0          |COMMON_SET|Manifest: NOSIGNATURE
		vanillaplustools-1.19-1.1.jar                     |Vanilla+ Tools                |vanillaplustools              |1.19-1.1            |COMMON_SET|Manifest: NOSIGNATURE
		libIPN-forge-1.19-3.0.2.jar                       |libIPN                        |libipn                        |3.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.19.2-13.0.14.jar  |EnchantmentDescriptions       |enchdesc                      |13.0.14             |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.19.2-2.0.1.166.jar           |TerraBlender                  |terrablender                  |2.0.1.166           |COMMON_SET|Manifest: NOSIGNATURE
		swingthroughgrass-1.19.2-1.10.0.jar               |SwingThroughGrass             |swingthroughgrass             |1.19.2-1.10.0       |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.19-2.23.jar                 |Mouse Tweaks                  |mousetweaks                   |2.23                |COMMON_SET|Manifest: NOSIGNATURE
		commonality-1.19.2-4.2.1.jar                      |Commonality                   |commonality                   |4.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		mysterious_mountain_lib-1.2.3-1.19.2.jar          |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.2.3-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		corn_delight-1.0.2-1.19.2.jar                     |Corn Delight                  |corn_delight                  |1.0.2-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.8.1.jar                       |Jade                          |jade                          |8.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.4_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |COMMON_SET|Manifest: NOSIGNATURE
		AdLods-1.19.2-7.0.8.1-build.0865.jar              |Large Ore Deposits            |adlods                        |7.0.8.1             |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.12.5+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.5+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		NethersDelight-1.19-3.0.jar                       |Nether's Delight              |nethersdelight                |1.19-3.0            |COMMON_SET|Manifest: NOSIGNATURE
		domum_ornamentum-1.19-1.0.111-BETA-universal.jar  |Domum Ornamentum              |domum_ornamentum              |1.19-1.0.111-BETA   |COMMON_SET|Manifest: NOSIGNATURE
		betterfpsdist-1.19.2-2.9.jar                      |betterfpsdist mod             |betterfpsdist                 |1.19.2-2.9          |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-3.12.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.12.0              |COMMON_SET|Manifest: NOSIGNATURE
		FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.19.2-5.1.0.jar                            |mutil                         |mutil                         |5.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		art_of_forging-1.6.7-1.19.2.jar                   |Art of Forging                |art_of_forging                |1.6.7-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		ecologics-forge-1.19.2-2.1.11.jar                 |Ecologics                     |ecologics                     |2.1.11              |COMMON_SET|Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		glowingores-1.19.2-1.7.jar                        |glowingores mod               |glowingores                   |1.19.2-1.7          |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-0.46.4+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.4+1.19.2       |COMMON_SET|Manifest: NOSIGNATURE
		corail_recycler-5.6.0-1.19.jar                    |Corail Recycler               |corail_recycler               |5.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		entityculling-forge-1.6.1-mc1.19.2.jar            |EntityCulling                 |entityculling                 |1.6.1               |COMMON_SET|Manifest: NOSIGNATURE
		miners_delight-1.19.2-1.1.1.jar                   |Miner's Delight               |miners_delight                |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		global_packs-forge-1.19.2-1.14.5_forge.jar        |Global Packs                  |globaldataandresourcepacks    |1.14.5_forge        |COMMON_SET|Manifest: NOSIGNATURE
		structurize-1.19.2-1.0.591-BETA.jar               |Structurize                   |structurize                   |1.19.2-1.0.591-BETA |COMMON_SET|Manifest: NOSIGNATURE
		multipiston-1.19.2-1.2.25-ALPHA.jar               |Multi-Piston                  |multipiston                   |1.19.2-1.2.25-ALPHA |COMMON_SET|Manifest: NOSIGNATURE
		FlowerPatch-forge-1.19.2-2.0.3.jar                |Flower Patch                  |flowerpatch                   |2.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		minecolonies-1.19.2-1.1.36-BETA.jar               |MineColonies                  |minecolonies                  |1.19.2-1.1.36-BETA  |COMMON_SET|Manifest: NOSIGNATURE
		JadeColonies-1.19.2-1.0.1.jar                     |JadeColonies                  |jadecolonies                  |1.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.19.2.jar                    |Ocean's Delight               |oceansdelight                 |1.0.2-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		mvs-3.2-1.19.2.jar                                |Moog's Voyager Structures     |mvs                           |3.2-1.19.2          |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		alexsdelight-1.4.1.jar                            |Alex's Delight                |alexsdelight                  |1.4.1               |COMMON_SET|Manifest: NOSIGNATURE
		ThursdayDelight-Forge-1.19.2-1.0.3 .jar           |With Thursday Delight         |thursday_delight              |0.0NONE             |COMMON_SET|Manifest: NOSIGNATURE
		ferritecore-5.0.3-forge.jar                       |Ferrite Core                  |ferritecore                   |5.0.3               |COMMON_SET|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		extradelight-1.0.2.jar                            |ExtraDelight                  |extradelight                  |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		biomemusic-1.19.2-1.6.jar                         |biomemusic mod                |biomemusic                    |1.19.2-1.6          |COMMON_SET|Manifest: NOSIGNATURE
		fastfooddelight-1.19-1.2.3.jar                    |https://github.com/akaneoMT/Fa|fastfooddelight               |1.19-1.2.3          |COMMON_SET|Manifest: NOSIGNATURE
		apexcore-1.19.2-7.3.1.jar                         |ApexCore                      |apexcore                      |7.3.1               |COMMON_SET|Manifest: NOSIGNATURE
		fantasyfurniture-1.19.2-6.7.0.jar                 |Fantasy's Furniture           |fantasyfurniture              |6.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		ItalianDelight-1.19.2 1.5-MAR_FIX.jar             |Italian Delight               |italian_delight               |1.2                 |COMMON_SET|Manifest: NOSIGNATURE
		PizzaCraft-1.19.2-6.2.2.jar                       |PizzaCraft                    |pizzacraft                    |6.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.1.4.jar  |Oh The Biomes You'll Go       |byg                           |2.0.1.4             |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |COMMON_SET|Manifest: NOSIGNATURE
		CorgiLib-forge-1.19.2-1.0.0.34.jar                |CorgiLib                      |corgilib                      |1.0.0.34            |COMMON_SET|Manifest: NOSIGNATURE
		creeperoverhaul-2.0.9-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |2.0.9               |COMMON_SET|Manifest: NOSIGNATURE
		Craftable Horse Armour  Saddle-1.19-1.9.jar       |CHA&S - Craftable Horse Armour|craftablehorsearmour          |1.9                 |COMMON_SET|Manifest: NOSIGNATURE
		varietree-1.1.1.jar                               |Varietree                     |varietree                     |1.19.2-1.1.1        |COMMON_SET|Manifest: NOSIGNATURE
		expandability-7.0.0.jar                           |ExpandAbility                 |expandability                 |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Delightful-1.19.2-3.3.jar                         |Delightful                    |delightful                    |3.3                 |COMMON_SET|Manifest: NOSIGNATURE
		convenientcurioscontainer-1.12-1.19.2.jar         |Convenient Curios Container   |convenientcurioscontainer     |12_forge-1.19.2     |COMMON_SET|Manifest: NOSIGNATURE
		no-telemetry-1.7.0.jar                            |No Telemetry                  |no_telemetry                  |1.7.0               |COMMON_SET|Manifest: NOSIGNATURE
		toolbooster-1.0-1.19.2.jar                        |Tetra Toolbooster             |toolbooster                   |1.0-1.19.2          |COMMON_SET|Manifest: NOSIGNATURE

### Logs

[https://paste.ee/p/IspJg](https://paste.ee/p/IspJg)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
It seems that **Tofu Delight** is having initialization problems when registering its custom Cooking Pot block. When disabled, the instance should boot properly.

Please forward this issue to the Tofu Delight issue board:
https://github.com/baguchan/TofuDelight/issues

**Comment by kedamono** [comment]
Thanks, I filed a bug in Tofu Delight. 

[https://github.com/baguchan/TofuDelight/issues/1#issue-1828005708](https://github.com/baguchan/TofuDelight/issues/1#issue-1828005708)
