### ISSUE TITLE
Game Failed To Start With Farmer's Delight, Create, and OptiFine Installed

### ISSUE THREAD

**Issue by AlisonHuang777** [vectorwing/FarmersDelight#791]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.0

### Description

As the title described, when I try to start the game with these 3 mod, it failed to initialize.

### Mod list

I have also performed some extra tests:

F: Farmer's Delight (1.2.3)
C: Create (0.5.1.d)
O: OptiFine (I5)
R: Rubidium (0.7.0a)

F+C+O: Failed to initialize (the case for this issue)
F+C+R: Success
F+C: Success
C+O: Failed
F+O: Success

Note: I only test for initializing the game, without loading worlds. Also, all of these tests are done with JEI (15.2.0.23) installed.

### Logs

[crash-2023-08-08_22.39.42-client.txt](https://github.com/vectorwing/FarmersDelight/files/12292566/crash-2023-08-08_22.39.42-client.txt)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/12292571/latest.log)

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by SkyKingPX** [comment]
Same:

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Farmer's Delight (farmersdelight) encountered an error during the common_setup event phase

[crash-2023-08-13_17.27.26-client.txt](https://github.com/vectorwing/FarmersDelight/files/12329796/crash-2023-08-13_17.27.26-client.txt)

**Comment by vectorwing** [comment]
After asking around regarding this crash, it seems to be squarely an OptiFine issue.

OF does something to the target method of Create's mixin, which causes it to apply wrongly; Farmer's Delight just happened to get caught in the crossfire. Similar crashes could happen with other mod interactions, and there doesn't seem to be much I can do to fix it.

I suggest reporting this to OptiFine, or waiting for an updated version.

**Comment by SkyKingPX** [comment]
Ok, i will try
