### ISSUE TITLE
[1.20.1] Error in server console while loading up with Farmer's Delight

### ISSUE THREAD

**Issue by BugmanBugman** [vectorwing/FarmersDelight#792]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3 

### Forge version

47.1.58

### Description

While loading up a server with Farmer's delight an error related to rendering. It doesn't crash, but i thought i should report it

### Steps to reproduce

1. Start up server
2. Read log

### Mod list

Just farmers delight

### Logs

https://hastebin.com/share/uzipehasey.css

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by edgarogh** [comment]
The crash log link is expired. Use pastebin or [mclo.gs](https://mclo.gs).

**Comment by MrLoLf** [comment]
I think this error means this line `[main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class vectorwing/farmersdelight/client/renderer/CanvasSignRenderer for invalid dist DEDICATED_SERVER` I found it in my debug logs 
[debug.log](https://github.com/vectorwing/FarmersDelight/files/13636043/debug.log) I'm on forge version 47.2.16, and I'm playing atm9 on version 0.2.28 it uses the same farmersdelight version 1.2.3 on 1.20.1

**Comment by vectorwing** [comment]
This seems to be caused by **Supplementaries**: it has a compat mixin for CanvasSignRenderer, which is being loaded into the server side.
The warning seems harmless, but I suggest forwarding this to the mod's issue board.
