### ISSUE TITLE
Very Minor Issue

### ISSUE THREAD

**Issue by MLPShockfury** [vectorwing/FarmersDelight#797]
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.1

### Forge version

40.2.0

### Description

When using a Kama, or Scythe (Added by Tinkers Construct) Onions fail to replant after harvesting.
Cabbage functions properly, replanting itself after being harvested with a Kama or Scythe.

This may happen with other mods that auto replant after harvesting, but i am unsure.
(I am unsure if this issue persists in current versions, as Tinkers Constructs is currently only up to 1.18.x)

### Steps to reproduce

Simply harvest Onions with a Kama or Scythe from Tinkers Constructs, and they will not automatically replant.

### Mod list

All are for Version 1.18.2 of Minecraft, the mods Version numbers are at the end of their names.

BetterF3 3.0.0
Cloth-Config 6.5.102
Farmers Delight 1.18.2-1.2.1
Inventory Sorter 1.18.2-19.0.4
JEI 10.2.1.1005
Mantle 1.9.45
Rubidium 0.5.6
Tinkers Constructs 3.6.4.113

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This was fixed in the latest 1.18.2 patches.
Please download version **1.2.3**, and onions will be tagged as plantable for Tinker's construct. 👍
