### ISSUE TITLE
Apple Cider Includes an Eating Sound when it is consumed.

### ISSUE THREAD

**Issue by FoggyHillside** [vectorwing/FarmersDelight#801]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.0

### Description

I don't know if this is intentional, but when consuming Apple Cider, one of the eating sounds is played at the end.

### Mod list

FarmersDelight-1.20.1-1.2.3

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Yup, it's known. It's a quirk of the food system... Apple Cider has food values so that it inflicts Absorption on the player, so the game always plays a little burp. Haven't figured out yet how to stop it, unless I make a custom implementation. :(

It's in the backlog. 👍
