### ISSUE TITLE
Can't plant rice

### ISSUE THREAD

**Issue by Ethanthelandlord92** [vectorwing/FarmersDelight#803]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.3

### Description

Whenever I get rice and try to plant it, it states that the crop cannot survive well outside of water even when I'm in the water. 

### Steps to reproduce

1. Obtain rice (through creative mode due to rice plants not spawning)
2. Attempt to place rice on dirt underwater (This also applies to rich soil)

### Mod list

Mod List: 
		grappling_hook_mod-1.20.1-1.20.1-v13.jar          |Grappling Hook Mod            |grapplemod                    |1.20.1-v13          |DONE      |Manifest: NOSIGNATURE
		TreeChop-1.20.1-forge-0.18.3.jar                  |HT's TreeChop                 |treechop                      |0.18.3              |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.20.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.2.2.jar                   |GeckoLib 4                    |geckolib                      |4.2.2               |DONE      |Manifest: NOSIGNATURE
		scena-forge-1.0.102.jar                           |Scena                         |scena                         |1.0.102             |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.2.0.jar                   |Botarium                      |botarium                      |2.2.0               |DONE      |Manifest: NOSIGNATURE
		nether-s-exoticism-1.20.1-1.2.6.jar               |Nether's Exoticism            |nethers_exoticism             |1.2.6               |DONE      |Manifest: NOSIGNATURE
		Galosphere-1.20.1-1.3.2-Forge.jar                 |Galosphere                    |galosphere                    |1.20.1-1.3.2        |DONE      |Manifest: NOSIGNATURE
		dynamiclights-1.20.1.1.jar                        |Dynamic Lights                |dynamiclights                 |1.20.1.1            |DONE      |Manifest: NOSIGNATURE
		immersive_aircraft-0.5.2+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.5.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.83.395.jar           |Sophisticated Core            |sophisticatedcore             |1.20.1-0.5.83.395   |DONE      |Manifest: NOSIGNATURE
		modnametooltip-1.20.1-1.20.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.20.0              |DONE      |Manifest: NOSIGNATURE
		duckling-3.0.0-forge.jar                          |Duckling                      |duckling                      |3.0.0               |DONE      |Manifest: NOSIGNATURE
		jumpoverfences-forge-1.20.1-1.3.0.jar             |Jump Over Fences              |jumpoverfences                |1.3.0               |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |DONE      |Manifest: NOSIGNATURE
		BotanyPotsTiers-Forge-1.20.1-6.0.0.jar            |BotanyPotsTiers               |botanypotstiers               |6.0.0               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.0.3.jar                 |Bookshelf                     |bookshelf                     |20.0.3              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Kambrik-6.1.1+1.20.1-forge.jar                    |Kambrik                       |kambrik                       |6.1.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.18.56.890.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.20.1-3.18.56.890  |DONE      |Manifest: NOSIGNATURE
		create-new-age-forge-1.20.1-1.0.1.jar             |Create: New Age               |create_new_age                |1.0.1               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20-7.0.7.jar                         |Balm                          |balm                          |7.0.7               |DONE      |Manifest: NOSIGNATURE
		FpsReducer2-forge-1.20-2.5.jar                    |FPS Reducer                   |fpsreducer                    |1.20-2.5            |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.0.1.jar                  |Carry On                      |carryon                       |2.1.0.1             |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.20.1-1.4.0.238.jar          |Just Enough Resources         |jeresources                   |1.4.0.238           |DONE      |Manifest: NOSIGNATURE
		Paraglider-1.20.1-1.9.0.0.jar                     |Paraglider                    |paraglider                    |1.9.0.0             |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1809-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1809            |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.5.26.jar                   |Supplementaries               |supplementaries               |1.20-2.5.26         |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		ends_delight-1.20.1-1.0.1.jar                     |End's Delight                 |ends_delight                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		BetterCookedAxolotls-1.0-1.20.1-Forge.jar         |Better Cooked Axolotls        |bca                           |1.0-1.20.1          |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.1.jar                |Handcrafted                   |handcrafted                   |3.0.1               |DONE      |Manifest: NOSIGNATURE
		repurposed_structures-7.1.4+1.20.1-forge.jar      |Repurposed Structures         |repurposed_structures         |7.1.4+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		CozyHome-1.20.1-2.2.2.jar                         |Cozy Home                     |cozy_home                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		fakeplayers-0.7.6+1.20.1.jar                      |Fake Players                  |fakeplayers                   |0.7.6+1.20.1        |DONE      |Manifest: NOSIGNATURE
		CreateDrinks-1.0.1-1.20.1.jar                     |Create: Drinks                |create_drinks                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		BloodAndMadness-Forge1.20.1-v2.1.5.2.jar          |Blood And Madness             |bloodandmadness               |2.0                 |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.12a-forge-mc1.20.jar   |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.12a             |DONE      |Manifest: NOSIGNATURE
		TrailsandTalesPlus-1.20.1-4.0.jar                 |Trails and Tales Plus Mod     |trailsandtalesplus            |1.20-1.0.0          |DONE      |Manifest: NOSIGNATURE
		Sniffer+-forge-1.20.1-0.2.0.jar                   |Hellion's Sniffer+            |snifferplus                   |0.2.0               |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.0.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Bountiful-6.0.3+1.20.1-forge.jar                  |Bountiful                     |bountiful                     |6.0.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |DONE      |Manifest: NOSIGNATURE
		nocube's_better_blast_furnace_1.0.1_Forge_1.20.1.j|NoCube's Better Blast Furnace |ncbetterblastfurnace          |1.0.1               |DONE      |Manifest: NOSIGNATURE
		extendedmushrooms-1.20.1-4.1.0.0.jar              |Extended Mushrooms            |extendedmushrooms             |1.20.1-4.1.0.0      |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-6.65.jar                        |Collective                    |collective                    |6.65                |DONE      |Manifest: NOSIGNATURE
		Nature_Arise-0.4.3-1.20.1.jar                     |Nature Arise                  |nature_arise                  |0.4.3               |DONE      |Manifest: NOSIGNATURE
		Measurements-forge-1.20.1-2.0.0.jar               |Measurements                  |measurements                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		bettervillage-forge-1.20.1-3.2.0.jar              |Better village                |bettervillage                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.10.jar            |Resourceful Lib               |resourcefullib                |2.1.10              |DONE      |Manifest: NOSIGNATURE
		giacomos_fishing_net-1.20.1-1.7.9.jar             |Giacomo's Fishing net mod     |giacomos_fishing_net          |1.20.1-1.7.9        |DONE      |Manifest: NOSIGNATURE
		Butchersdelight beta 1.20.1 1.0.0.jar             |ButchersDelight               |butchersdelight               |1.20.11.0.0         |DONE      |Manifest: NOSIGNATURE
		twilightdelight-2.0.2.jar                         |Twilight's Flavor & Delight   |twilightdelight               |2.0.2               |DONE      |Manifest: NOSIGNATURE
		wormhole-1.1.13a-forge-mc1.20.jar                 |Wormhole (Portals)            |wormhole                      |1.1.13a             |DONE      |Manifest: NOSIGNATURE
		deeperdarker-forge-1.20.1-1.2.0.jar               |Deeper and Darker             |deeperdarker                  |1.2.0               |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		cupboard-1.20.1-1.8.jar                           |Cupboard utilities            |cupboard                      |1.20.1-1.8          |DONE      |Manifest: NOSIGNATURE
		l2library-2.4.11-slim.jar                         |L2 Library                    |l2library                     |2.4.11              |DONE      |Manifest: NOSIGNATURE
		exoticbirds-1.20.1-1.0.0.jar                      |Exotic Birds                  |exoticbirds                   |1.0.0               |DONE      |Manifest: NOSIGNATURE
		crawlondemand-1.20.x-1.0.0.jar                    |Crawl on Demand               |crawlondemand                 |1.20.x-1.0.0        |DONE      |Manifest: NOSIGNATURE
		BetterAdvancements-1.20.1-0.3.2.161.jar           |Better Advancements           |betteradvancements            |0.3.2.161           |DONE      |Manifest: NOSIGNATURE
		Saros-Easy-Mining-Mod-1.20.1-1.1.jar              |Saro´s Easy Mining Mod        |saros_easy_mining_mod         |1.0.0               |DONE      |Manifest: NOSIGNATURE
		super_block_world-0.0.7-1.20.jar                  |Super Block World             |super_block_world             |0.0.7-1.20          |DONE      |Manifest: NOSIGNATURE
		doubledoors-1.20.1-5.0.jar                        |Double Doors                  |doubledoors                   |5.0                 |DONE      |Manifest: NOSIGNATURE
		fishermens_trap-2.1.1.jar                         |Fishermens Trap               |fishermens_trap               |2.1.1               |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-2001.1.3.jar                    |FTB Library                   |ftblibrary                    |2001.1.3            |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-2001.1.4.jar                      |FTB Teams                     |ftbteams                      |2001.1.4            |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		VisualWorkbench-v8.0.0-1.20.1-Forge.jar           |Visual Workbench              |visualworkbench               |8.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		libraryferret-forge-1.20.1-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		flying_fox-1.20.1-1.0.2.jar                       |Flying Fox                    |flying_fox                    |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		epicsamurai-0.0.25-1.20.1-forge.jar               |Epic Samurai                  |epicsamurai                   |0.0.25-1.20.1-forge |DONE      |Manifest: NOSIGNATURE
		caelus-forge-3.1.0+1.20.jar                       |Caelus API                    |caelus                        |3.1.0+1.20          |DONE      |Manifest: NOSIGNATURE
		obscure_api-15.jar                                |Obscure API                   |obscure_api                   |15                  |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.1.jar                   |Waystones                     |waystones                     |14.0.1              |DONE      |Manifest: NOSIGNATURE
		MonsterPlus-Forge1.20.1-v1.1.6.1.jar              |Monster Plus                  |monsterplus                   |1.0                 |DONE      |Manifest: NOSIGNATURE
		mcpitanlibarch-1.7.8-1.20.1-forge.jar             |MCPitanLib                    |mcpitanlibarch                |1.7.8-1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		comforts-forge-6.3.3+1.20.1.jar                   |Comforts                      |comforts                      |6.3.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		artifacts-forge-9.0.5.jar                         |Artifacts                     |artifacts                     |9.0.5               |DONE      |Manifest: NOSIGNATURE
		untamedwilds-4.0.2.jar                            |Untamed Wilds                 |untamedwilds                  |4.0.2               |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.43.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.43            |DONE      |Manifest: NOSIGNATURE
		BotanyPots-Forge-1.20.1-13.0.9.jar                |BotanyPots                    |botanypots                    |13.0.9              |DONE      |Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.20.1-1.3.3-forge.jar           |Explorer's Compass            |explorerscompass              |1.20.1-1.3.3-forge  |DONE      |Manifest: NOSIGNATURE
		Ore Creeper-1.20.1-1.2.0.jar                      |Ore Creeper                   |ore_creeper                   |1.20.1-1.2.0        |DONE      |Manifest: NOSIGNATURE
		netherdepthsupgrade-3.1.0-1.20.jar                |Nether Depths Upgrade         |netherdepthsupgrade           |3.1.0-1.20          |DONE      |Manifest: NOSIGNATURE
		moremobheads-0.2.1-1.20.1.jar                     |More Mob Heads                |moremobheads                  |0.2.1-1.20.1        |DONE      |Manifest: NOSIGNATURE
		imst-2.1.0.jar                                    |Immersive Structures          |imst                          |2.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.1.3-universal.jar                 |Forge                         |forge                         |47.1.3              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		friendsandfoes-forge-mc1.20.1-1.9.4.jar           |Friends&Foes                  |friendsandfoes                |1.9.4               |DONE      |Manifest: NOSIGNATURE
		createbb-1.20.1-3.1.1.jar                         |Create: Broken Bad            |createbb                      |3.1.1               |DONE      |Manifest: NOSIGNATURE
		craftingtweaks-forge-1.20-18.0.2.jar              |CraftingTweaks                |craftingtweaks                |18.0.2              |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		EnchantmentDescriptions-Forge-1.20.1-17.0.4.jar   |EnchantmentDescriptions       |enchdesc                      |17.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.8.11-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.11         |DONE      |Manifest: NOSIGNATURE
		livingthings-forge-1.20.1-2.0.1.jar               |Living Things                 |livingthings                  |1.20.1-2.0.1        |DONE      |Manifest: NOSIGNATURE
		nightlights-1.20.1-1.1.jar                        |Night Lights                  |nightlights                   |1.1                 |DONE      |Manifest: NOSIGNATURE
		fish_of_thieves-mc1.20.1-v3.0.2-forge.jar         |Fish of Thieves               |fishofthieves                 |3.0.2               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.34_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.10.34             |DONE      |Manifest: NOSIGNATURE
		ava-1.20.1-2.5.5.jar                              |A.V.A - Alliance of Valiant Ar|ava                           |2.5.5               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.12+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.12+1.20.1      |DONE      |Manifest: NOSIGNATURE
		mobcompack-0.0.3.9-1.20.1.jar                     |Mob Compack                   |mobcompack                    |0.0.3.9-1.20.1      |DONE      |Manifest: NOSIGNATURE
		betterfpsdist-1.20.1-3.8.jar                      |betterfpsdist mod             |betterfpsdist                 |1.20.1-3.8          |DONE      |Manifest: NOSIGNATURE
		kffmod-4.4.0.jar                                  |Kotlin For Forge              |kotlinforforge                |4.4.0               |DONE      |Manifest: NOSIGNATURE
		brewinandchewin-2.0.1-mc1.20.1.jar                |Brewin' and Chewin'           |brewinandchewin               |1.20.1-2.0          |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20-0.6.9-4.jar                   |Flywheel                      |flywheel                      |0.6.9-4             |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.d.jar                         |Create                        |create                        |0.5.1.d             |DONE      |Manifest: NOSIGNATURE
		diet-forge-2.1.0+1.20.1.jar                       |Diet                          |diet                          |2.1.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.20.1-FORGE-2.3.2.jar                  |Croptopia                     |croptopia                     |2.3.2               |DONE      |Manifest: NOSIGNATURE
		some-assembly-required-1.20.1-4.0.0.jar           |Some Assembly Required        |some_assembly_required        |1.20.1-4.0.0        |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.0+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		DiagonalFences-v8.0.1-1.20.1-Forge.jar            |Diagonal Fences               |diagonalfences                |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		FPS-Monitor-1.20-1.3.0.jar                        |FPS Monitor                   |fps                           |1.3.0               |DONE      |Manifest: NOSIGNATURE
		brass_armory-1.20.1-1.0.3.jar                     |Brass's Armory                |brass_armory                  |1.0.3               |DONE      |Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.20.jar                      |Ocean's Delight               |oceansdelight                 |1.0.2-1.20          |DONE      |Manifest: NOSIGNATURE
		frogs.jar                                         |frogs can eat any hostile mob |frogs_can_eat_any_hostile_mob |1.0.0               |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-3.0.1-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |3.0.1               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.0.jar                |AppleSkin                     |appleskin                     |2.5.0+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		KawaiiDishes_1.10.2-1.20.1.jar                    |Kawaii Dishes                 |kawaiidishes                  |1.10.2              |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.0.24-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.0.24              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar      |Enhanced Celestials           |enhancedcelestials            |5.0.0.2             |DONE      |Manifest: NOSIGNATURE
		CorgiLib-forge-1.20.1-4.0.0.4.jar                 |CorgiLib                      |corgilib                      |4.0.0.4             |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.0.jar                      |Aquaculture 2                 |aquaculture                   |2.5.0               |DONE      |Manifest: NOSIGNATURE
		valkyrienskies-1201-2.3.0-beta.4.jar              |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.4        |DONE      |Manifest: NOSIGNATURE
		eureka-1201-1.3.0-beta.2.jar                      |VS Eureka Mod                 |vs_eureka                     |1.3.0-beta.2        |DONE      |Manifest: NOSIGNATURE
		CrabbersDelight-1.20.1-1.1.1.jar                  |Crabber's Delight             |crabbersdelight               |1.1.1               |DONE      |Manifest: NOSIGNATURE
		goated-1.20-1.3.3.jar                             |You've Goat to be kidding me  |goated                        |1.20-1.3.3          |DONE      |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		expandability-forge-9.0.0.jar                     |ExpandAbility                 |expandability                 |9.0.0               |DONE      |Manifest: NOSIGNATURE
		chisels-and-bits-forge-1.4.141.jar                |chisels-and-bits              |chiselsandbits                |1.4.141             |DONE      |Manifest: NOSIGNATURE
		healingcampfire-1.20.1-5.1.jar                    |Healing Campfire              |healingcampfire               |5.1                 |DONE      |Manifest: NOSIGNATURE
		aquamirae-6.API15.jar                             |Aquamirae                     |aquamirae                     |6.API15             |DONE      |Manifest: NOSIGNATURE
		cristellib-1.1.1-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.1               |DONE      |Manifest: NOSIGNATURE

### Logs

[latest.log](https://github.com/vectorwing/FarmersDelight/files/12449784/latest.log)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [x] I am using performance or shader mods

**Comment by TungstenWolf** [comment]
This is probs due to the rice_panicle and panicles bug i found, console/log is calling for rice_panicle but the blocks that DOES exist is rice_panicles, the difference of one letter. I just gotta assume these are related

**Comment by a-a-GiTHuB-a-a** [comment]
Is it one-block-deep water?

**Comment by Ethanthelandlord92** [comment]
Yes

**Comment by NickerAban** [comment]
discord exists?

**Comment by a-a-GiTHuB-a-a** [comment]
Is that question rhetorical?
