### ISSUE TITLE
Minecolonies does not see Farmer's Delight foods

### ISSUE THREAD

**Issue by kezmodius** [vectorwing/FarmersDelight#808]
### Minecraft version

1.20.1

### Farmer's Delight version

FarmersDelight-1.20.1-1.2.3

### Forge version

47.1.44

### Description

Minecolonies does not recognise Farmer's Delight foods as foods. There are two buildings that have a list of allowed foods and no Farmer's Delight foods appear on these lists. I have Pam's in the modpack and Minecolonies recognises their foods and they are on the lists.
I asked on the Minecolonies discord what was wrong and they said that Minecolonies looks at all the items in the creative tabs, and uses all of the food items it finds in there. Your foods are in the creative tabs but still not being recognised as food.
The other weirdness is that I can hand-feed a colonist with your food and eat it as a player, so it is a food.
This arose in a large modpack, so I tested on a minimal pack with Minecolonies + Farmer's Delight and the issue remained.
I have seen Farmer's Delight working with Minecolonies in 1.18.x & 1.19.x, so this is a new issue.

### Steps to reproduce

1. Start a colony (Minecolonies)
2. Build a restaurant
3. Open food list
4. No Farmer's Delight foods - Pam's and Vanilla appeared on my modpack. Minimal modpack was all vanilla foods.

### Mod list

Additional Structures - Rex's-AdditionalStructures-1.20.x-(v.4.1.2).jar
AppleSkin - appleskin-forge-mc1.20.1-2.5.0.jar
Architectury API (Fabric/Forge)
Ars Nouveau
Artifacts
AttributeFix
Awesome Dungeon - Forge
Awesome Dungeon Nether edition - Forge
Awesome Dungeon Ocean edition - Forge
Awesome Dungeon The End edition - Forge
B.F. End Cities
bad packets
Balm (Forge Edition)
Better Copper / Armor and Tools
Better Fps - Render Distance[Forge]
Better Harvesting
Better Treasure Map
Better Villages - Forge
Biome Music[Forge/Fabric]
Biomes O' Plenty
BlockUI
Bookshelf
Caelus API (Forge)
Charm of Undying (Fabric/Forge/Quilt)
Chunk Sending[Forge/Fabric]
Clickable advancements[Forge/Fabric]
Cloth Config API (Fabric/Forge)
Comforts (Fabric/Forge/Quilt)
Companion 🐕 (Forge)
Connectivity[Forge/Fabric]
Controlling
Cooking for Blockheads
Corail Woodcutter
Corpse
Cosmetic Armor Reworked
Cristel Lib
Cupboard
Curios API (Forge)
Curious Armor Stands
Domum Ornamentum
Dynamic View[Forge]
Elytra Slot (Fabric/Forge/Quilt)
Enchantment Descriptions
End Remastered
ExpandAbility
Explorer's Compass
Farmer's Delight
Farsight [Forge]
Forgiving World - Dimension Stacking[Forge/Fabric]
Framework
Friendly Fire
GeckoLib
Goblin Traders
Hostile Villages
HT's TreeChop
Immersive Armors [Fabric/Forge]
Infused Foods
Inventory Essentials
Inventory Sorter
Jade 🔍
Jade Addons (Forge)
JadeColonies
JourneyMap
Just Enough Items (JEI)
Library Ferret - Forge
Limited Chunkloading - Chunk cleanup[Forge/Fabric]
Login Protection[Forge/Fabric]
Loot Integrations[Forge/Fabric]
Lootr (Forge)
Max Health Fix
MC style paintings
MES - Moog's End Structures
MineColonies
Mouse Tweaks
Multi-Piston
MVS - Moog's Voyager Structures
Nameless Trinkets
Nature's Compass
Neat
Pam's HarvestCraft 2 - Crops
Pam's HarvestCraft 2 - Food Core
Pam's HarvestCraft 2 - Food Extended
Pam's HarvestCraft 2 - Trees
Passive Skill Tree
Patchouli
Philip's Ruins
Polymorph (Fabric/Forge/Quilt)
Portable Mobs
Repurposed Structures (Forge)
Searchables
Server Performance - Smooth Chunk Save[Forge/Fabric]
Simply Swords [Fabric & Forge]
Sophisticated Backpacks
Sophisticated Core
Sophisticated Storage
spark
Spice of Life: Apple Pie Edition
Structure Essentials[Forge/Fabric]
Structurize
Stylecolonies
SuperMartijn642's Core Lib
TerraBlender (Forge)
Terralith
The Lost Castle
Towns and Towers
TownTalk
TrashSlot
Vanilla Plus Tools
Waystones

The minimal modpack had:
BlockUI
Domum Ornamentum
Farmer's Delight
Jade
Jadecolonies
JEI
Minecolonies
Multi-Piston
Structurize
Stylecolonies
TownTalk
WorldEdit

### Logs

https://gist.github.com/kezmodius/dab733b863047e8fc37b9936d758054f

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by Raycoms** [comment]
This is already fixed in code, but the new version is not on curseforge yet.

**Comment by vectorwing** [comment]
As Raycoms said, I added a fix to this on a dev instance, but haven't launched it yet.
A fix has been added to the upcoming 1.2.4 patch. 👍
