### ISSUE TITLE
[1.19.2] Internal Exception when Joining Vanilla Server

### ISSUE THREAD

**Issue by MetalBox47** [vectorwing/FarmersDelight#810]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.3

### Forge version

43.2.23

### Description

Upon joining a vanilla server, an internal exception occurs that reads:

Vanilla server is 1.19.2 with no modifications.

Game:
![image](https://github.com/vectorwing/FarmersDelight/assets/35822953/96459e63-2a43-4cbb-8c34-0617ae7f22f2)

Server:
![image](https://github.com/vectorwing/FarmersDelight/assets/35822953/5a050e98-9473-480d-b5b4-26ed2f735315)

### Steps to reproduce

1. Launch Minecraft
2. Go to Multiplayer Screen
3. Click join server button on vanilla server
4. Result

### Mod list

Farmer's Delight v1.2.3

### Logs

[latest.log](https://github.com/vectorwing/FarmersDelight/files/12614934/latest.log)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Farmer's Delight is a Forge mod, and therefore not compatible with vanilla servers. You can't join one with Forge mods installed.
Please make a separate vanilla client to join this server instead.

**Comment by MetalBox47** [comment]
I understand.  However, Forge clients with various mods installed can join vanilla servers without crashing the server or the client, as shown in the attached video.

https://github.com/vectorwing/FarmersDelight/assets/35822953/8fc4ae0a-0a01-4faa-8878-4b36af11360c

Normally this is impractical, but I have a server that uses a vanilla lobby so that players can connect to multiple servers, including a modded one.  Farmer's Delight is the only mod that crashes whenever I do this.

I am more than willing to provide you with more information, and thank you for your time and patience!  Its really appreciated.

**Comment by underscoreffyerauhfasf** [comment]
farmer's delight isn't (only) a client-side mod, which means that it screws with servers upon joining them. other mods, like JEI, _are_ exclusively client-side, so they can join vanilla servers without any issues. this is unavoidable behaviour coming from the nature of any mod that adds content.

**Comment by vectorwing** [comment]
Yes, the issue primarily stems from FD being a content mod. It must be present in both the client *and* the server, or else the client/server cannot understand each other, since items would be missing from registries.

**Comment by MetalBox47** [comment]
Correct, I have no issues joining this server with mods such as mouse teaks and JEI.  However, I also have no issue when joining with mods installed like refined storage, sophisticated backpacks, tetra, and more. This leads me to believe it is a problem on Farmer's Delight's end and not that I am attempting to join a vanilla server with mods installed.

Sorry if I am being unclear or misunderstanding!

**Comment by underscoreffyerauhfasf** [comment]
strange behaviour, but this isn't a bug that needs to be fixed regardless; if you need to join a vanilla server with a forge profile, simply unload farmer's delight

**Comment by MetalBox47** [comment]
Im not trying to be argumentative, but this is problematic whenever server administrators want to have a server network where players have to connect to a lobby server and then join from that server into the modded server with Farmer's Delight installed.  This issue will prevent the clients from ever getting into the lobby so that they may join the modded server.

**Comment by vectorwing** [comment]
Assuming there is a specific issue with FD, the logs provided on the client will not show what it is.

If you can/have access, please provide the server logs in two scenarios:
- Connecting to the server with FD added onto the client;
- Connecting to the server without FD installed.

Also, just to iterate: Forge mods loading successfully in a vanilla server is usually an exception, as there's no explicit compatibility with that implemented. It should be assumed they won't work.

**Comment by MetalBox47** [comment]
Logs are attached, and understood!
[withfdserver.log](https://github.com/vectorwing/FarmersDelight/files/12623480/withfdserver.log)
[withoutfdserver.log](https://github.com/vectorwing/FarmersDelight/files/12623481/withoutfdserver.log)

I also saved the client logs and client screenshot from this run if you would like those.  It did give me a different error this time, however:
![clientimage](https://github.com/vectorwing/FarmersDelight/assets/35822953/1ef334bb-a936-42dc-905c-c6776e8a755f)

**Comment by vectorwing** [comment]
I've been informed that Netty exceptions are swallowed by Forge, thus it shows nothing on logs normally.

@MetalBox47, please add the following mod to your instance, and generate new logs after trying to connect again:
https://www.curseforge.com/minecraft/mc-mods/spit-it-out

It should reveal the exception, or at least give some detail as to why only FD is causing this issue.

**Comment by vectorwing** [comment]
I figured out what the issue is, but sadly, it's not fixable on my end; it's an issue in how Minecraft's enums are interpreted.

Please see this comment on another issue for more details: https://github.com/vectorwing/FarmersDelight/issues/805#issuecomment-1734746830
