### ISSUE TITLE
Refactor cooking recipe containers into recipe data

### ISSUE THREAD

**Issue by Treeways** [vectorwing/FarmersDelight#812]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.47

### Description

Cooking recipes are added via datapack, but their containers are still hardcoded. This would be much more convenient to have in datapack, so it can be read during KubeJS recipe porting.

Here's an analysis of the issue from the perspective of the codebase.

-----------------

Notice how there is no `container` key in this cooking recipe's data file:

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/generated/resources/data/farmersdelight/recipes/cooking/squid_ink_pasta.json#L1-L23

When registering bowl items, they are registered as a `bowlFoodItem` to take bowls as recipe remainders. There is seemingly no input for the container from the recipe data:

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L356-L357

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L29-L31

And vice-versa for `drinkItem`:

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L212-L213

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L33-L35

The only exception is the Stuffed Pumpkin Block:
https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/generated/resources/data/farmersdelight/recipes/cooking/stuffed_pumpkin_block.json#L2-L5

https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L367-L368

Also:
https://github.com/vectorwing/FarmersDelight/blob/ae3aabf76e9d02b5fed419e470b409ef8bcc072b/src/main/java/vectorwing/farmersdelight/common/block/entity/CookingPotBlockEntity.java#L64-L80

### Mod list

Farmer's Delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by Treeways** [comment]
However, contrary to what my (lengthy...) code analysis suggests, it looks like container support is quite easy to add via datapack out of the box.

The following data works just fine (and this is purely as a test):

![image](https://github.com/vectorwing/FarmersDelight/assets/56928485/6452bc5f-e053-4227-8412-6c862a4600ec)

`kubejs/data/farmersdelight/recipes/cooking/squid_ink_pasta.json`
```json
{
    "type": "farmersdelight:cooking",
    "container": {
        "item": "minecraft:glass_bottle"
    },
    "cookingtime": 200,
    "experience": 1.0,
    "ingredients": [
      {
        "tag": "forge:raw_fishes"
      },
      {
        "tag": "forge:pasta"
      },
      {
        "tag": "forge:crops/tomato"
      },
      {
        "item": "minecraft:ink_sac"
      }
    ],
    "recipe_book_tab": "meals",
    "result": {
      "item": "farmersdelight:squid_ink_pasta"
    }
}
```

**Comment by vectorwing** [comment]
Item containers are not an FD addition; they're a hardcoded item property from vanilla. When a contained item is consumed, it gives that item back.

The `container` field in cooking recipe specs allows the recipe to "override" which container item is needed to extract the food from the Cooking Pot. This allows items to require a container without necessarily giving it back when consumed, such as the Stuffed Pumpkin, where the pumpkin is also eaten per serving.

It does **not** affect the item which is given back by the food itself. Doing so would require food items to host NBT data, thus making them unstackable or complicated for the end user.

**Comment by vectorwing** [comment]
The method you saw in the code snippets above are simplifications for item registry. Containers can't be added outside of item registration, as all vanilla systems utilize this item property for that.

**Comment by Treeways** [comment]
Ah, that makes sense. So then it should be safe to assume that a food item's cooking recipes are generated with their remainder.

I'll just hook into the food's remainder with KubeJS in my script, then. Thank you for clarifying!
