### ISSUE TITLE
Farmers Delight rice_panicle log error

### ISSUE THREAD

**Issue by TungstenWolf** [vectorwing/FarmersDelight#813]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.3

### Description

Checking live log while running minecraft shows a infinity repeating error
Block "farmersdelight:rice_panicle" from farmersdelight:rice_panicle does not exist!

I believe this is due to the block having an s at the end of panicle in the command for setblock. Its just a mistyped variable name but it causes tons of errors in the console.

### Mod list

![image](https://github.com/vectorwing/FarmersDelight/assets/85911010/8c481ac3-c9b0-4d88-b347-dbbfaabef103)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
`rice_panicles` refers to a block, the upper half of a rice crop. `rice_panicle`, without the 's', refers to an item. FD's references seem to be correct, as I haven't seen this log spam happen otherwise.

Are you trying to /setblock the rice panicles block through commands? @TungstenWolf

**Comment by vectorwing** [comment]
I'm closing this issue, as it has gotten stale.
Feel free to reopen and reply to the questions above, if it's still happening. 👍
