### ISSUE TITLE
Lattice incompatible with supplementaries

### ISSUE THREAD

**Issue by dchieh222** [vectorwing/FarmersDelight#816]
### Minecraft version

1.20

### Farmer's Delight version

1.2.3

### Forge version

The latest

### Description

When attempting to build the lattice structure with Supplementaries mod installed, the timber frame takes precedence.

### Steps to reproduce

1. Attempt to build lattice
2. Get timber frame

### Mod list

Farmer's Delight
Supplementaries

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
I'm sorry, but what do you mean by lattice? Farmer's Delight has no such block.
Please add more details, and/or a screenshot, of the issue you're facing.

**Comment by vectorwing** [comment]
I'm closing this issue, as no further info was given. 👍
