### ISSUE TITLE
[Feature request] Products spoil over time

### ISSUE THREAD

**Issue by ksk-waqs** [vectorwing/FarmersDelight#82]
Hi 👋. First, thank you for the great fashion!

How about adding functionality to spoil products over time (raw products spoil faster than prepared or cooked). And also ways to keep food fresh?  (cellar, salting, curing, canning).

**Comment by vectorwing** [comment]
Hello there!

Sorry, I have no plans for food spoiling. Not only is it a rather tiring mechanic to most players, it's also technically quite difficult to pull off, as both vanilla and modded container blocks would have to tick (which they don't) for spoilage to take place. Thanks for suggesting, though!
