### ISSUE TITLE
Farmer's Delight contains an outdated structure file

### ISSUE THREAD

**Issue by WFPhantom** [vectorwing/FarmersDelight#820]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.3

### Description

ModernFix shows this in the console when FD is present
```
The namespace farmersdelight contains an outdated structure file, which can cause worldgen lag.

Structure farmersdelight:village/houses/desert_compost_pile is being run through DFU (hash c806a3403a5760942762d159958748160b9059fbba0d015a616c97f5beb80393), this will cause launch time delays
```

AFAIK mojang changed something with the DFU in 1.19.4 and that might be the reason ModernFix is showing that

### Mod list

Only modernfix and FD are required for this

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
According to the author, I just need to re-save the structure files on 1.20.1 to fix the DFU trigger. I'll put this on the backlog.

**Comment by vectorwing** [comment]
I added a tool shared by malte0811 (from Immersive Engineering), which will auto-update these structure files with each new Minecraft version on `runData`. This should fix this issue moving forward, and will be out on the 1.2.4 release. 👍
