### ISSUE TITLE
Hot Cocoa doesn't clear Bad Omen

### ISSUE THREAD

**Issue by capyisslay** [vectorwing/FarmersDelight#821]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.1

### Description

Hot Cocoa clears one harmful effect, but doesn't clear Bad Omen

### Steps to reproduce

Drink Hot Cocoa with Bad Omen

### Mod list

Minecraft
Forge
Farmer's Delight
Just Enough Items
Catalogue

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
As weird as it may sound, Bad Omen is classified as a "neutral" effect, not harmful. So Hot Cocoa doesn't target it. :(
