### ISSUE TITLE
Sugar Cane not growing on rich soil.

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#823]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1-1.2.3

### Forge version

47.2.1

### Description

When attempting to plant sugar cane on a block of rich soil next to water, the sugar cane does not grow as expected.

### Steps to reproduce

1. Place rich soil next to water.
2. Place down sugar cane.
3. Wait.

### Mod list

		Stackable+Potions-forge-1.20.1-1.0.0.jar          |Stackable Potions             |stackablepotions              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.20-15.0.0.jar                   |TrashSlot                     |trashslot                     |15.0.0              |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		callablehorses-1.20.1-1.3.0.1.jar                 |Callable Horses               |callablehorses                |1.3.0.1             |DONE      |Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		map_atlases-1.20-5.8.3-all.jar                    |Map Atlases                   |map_atlases                   |1.20-5.8.3          |DONE      |Manifest: NOSIGNATURE
		goblintraders-forge-1.20.1-1.9.2.jar              |Goblin Traders                |goblintraders                 |1.9.2               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		immersive_aircraft-0.6.2+1.20.1-forge.jar         |Immersive Aircraft            |immersive_aircraft            |0.6.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		guiclock-1.20.1-4.2.jar                           |GUI Clock                     |guiclock                      |4.2                 |DONE      |Manifest: NOSIGNATURE
		HorseExpert-v8.0.1-1.20.1-Forge.jar               |Horse Expert                  |horseexpert                   |8.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		waystones-forge-1.20-14.0.1.jar                   |Waystones                     |waystones                     |14.0.1              |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.20.1-12.0.0.3.jar                  |Clumps                        |clumps                        |12.0.0.3            |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.2-1.20.1.jar                          |Citadel                       |citadel                       |2.4.2               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.5.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.5              |DONE      |Manifest: NOSIGNATURE
		guicompass-1.20.1-4.2.jar                         |GUI Compass                   |guicompass                    |4.2                 |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-rc.5.jar                  |MixinExtras                   |mixinextras                   |0.2.0-rc.5          |DONE      |Manifest: NOSIGNATURE
		Dungeon+Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		Corail-Spawners-1.20.1-035.jar                    |Corail Spawners               |corail_spawners               |1.20.1-035          |DONE      |Manifest: NOSIGNATURE
		catalogue-forge-1.20.1-1.7.1.jar                  |Catalogue                     |catalogue                     |1.7.1               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		balm-forge-1.20-7.0.7.jar                         |Balm                          |balm                          |7.0.7               |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.0.1.jar                  |Carry On                      |carryon                       |2.1.0.1             |DONE      |Manifest: NOSIGNATURE
		Paraglider-forge-20.1.1.jar                       |Paraglider                    |paraglider                    |20.1.1              |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.1-universal.jar                 |Forge                         |forge                         |47.2.1              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		PassthroughSigns-1.20-2.6.2.jar                   |Passthrough Signs             |passthroughsigns              |2.6.2               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.6.11.jar                   |Supplementaries               |supplementaries               |1.20-2.6.11         |DONE      |Manifest: NOSIGNATURE
		embeddium-0.1.15+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.1.15+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		athena-forge-1.20.1-3.1.1.jar                     |Athena                        |athena                        |3.1.1               |DONE      |Manifest: NOSIGNATURE
		PrettyPipes-1.15.0-all.jar                        |PrettyPipes                   |prettypipes                   |1.15.0              |DONE      |Manifest: NOSIGNATURE
		corpse-1.20.1-1.0.5.jar                           |Corpse                        |corpse                        |1.20.1-1.0.5        |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.8.46-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.8.46         |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.20-2.25.jar                 |Mouse Tweaks                  |mousetweaks                   |2.25                |DONE      |Manifest: NOSIGNATURE
		Female-Gender-Mod-forge-1.20.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.20.1-3.0.1        |DONE      |Manifest: NOSIGNATURE
		silent-lib-1.20.1-8.0.0.jar                       |Silent Lib                    |silentlib                     |8.0.0               |DONE      |Manifest: NOSIGNATURE
		ironfurnaces-1.20-3.9.0.jar                       |Iron Furnaces                 |ironfurnaces                  |3.9.0               |DONE      |Manifest: NOSIGNATURE
		silent-gear-1.20.1-3.5.1.jar                      |Silent Gear                   |silentgear                    |3.5.1               |DONE      |Manifest: NOSIGNATURE
		cleanswing-1.20-1.3.jar                           |Clean Swing Through Grass     |cleanswing                    |1.20-1.3            |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.13.13+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.13+1.20.1      |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.14-forge-mc1.20.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.14              |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		simplybackpacks-1.20.1-2.1.5-build.51.jar         |Simply Backpacks              |simplybackpacks               |1.20.1-2.1.5-build.5|DONE      |Manifest: NOSIGNATURE
		portablemobs-1.2.0-forge-mc1.20.jar               |Portable Mobs                 |portablemobs                  |1.2.0               |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.2.0-beta.3+1.20.1.jar              |Curios API                    |curios                        |5.2.0-beta.3+1.20.1 |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.9.jar                         |Oculus                        |oculus                        |1.6.9               |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-6.65.jar                        |Collective                    |collective                    |6.65                |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.49.0+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.0+1.20.1       |DONE      |Manifest: NOSIGNATURE
		nocube's_villagers_sell_animals_1.2.1_forge_1.20.1|Villagers Sell Animals (by NoC|villagersellanimals           |1.2.1               |DONE      |Manifest: NOSIGNATURE
		expandedstorage-10.0.0-beta.3+1.20-forge.jar      |Expanded Storage              |expandedstorage               |10.0.0-beta.3       |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.10.jar            |Resourceful Lib               |resourcefullib                |2.1.10              |DONE      |Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.20.jar                      |Ocean's Delight               |oceansdelight                 |1.0.2-1.20          |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.0.24-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.0.24              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		charmofundying-forge-6.4.2+1.20.1.jar             |Charm of Undying              |charmofundying                |6.4.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		FallingTree-1.20.1-5.0.0b1.jar                    |FallingTree                   |fallingtree                   |5.0.0b1             |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		heartstone-1.20-1.2.2.jar                         |Heartstone                    |heartstone                    |1.20-1.2.2          |DONE      |Manifest: NOSIGNATURE
		furnacerecycle-1.20.1-2.0.jar                     |Furnace Recycle               |furnacerecycle                |2.0                 |DONE      |Manifest: NOSIGNATURE
		Disenchanting-forge-1.20.1-2.2.4.jar              |Disenchanting                 |disenchanting                 |2.2.3               |DONE      |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.20.1-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.20.1-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		xptome-1.20.1-2.1.8.jar                           |XP Tome                       |xpbook                        |2.1.8               |DONE      |Manifest: NOSIGNATURE

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by MythrilBagels** [comment]
did you close the issue because you figured it out or...?

**Comment by ghost** [comment]
> did you close the issue because you figured it out or...?

No, I didn't figure it out. I thought it wasn't working because bone meal does not work on sugar cane in java. I had looked that up. They are growing, albeit slowly. The rich soil seems to have no effect.

**Comment by vectorwing** [comment]
Rich Soil works by applying infinite Bone Meal to the plant above, at slow chances and intervals.
Since Sugar Cane doesn't accept Bone Meal, Rich Soil has no effect on it. ^^
