### ISSUE TITLE
Crafting Recipes broken 

### ISSUE THREAD

**Issue by A-0-K** [vectorwing/FarmersDelight#825]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.43

### Description

When i try to craft certain things, the crafting doesn't work, and the product doesn't show. Also, for certain recipes on the pot, the item used don't always work, for example the raw beef doesn't craft dumplings, but the chicken does. I've attached two screen recordings.

https://github.com/vectorwing/FarmersDelight/assets/49211388/b8744e9b-8637-4e9a-bd40-2ed92e54ba87

https://github.com/vectorwing/FarmersDelight/assets/49211388/2fcb570a-8449-4e57-ad89-0380ce5a9ca0

### Steps to reproduce

In a pot, go to the dumplings recipe with the recipe book
In a crafting table, try crafting a stuffed potato

### Mod list

i will attach a screenshot of them
![image_2023-10-11_212017117](https://github.com/vectorwing/FarmersDelight/assets/49211388/8ef2e70f-a7a3-4be3-bb2e-97dbe512b53f)

### Logs

i dont think the logs matter.

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by Aceplante** [comment]
try turning off the "show only craftable button" to see if the recipe is even there. Second, you can use jei to view recipes in case it perhaps changed. Third, you can run with the log open to see if the recipe fails to load.

**Comment by vectorwing** [comment]
It seems that the mod **Butcher's Delight** is breaking some of the meat tags in the `forge` namespace, due to missing item references. Please forward this bug to BD's developer, or try updating the mod to its latest versions.
