### ISSUE TITLE
A way to add our own recipe categories?

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#826]
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.3

### Forge version

40.2.9

### Description

There should be a deserts recipe tab, or at least a way to add our own tabs?

**Comment by edgarogh** [comment]
A deserts tab where? What categories are you talking about? Please provide screenshots.

**Comment by Aceplante** [comment]
I'm saying there should be a tab for deserts in your pot. Currently there is Meals and Misc I believe?

**Comment by edgarogh** [comment]
I don't understand what you're sayings. There are no tabs in the cooking pot GUI. You just put ingredients and it cooks... And what's "Meals and Misc"? Is that a mod?

Also, by the looks of the dozens of issues you open on mod repos, [you're](https://github.com/VazkiiMods/Quark/issues/4342) a [homophobic bigot](https://github.com/VazkiiMods/Quark/issues/4378), so I won't try to help you further anyways.

**Note: I'm not affiliated with Farmer's Delight**, just trying to help them. Not you, though.

**Comment by Aceplante** [comment]
To clarify, I am referring to the tabs on the side of the pot. Here is a screenshot for reference. There is currently "meals", "drinks", and "misc". I am suggesting there should definitely be a deserts one, since a lot of FD addons add deserts.
![mealsandmisc](https://github.com/vectorwing/FarmersDelight/assets/101857505/3e79e2af-1ada-4199-bc84-7fb991602853)

Second, no I do not support the lgbt. Never have and do not plan to, since, as a Christian, I know it to be morally wrong. Not sure how not supporting them makes me "homophobic", and as for "bigot": according to google it means "One who is strongly partial to one's own group, religion, race, or politics and is intolerant of those who differ." which also does not fit me, depending on what you consider "tolerance". Unfortunately, everyone is entitled to their own life choices, whatever they may be. All I can do it call you out on it, which you can certainly ignore if you wish, but please do not mistake my respect for you as a fellow human being and acknowledgement of your ability to make your life choices as tolerance or support for them.

...but how is any of that relevant to this conversation? I find it odd that you would go to my profile and search through my post history then get upset at something you sought out. Your response seems unnecessarily rude. I hope the actual creator of Farmer's Delight then is willing to listen to feedback.

**Comment by edgarogh** [comment]
The screenshot makes the issue much clearer. Thank you for that. I didn't realize you were talking about the recipe book.

<details>
<summary>regarding the rest of the message</summary>

> ...but how is any of that relevant to this conversation

Because this is literally insulting to me. I wanted to help you, but I'm part of the people you hate for dumb reasons, even though I never did anything reprehensible to anyone in that regards. You're using stupid religious standards to consider yourself morally superior to others ("I know it to be morally wrong"). That's not a civil way to act in public in places where people are literally doing free work out of passion.

> I find it odd that you would go to my profile

I didn't specifically. I browse a lot of Minecraft mod issue sections to find issues I can help modders with, and I happen to have seen your name recently in the Quark repo and remembered about it. It's not my problem if you expose your middle-ages hateful ideas publicly online.

Now, **this is not the place to "debate" about that**. I told you that I wouldn't help you, there's no debate to be had here.

Keep your issue open, receive help from someone else, that's completely fine to me. sincerely. Just consider my involvement done.

</details>

**Comment by Aceplante** [comment]
> Because this is literally insulting to me. I wanted to help you, but I'm part of the people you hate for dumb reasons, even though I never did anything reprehensible to anyone in that regards. You're using stupid religious standards to consider yourself morally superior to others ("I know it to be morally wrong").

In case it was not clear in my first message, I respect you as a fellow human, and your right to make your own life choices. I do not hate you for it, so I am not sure where you got that impression, unless any disagreement is hate to you? As for me supposedly considering myself to be "morally superior", I never said that. In reference to those other issues you linked, I was simply asking for a way to disable them, becuase some of us dont want political propaganda/modern issues in our fun block game where we go to escape all that.

> That's not a civil way to act in public in places where people are literally doing free work out of passion.

I mean I'm not the one that brought up this completely unrelated topic. And I respect the work of modders regardless of what their views may be. In the case of farmers delight for example, I just want to say that I consider it to be the best Minecraft mod BY FAR. It fits the game so perfectly, and whenever Minecraft does a farming/food update, I would want it to be exactly like this! Amazing texture work, and attention to game balance/detail.

> I didn't specifically. I browse a lot of Minecraft mod issue sections to find issues I can help modders with, and I happen to have seen your name recently in the Quark repo and remembered about it. It's not my problem if you expose your middle-ages hateful ideas publicly online.

lol so asking for a toggle/how to disable it is hateful/middle aged? Again, I do not hate you as a person for your choices. I simply disagree. Now if you consider that hate, that's another issue entirely.

> Now, **this is not the place to "debate" about that**. I told you that I wouldn't help you, there's no debate to be had here.

I agree, but just wanted to clarify on my intent. To recap, it is not out of hate, I simply wish to keep my distance and not involve myself in that.

> Keep your issue open, receive help from someone else, that's completely fine to me. sincerely. Just consider my involvement done.

fair enough, thanks for your useful contributions to this thread

**Comment by WaterOre** [comment]
Data driven recipe tabs are not supported by default in Minecraft's recipe book, unfortunately including any mods which directly extend its capabilities like Farmer's Delight. There might be an external mod available on Curseforge or Modrinth that does this, but at the moment custom recipe tabs is outside the scope of Farmer's Delight.

**Comment by Aceplante** [comment]
Perhaps at least add a deserts one then, just like the other two. It doesnt have to support adding more, but I think a deserts one would be highly used by a lot of mods

**Comment by vectorwing** [comment]
I can consider adding a Sweets tab sometime, but yeah, I cannot actually expose recipe book tabs to datagen. Sorry!
