### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by CosmicGlowsticks** [vectorwing/FarmersDelight#833]
### Minecraft version

1.20.1

### Farmer's Delight version

Any

### Forge version

47.2.0, 47.2.1

### Description

The game crashes while forge is loading. 
After doing some digging, it seems Supplementaries is the issue. Unfortunately, I can't read crash reports. 
Noteable: On minimal instance, a crash report didn't even generate. It only generates when other mods are in there, but won't crash without supplementaries.

I am posting an issue on both mods.

### Steps to reproduce

1. Have supplementaries in mods folder
2. Launch game 

### Mod list

![image](https://github.com/vectorwing/FarmersDelight/assets/43255768/55b8ac63-dae8-4560-80a1-c08df7da7b09)

### Logs

https://pastebin.com/xte2e7sZ
47.2.0 ^^

https://pastebin.com/5dzuzFk0
47.2.1^^^

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by edgarogh** [comment]
The crash log says: `Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.mehvahdjukaar.moonlight.api.client.util.ColorUtil`, so it has to do with Supplementaries.
Also, Farmer's Delight is never ever mentioned in the crash log.

**Comment by vectorwing** [comment]
Hmm, yeah, this doesn't seem to be related to FD at all. In fact, neither of your logs, nor your mod list, seems to include Farmer's Delight on them.

Seems like a Supplementaries issue. I suggest posting this on their issue board, if it persists.
