### ISSUE TITLE
Rope gets destroyed when harvesting Tomatoes

### ISSUE THREAD

**Issue by Leichenengel** [vectorwing/FarmersDelight#837]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.43

### Description

Hello there :)

I'm not sure if it's a bug or a wanted feature, but I noticed, that ropes over tomatoes get destroyed when right-click harvesting them (no matter if with or without knife). By destroyed I mean, that the blocks of the tomato vines stay, but the rope completely vanishes not even leaving an item drop behind and as soon as I harvest the next plant the grown vines also get destroyed.

I have my tomato farm set up as follows:

A slim rectangle of logs in the ground containing 1xfield length rich soil farmland plus some spots where I put water so it can apply the bonemeal effect. I set up fence posts at the beginning and end of the field 4 blocks high with "overhangs" connecting them. the ropes for each plant hang down from there. There is no block of space between the plants, so the ropes connect creating a loosely webbed structure that vanishes as soon as the vines grow.

When I harvest a grown vine and then harvest the next vine of the connecting rope block both ropes disappear and at least one of the grown vine blocks gets destroyed. If not immediately the vine block that survives gets destroyed with the next harvest.

The order of harvesting tomatoes I use:

Tried different ones. as long as it's only a bush without vines harvesting them with or without knife works fine. As soon as I grow vines with one or two ropes the issue described happens. When I start with the upper vine the rope disappears, when I harvest the middle vine both vines get destroyed including the ropes used. When I harvest the bottom bush at first both upper vines get destroyed dropping the tomatoes but no rope item.

Also I don't receive credit for the Advancement for using ropes to grow tomatoes taller.

Thank for taking a look (or providing me with missing info ^^)

Best regards,

Rike

### Steps to reproduce

Well...

- plant tomatoes on rich soil farmland and build the setup I described (also works when you only place the ropes without the fences...produced the same 'issue')
- harvest tomatoes by left clicking the vines or the bottom bush with/without a knife

### Mod list

        - ametrin 0.1.2
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.1.12
	- automaticdoors 4.4
	- badpackets 0.4.3
	- biggerstacks 1.20.1-0.0.3
	- block_variants 5.0
	- butchersdelight 1.20.12.0.8
	- butchersdelightfoods 1.20.11.0.2
	- climbladdersfast 4.0-1.20.1
	- cloth_config 11.1.106
	- collective 6.66
	- connectedglass 1.1.8
	- crabbersdelight 1.1.2
	- create 0.5.1.f
	- create_sa 2.0.4.
	- denseores 1.2.1
	- doubledoors 5.0
	- duckling 3.0.0
	- easyanvils 8.0.1
	- endersdelight 1.0.3
	- everycomp 1.20-2.6.16
	- extended_villager_trades 2.0
	- farmersdelight 1.20.1-1.2.3
	- ferritecore 6.0.1
	- fishermens_trap 2.1.1
	- flywheel 0.6.10-7
	- forge 47.1.43
	- funnybagelmod 1.0.0-1.20.1
	- geckolib 4.2.4
	- geophilic 2.0.0-mc1.20u1.20.1
	- hardernaturalhealing 46.1.13
	- heyberryshutup 1.20.1-2.0.4
	- hoetweaks 3.2
	- incendium 5.3.3
	- jei 15.2.0.27
	- keepmysoiltilled 2.0
	- leavemybarsalone 8.0.0
	- mcwbridges 2.1.1
	- mcwdoors 1.1.0
	- mcwfurnitures 3.2.0
	- mcwpaintings 1.0.4
	- minecraft 1.20.1
	- mixinextras 0.2.0-rc.3
	- mobneutralizer 1.20.1-v1
	- modernfix 5.9.2+mc1.20.1
	- moonlight 1.20-2.8.60
	- mooshroomtweaks 3.2
	- naturals 1.0.0
	- nethersdelight 1.20.1-4.0
	- packedup 1.0.30-dev
	- phantomslma 0.1.1
	- purified_flesh_mod 1.3.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.8
	- reclaimed_rocks 0.2-1.20.1
	- repurposed_structures 7.1.7+1.20.1-forge
	- rightclickharvest 3.2.3+1.20.1-forge
	- simplybackpacks 1.20.1-2.1.5-build.51
	- stackrefill 4.0
	- storagedrawers 12.0.2
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.15
	- terrablender 3.0.0.169
	- terralith 2.4.8
	- tramplestopper 5.0.0+mc1.20.1
	- treasuredistance 1.20-1.2
	- treeharvester 8.2
	- trenzalore 3.3.9
	- twigs 1.20.1-3.1.0
	- waila 8.4.0
	- wthit 8.4.0
	- xaerominimap 23.8.2

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This is caused by the **RightClickHarvest** mod, in your mod list.

Tomato Vines are already pluckable on their own, like Sweet Berries, but since they're CropBlocks, those mods override it with their own behavior, often breaking the crop and replanting it from scratch. Despite my best efforts to prevent that, many of them still manage to break custom crop behavior.

Check if RightClickHarvest allows you to deny-list `farmersdelight:tomatoes`, so that the mod doesn't affect it.
