### ISSUE TITLE
Expected: 763 Got: 1251

### ISSUE THREAD

**Issue by AkavaneL** [vectorwing/FarmersDelight#840]
### Minecraft version

1.16.5

### Farmer's Delight version

0.6

### Forge version

36.2.26

### Description

I'm making a server for my friends and at the time of adding the mod I've run into a lot of bugs like this.

15.11 22:10:30 [Server] main/WARN [forge/ForgeRegistry]: Registry minecraft:block: Object did not get ID it asked for. Name: farmersdelight:stove Expected: 763 Got: 1251

If I want to solve it on my own, where are the object ids housed? If I change the object id, more problems could arise when ordering the old ones?

### Steps to reproduce

1. I introduced the TombStone and SecurityCraft mods.
2. I tried them and confirmed that they worked perfectly
3. I put the mod in and it gave me this error on the console

### Mod list

tombstone-6.8.15-1.16.5.jar
[1.16.5]+SecurityCraft+v1.9.8.jar

### Logs

https://pastebin.com/cawGP4iD

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This isn't actually an error, but rather how Forge resolves ID's for newly-added mods. This will appear when you add any mod with new blocks/items to an existing world. The new mod should work fine after that.

You can safely ignore these messages, and they shouldn't appear again on world reload. 👍
