### ISSUE TITLE
Pasta with Meatballs recipe voids bowls

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [vectorwing/FarmersDelight#844]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.1

### Description

When I use the Cooking Pot to make Pasta with Meatballs, the bowl used for the Tomato Sauce is voided.

### Steps to reproduce

1. Make Tomato Sauce (in the bowl), Minced Beef, and Raw Pasta.
2. Cook up some Pasta with Meatballs.
3. The Tomato Sauce bowl is gone.

### Mod list

* Ad Astra
* AppleSkin
* Applied Cooking
* AE2
* Architectury API
* bad packets
* Balm
* Botarium
* Cooking for Blockheads
* Enchanting Infuser
* Farmer's Delight (duh)
* Fast Leaf Decay
* FTB Library
* FTB Ultimime
* Functional Storage
* Ore Cane
* Hostile Neural Networks
* I Like Wood
* JourneyMap
* JEI
* JER
* OpenBlocks Elevator
* Patchouli
* Placebo
* Portable Tanks
* Puzzles Lib
* Rebind Narrator
* Resourceful Config
* Resourceful Lib
* SebastrnLib
* SuperMartijn642's Config Lib
* SuperMartijn642's Core Lib
* Titanium
* WTHIT
* WTHIT Harvestability

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Have you checked the pot's surroundings? When ingredients have containers, they are thrown out of the pot's top face, and you must capture them using Hoppers or Baskets. Chances are your bowls have been flung to a corner next to the pot.

**Comment by a-a-GiTHuB-a-a** [comment]
Ah, that makes sense. Perhaps the bowl was flung into my inventory and I didn't notice.
