### ISSUE TITLE
Canvas Signs not working with 

### ISSUE THREAD

**Issue by mint47** [vectorwing/FarmersDelight#845]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.16

### Description

Canvas signs fail when starting the server and are bugged in game (cannot write and duplicate when placed)
I am using Arclight on Aternos which is a combination of forge and bukkit

### Steps to reproduce

Occurs on server startup
1. create an aternos server
2. select arclight as mod runner
3. install mods
4. run server
5. check log

### Mod list

Farmer's Delight
Alex's Mobs

### Logs

<html>
<body>

[03Dec2023 01:38:45.821] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class vectorwing/farmersdelight/client/renderer/CanvasSignRenderer for invalid dist DEDICATED_SERVER
--
31 | [03Dec2023 01:38:45.826] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/client/renderer/CanvasSignRenderer (java.lang.RuntimeException: Attempted to load class vectorwing/farmersdelight/client/renderer/CanvasSignRenderer for invalid dist DEDICATED_SERVER)
32 | [03Dec2023 01:38:50.301] [main/ERROR] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class vectorwing/farmersdelight/client/renderer/CanvasSignRenderer for invalid dist DEDICATED_SERVER
33 | [03Dec2023 01:38:50.304] [main/WARN] [mixin/]: Error loading class: vectorwing/farmersdelight/client/renderer/CanvasSignRenderer (java.lang.RuntimeException: Attempted to load class vectorwing/farmersdelight/client/renderer/CanvasSignRenderer for invalid dist DEDICATED_SERVER)
34 | [03Dec2023 01:38:50.307] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/blockentity/SignRenderer (java.lang.ClassNotFoundException: net.minecraft.client.renderer.blockentity.SignRenderer)
35 | [03Dec2023 01:38:50.307] [main/ERROR] [mixin/]: Cannot invoke "org.spongepowered.asm.mixin.transformer.ClassInfo.isMixin()" because "superClass" is null

</body>
</html>

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by TelepathicGrunt** [comment]
Is that your complete mod list? Do you have the full latest.log file with the error?

**Comment by vectorwing** [comment]
Arclight uses a custom implementation of Forge and Bukkit, which are known to conflict with mods, so I'm unable to support it.

You should try and report this issue to the Arclight issues board, as they may have a better idea of what's going on, or if they're able to support modded signs.
