### ISSUE TITLE
Game crashes when cooking and cutting

### ISSUE THREAD

**Issue by Nova-Ozuka** [vectorwing/FarmersDelight#846]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.0

### Description

crash happens when cooking pot finishes cooking something or while using cutting board. 

### Steps to reproduce

steps to reproduce cooking pot crash:
literally just put any recipe in
wait for food to finish cooking

steps to reproduce cutting board crash:
place raw chicken (other food items will like work as well) on cutting board
cut with knife

### Mod list

client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		xaeros_waystones_compability-1.0.jar              |Xaero's Map - Waystones Compab|w2w2                          |1.0                 |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.0.169.jar           |TerraBlender                  |terrablender                  |3.0.0.169           |DONE      |Manifest: NOSIGNATURE
		cobblemonintegrations-1.20.1-1.0.3.jar            |Cobblemon Integrations        |cobblemonintegrations         |1.0.3               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.598.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.598          |DONE      |Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.6.3.jar                      |Jade                          |jade                          |11.6.3              |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		hearth_and_home-forge-1.20.1-2.0.1.jar            |Hearth & Home                 |hearth_and_home               |1.20.1-2.0.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.107.496.jar          |Sophisticated Core            |sophisticatedcore             |0.5.107.496         |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.4.3+1.20.1.jar                     |Curios API                    |curios                        |5.4.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-81-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-81-FORGE     |DONE      |Manifest: NOSIGNATURE
		cobblemon-counter-1.4-forge-1.2.0.jar             |Cobblemon Counter             |cobbled_counter               |1.4-forge-1.2.0     |DONE      |Manifest: NOSIGNATURE
		cobblemon-capturexp-1.4-forge-1.0.1.jar           |Cobblemon Capture XP          |capture_xp                    |1.4-forge-1.0.1     |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.8.4_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.8.4              |DONE      |Manifest: NOSIGNATURE
		waystones-forge-1.20-14.0.2.jar                   |Waystones                     |waystones                     |14.0.2              |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar     |ForgeEndertech                |forgeendertech                |11.1.0.0            |DONE      |Manifest: NOSIGNATURE
		AdFinders-1.20.1-9.1.1.0-build.0270.jar           |Advanced Finders              |adfinders                     |9.1.1.0             |DONE      |Manifest: NOSIGNATURE
		pet-your-cobblemon-1.0.0.jar                      |Pet Your Cobblemon            |petyourcobblemon              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		pmmo_farmers_compat-1.20.1-1.0.2.jar              |PMMO Farmers Delight Compat   |pmmo_farmers_compat           |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
		Cobblepedia-Forge-0.5.0.jar                       |Cobblepedia                   |cobblepedia                   |0.5.0               |DONE      |Manifest: NOSIGNATURE
		Cobblemon+O'+Plenty+1.20.1+B.1.0.jar              |Cobblemon O' Plenty           |tmtcop                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		fightorflight-forge-0.5.3.jar                     |Cobblemon Fight or Flight     |fightorflight                 |0.5.0               |DONE      |Manifest: NOSIGNATURE
		cobblemonoutbreaks-1.1.4-1.20.1.jar               |Cobblemon Outbreaks           |cobblemonoutbreaks            |1.1.4-1.20.1        |DONE      |Manifest: NOSIGNATURE
		kffmod-4.6.2.jar                                  |Kotlin For Forge              |kotlinforforge                |4.6.2               |DONE      |Manifest: NOSIGNATURE
		Cobblemon-forge-1.4.0+1.20.1.jar                  |Cobblemon                     |cobblemon                     |1.4.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.18.68.952.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |3.18.68.952         |DONE      |Manifest: NOSIGNATURE
		Tomtaru's+Cobblemon++Farmer's+Delight+Tweaks+-+1.2|Tomtaru's Cobblemon & Farmer's|tmtcd                         |0.0.2               |DONE      |Manifest: NOSIGNATURE
		ironbookshelves-1.20.1-1.2.3-forge.jar            |Iron Bookshelves              |ironbookshelves               |1.20.1-1.2.3-forge  |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.12-forge.jar                     |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		cobblemon-spawn-notification-1.4-forge-1.0.1.jar  |Cobblemon Spawn Notification  |spawn_notification            |1.4-forge-1.0.0     |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.1.4.jar                       |Balm                          |balm                          |7.1.4               |DONE      |Manifest: NOSIGNATURE
		cobblemon-unimplemented-items-1.4-forge-1.1.0.jar |Unimplemented Items           |unimplemented_items           |1.4-forge-1.1.0     |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.1.9-1.20.1-Forge.jar                |Puzzles Lib                   |puzzleslib                    |8.1.9               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Paraglider-forge-20.1.1.jar                       |Paraglider                    |paraglider                    |20.1.1              |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.106-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.106            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v8.0.2-1.20.1-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |8.0.2               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		CobblemonUpdatedEnhanced-1.20.1-0.0.6.jar         |Cobblemon Updated Enhanced    |cobblemonupdatedenhanced      |1.20.1-0.0.6        |DONE      |Manifest: NOSIGNATURE
		Essential (forge_1.20.1).jar                      |Essential                     |essential                     |1.2.3.1+g169bd9af6a |DONE      |Manifest: NOSIGNATURE

### Logs

[crash-2023-12-03_17.21.30-client.txt](https://github.com/vectorwing/FarmersDelight/files/13540574/crash-2023-12-03_17.21.30-client.txt)
[crash-2023-12-03_17.36.21-server.txt](https://github.com/vectorwing/FarmersDelight/files/13540575/crash-2023-12-03_17.36.21-server.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by edgarogh** [comment]
The problem is caused by Project MMO. Uninstall it and check if it happens again.

The first lines of the stack trace are
```
java.lang.NoClassDefFoundError: harmonised/pmmo/api/events/FurnaceBurnEvent
	at vectorwing.farmersdelight.common.block.entity.CookingPotBlockEntity.postEvent(CookingPotBlockEntity.java:639) ~[FarmersDelight-1.20.1-1.2.3.jar%23215!/:1.20.1-1.2.3] {re:mixin,re:classloading,pl:mixin:APP:pmmo_farmers_compat.mixins.json:CookingPotProcessCookingMixin,pl:mixin:A}
```
but `CookingPotBlockEntity.java` doesn't have any `postEvent` method, and no reference to `harmonised/pmmo/api/events/FurnaceBurnEvent` either. Also, it clearly shows that a "`pmmo_farmers_compat`" mixin is currently patching the class.

**Comment by vectorwing** [comment]
Yes, there is a Project MMO addon inserting mixins into FD's Cooking Pot and Cutting Board, which seems to be causing those crashes. FD does not currently have any explicit integrations with Project MMO.

I suggest forwarding this to the add-on's creator, or to Project MMO's issues board.
