### ISSUE TITLE
Knife Tag Missing

### ISSUE THREAD

**Issue by Creeperman2000** [vectorwing/FarmersDelight#849]
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.3

### Forge version

40.2.14

### Description

When I try to use the knife (from this mod) on the cutting board, it says that the knife is the wrong kind of tool.

### Mod list

		grappling_hook_mod-1.18.2-v13.jar                 |Grappling Hook Mod            |grapplemod                    |1.18.2-v13          |DONE      |Manifest: NOSIGNATURE
		TreeChop-forge-1.18.2-0.17.7.jar                  |HT's TreeChop                 |treechop                      |0.17.7              |DONE      |Manifest: NOSIGNATURE
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar        |YUNG's Better Dungeons        |betterdungeons                |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		EasyAnvils-v3.0.0-1.18.2-Forge.jar                |Easy Anvils                   |easyanvils                    |3.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		supermartijn642configlib-1.1.8-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar       |YUNG's Better Witch Huts      |betterwitchhuts               |1.18.2-Forge-1.0.1  |DONE      |Manifest: NOSIGNATURE
		[Forge 1.18.2] Dense Ores Reborn v3.2.jar         |Dense Ores Reborn             |denseoresreborn               |3.2                 |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-1.0.2+1.18.jar         |Player Animator               |playeranimator                |1.0.2+1.18          |DONE      |Manifest: NOSIGNATURE
		nether-s-exoticism-1.18.2-1.2.6.jar               |Nether's Exoticism            |nethers_exoticism             |1.2.6               |DONE      |Manifest: NOSIGNATURE
		nether-s-cruelty-1.18.2-1.0.2-AFTER.jar           |Nether's Cruelty              |sweetys_nethers_cruelty       |1.0.2               |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.2-2.5.11.jar                    |Doggy Talents 2               |doggytalents                  |2.5.11              |DONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar  |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.18.2-Forge-1.0.3  |DONE      |Manifest: NOSIGNATURE
		stalwart-dungeons-1.18.2-1.2.8.jar                |Stalwart Dungeons             |stalwart_dungeons             |1.2.8               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.106.502.jar          |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.106.502  |DONE      |Manifest: NOSIGNATURE
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |DONE      |Manifest: NOSIGNATURE
		piglinproliferation-1.0.0.jar                     |Piglin Proliferation          |piglinproliferation           |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+23.jar               |Controlling                   |controlling                   |9.0+23              |DONE      |Manifest: NOSIGNATURE
		Prism-1.18.2-1.0.1.jar                            |Prism                         |prism                         |1.0.1               |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.18.2-Forge-2.2.9.jar                   |YUNG's API                    |yungsapi                      |1.18.2-Forge-2.2.9  |DONE      |Manifest: NOSIGNATURE
		nocube's_farmers_compats_1.0.0_Forge_1.18.2.jar   |Farmer's Compats (by NoCube)  |nocubes_farmer_compats        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.3.56.jar                |Bookshelf                     |bookshelf                     |13.3.56             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.18.2-3.19.1.959.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.19.1.959   |DONE      |Manifest: NOSIGNATURE
		hammers_1.18.2-1.9.jar                            |Hammers!                      |hammers                       |1.18.21.9           |DONE      |Manifest: NOSIGNATURE
		balm-3.2.6.jar                                    |Balm                          |balm                          |3.2.6               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |DONE      |Manifest: NOSIGNATURE
		ShieldExpansion-1.18.2-1.1.7.jar                  |Shield Expansion              |shieldexp                     |1.1.7               |DONE      |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar|YUNG's Better Nether Fortresse|betterfortresses              |1.18.2-Forge-1.0.0  |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.5.102-forge.jar                    |Cloth Config v4 API           |cloth_config                  |6.5.102             |DONE      |Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.18.2-4.1.1494-universal.jar      |The Twilight Forest           |twilightforest                |4.1.1494            |DONE      |Manifest: NOSIGNATURE
		durabilitytooltip-1.1.5-forge-mc1.18.jar          |Durability Tooltip            |durabilitytooltip             |1.1.5               |DONE      |Manifest: NOSIGNATURE
		AdvancementPlaques-1.18.2-1.4.5.1.jar             |Advancement Plaques           |advancementplaques            |1.4.5.1             |DONE      |Manifest: NOSIGNATURE
		MoreBows-1.0.12+1.18.x.forge.jar                  |More Bows Restrung            |morebows                      |1.0.12              |DONE      |Manifest: NOSIGNATURE
		simpleshops-1.2.1.jar                             |Simple Shops                  |simpleshops                   |1.1.4               |DONE      |Manifest: NOSIGNATURE
		endrem_forge-5.2.0-R-1.18.2.jar                   |End Remastered                |endrem                        |5.2.0-R-1.18.2      |DONE      |Manifest: NOSIGNATURE
		UnusualEnd1.18.2_V1.4.3.jar                       |Unusual End                   |unusualend                    |1.4.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_[Forge]1.18.2_1.17.jar              |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		CNB-1.18.2-1.5.3.jar                              |Creatures and Beasts          |cnb                           |1.5.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.9.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.9.1      |DONE      |Manifest: NOSIGNATURE
		rotten_pilins_1.18_first_alpha.jar                |rotten_piglins                |rotten_piglins                |0.1.0               |DONE      |Manifest: NOSIGNATURE
		realmrpg_seadwellers_2.9.9_forge_1.18.2.jar       |Realm RPG: Sea Dwellers       |seadwellers                   |2.9.9               |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.18.2-Forge-2.1.0.jar                |YUNG's Extras                 |yungsextras                   |1.18.2-Forge-2.1.0  |DONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.18.2-1.9.0.jar          |Better Third Person           |betterthirdperson             |1.9.0               |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.18.2-Forge-2.1.1  |DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge.jar                    |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		curiouselytra-forge-1.18.1-5.0.1.0.jar            |Curious Elytra                |curiouselytra                 |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.18.2-Forge-1.0.jar         |YUNG's Better End Island      |betterendisland               |1.18.2-Forge-1.0    |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.18.2-0.4.3.jar                  |Framework                     |framework                     |0.4.3               |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar        |YUNG's Better Mineshafts      |bettermineshafts              |1.18.2-Forge-2.2    |DONE      |Manifest: NOSIGNATURE
		EnchantingInfuser-v3.3.3-1.18.2-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |3.3.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		DarkPaintings-Forge-1.18.2-10.0.4.jar             |DarkPaintings                 |darkpaintings                 |10.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		dreadsteel-1.18.2-1.1.6.jar                       |Dreadsteel                    |dreadsteel                    |1.18.2-1.1.6        |DONE      |Manifest: NOSIGNATURE
		mowziesmobs-1.5.32.jar                            |Mowzie's Mobs                 |mowziesmobs                   |1.5.32              |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.18-3.0.57.jar                    |GeckoLib                      |geckolib3                     |3.0.57              |DONE      |Manifest: NOSIGNATURE
		Festive_Delight_1.1_1.18.2.jar                    |Festive Delight               |festive_delight               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.18.2-11.0.3.jar                 |TrashSlot                     |trashslot                     |11.0.3              |DONE      |Manifest: NOSIGNATURE
		cgm-1.3.3-1.18.2.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.3.3               |DONE      |Manifest: NOSIGNATURE
		EasyMagic-v3.3.0-1.18.2-Forge.jar                 |Easy Magic                    |easymagic                     |3.3.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		realmrpg_imps_and_demons_0.9.0_forge_1.18.2.jar   |Realm RPG: Imps & Demons      |realmrpg_demons               |0.9.0               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1005.jar                  |Just Enough Items             |jei                           |10.2.1.1005         |DONE      |Manifest: NOSIGNATURE
		UniversalBoneMeal-v3.1.0-1.18.2-Forge.jar         |Universal Bone Meal           |universalbonemeal             |3.1.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		goblintraders-1.8.0-1.18.2.jar                    |Goblin Traders                |goblintraders                 |1.8.0               |DONE      |Manifest: NOSIGNATURE
		epicsamurai-0.0.2-1.18.2-forge.jar                |Epic Samurai                  |epicsamurai                   |0.0.2-1.18.2-forge  |DONE      |Manifest: NOSIGNATURE
		realmrpg_creep_and_crop_1.0.2_forge_1.18.2.jar    |Realm RPG: Creep & Crop       |realmrpg_creep                |1.0.2               |DONE      |Manifest: NOSIGNATURE
		gnumus_settlement_[Forge]1.18.2_v1.7.jar          |Gnumus Settlement             |gnumus                        |1.0.0               |DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.18.1-3.0.0.2.jar                   |Caelus API                    |caelus                        |1.18.1-3.0.0.2      |DONE      |Manifest: NOSIGNATURE
		Structory-1.18.2-1.0.2.jar                        |Structory                     |structory                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		journeymap-1.18.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.6.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.6      |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |DONE      |Manifest: NOSIGNATURE
		artifacts-1.18.2-4.2.2.jar                        |Artifacts                     |artifacts                     |1.18.2-4.2.2        |DONE      |Manifest: NOSIGNATURE
		configured-2.0.1-1.18.2.jar                       |Configured                    |configured                    |2.0.1               |DONE      |Manifest: NOSIGNATURE
		champions-forge-1.18.2-2.1.6.3.jar                |Champions                     |champions                     |1.18.2-2.1.6.3      |DONE      |Manifest: NOSIGNATURE
		[1.18.2-forge]-Epic-Knights-8.2.jar               |Epic Knights Mod              |magistuarmory                 |8.2                 |DONE      |Manifest: NOSIGNATURE
		curioofundying-forge-1.18-5.3.0.0.jar             |Curio of Undying              |curioofundying                |1.18-5.3.0.0        |DONE      |Manifest: NOSIGNATURE
		snuffles-1.0.2.jar                                |Snuffles                      |snuffles                      |1.0.2               |DONE      |Manifest: NOSIGNATURE
		RespawningAnimals-v3.0.1-1.18.2-Forge.jar         |Respawning Animals            |respawninganimals             |3.0.1               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		everycomp-1.18.2-1.6.6.jar                        |Every Compat                  |everycomp                     |1.18.2-1.6.6        |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar   |YUNG's Better Desert Temples  |betterdeserttemples           |1.18.2-Forge-1.3.1  |DONE      |Manifest: NOSIGNATURE
		ExplorersCompass-1.18.2-1.3.0-forge.jar           |Explorer's Compass            |explorerscompass              |1.18.2-1.3.0-forge  |DONE      |Manifest: NOSIGNATURE
		medieval_paintings-1.18.2-7.0.jar                 |Medieval Paintings            |medieval_paintings            |7.0                 |DONE      |Manifest: NOSIGNATURE
		fusion-1.1.0-forge-mc1.18.jar                     |Fusion                        |fusion                        |1.1.0               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.18.2-5.5.0.jar                        |Blueprint                     |blueprint                     |5.5.0               |DONE      |Manifest: NOSIGNATURE
		environmental-1.18.2-2.0.0.jar                    |Environmental                 |environmental                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		savage_and_ravage-1.18.2-4.0.1.jar                |Savage & Ravage               |savage_and_ravage             |4.0.1               |DONE      |Manifest: NOSIGNATURE
		woodworks-1.18.2-1.2.1.jar                        |Woodworks                     |woodworks                     |1.2.1               |DONE      |Manifest: NOSIGNATURE
		buzzier_bees-1.18.2-4.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |4.0.0               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.18.2-5.0.0.jar                       |Berry Good                    |berry_good                    |5.0.0               |DONE      |Manifest: NOSIGNATURE
		3dskinlayers-forge-1.5.2-mc1.18.2.jar             |3dSkinLayers                  |skinlayers3d                  |1.5.2               |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.14-universal.jar                |Forge                         |forge                         |40.2.14             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		neapolitan-1.18.2-3.0.0.jar                       |Neapolitan                    |neapolitan                    |3.0.0               |DONE      |Manifest: NOSIGNATURE
		selene-1.18.2-1.17.14.jar                         |Selene                        |selene                        |1.18.2-1.17.14      |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.18.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.18       |DONE      |Manifest: NOSIGNATURE
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		upgrade_aquatic-1.18.2-4.0.0.jar                  |Upgrade Aquatic               |upgrade_aquatic               |4.0.0               |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar  |EnchantmentDescriptions       |enchdesc                      |10.0.12             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		bettercombat-forge-1.6.2+1.18.2.jar               |Better Combat                 |bettercombat                  |1.6.2+1.18.2        |DONE      |Manifest: NOSIGNATURE
		combatroll-forge-1.1.5+1.18.2.jar                 |Combat Roll                   |combatroll                    |1.1.5+1.18.2        |DONE      |Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.3.1.jar                       |Jade                          |jade                          |5.3.1               |DONE      |Manifest: NOSIGNATURE
		another_furniture-forge-1.2.2-1.18.2.jar          |Another Furniture             |another_furniture             |1.2.2-1.18.2        |DONE      |Manifest: NOSIGNATURE
		Simple Weapons 1.4.5 - 1.18.2.jar                 |Simple Weapons                |simple_weapons                |1.4.5               |DONE      |Manifest: NOSIGNATURE
		rottencreatures-forge-1.18.2-1.0.0.jar            |Rotten Creatures              |rottencreatures               |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.18.2-forge-1.0.49.jar                   |Iceberg                       |iceberg                       |1.0.49              |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.18.2-1.3.1.jar                |Legendary Tooltips            |legendarytooltips             |1.3.1               |DONE      |Manifest: NOSIGNATURE
		ecologics-forge-1.18.2-1.7.11.jar                 |Ecologics                     |ecologics                     |1.7.11              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.18.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		autumnity-1.18.2-3.0.0.jar                        |Autumnity                     |autumnity                     |3.0.0               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.49.jar                   |Polymorph                     |polymorph                     |1.18.2-0.49         |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |DONE      |Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |DONE      |Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |DONE      |Manifest: NOSIGNATURE
		irons_spellbooks-1.18.2-1.1.4.3.jar               |Iron's Spells 'n Spellbooks   |irons_spellbooks              |1.18.2-1.1.4.3      |DONE      |Manifest: NOSIGNATURE
		crittersandcompanions-1.18.2-1.0.2.jar            |Critters and Companions       |crittersandcompanions         |1.18.2-1.0.2        |DONE      |Manifest: NOSIGNATURE
		BetterTridents-v3.0.0-1.18.2-Forge.jar            |Better Tridents               |bettertridents                |3.0.0               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		oceansdelight-1.0.0-1.18.2.jar                    |Ocean's Delight               |oceansdelight                 |1.0.0-1.18.2        |DONE      |Manifest: NOSIGNATURE
		nzgExpansion-1.3.2-1.18.2.jar                     |NineZero's Gun Expansion      |nzgexpansion                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		creeperoverhaul-1.3.1-forge.jar                   |Creeper Overhaul              |creeperoverhaul               |1.3.1               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18.2-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.18.2      |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.18.2-1.3.3.jar                     |Alex's Delight                |alexsdelight                  |1.3.3               |DONE      |Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.18.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		endersdelight-1.18.2-1.2.1.jar                    |Ender's Delight               |endersdelight                 |1.18.2-1.2.1        |DONE      |Manifest: NOSIGNATURE
		L_Enders Cataclysm-0.51-changed Them -1.18.2.jar  |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		iceandfire-2.1.12-1.18.2.jar                      |Ice and Fire                  |iceandfire                    |2.1.12-1.18.2       |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.18.2-2.2.0.jar                   |Nethers Delight               |nethersdelight                |2.2                 |DONE      |Manifest: NOSIGNATURE
		BrewinAndChewin-1.18.2-1.0.1.jar                  |Brewin' and Chewin'           |brewinandchewin               |1.18.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.18.2-1.3.0.jar                   |Farmer's Respite              |farmersrespite                |1.18.1-1.3.0        |DONE      |Manifest: NOSIGNATURE
		dragonseeker-1.1.1-1.18.2.jar                     |Dragonseeker                  |dragonseeker                  |1.1.1-1.18.2        |DONE      |Manifest: NOSIGNATURE
		abnormals_delight-1.18.2-3.0.2.jar                |Abnormals Delight             |abnormals_delight             |3.0.2               |DONE      |Manifest: NOSIGNATURE
		lootr-1.18.2-0.3.25.64.jar                        |Lootr                         |lootr                         |0.3.25.64           |DONE      |Manifest: NOSIGNATURE
		connectedglass-1.1.9-forge-mc1.18.jar             |Connected Glass               |connectedglass                |1.1.9               |DONE      |Manifest: NOSIGNATURE
		largemeals-1.18.2-2.0.jar                         |Large Meals                   |largemeals                    |1.18.2-2.0          |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v3.5.8-1.18.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |3.5.8               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		CrabbersDelight-1.18.2-1.1.2.jar                  |Crabber's Delight             |crabbersdelight               |1.1.2               |DONE      |Manifest: NOSIGNATURE
		expandability-6.0.0.jar                           |ExpandAbility                 |expandability                 |6.0.0               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.18.2-v2a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.18.2-v2a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		UndeadUnleashed-1.1.1-1.18.2.jar                  |Undead Unleashed              |undead_unleashed              |1.1.0               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 6fce75bd-aa88-4ceb-b727-4b3df1d13d42
	FML: 40.2
	Forge: net.minecraftforge:40.2.14

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by underscoreffyerauhfasf** [comment]
the culprit is abnormals' delight; it modifies the knife tag to work incorrectly. i'd advise removing it until there's a fix.

**Comment by vectorwing** [comment]
This bug is caused by **Farmer's Compats**, and is a long-standing bug with the add-on. I believe the add-on has been abandoned for over a year, so I suggest removing it.
