### ISSUE TITLE
Skillet cannot be waterlogged

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#851]
### Minecraft version

1.19.2

### Farmer's Delight version

latest

### Forge version

43.3.5

### Description

Title

![Skillet](https://github.com/vectorwing/FarmersDelight/assets/101857505/3d947bae-6a24-4d33-a9bf-45509d0b5f6c)

### Steps to reproduce

Place skillet underwater

### Mod list

N/a

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
I'm not sure if you *should* be able to waterlog a skillet, to be honest... the Cooking Pot has the potential excuse of being closed while cooking, but frying would not fly (fry) underwater.

I could make it waterlog, but it wouldn't function.

**Comment by Aceplante** [comment]
Exactly, I'm fine with it not frying when waterlogged, or maybe making bubbles if "hot" (aka above a heat source), but its weird that it cannot be waterlogged at all.

**Comment by vectorwing** [comment]
Implemented on commit b19e3d7.

**Comment by BarchamMal** [comment]
I like your style.
