### ISSUE TITLE
forge:milk tag is empty

### ISSUE THREAD

**Issue by EisiaDEV** [vectorwing/FarmersDelight#852]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.3

### Forge version

43.3.5

### Description

forge:milk item tag is empty. it showing as barrier in JEI, and a recipes which use tag forge:milk is unavailable.

### Steps to reproduce

1 - install JEI, and Farmer's Delight

2 - check the JEI a recipes which use item tag forge:milk.

### Mod list

maenchants-1.19.2-6.0.0.jar                       |Ma Enchants                   |maenchants                    |1.19.2-6.0.0        |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.19.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		aether-1.19.2-1.0.0-beta.2.2-forge.jar            |The Aether                    |aether                        |1.19.2-1.0.0-beta.2.|DONE      |Manifest: NOSIGNATURE
		Incendium_1.19.3_v5.1.6.jar                       |Incendium                     |incendium                     |5.1.6               |DONE      |Manifest: NOSIGNATURE
		rubidium-mc1.19.2-0.6.2c.jar                      |Rubidium                      |rubidium                      |0.6.2c              |DONE      |Manifest: NOSIGNATURE
		Prism-1.19.1-1.0.2.jar                            |Prism                         |prism                         |1.0.2               |DONE      |Manifest: NOSIGNATURE
		Placebo-1.19.2-7.3.4.jar                          |Placebo                       |placebo                       |7.3.4               |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.19.2-Forge-3.8.10.jar                  |YUNG's API                    |yungsapi                      |1.19.2-Forge-3.8.10 |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |DONE      |Manifest: NOSIGNATURE
		spawnermod-1.19.0-1.9.1+Forge.jar                 |Enhanced Mob Spawners         |spawnermod                    |1.9.1               |DONE      |Manifest: NOSIGNATURE
		toolleveling-forge-1.19.2-1.4.1.jar               |Tool Leveling                 |toolleveling                  |1.19.2-1.4.1        |DONE      |Manifest: NOSIGNATURE
		u_team_core-1.19.2-4.4.3.260.jar                  |U Team Core                   |uteamcore                     |4.4.3.260           |DONE      |Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		bygonenether-1.3.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.19.2-4.6.0.jar                       |Balm                          |balm                          |4.6.0               |DONE      |Manifest: NOSIGNATURE
		carryon-forge-1.19.2-2.1.1.22.jar                 |Carry On                      |carryon                       |2.1.1.22            |DONE      |Manifest: NOSIGNATURE
		biggerstacks-1.19.2-3.8.1-all.jar                 |Bigger Stacks                 |biggerstacks                  |1.19.2-3.8.1        |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.19.2-1.1.0.179.jar          |Just Enough Resources         |jeresources                   |1.1.0.179           |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |DONE      |Manifest: NOSIGNATURE
		ConfigurableCane-1.19.3-2.5.1.jar                 |Configurable Cane             |configurablecane              |2.5.1               |DONE      |Manifest: NOSIGNATURE
		replantingcrops-1.19.2-5.2.jar                    |Replanting Crops              |replantingcrops               |5.2                 |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		endsdelight-1.19.2-1.2.1.jar                      |End's Delight                 |ends_delight                  |1.19.2-1.2.1        |DONE      |Manifest: NOSIGNATURE
		repurposed_structures_forge-6.3.28+1.19.2.jar     |Repurposed Structures         |repurposed_structures         |6.3.28+1.19.2       |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.19.2.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		AdditionalPlacements-1.19.2-1.7.6.jar             |Additional Placements         |additionalplacements          |1.7.6               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.3.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		collective-1.19.2-7.16.jar                        |Collective                    |collective                    |7.16                |DONE      |Manifest: NOSIGNATURE
		Gobber2-Forge-1.19.2-2.7.28.jar                   |Gobber 2                      |gobber2                       |2.7.28              |DONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar     |YUNG's Better Strongholds     |betterstrongholds             |1.19.2-Forge-3.2.0  |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |DONE      |Manifest: NOSIGNATURE
		cumulus_menus-1.19.2-1.0.0-beta.1-forge.jar       |Cumulus                       |cumulus_menus                 |1.19.2-1.0.0-beta.1-|DONE      |Manifest: NOSIGNATURE
		twilightdelight-1.4.1.jar                         |Twilight's Flavor & Delight   |twilightdelight               |1.4.1               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre35-1.19.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre35         |DONE      |Manifest: NOSIGNATURE
		BetterFurnaces-1.19.2-1.1.2-forge.jar             |Better Furnaces Reforged      |betterfurnacesreforged        |1.1.2               |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.2.8a-forge-mc1.19.jar              |Chunk Loaders                 |chunkloaders                  |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		nitrogen_internals-1.19.2-0.3.0-forge.jar         |Nitrogen                      |nitrogen_internals            |1.19.2-0.3.0-forge  |DONE      |Manifest: NOSIGNATURE
		the_bumblezone_forge-6.8.3+1.19.2.jar             |The Bumblezone                |the_bumblezone                |6.8.3+1.19.2        |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.19.2-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		FallingTree-1.19.2-3.10.1.jar                     |FallingTree                   |fallingtree                   |3.10.1              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		AnvilNeverTooExpensive-1.0.jar                    |Anvil Never Too Expensive     |ante                          |1.0                 |DONE      |Manifest: NOSIGNATURE
		l2library-1.9.7.jar                               |L2 Library                    |l2library                     |1.9.7               |DONE      |Manifest: NOSIGNATURE
		infinitetrading-1.19.2-4.2.jar                    |Infinite Trading              |infinitetrading               |4.2                 |DONE      |Manifest: NOSIGNATURE
		YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar      |YUNG's Better Mineshafts      |bettermineshafts              |1.19.2-Forge-3.2.1  |DONE      |Manifest: NOSIGNATURE
		BetterModsButton-v4.2.4-1.19.2-Forge.jar          |Better Mods Button            |bettermodsbutton              |4.2.4               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		frozen_delight_1.3.2_forge_1.19.2.jar             |Frozen Delight (by NoCube)    |frozen_delight                |1.3.2               |DONE      |Manifest: NOSIGNATURE
		elytraslot-forge-6.1.1+1.19.2.jar                 |Elytra Slot                   |elytraslot                    |6.1.1+1.19.2        |DONE      |Manifest: NOSIGNATURE
		inventorysorter-22.0.0.jar                        |Simple Inventory Sorter       |inventorysorter               |22.0.0              |DONE      |Manifest: NOSIGNATURE
		clienttweaks-forge-1.19.2-8.3.0.jar               |Client Tweaks                 |clienttweaks                  |8.3.0               |DONE      |Manifest: NOSIGNATURE
		fullbrightnesstoggle-1.19.2-3.1.jar               |Full Brightness Toggle        |fullbrightnesstoggle          |3.1                 |DONE      |Manifest: NOSIGNATURE
		Fastload-Reforged-mc1.19.2-3.4.0.jar              |Fastload-Reforged             |fastload                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		trashslot-forge-1.19.2-12.1.0.jar                 |TrashSlot                     |trashslot                     |12.1.0              |DONE      |Manifest: NOSIGNATURE
		culturaldelights-1.19.2-0.15.4.jar                |Cultural Delights             |culturaldelights              |0.15.4              |DONE      |Manifest: NOSIGNATURE
		advanced-xray-forge-1.19.1-2.13.0-build.15.jar    |Advanced XRay                 |xray                          |1.19.1-2.13.0-build.|DONE      |Manifest: NOSIGNATURE
		spiderstpo-1.19.2-2.0.4.jar                       |Nyf's Spiders 2.0             |spiderstpo                    |2.0.4               |DONE      |Manifest: NOSIGNATURE
		quickstack-1.19.2-6.1.jar                         |QuickStack                    |quickstack                    |1.19.2-6.1          |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |DONE      |Manifest: NOSIGNATURE
		OldCombatMod_1.19.2.jar                           |Old Combat Mod                |old_combat_mod                |1.1                 |DONE      |Manifest: NOSIGNATURE
		tieredshulkerses-1.19.2-1.1.43.jar                |Tiered Shulkers               |tieredshulkers                |1.19.2-7.1.DEV.59fad|DONE      |Manifest: NOSIGNATURE
		caelus-forge-1.19.2-3.0.0.6.jar                   |Caelus API                    |caelus                        |1.19.2-3.0.0.6      |DONE      |Manifest: NOSIGNATURE
		enchantingcommands-1.19.2-3.1.jar                 |Enchanting Commands           |enchantingcommands            |3.1                 |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.2-9.0.0+14.jar                  |Clumps                        |clumps                        |9.0.0+14            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |DONE      |Manifest: NOSIGNATURE
		configured-2.1.1-1.19.2.jar                       |Configured                    |configured                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		BetterHurtTimer-1.19-6.5.2.9.jar                  |Better Hurt Timer             |betterhurttimer               |6.5.2.9             |DONE      |Manifest: NOSIGNATURE
		blueprint-1.19.2-6.2.0.jar                        |Blueprint                     |blueprint                     |6.2.0               |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.1.52.jar             |CraftTweaker                  |crafttweaker                  |10.1.52             |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.5-universal.jar                 |Forge                         |forge                         |43.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		TC-Redstone-1.19.2-3.1.2.jar                      |TC Redstone                   |gircredstone                  |3.1.2               |DONE      |Manifest: NOSIGNATURE
		TF_Lost_Blocks-1.19.2-1.3.3.jar                   |Twilight Forest: The Lost Bloc|tflostblocks                  |1.19.2-1.3.3        |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		JsonThings-1.19.2-0.7.15.jar                      |Json Things                   |jsonthings                    |0.7.15              |DONE      |Manifest: NOSIGNATURE
		DungeonsArise-1.19.2-2.1.56-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.56-1.19.2       |DONE      |Manifest: NOSIGNATURE
		useless-sword-1.19.2-V1.4.1.jar                   |Useless Sword                 |useless_sword                 |1.4.1               |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FactoryAPI-1.19.2-2.0-forge.jar                   |Factory API                   |factory_api                   |2.0                 |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.2-2.0.1.166.jar           |TerraBlender                  |terrablender                  |2.0.1.166           |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.2.544.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.2.544          |DONE      |Manifest: NOSIGNATURE
		healthbarplus-forge-1.19.2-1.0.1.jar              |Health Bar Plus               |healthbarplus                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Female-Gender-Mod-forge-1.19.1-3.0.1.jar          |Wildfire's Female Gender Mod  |wildfire_gender               |1.19-3.0.0          |DONE      |Manifest: NOSIGNATURE
		Jade-1.19.1-forge-8.9.2.jar                       |Jade                          |jade                          |8.9.2               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.9.4_mc1.19.2.jar            |CreativeCore                  |creativecore                  |2.9.3               |DONE      |Manifest: NOSIGNATURE
		spectrelib-forge-0.12.6+1.19.2.jar                |SpectreLib                    |spectrelib                    |0.12.6+1.19.2       |DONE      |Manifest: NOSIGNATURE
		NethersDelight-1.19-3.1.jar                       |Nether's Delight              |nethersdelight                |1.19-3.1            |DONE      |Manifest: NOSIGNATURE
		notenoughanimations-forge-1.6.2-mc1.19.2.jar      |NotEnoughAnimations Mod       |notenoughanimations           |1.6.2               |DONE      |Manifest: NOSIGNATURE
		Iceberg-1.19.2-forge-1.1.4.jar                    |Iceberg                       |iceberg                       |1.1.4               |DONE      |Manifest: NOSIGNATURE
		FarmersRespite-1.19-2.0.jar                       |Farmer's Respite              |farmersrespite                |1.19-2.0            |DONE      |Manifest: NOSIGNATURE
		LegendaryTooltips-1.19.2-forge-1.4.0.jar          |Legendary Tooltips            |legendarytooltips             |1.4.0               |DONE      |Manifest: NOSIGNATURE
		gobber_delight_2.0.0_forge_1.19.2.jar             |Gobber Delight (by NoCube)    |gobberdelight                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-0.46.5+1.19.2.jar                 |Polymorph                     |polymorph                     |0.46.5+1.19.2       |DONE      |Manifest: NOSIGNATURE
		Nullscape_1.19.3_v1.2.2.jar                       |Nullscape                     |nullscape                     |1.2.2               |DONE      |Manifest: NOSIGNATURE
		global_packs-forge-1.19.2-1.14.5_forge.jar        |Global Packs                  |globaldataandresourcepacks    |1.14.5_forge        |DONE      |Manifest: NOSIGNATURE
		oceansdelight-1.0.2-1.19.2.jar                    |Ocean's Delight               |oceansdelight                 |1.0.2-1.19.2        |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.4.1.jar                            |Alex's Delight                |alexsdelight                  |1.4.1               |DONE      |Manifest: NOSIGNATURE
		Debris-Chunk-1.19.X-0.0.5.jar                     |Debris Chunk(Raw Netherite scr|raw_netherite                 |0.0.5               |DONE      |Manifest: NOSIGNATURE
		ModernUI-Forge-1.19.2-3.9.0.2-universal.jar       |Modern UI                     |modernui                      |3.9.0.2             |DONE      |Manifest: 01:c4:52:25:b1:6e:5f:ac:fe:88:35:7e:cf:65:2f:69:1d:56:db:2b:93:f8:dd:7c:93:47:04:8c:e4:22:13:91
		Aquaculture-1.19.2-2.4.8.jar                      |Aquaculture 2                 |aquaculture                   |1.19.2-2.4.8        |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.19.2-v1a.jar              |CosmeticArmorReworked         |cosmeticarmorreworked         |1.19.2-v1a          |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by underscoreffyerauhfasf** [comment]
Your issue is caused by Frozen Delights; this is not the fault of Farmer's and should be sent to them instead.

**Comment by vectorwing** [comment]
As mentioned above, this bug is caused by the add-on **Frozen Delights**. Please forward this issue to their board. 👍
