### ISSUE TITLE
Quark 1.20.1 Is Incompatible 

### ISSUE THREAD

**Issue by Mari-Fey** [vectorwing/FarmersDelight#853]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.1.30

### Description

Quark causes crashes with farmers delights

### Steps to reproduce

Download 1.20 Quark

Run with Farmers Deslight

### Mod list

	- abverticaledition 1.0.3b
	- alexscaves 1.0.9
	- alexsmobs 1.22.7
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.1.12
	- athena 3.1.1
	- bellsandwhistles 0.4.3-1.20.x
	- buildinggadgets2 1.0.6
	- callablehorses 1.3.0.1
	- carpeted 1.20-1.4
	- cave_dweller 1.6.4
	- cfm 7.0.0-pre36
	- chipped 3.0.1
	- citadel 2.4.9
	- comforts 6.3.4+1.20.1
	- controlling 12.0.2
	- corpse 1.20.1-1.0.9
	- create 0.5.1.f
	- create_confectionery 1.1.0
	- create_deco_casing 3.1.0
	- create_dragon_lib 1.3.3
	- create_enchantment_industry 1.2.7.h
	- create_sa 2.0.4.
	- createaddition 1.20.1-1.2.1
	- createcasing 1.20.1-1.5.0-ht3
	- createdieselgenerators 1.20.1-1.2e
	- createendertransmission 2.0.6-1.20.1
	- creategoggles 0.5.5.e_hf
	- createsifter 1.20.1-1.8.1.e-22
	- ctov 3.3.6
	- curios 5.4.6+1.20.1
	- davebuildingmod 5.0
	- decorative_blocks 4.0.2
	- decorative_lgbt_wall_flags 1.2.0
	- diagonalblocks 8.0.3
	- diagonalfences 8.1.3
	- diagonalwindows 8.1.3
	- easy_villagers 1.20.1-1.0.17
	- embeddium 0.2.13+mc1.20.1
	- embeddiumplus 1.1.0
	- entity_model_features 1.1.0
	- entity_texture_features 4.6.1
	- eyesinthedarkness 1.3.10
	- fairylights 7.0.0
	- farmersdelight 1.20.1-1.2.3
	- flib 0.0.11
	- flywheel 0.6.10-7
	- forge 47.1.30
	- framedblocks 9.1.6
	- framedcompactdrawers 1.20-6.0.0
	- ftbchunks 2001.2.4
	- ftblibrary 2001.1.4
	- ftbteams 2001.1.4
	- fusion 1.1.0b
	- geckolib 4.3.1
	- iceberg 1.1.18
	- immersive_paintings 0.6.7+1.20.1
	- interiors 0.5.2
	- irisflw 1.20.1-0.2.0
	- jade 11.6.4
	- jei 15.2.0.27
	- jeresources 1.4.0.238
	- kotlinforforge 4.9.0
	- legendarytooltips 1.4.5
	- man 1.0.0
	- mcwbridges 2.1.1
	- mcwdoors 1.1.0
	- mcwfences 1.0.7
	- mcwfurnitures 3.2.1
	- mcwholidays 1.0.0
	- mcwlights 1.0.6
	- mcwpaintings 1.0.5
	- mcwpaths 1.0.3
	- mcwroofs 2.2.4b
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- minecraft 1.20.1
	- mixinextras 0.2.0-beta.6
	- mixinsquared 0.1.1
	- moonlight 1.20-2.8.67
	- moremobgriefingoptions 2.0.4
	- mousetweaks 2.25
	- naturescompass 1.20.1-1.11.2-forge
	- oculus 1.6.13
	- pehkui 3.7.11+1.20.1-forge
	- prism 1.0.5
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.11
	- railways 1.5.3+forge-mc1.20.1
	- rechiseled 1.1.5c
	- resourcefullib 2.1.19
	- rubidium 0.7.1
	- searchables 1.0.2
	- sereneseasons 9.0.0.46
	- sophisticatedbackpacks 3.19.4.978
	- sophisticatedcore 0.5.111.517
	- spectrelib 0.13.14+1.20.1
	- storagedrawers 12.0.2
	- storagenetwork 1.10.0
	- stylisheffects 8.0.0
	- supermartijn642configlib 1.1.8
	- supermartijn642corelib 1.1.16
	- supplementaries 1.20-2.7.11
	- terralith 2.4.11
	- twigs 1.20.1-3.1.0
	- visualworkbench 8.0.0
	- watching 1.9.2
	- waveycapes 1.3.2
	- wildfire_gender 1.20.1-3.0.1
	- xaerominimap 23.9.3
	- xaeroworldmap 1.37.2

### Logs

[crash-2023-12-18_09.15.07-client.txt](https://github.com/vectorwing/FarmersDelight/files/13705877/crash-2023-12-18_09.15.07-client.txt)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by FynnWaelsing** [comment]
Although the crash report above is not actually from a "minimal instance," I have confirmed that I am getting the same error on the same version of Forge on an instance with only Farmer's Delight 1.2.3 and Quark 4.0-alpha-420. It's worth noting, though, that the Quark version in question is still an alpha, and thus will undoubtedly change before the final 1.20.1 version.
[crash-2023-12-20_15.24.31-client.txt](https://github.com/vectorwing/FarmersDelight/files/13732256/crash-2023-12-20_15.24.31-client.txt)

**Comment by vectorwing** [comment]
This was a bug on Quark's side, and has been fixed a while ago in the alpha version 421.
Please update Quark 1.20.1 to the latest public beta, and it should be resolved.
