### ISSUE TITLE
bread recipe not working 1.20.1

### ISSUE THREAD

**Issue by Aceplante** [vectorwing/FarmersDelight#854]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.0

### Description

The bread recipe uses vanillas, and does not include the egg

### Mod list

Maybe n/a?

### Minimal instance

I have tested this on a minimal instance: yes

![yep](https://github.com/vectorwing/FarmersDelight/assets/101857505/6f71a0dd-cb3d-4191-877e-d66f017139d9)

### Performance and shader mods

I am using performance or shader mods: no

**Comment by MythrilBagels** [comment]
The mod does not, and never has, removed the vanilla bread recipe.

**Comment by Aceplante** [comment]
but then you can skip dough and make bread directly?

**Comment by MythrilBagels** [comment]
Yes. It's more efficient to use dough, as you get three bread for three wheat, rather than one bread for three wheat.
Vector has stated that he doesn't want to modify the base game in a way that is obtrusive, this being one such change.

**Comment by Aceplante** [comment]
ah, i suppose the conversion rate checks out. that makes sense thank you
