### ISSUE TITLE
incomplete server tags

### ISSUE THREAD

**Issue by ghost** [vectorwing/FarmersDelight#856]
### Minecraft version

1.16.5

### Farmer's Delight version

0.6.0

### Forge version

36.2.39

### Description

Incomplete server tags, disconnecting. Missing: {minecraft:item=[farmersdelight:cabbage_roll_ingredients]} when you try to re-enter the server after logging out. If you restart launcher with 1 time you can log in, but if you exit and try to log in without restarting - the error is repeated

### Steps to reproduce

when you try to re-enter the server after logging out. If you restart launcher with 1 time you can log in, but if you exit and try to log in without restarting - the error is repeated

### Mod list

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_392, BellSoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), BellSoft
	Memory: 10898227080 bytes (10393 MB) / 15569256448 bytes (14848 MB) up to 15569256448 bytes (14848 MB)
	CPUs: 16
	JVM Flags: 5 total; -XX:+DisableAttachMechanism -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -Xms14848M -Xmx14848M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.39.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.39.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.17.0
	Mod List: 
		saturn-mc1.16.5-0.0.3.jar                         |Saturn                        |saturn                        |0.0.3               |DONE      |Manifest: NOSIGNATURE
		dynamiclightsreforged-mc1.16.5_v1.0.1.jar         |Dynamic Lights Reforged       |dynamiclightsreforged         |mc1.16.5_v1.0.1     |DONE      |Manifest: NOSIGNATURE
		treechop-1.16.4-0.14.6-fixed.jar                  |HT's TreeChop                 |treechop                      |0.14.6              |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.01.16.5.jar        |Player Animator               |playeranimator                |0.4.0+1.16.5        |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.16.5forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		rubidium-0.2.11.jar                               |Rubidium                      |rubidium                      |0.2.11              |DONE      |Manifest: NOSIGNATURE
		macawsroofsbyg-1.16.5-1.7.jar                     |Macaw's Roofs - BYG           |macawsroofsbyg                |1.16.5-1.7          |DONE      |Manifest: NOSIGNATURE
		Controlling-7.0.0.29.jar                          |Controlling                   |controlling                   |7.0.0.29            |DONE      |Manifest: NOSIGNATURE
		jumpoverfences-1.16.4-1.0.1.jar                   |Jump Over Fences              |jumpoverfences                |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		farmersdelightintegrations-1.16.5-1.2.jar         |Farmer's Delight Compats      |farmersdelightintegrations    |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.33.jar                |Bookshelf                     |bookshelf                     |10.4.33             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.5-3.15.20.755.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.5-3.15.20.755  |DONE      |Manifest: NOSIGNATURE
		Wallets-1.16.5-1.0.4.jar                          |Wallets                       |wallets                       |1.0.4               |DONE      |Manifest: NOSIGNATURE
		abyg-1.2-forge.jar                                |[BYG Addon] Enhanced Vanilla B|bygvanillabiomes              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Hwyla_forge_1.10.11_B78_1.16.2.jar                |Waila                         |waila                         |1.10.11-B78_1.16.2  |DONE      |Manifest: NOSIGNATURE
		carryon-1.16.5-1.15.6.24.jar                      |Carry On                      |carryon                       |1.15.6.24           |DONE      |Manifest: NOSIGNATURE
		chat_heads-0.6.0-forge-1.16.5.jar                 |Chat Heads                    |chat_heads                    |0.6.0               |DONE      |Manifest: NOSIGNATURE
		shetiphiancore-forge-1.16.2-lts-3.8.22.jar        |ShetiPhian-Core               |shetiphiancore                |3.8.22              |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.4.jar                 |Supplementaries               |supplementaries               |0.18.2              |DONE      |Manifest: NOSIGNATURE
		tea_kettle-1.16.5-0.4.0.0.jar                     |Tea Kettle                    |tea_kettle                    |task ':jar' property|DONE      |Manifest: NOSIGNATURE
		refinedstorage-1.9.18.jar                         |Refined Storage               |refinedstorage                |1.9.18              |DONE      |Manifest: NOSIGNATURE
		Growthcraft-6.1.4-1.16.5.jar                      |Growthcraft                   |growthcraft                   |6.1.4               |DONE      |Manifest: NOSIGNATURE
		sanitydim-mc1.16-1.0.0.jar                        |Sanity: Descent Into Madness  |sanitydim                     |1.0.0               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.6.0.jar                   |Farmer's Delight              |farmersdelight                |1.16.5-0.6.0        |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v3.1.11_mc1.16.5.jar                |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		geolosys-1.16.5-6.0.2.jar                         |Geolosys                      |geolosys                      |6.0.1c_beta         |DONE      |Manifest: NOSIGNATURE
		craftablechainmail-1.16.5-1.1.0.jar               |Craftable Chainmail Armor     |craftablechainmail            |1.1.0               |DONE      |Manifest: NOSIGNATURE
		Blur-1.1.0-1.jar                                  |Blur                          |blur                          |1.1.0-1             |DONE      |Manifest: NOSIGNATURE
		letsleepingdogslie-1.16.3-1.1.1.jar               |Let Sleeping Dogs Lie         |dogslie                       |1.1.1               |DONE      |Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.16.5forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |DONE      |Manifest: NOSIGNATURE
		born_in_chaos_1.16_1.3.jar                        |Born in Chaos                 |born_in_chaos_v1              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		patchouli-1.16.4-53.2.jar                         |Patchouli                     |patchouli                     |1.16.4-53.2         |DONE      |Manifest: NOSIGNATURE
		oculus-1.2.6.jar                                  |Oculus                        |oculus                        |1.2.6               |DONE      |Manifest: NOSIGNATURE
		obfuscate-0.6.3-1.16.5.jar                        |Obfuscate                     |obfuscate                     |0.6.3               |DONE      |Manifest: NOSIGNATURE
		vehicle-mod-0.45.2-1.16.3.jar                     |MrCrayfish's Vehicle Mod      |vehicle                       |0.45.2              |DONE      |Manifest: NOSIGNATURE
		Butchersdelight+Beta+1.16+1.1.2.jar               |ButchersDelight               |butchersdelight               |1.161.1.2           |DONE      |Manifest: NOSIGNATURE
		spartanweaponry-1.16.5-2.2.0-rc-2.jar             |Spartan Weaponry              |spartanweaponry               |2.2.0 Release Candid|DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.2.4-mc1.16.5forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.2.4               |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.1-mc1.16.5forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.1               |DONE      |Manifest: NOSIGNATURE
		unnamed_delight_1.2.0_forge_1.16.5.jar            |Unnamed Delight (By NoCube)   |unnamed_delight               |1.2.0               |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |DONE      |Manifest: NOSIGNATURE
		AgriCraft+Seed+Fix+1.0.0+mc1.16.5.jar             |AgriCraft Seed Fix            |agricraftseedfix              |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Frozen_Delight_1.1.2_Forge_1.16.5.jar             |Frozen Delight (By NoCube)    |frozen_delight                |1.1.2               |DONE      |Manifest: NOSIGNATURE
		betteranimationscollection-v1.2.4-1.16.5-forge.jar|Better Animations Collection  |betteranimationscollection    |1.2.4               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		torchslabmod-1.16.4_v1.6.19.jar                   |Torch Slab Mod                |torchslabmod                  |1.6.18              |DONE      |Manifest: NOSIGNATURE
		cgm-1.2.6-1.16.5.jar                              |MrCrayfish's Gun Mod          |cgm                           |1.2.6               |DONE      |Manifest: NOSIGNATURE
		spiderstpo-1.16.4-2.0.0.jar                       |Spiders 2.0                   |spiderstpo                    |2.0.0               |DONE      |Manifest: NOSIGNATURE
		locks-1.16.5-3.0.3.jar                            |Locks                         |locks                         |3.0.3               |DONE      |Manifest: NOSIGNATURE
		abnormals_core-1.16.5-3.3.1.jar                   |Abnormals Core                |abnormals_core                |3.3.1               |DONE      |Manifest: NOSIGNATURE
		berry_good-1.16.5-4.1.2.jar                       |Berry Good                    |berry_good                    |4.1.2               |DONE      |Manifest: NOSIGNATURE
		Contact-Forge-1.16.5-0.3.5-Beta.jar               |Contact                       |contact                       |0.3.5-Beta          |DONE      |Manifest: NOSIGNATURE
		SilveroakOutpost-Forge-1.16.5-0.4.5-Alpha.jar     |Silveroak Outpost             |silveroakoutpost              |0.4.5-Alpha         |DONE      |Manifest: NOSIGNATURE
		comforts-forge-1.16.5-4.0.1.5.jar                 |Comforts                      |comforts                      |1.16.5-4.0.1.5      |DONE      |Manifest: NOSIGNATURE
		catjammies-1.1.0.jar                              |CatJammies                    |catjammies                    |NONE                |DONE      |Manifest: NOSIGNATURE
		chromatocreeper-1.16.5-1.1.jar                    |�3Chromato Creeper�r          |chromatocreeper               |1.1                 |DONE      |Manifest: NOSIGNATURE
		MyServerIsCompatible-1.16.5-1.0.jar               |MyServerIsCompatible          |myserveriscompatible          |1.0                 |DONE      |Manifest: NOSIGNATURE
		snowundertrees-1.16.5-v1.3.jar                    |Snow Under Trees              |snowundertrees                |v1.3                |DONE      |Manifest: NOSIGNATURE
		table_top_craft-1.16-1.2.1.jar                    |Table Top Craft               |table_top_craft               |1.16-1.2.1          |DONE      |Manifest: NOSIGNATURE
		catalogue-1.6.1-1.16.5.jar                        |Catalogue                     |catalogue                     |1.6.1               |DONE      |Manifest: NOSIGNATURE
		magnesium_extras-mc1.16.5_v1.4.0.jar              |Magnesium Extras              |magnesium_extras              |mc1.16.5_v1.4.0     |DONE      |Manifest: NOSIGNATURE
		3dSkinLayers-forge-1.1.0.jar                      |3dSkinLayers                  |skinlayers3d                  |1.1.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		waddles-1.16.5-0.8.13(1).jar                      |Waddles                       |waddles                       |1.16.5-0.8.13       |DONE      |Manifest: NOSIGNATURE
		WailaHarvestability-mc1.16.x-forge-1.1.15.jar     |Waila Harvestability          |wailaharvestability           |1.1.15              |DONE      |Manifest: NOSIGNATURE
		morecraftingtables1.16.5.jar                      |More Crafting Tables Mod      |mctb                          |1.16.5 - 1.0.0      |DONE      |Manifest: NOSIGNATURE
		ImmersiveFX-1.0.2-1.16.5.jar                      |�3ImmersiveFX                 |dsurround                     |4.0.5.0             |DONE      |Manifest: NOSIGNATURE
		emotecraft-for-MC1.16.5-2.2.7-b.build.47-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.47    |DONE      |Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |DONE      |Manifest: NOSIGNATURE
		universalmodcore-1.16.5-forge-1.1.3.jar           |Universal Mod Core            |universalmodcore              |1.1.3               |DONE      |Manifest: NOSIGNATURE
		sounddeviceoptions-1.4.3.jar                      |Sound Device Options          |sounddeviceoptions            |1.4.3               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		upgrade_aquatic-1.16.5-3.1.2.jar                  |Upgrade Aquatic               |upgrade_aquatic               |3.1.2               |DONE      |Manifest: NOSIGNATURE
		registrator-1.16.5-1.4.2.jar                      |Registrator                   |registrator                   |1.4.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.16.5-7.7.1.152.jar                          |Just Enough Items             |jei                           |7.7.1.152           |DONE      |Manifest: NOSIGNATURE
		invtweaks-1.16.4-1.0.1.jar                        |Inventory Tweaks Renewed      |invtweaks                     |1.16.4-1.0.1        |DONE      |Manifest: NOSIGNATURE
		radon-0.8.0a-1.16.5.jar                           |Radon                         |radon                         |0.8.0a              |DONE      |Manifest: NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |DONE      |Manifest: NOSIGNATURE
		immersiveengineering-1.16.5-5.1.0-148.jar         |Immersive Engineering         |immersiveengineering          |1.16.5-5.1.0-148    |DONE      |Manifest: NOSIGNATURE
		immersiveindustry-1.16.5-0.1.8f.jar               |Immersive Industry            |immersiveindustry             |1.16.5-0.1.8f       |DONE      |Manifest: NOSIGNATURE
		Forge-1.16-Plasmo-Voice-1.2.17.jar                |Plasmo Voice                  |plasmo_voice                  |1.2.17              |DONE      |Manifest: NOSIGNATURE
		creativecore_v2.2.1_mc1.16.5.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |Manifest: NOSIGNATURE
		smoothboot-forge-1.16.4-1.2.2.jar                 |Smooth Boot                   |smoothboot                    |1.16.4-1.2.2        |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		SpartanShields-1.16.5-2.1.2.jar                   |Spartan Shields               |spartanshields                |2.1.2               |DONE      |Manifest: NOSIGNATURE
		gravestone-1.16.5-1.0.7.jar                       |Gravestone Mod                |gravestone                    |1.16.5-1.0.7        |DONE      |Manifest: NOSIGNATURE
		mobsunscreen-1.16.5-3.0.4.jar                     |Mob Sunscreen                 |mobsunscreen                  |1.16.5-3.0.4        |DONE      |Manifest: NOSIGNATURE
		polymorph-forge-1.16.5-0.41.jar                   |Polymorph                     |polymorph                     |1.16.5-0.41         |DONE      |Manifest: NOSIGNATURE
		multibeds-forge-1.16.2-lts-1.7.20.jar             |Multi-Beds                    |multibeds                     |1.7.20              |DONE      |Manifest: NOSIGNATURE
		decentblocker-1.0.0-CLIENT(1).jar                 |DecentBanItem                 |decentbanitem                 |1.0.0               |DONE      |Manifest: NOSIGNATURE
		doubleslabs-1.16-3.7.3.jar                        |Double Slabs                  |doubleslabs                   |3.7.3               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.16.4      |DONE      |Manifest: NOSIGNATURE
		infinitylib-2.0.7.jar                             |InfinityLib                   |infinitylib                   |1.16.5-2.0.7        |DONE      |Manifest: NOSIGNATURE
		agricraft-3.0.8.jar                               |AgriCraft                     |agricraft                     |1.16.5-3.0.8        |DONE      |Manifest: NOSIGNATURE
		ferritecore-2.1.1-forge.jar                       |Ferrite Core                  |ferritecore                   |2.1.1               |DONE      |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		engineersdecor-1.16.5-forge-1.1.19.jar            |Engineer's Decor              |engineersdecor                |1.1.19              |DONE      |Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		apexcore-1.16.5-1.9.4.jar                         |ApexCore                      |apexcore                      |1.9.4               |DONE      |Manifest: NOSIGNATURE
		fantasyfurniture-1.16.5-2.0.2.jar                 |Fantasy's Furniture           |fantasyfurniture              |2.0.2               |DONE      |Manifest: NOSIGNATURE
		puzzleslib-v1.0.15-1.16.5-forge.jar               |Puzzles Lib                   |puzzleslib                    |1.0.15              |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		byg-1.3.6.jar                                     |Oh The Biomes You'll Go       |byg                           |1.3.4               |DONE      |Manifest: NOSIGNATURE
		mcwfencesbyg-1.16.5-1.2.jar                       |Macaw's Fences - BYG          |mcwfencesbyg                  |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		notreepunching-forge-1.16.5-4.3.0.jar             |No Tree Punching              |notreepunching                |4.3.0               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.16.5-2.1.22-1.16.5.jar              |Aquaculture 2                 |aquaculture                   |1.16.5-2.1.22       |DONE      |Manifest: NOSIGNATURE
		baby_delight_1.0.1_forge_1.16.5.jar               |Baby Delight (by NoCube)      |babydelight                   |1.0.1               |DONE      |Manifest: NOSIGNATURE
		mcwfurnituresbyg-1.16.5-1.2.jar                   |Macaw's Furnitures - BYG      |mcwfurnituresbyg              |1.16.5-1.2          |DONE      |Manifest: NOSIGNATURE
		refinedstorageaddons-0.7.4.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.7.4               |DONE      |Manifest: NOSIGNATURE
		CosmeticArmorReworked-1.16.5-v5.jar               |CosmeticArmorReworked         |cosmeticarmorreworked         |1.16.5-v5           |DONE      |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		drinkbeer-1.16.5-2.3.5.jar                        |Drink Beer                    |drinkbeer                     |2.3.5               |DONE      |Manifest: NOSIGNATURE

### Logs

https://mclo.gs/SCPQveu

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
You added the add-ons **Baby Delight** and **Unnamed Delight**, but forgot to add the mods these add-ons are meant to work with:
- [Baby Fat](https://www.curseforge.com/minecraft/mc-mods/baby-fat)
- [Unnamed Animal Mod](https://www.curseforge.com/minecraft/mc-mods/unnamed-animal-mod)

The add-ons cannot find the items from those mods, thus breaking tags and recipes. Adding them in your client and server should fix the issue. 👍

Also, I'm no longer offering support to FD on 1.16, only 1.19 and above. ^^
