### ISSUE TITLE
Datapack error

### ISSUE THREAD

**Issue by Dilsinho1510** [vectorwing/FarmersDelight#857]
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.3

### Forge version

40.2.14

### Description

I´m trying to add the FD to my game (1.18.2) but I´m having a datapack error even when creating a new world, nay reason or idea why?

### Steps to reproduce

Just trying to load a save or starting a new world

### Mod list

![image](https://github.com/vectorwing/FarmersDelight/assets/155014002/58387334-1485-43d4-b3e2-40069a57b8df)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by ObliviousSpartan** [comment]
Sorry about this. This is my fault. My mod Spartan Weaponry is causing this issue because Farmer's Delight is looking up Tool Actions for ingredients for some reason.
I need to add a sanity check for looking up weapon traits early to prevent this problem from happening again.

**Comment by vectorwing** [comment]
Thanks for providing context, @ObliviousSpartan!

FD adds an ingredient which verifies Forge's ToolActions to execute Cutting Board recipes. Usually, this method defaults to `false`, so it doesn't traditionally cause issues if you don't override it.

Was this bug just a missed check on your end, or is there something I could do on FD's checks to prevent these conflicts?
