### ISSUE TITLE
Farmer's Delight Recipes 

### ISSUE THREAD

**Issue by Skel200** [vectorwing/FarmersDelight#859]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.3

### Forge version

47.2.17

### Description

When using REI to view recipes, Pasta and more recipes don't exist.

### Steps to reproduce

Install the latest version with REI and see the bug.

### Mod list

Farmer's Delight, REI, Fabric Seasons , Sintra Connector.

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by ThisMasquerade** [comment]
I can confirm this issue happens on my modpack as well

**Comment by agr-97** [comment]
I can confirm that the Raw Pasta recipe is not showing up. My modpack is 1.20.1 latest mod update. No shader mods.

**Comment by vectorwing** [comment]
FD doesn't currently have explicit REI integration, so cooking and cutting recipes may not show up. I believe there are ways to make REI "import" a JEI plugin and display them, but I'm not sure how that works. I'll reply here if I recall how that's done.

**Comment by vectorwing** [comment]
Found it!
https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items-hacks

This REI add-on will read JEI plugins, and make them work with REI. This should display FD's recipes properly. 👍

**Comment by agr-97** [comment]
Thank you vectorwing we appreciate your work. Loving the mod as always.
