### ISSUE TITLE
[Suggestion]Add a knife hanger(Decoration) and others... 1.16.3

### ISSUE THREAD

**Issue by Gixuu** [vectorwing/FarmersDelight#86]
A knife hanger would be nice to add.
==========================
Can you add a little function to the stove?
*Add a coal before it starts to lit up like how furnace works
*Make the animation fire animation glow and fire particles on top of the stove.
Thanks for reading my suggestion and I hope this add in the near future : D

**Comment by vectorwing** [comment]
Sorry for ignoring this for so long! 😅

I've had more than one convo about the stove using fuel by now, and I suppose it could be some form of config, perhaps. Something like a "realistic stove" mode, where it either needs fuel, or operates faster under fuel.

Thanks for suggesting! The Stove may be retouched in the future, and I'll keep this in mind. 👍
