### ISSUE TITLE
Cooking pot behaves in a weird way.

### ISSUE THREAD

**Issue by OHOgameplay** [vectorwing/FarmersDelight#862]
### Minecraft version

1.19.2

### Farmer's Delight version

1.2.3

### Forge version

43.3.5

### Description

For example, making Cooked Rice works only if a single slot has rice. If i put rice into 2, or more, it just does not work.

This makes it impossible to automate with AE2.

I suggest an option, where you can "lock" a specific recipe to each pot, which will make the pot only accept a stack of each ingredient, and the slots, that are not used will not accept anything.
Like in this image.
![image](https://github.com/vectorwing/FarmersDelight/assets/124529188/93c75539-dc0a-4f3e-8b2d-4f3de904598e)
This way, you can automate the crafting of the items using AE2, or even just vanilla hoppers.
Later, the "locked" recipe can be changed, if the player wants to.

Another thing:
If a recipe needs 2, or 3 of the same thing (like Beetroot Soup, Tomato Sauce, Chorus Juice), allow the crafting of the item, if the needed ingredients are in the same slot.
For example, make this a valid recipe:
![image](https://github.com/vectorwing/FarmersDelight/assets/124529188/3aeee2f4-d161-4e1d-8c0f-2a84aaf7cd38)

### Mod list

BetterAnimationsCollection-v4.0.5-1.19.2-Forge.jar|Better Animations Collection  |betteranimationscollection    |4.0.5               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		FishTank-1.0.2-1.19.2-forge.jar                   |Fish Tanks                    |fish_tank                     |1.0.2               |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.8-forge-mc1.19.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.8               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.19.2-1192.3.45.jar     |QuarryPlus                    |quarryplus                    |1192.3.45           |DONE      |Manifest: ef:50:af:b3:03:e0:3e:70:a7:ef:78:77:a5:4d:d4:b5:07:ec:df:9d:d6:f3:12:13:c9:3c:cd:9a:0a:3e:6b:43
		Connectible Chains-forge-1.19.2-1.1.0.jar         |Connectible Chains            |connectiblechains             |1.0.0               |DONE      |Manifest: NOSIGNATURE
		simplemagnets-1.1.10-forge-mc1.19.jar             |Simple Magnets                |simplemagnets                 |1.1.10              |DONE      |Manifest: NOSIGNATURE
		beenfo-1.19.1-forge42.0.1-1.2.jar                 |Beenfo                        |beenfo                        |1.19.1-forge42.0.1-1|DONE      |Manifest: NOSIGNATURE
		BasicEndOres-1.19.2-3.2.2.jar                     |Basic End Ores                |beo                           |3.2.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1018.jar                  |Just Enough Items             |jei                           |11.6.0.1018         |DONE      |Manifest: NOSIGNATURE
		naturalist-forge-4.0.3-1.19.2.jar                 |Naturalist                    |naturalist                    |4.0.3               |DONE      |Manifest: NOSIGNATURE
		tesseract-1.0.35a-forge-mc1.19.jar                |Tesseract                     |tesseract                     |1.0.35a             |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.19.2-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		Strawgolem-forge-1.19.2-2.0.0-beta.4.jar          |Straw Golem                   |strawgolem                    |2.0.0-beta.4        |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.19.2-0.5.111.525.jar          |Sophisticated Core            |sophisticatedcore             |1.19.2-0.5.111.525  |DONE      |Manifest: NOSIGNATURE
		rubidium-0.6.2b.jar                               |Rubidium                      |rubidium                      |0.6.2b              |DONE      |Manifest: NOSIGNATURE
		Structory_1.19.3_v1.3.1a.jar                      |Structory                     |structory                     |1.3.1a              |DONE      |Manifest: NOSIGNATURE
		citadel-2.1.4-1.19.jar                            |Citadel                       |citadel                       |2.1.4               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.21.1.jar                              |Alex's Mobs                   |alexsmobs                     |1.21.1              |DONE      |Manifest: NOSIGNATURE
		endermanantigrief-1.0.0-1.19.jar                  |Enderman Anti Grief           |endermanantigrief             |1.0.0-1.19          |DONE      |Manifest: NOSIGNATURE
		themissingvillages-2.0.0-1.19.2.jar               |The Missing Villages          |themissingvillages            |2.0.0-1.19.2        |DONE      |Manifest: NOSIGNATURE
		BasicNetherOres-1.19.2-8.2.1.jar                  |Basic Nether Ores             |bno                           |8.2.1               |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.0-beta.9.jar                |MixinExtras                   |mixinextras                   |0.2.0-beta.9        |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.19.2-16.3.20.jar                |Bookshelf                     |bookshelf                     |16.3.20             |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.19.2-3.19.5.989.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19.2-3.19.5.989   |DONE      |Manifest: NOSIGNATURE
		mcjtylib-1.19-7.2.5.jar                           |McJtyLib                      |mcjtylib                      |1.19-7.2.5          |DONE      |Manifest: NOSIGNATURE
		rftoolsbase-1.19-4.1.7.jar                        |RFToolsBase                   |rftoolsbase                   |1.19-4.1.7          |DONE      |Manifest: NOSIGNATURE
		xnet-1.19-5.1.4.jar                               |XNet                          |xnet                          |1.19-5.1.4          |DONE      |Manifest: NOSIGNATURE
		notenoughwands-1.19-5.0.2.jar                     |Not Enough Wands              |notenoughwands                |1.19-5.0.2          |DONE      |Manifest: NOSIGNATURE
		forcecraft-1.19.2-3.3.3.jar                       |ForceCraft                    |forcecraft                    |3.3.3               |DONE      |Manifest: NOSIGNATURE
		DarkUtilities-Forge-1.19.2-13.1.9.jar             |DarkUtilities                 |darkutils                     |13.1.9              |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.3.2-1.19.2.jar                     |Bygone Nether                 |bygonenether                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.3.115-forge.jar                    |Cloth Config v8 API           |cloth_config                  |8.3.115             |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.3.5-universal.jar                 |Forge                         |forge                         |43.3.5              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		twilightforest-1.19.2-4.2.1518-universal.jar      |The Twilight Forest           |twilightforest                |4.2.1518            |DONE      |Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.19.2-2.0.6.jar           |Friends&Foes                  |friendsandfoes                |2.0.6               |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		cofh_core-1.19.2-10.3.1.48.jar                    |CoFH Core                     |cofh_core                     |10.3.1              |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_core-1.19.2-10.3.0.9.jar                  |Thermal Series                |thermal                       |10.3.0              |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_integration-1.19.2-10.3.0.19.jar          |Thermal Integration           |thermal_integration           |10.3.0              |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		industrial-foregoing-1.19.2-3.3.2.3-5.jar         |Industrial Foregoing          |industrialforegoing           |3.3.2.3             |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.19.2-1.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.19.2-1.2.3        |DONE      |Manifest: NOSIGNATURE
		panthalassa-1.3.2-1.19.2.jar                      |Panthalassa                   |panthalassa                   |1.3.2               |DONE      |Manifest: NOSIGNATURE
		morevillagers-forge-1.19-4.0.3.jar                |More Villagers                |morevillagers                 |4.0.3               |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.19-6.2.2.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.2          |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.8.jar              |Applied Energistics 2         |ae2                           |12.9.8              |DONE      |Manifest: NOSIGNATURE
		moonlight-1.19.2-2.3.6-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.3.6        |DONE      |Manifest: NOSIGNATURE
		babyfat-forge-1.19.2-1.1.2.jar                    |Baby Fat                      |babyfat                       |1.19.2-1.1.2        |DONE      |Manifest: NOSIGNATURE
		titanium-1.19.2-3.7.4-28.jar                      |Titanium                      |titanium                      |3.7.4               |DONE      |Manifest: NOSIGNATURE
		MagnumTorch-v4.2.3-1.19.2-Forge.jar               |Magnum Torch                  |magnumtorch                   |4.2.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		UnusualEnd1.19.2_V1.4.3.jar                       |Unusual End                   |unusualend                    |1.4.3               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.16-forge-mc1.19.2.jar  |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.16              |DONE      |Manifest: NOSIGNATURE
		LargeFluidTank-19.8.jar                           |FluidTank                     |fluidtank                     |19.8                |DONE      |Manifest: NOSIGNATURE
		CNB-1.19-1.5.4.jar                                |Creatures and Beasts          |cnb                           |1.5.4               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.2-5.1.4.3.jar                   |Curios API                    |curios                        |1.19.2-5.1.4.3      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |DONE      |Manifest: NOSIGNATURE
		IC2Classic-1.19.2-2.0.8.1.jar                     |IC2 Classic                   |ic2                           |1.19.2-2.0.8.1      |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.3_Forge_1.19.1.jar            |Xaero's Minimap               |xaerominimap                  |23.9.3              |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.19.2-FORGE-2.2.2.jar                  |Croptopia                     |croptopia                     |2.2.2               |DONE      |Manifest: NOSIGNATURE
		PigPen-Forge-1.19.2-11.1.2.jar                    |PigPen                        |pigpen                        |11.1.2              |DONE      |Manifest: NOSIGNATURE
		AutoRegLib-1.8.2-55.jar                           |AutoRegLib                    |autoreglib                    |1.8.2-55            |DONE      |Manifest: NOSIGNATURE
		Quark-3.4-418.jar                                 |Quark                         |quark                         |3.4-418             |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.19.2-2.4.15.jar                 |Supplementaries               |supplementaries               |1.19.2-2.4.15       |DONE      |Manifest: NOSIGNATURE
		thermal_foundation-1.19.2-10.3.1.57.jar           |Thermal Foundation            |thermal_foundation            |10.3.1              |DONE      |Manifest: NOSIGNATURE
		thermal_expansion-1.19.2-10.3.1.25.jar            |Thermal Expansion             |thermal_expansion             |10.3.1              |DONE      |Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		bettervillage-forge-1.19.2-3.2.0.jar              |Better village                |bettervillage                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		morefrogs-1.19.x-1.1.1a-forge.jar                 |More Frogs                    |morefrogs                     |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		Runelic-Forge-1.19.2-14.1.4.jar                   |Runelic                       |runelic                       |14.1.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		deeperdarker-forge-1.19.2-1.2.2.jar               |Deeper and Darker             |deeperdarker                  |1.2.2               |DONE      |Manifest: NOSIGNATURE
		cfm-7.0.0-pre35-1.19.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre35         |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.85-forge.jar                     |Architectury                  |architectury                  |6.5.85              |DONE      |Manifest: NOSIGNATURE
		mobcatcher-1.19.2-5.jar                           |Mob Catcher                   |mobcatcher                    |1.19.2-5            |DONE      |Manifest: NOSIGNATURE
		light-overlay-7.0.1-forge.jar                     |Light Overlay                 |lightoverlay                  |7.0.1               |DONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v4.4.3-1.19.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.4.3               |DONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		chunkloaders-1.2.8a-forge-mc1.19.jar              |Chunk Loaders                 |chunkloaders                  |1.2.8a              |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.19.2-2.4.8.jar                      |Aquaculture 2                 |aquaculture                   |1.19.2-2.4.8        |DONE      |Manifest: NOSIGNATURE
		FallingTree-1.19.2-3.10.1.jar                     |FallingTree                   |fallingtree                   |3.10.1              |DONE      |Manifest: 3c:8e:df:6c:df:a6:2a:9f:af:64:ea:04:9a:cf:65:92:3b:54:93:0e:96:50:b4:52:e1:13:42:18:2b:ae:40:29
		AnvilNeverTooExpensive-1.19-1.1.jar               |Anvil Never Too Expensive     |ante                          |1.1                 |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.40.jar                    |GeckoLib                      |geckolib3                     |3.1.40              |DONE      |Manifest: NOSIGNATURE

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This is a long-standing design problem, and is being addressed in an upcoming version. Chances are that the Cooking Pot will simply be updated to no longer care about the grid, and read stack sizes instead; this is being tested, and may take a while to be confirmed. 👍 

Please refer to this issue for updates, or to share suggestions/feedback: https://github.com/vectorwing/FarmersDelight/issues/26

**Comment by OHOgameplay** [comment]
If this will be implemented, will you make it to the 1.19.2 version too?
