### ISSUE TITLE
mod not showing 

### ISSUE THREAD

**Issue by Hunipudding** [vectorwing/FarmersDelight#872]
### Minecraft version

1.20.4

### Farmer's Delight version

1.20.1

### Forge version

neoforge 1.20.4 137-beta  //  forge 1.20.4 (90.0.22)

### Description

hi I'm new to downloading mods, I downloaded neoforge and tried to add Farmers Delight but for some reason it's not showing up in game? Its in the mod folder and i have a few other mods along with it but its Farmers Delight is the only one not showing up. i decided to switch to regular forge while removing every other mod and it keeps crashing. i never had a problem downloading mods until minecraft updated to 1.20.4 im so confused on what to do :(

### Mod list

NEOFORGE
-Appleskin 1.20.4
-Bookshelf 1.20.4
-Enchantment description 1.20.2
-Farmers Delight 1.20.1-1.2.4

FORGE
-Farmers Delight 1.20.1-1.2.4

### Logs

FORGE
https://mclo.gs/wy1V6gk#L21

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Hello! Sorry, but Farmer's Delight isn't out for 1.20.4 yet, as the codebase changes between it and 1.20.1. I'm pretty sure that trying to load it in this version will soft-fail, like you described.

**Comment by Hunipudding** [comment]
no wonder why it wasnt working, tysm!! :>
