### ISSUE TITLE
Tomato sauce is a bowl but it can be stacked up to 64 pieces

### ISSUE THREAD

**Issue by tankplanelaserkoala** [vectorwing/FarmersDelight#873]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.20

### Description

According to the principle of Farmer's Delight, dishes made from bowls should stack up to 16, but tomato sauce ignores this principle and stacks up to 64.
![스크린샷 2024-01-29 154710](https://github.com/vectorwing/FarmersDelight/assets/157739795/1e1760f2-8fb2-4a87-b17e-5307fe16a122)

### Steps to reproduce

 Add 64 tomato sauce to your inventory.

### Mod list

	Mod List: 
		createbigcannons-forge-1.20.1-0.5.3.b.jar         |Create Big Cannons            |createbigcannons              |0.5.3.b-nightly-8a45|DONE      |Manifest: NOSIGNATURE
		skin_changer-0.6.0.jar                            |Skin Changer                  |skin_changer                  |0.6.0               |DONE      |Manifest: NOSIGNATURE
		Dice-[MC-1.20.1]-1.0.0.jar                        |Dice                          |dice                          |1.0.0               |DONE      |Manifest: NOSIGNATURE
		Divine_Weaponry_v1.7_1.20.1.jar                   |Divine Weaponry               |divine_weaponry               |1.6.0               |DONE      |Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.2.3.jar                   |Botarium                      |botarium                      |2.2.3               |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.2.0.27.jar                    |Just Enough Items             |jei                           |15.2.0.27           |DONE      |Manifest: NOSIGNATURE
		CGM-Unofficial-1.4.7+Forge+1.20.1.jar             |MrCrayfish's Gun Mod          |cgm                           |1.4.7+Forge+1.20.1} |DONE      |Manifest: NOSIGNATURE
		Pehkui-3.7.12+1.20.1-forge.jar                    |Pehkui                        |pehkui                        |3.7.12+1.20.1-forge |DONE      |Manifest: NOSIGNATURE
		libraryferret-forge-1.20.1-4.0.0.jar              |Library ferret                |libraryferret                 |4.0.0               |DONE      |Manifest: NOSIGNATURE
		obscure_api-15.jar                                |Obscure API                   |obscure_api                   |15                  |DONE      |Manifest: NOSIGNATURE
		immersive_aircraft-0.6.21.20.1-forge.jar          |Immersive Aircraft            |immersive_aircraft            |0.6.2+1.20.1        |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.20.1-0.5.113.524.jar          |Sophisticated Core            |sophisticatedcore             |0.5.113.524         |DONE      |Manifest: NOSIGNATURE
		ritchiesprojectilelib-1.0.0-369e88d+1.20.1-forge.j|Ritchie's Projectile Library  |ritchiesprojectilelib         |1.0.0-369e88d+1.20.1|DONE      |Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.20-16.0.1.jar        |CookingForBlockheads          |cookingforblockheads          |16.0.1              |DONE      |Manifest: NOSIGNATURE
		citadel-2.4.9-1.20.1.jar                          |Citadel                       |citadel                       |2.4.9               |DONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.7.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.7              |DONE      |Manifest: NOSIGNATURE
		EpheroLib-1.20.1-FORGE-1.2.0.jar                  |BOZOID                        |epherolib                     |0.1.2               |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |DONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.2.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.2    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.1-beta.2.jar                |MixinExtras                   |mixinextras                   |0.2.1-beta.2        |DONE      |Manifest: NOSIGNATURE
		gemsnjewels-1.20.1-1.1.3.jar                      |Gems & Jewels                 |gemsnjewels                   |0.1.0               |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.20.1-3.19.5.988.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |3.19.5.988          |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.20.1-1.6.3.jar                   |Guard Villagers               |guardvillagers                |1.20.1-1.6.3        |DONE      |Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.3.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.3.3               |DONE      |Manifest: NOSIGNATURE
		bygonenether-1.3.2-1.20.x.jar                     |Bygone Nether                 |bygonenether                  |1.3.2               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		immersive_armors-1.6.11.20.1-forge.jar            |Immersive Armors              |immersive_armors              |1.6.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		hauntedharvest-1.20-3.1.18.jar                    |Haunted Harvest               |hauntedharvest                |1.20-3.1.18         |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.20-universal.jar                |Forge                         |forge                         |47.2.20             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		dummmmmmy-1.20-1.8.14.jar                         |MmmMmmMmmmmm                  |dummmmmmy                     |1.20-1.8.14         |DONE      |Manifest: NOSIGNATURE
		chalk-1.20.1-1.6.3.jar                            |Chalk                         |chalk                         |1.6.3               |DONE      |Manifest: NOSIGNATURE
		twilightforest-1.20.1-4.3.1893-universal.jar      |The Twilight Forest           |twilightforest                |4.3.1893            |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.7.30.jar                   |Supplementaries               |supplementaries               |1.20-2.7.30         |DONE      |Manifest: NOSIGNATURE
		embeddium-0.2.18+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.2.18+mc1.20.1     |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		ends_delight-1.20.1-1.0.1.jar                     |End's Delight                 |ends_delight                  |1.0.1               |DONE      |Manifest: NOSIGNATURE
		handcrafted-forge-1.20.1-3.0.5.jar                |Handcrafted                   |handcrafted                   |3.0.5               |DONE      |Manifest: NOSIGNATURE
		alexscaves-1.0.9.jar                              |Alex's Caves                  |alexscaves                    |1.0.9               |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.9.3-forge.jar                    |Moonlight Library             |moonlight                     |1.20-2.9.3          |DONE      |Manifest: NOSIGNATURE
		chefs-delight-1.0.3-forge-1.20.1.jar              |Chefs Delight                 |chefsdelight                  |1.0.3-forge-1.20.1  |DONE      |Manifest: NOSIGNATURE
		mysterious_mountain_lib-1.4.2-1.20.1.jar          |Mysterious Mountain Lib       |mysterious_mountain_lib       |1.4.2-1.20.1        |DONE      |Manifest: NOSIGNATURE
		endersdelight-1.20.1-1.0.3.jar                    |Ender's Delight               |endersdelight                 |1.0.3               |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		Obscure-Tooltips-2.2.jar                          |Obscure Tooltips              |obscure_tooltips              |2.2                 |DONE      |Manifest: NOSIGNATURE
		Chunky-1.3.92.jar                                 |Chunky                        |chunky                        |1.3.92              |DONE      |Manifest: NOSIGNATURE
		nethersdelight-1.20.1-4.0.jar                     |Nether's Delight              |nethersdelight                |1.20.1-4.0          |DONE      |Manifest: NOSIGNATURE
		NBTac-FORGE-1.20.1-1.1.7.jar                      |NBT Autocomplete              |nbt_ac                        |1.1.7               |DONE      |Manifest: NOSIGNATURE
		resourcefulconfig-forge-1.20.1-2.1.2.jar          |Resourcefulconfig             |resourcefulconfig             |2.1.2               |DONE      |Manifest: NOSIGNATURE
		L_Enders_Cataclysm-1.90+-1.20.1.jar               |Cataclysm Mod                 |cataclysm                     |1.0                 |DONE      |Manifest: NOSIGNATURE
		curios-forge-5.5.0+1.20.1.jar                     |Curios API                    |curios                        |5.5.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		create_central_kitchen-1.20.1-for-create-0.5.1.f-1|Create: Central Kitchen       |create_central_kitchen        |1.3.9.d             |DONE      |Manifest: NOSIGNATURE
		suppsquared-1.20-1.1.12.jar                       |Supplementaries Squared       |suppsquared                   |1.20-1.1.12         |DONE      |Manifest: NOSIGNATURE
		Croptopia-1.20.1-FORGE-3.0.4.jar                  |Croptopia                     |croptopia                     |3.0.4               |DONE      |Manifest: NOSIGNATURE
		CroptopiaDelight-1.20.1_1.2.2-forge.jar           |Croptopia Delight             |croptopia_delight             |1.0                 |DONE      |Manifest: NOSIGNATURE
		[1.20.1]+SecurityCraft+v1.9.8.jar                 |SecurityCraft                 |securitycraft                 |1.9.8               |DONE      |Manifest: NOSIGNATURE
		immersive_paintings-0.6.71.20.1-forge.jar         |Immersive Paintings           |immersive_paintings           |0.6.7+1.20.1        |DONE      |Manifest: NOSIGNATURE
		bettervillage-forge-1.20.1-3.2.0.jar              |Better village                |bettervillage                 |3.1.0               |DONE      |Manifest: NOSIGNATURE
		xercapaint-1.20.1-1.0.0.jar                       |Joy of Painting               |xercapaint                    |1.20.1-1.0.0        |DONE      |Manifest: NOSIGNATURE
		witherstormmod-1.20.1-4.0.1.1.jar                 |Cracker's Wither Storm Mod    |witherstormmod                |4.0.1.1             |DONE      |Manifest: NOSIGNATURE
		miners_delight-1.20.1-1.2.3.jar                   |Miner's Delight               |miners_delight                |1.20.1-1.2.3        |DONE      |Manifest: NOSIGNATURE
		betterarcheology-1.1.2-1.20.1.jar                 |Better Archeology             |betterarcheology              |1.1.2-1.20.1        |DONE      |Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.20.jar            |Resourceful Lib               |resourcefullib                |2.1.20              |DONE      |Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |DONE      |Manifest: NOSIGNATURE
		twilightdelight-2.0.3.jar                         |Twilight's Flavor & Delight   |twilightdelight               |2.0.3               |DONE      |Manifest: NOSIGNATURE
		cfm-forge-1.20.1-7.0.0-pre36.jar                  |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre36         |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		automobility-0.4.2+1.20.1-forge.jar               |Automobility                  |automobility                  |0.4.2+1.20.1-forge  |DONE      |Manifest: NOSIGNATURE
		alexsdelight-1.5.jar                              |Alex's Delight                |alexsdelight                  |1.5                 |DONE      |Manifest: NOSIGNATURE
		9.1.12-forge.jar                                  |Architectury                  |architectury                  |9.1.12              |DONE      |Manifest: NOSIGNATURE
		doapi-1.2.8-forge.jar                             |Lets Do Api                   |doapi                         |1.2.8               |DONE      |Manifest: NOSIGNATURE
		letsdo-candlelight-forge-1.2.8.jar                |Candlelight Dinner            |candlelight                   |1.2.8               |DONE      |Manifest: NOSIGNATURE
		simplyswords-forge-1.51.5-1.20.1.jar              |Simply Swords                 |simplyswords                  |1.51.5-1.20.1       |DONE      |Manifest: NOSIGNATURE
		corn_delight-1.0.3-1.20.1.jar                     |Corn Delight                  |corn_delight                  |1.0.3-1.20.1        |DONE      |Manifest: NOSIGNATURE
		Chimes-v2.0.1-1.20.1.jar                          |Chimes                        |chimes                        |2.0.1               |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.1.jar                      |Aquaculture 2                 |aquaculture                   |2.5.1               |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.16.jar                 |Framework                     |framework                     |0.6.16              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		l2library-2.4.16-slim.jar                         |L2 Library                    |l2library                     |2.4.16              |DONE      |Manifest: NOSIGNATURE
		immersive_melodies-0.1.0+1.20.1-forge.jar         |Immersive Melodies            |immersive_melodies            |0.1.0+1.20.1        |DONE      |Manifest: NOSIGNATURE
		create_oppenheimered-1.20.1-1.0.1.jar             |Create: Oppenheimered         |create_oppenheimered          |1.0.1               |DONE      |Manifest: NOSIGNATURE
		aquamirae-6.API15.jar                             |Aquamirae                     |aquamirae                     |6.API15             |DONE      |Manifest: NOSIGNATURE
		ad_astra-forge-1.20.1-1.15.5.jar                  |Ad Astra                      |ad_astra                      |1.15.5              |DONE   

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [x] I am using performance or shader mods

**Comment by vectorwing** [comment]
Though I understand this is a bit inconsistent visually, Tomato Sauce is not considered a meal, but rather an ingredient. Therefore, it stacks to 64 normally.

Usually, any contained ingredient which stacks to 16 has a special effect tied to it, which Tomato Sauce lacks.
