### ISSUE TITLE
Disastrous item copy bug

### ISSUE THREAD

**Issue by QyInvoLing** [vectorwing/FarmersDelight#876]
### Minecraft version

1.18.2

### Farmer's Delight version

latest

### Forge version

latest

### Description

When FD, Valkyrien skies and Eureka! are installed, assemble/disassemble a ship where there's a FD's cutting board on it by eureka's ship helm would copy the item. For example, assemble a ship made from cutting board and disassemble it, then you'll find the item copied twice, which means there're three items (including the origin one).
![QQ截图20240202221050](https://github.com/vectorwing/FarmersDelight/assets/13376296/bdac0a0b-0cf6-40c0-9ecb-3ef8e1205503)

### Mod list

create0.5.1f
valkyrien skies-118-forge-2.1.1-beta.6+b1ee932637
eureka-1.4.0-beta.1
FarmersDelight-1.18.2-1.2.3

### Logs

No log spawned

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Given this is an issue with a mod which forms multiblocks out of existing ones, I'm not sure if there is much I can do about it on my end, aside from verifying common block methods that these two mods might invoke.

Have you posted this issue in their board as well? They might have better knowledge of what's happening, and whether it's FD which made a mistake on its methods, or if it's Vakyrien/Eureka failing to properly save functional blocks, and their inventory drops when broken.

**Comment by vectorwing** [comment]
Closing this issue as it's gotten stale. I see that you haven't forwarded this to the Valkyrien Skies team; if possible, please forward it to them, as they may be able to help better.
