### ISSUE TITLE
minecraft 1.20.1 forge 47.2.0 mod loading error

### ISSUE THREAD

**Issue by Thunderrock424242** [vectorwing/FarmersDelight#882]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.0

### Description

crash during world loading

### Mod list

i am using my own pack list should be in logs

### Logs

[launcher_log.txt](https://github.com/vectorwing/FarmersDelight/files/14366592/launcher_log.txt)
[latest.log](https://github.com/vectorwing/FarmersDelight/files/14366593/latest.log)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This seems to be caused by an outdated version of **Amendments**.
Please update the mod, and the issue should be fixed. 👍
