### ISSUE TITLE
Cutting Board not working

### ISSUE THREAD

**Issue by Ophelia-Sakura** [vectorwing/FarmersDelight#884]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.0

### Description

When trying to cut anything on a cutting board such as mutton chops with a Flint Knife the "Maybe with a different tool..." message is displayed

### Steps to reproduce

place any cuttable object on the cutting board, try cutting

### Mod list

Mod List: 
		Kiwi-1.20.1-forge-11.5.3.jar                      |Kiwi Library                  |kiwi                          |11.5.3              |DONE      |Manifest: NOSIGNATURE
		ancient_manuscripts-1.1.4-1.20.1.jar              |Ancient Manuscripts           |ancient_manuscripts           |1.1.4-1.20.1        |DONE      |Manifest: NOSIGNATURE
		floralis-1.20.1-10.5.0.jar                        |Floralis                      |floralis                      |1.20.1-10.5.0       |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |DONE      |Manifest: NOSIGNATURE
		firstperson-forge-2.3.3-mc1.20.1.jar              |FirstPerson                   |firstperson                   |2.3.3               |DONE      |Manifest: NOSIGNATURE
		keebszs_battletowers_0.6.0-1.20.1BETA.jar         |Keebsz's Battle Towers        |keebszs_battle_towers         |0.6.0-1.20.1        |DONE      |Manifest: NOSIGNATURE
		Satako-7.0.14-1.20.1.jar                          |Satako                        |satako                        |7.0.14-1.20.1       |DONE      |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.20.1forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |DONE      |Manifest: NOSIGNATURE
		immersive_weathering-1.20.1-2.0.0-forge.jar       |Immersive Weathering          |immersive_weathering          |1.20.1-2.0.0        |DONE      |Manifest: NOSIGNATURE
		material_elements_armor_tools_weapons_1.20.1-7.1.1|Material Elements Armor, Tools|material_elements_armor_tools_|7.1.1               |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.20.1-11.1.0.1-build.0289.jar     |ForgeEndertech                |forgeendertech                |11.1.0.1            |DONE      |Manifest: NOSIGNATURE
		AdFinders-1.20.1-9.1.3.0-build.0351.jar           |Advanced Finders              |adfinders                     |9.1.3.0             |DONE      |Manifest: NOSIGNATURE
		Fallingleaves-1.20.1-2.1.0.jar                    |Falling Leaves                |fallingleaves                 |2.1.0               |DONE      |Manifest: NOSIGNATURE
		Structory_1.20.2_v1.3.4.jar                       |Structory                     |structory                     |1.3.4               |DONE      |Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.20.1forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |DONE      |Manifest: NOSIGNATURE
		advancementframes-1.20-2.2.3.jar                  |Advancement Frames            |advancementframes             |1.20-2.2.3          |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.37.8_Forge_1.20.jar              |Xaero's World Map             |xaeroworldmap                 |1.37.8              |DONE      |Manifest: NOSIGNATURE
		citadel-2.5.3-1.20.1.jar                          |Citadel                       |citadel                       |2.5.3               |DONE      |Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.20.1-9.0.0.46.jar                 |Serene Seasons                |sereneseasons                 |9.0.0.46            |DONE      |Manifest: NOSIGNATURE
		configured-forge-1.20.1-2.2.2.jar                 |Configured                    |configured                    |2.2.2               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		YungsApi-1.20-Forge-4.0.3.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.2.1-beta.2.jar                |MixinExtras                   |mixinextras                   |0.2.1-beta.2        |DONE      |Manifest: NOSIGNATURE
		Dungeon Crawl-1.20.1-2.3.14.jar                   |Dungeon Crawl                 |dungeoncrawl                  |2.3.14              |DONE      |Manifest: NOSIGNATURE
		Bookshelf-Forge-1.20.1-20.1.9.jar                 |Bookshelf                     |bookshelf                     |20.1.9              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		Kambrik-6.1.1+1.20.1-forge.jar                    |Kambrik                       |kambrik                       |6.1.1+1.20.1        |DONE      |Manifest: NOSIGNATURE
		simpleplanes-1.20.1-5.2.7.jar                     |Simple Planes                 |simpleplanes                  |1.20.1-5.2.7        |DONE      |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.20-Forge-3.0.3.jar     |YUNG's Better Desert Temples  |betterdeserttemples           |1.20-Forge-3.0.3    |DONE      |Manifest: NOSIGNATURE
		mcw-doors-1.1.0forge-mc1.20.1.jar                 |Macaw's Doors                 |mcwdoors                      |1.1.0               |DONE      |Manifest: NOSIGNATURE
		HopoBetterUnderwaterRuins-[1.20-1.20.2]-1.1.4b.jar|HopoBetterUnderwaterRuins     |hopour                        |1.1.4               |DONE      |Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.1.jar                       |Balm                          |balm                          |7.2.1               |DONE      |Manifest: NOSIGNATURE
		SnowRealMagic-1.20.1-forge-10.2.7.jar             |Snow! Real Magic!             |snowrealmagic                 |10.2.7              |DONE      |Manifest: NOSIGNATURE
		spelunkery-1.20.1-0.3.5-forge.jar                 |Spelunkery                    |spelunkery                    |1.20.1-0.3.5        |DONE      |Manifest: NOSIGNATURE
		ShieldExpansion-1.20.1-1.1.7a.jar                 |Shield Expansion              |shieldexp                     |1.1.7a              |DONE      |Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |DONE      |Manifest: NOSIGNATURE
		soundphysics-forge-1.20.1-1.1.2 (1).jar           |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.1.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.2.0-universal.jar                 |Forge                         |forge                         |47.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		ctov-3.3.4.jar                                    |ChoiceTheorem's Overhauled Vil|ctov                          |3.3.4               |DONE      |Manifest: NOSIGNATURE
		TravelersTitles-1.20-Forge-4.0.2.jar              |Traveler's Titles             |travelerstitles               |1.20-Forge-4.0.2    |DONE      |Manifest: NOSIGNATURE
		scuba_gear-1.20.1-1.0.6.jar                       |Scuba Gear                    |scuba_gear                    |1.0.6               |DONE      |Manifest: NOSIGNATURE
		supplementaries-1.20-2.7.36.jar                   |Supplementaries               |supplementaries               |1.20-2.7.36         |DONE      |Manifest: NOSIGNATURE
		embeddium-0.3.4+mc1.20.1.jar                      |Embeddium                     |embeddium                     |0.3.4+mc1.20.1      |DONE      |Manifest: NOSIGNATURE
		mcw-paths-1.0.4forge-mc1.20.1.jar                 |Macaw's Paths and Pavings     |mcwpaths                      |1.0.4               |DONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		mcw-bridges-2.1.1-mc1.20.1forge.jar               |Macaw's Bridges               |mcwbridges                    |2.1.1               |DONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |DONE      |Manifest: NOSIGNATURE
		torchmaster-20.1.5.jar                            |Torchmaster                   |torchmaster                   |20.1.5              |DONE      |Manifest: NOSIGNATURE
		moonlight-1.20-2.9.17-forge.jar                   |Moonlight Library             |moonlight                     |1.20-2.9.17         |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.3.8_mc1.20.1.jar           |AmbientSounds                 |ambientsounds                 |5.3.8               |DONE      |Manifest: NOSIGNATURE
		psg-5.03b-1.20.1.jar                              |Potassium & sulphur's gunpowdw|psg                           |4.01                |DONE      |Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |DONE      |Manifest: NOSIGNATURE
		material_elements_1.20.1-7.1.1.jar                |Material Elements             |material_elements             |7.1.1               |DONE      |Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.11.24_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.24             |DONE      |Manifest: NOSIGNATURE
		Oreganized_1.20.1-2.0.2.jar                       |Oreganized                    |oreganized                    |2.0.2               |DONE      |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.2-mc1.20.1forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.2               |DONE      |Manifest: NOSIGNATURE
		cleanswing-1.20-1.5.jar                           |Clean Swing Through Grass     |cleanswing                    |1.20-1.5            |DONE      |Manifest: NOSIGNATURE
		AdLods-1.20.1-8.1.0.0-build.0142.jar              |Large Ore Deposits            |adlods                        |8.1.0.0             |DONE      |Manifest: NOSIGNATURE
		enchantmenttransfer-0.0.6-1.20.1.jar              |Enchantment Transfer          |enchantmenttransfer           |0.0.6               |DONE      |Manifest: NOSIGNATURE
		car-forge-1.20.1-1.0.15.jar                       |Ultimate Car Mod              |car                           |1.20.1-1.0.15       |DONE      |Manifest: NOSIGNATURE
		Bountiful-6.0.3+1.20.1-forge.jar                  |Bountiful                     |bountiful                     |6.0.3+1.20.1        |DONE      |Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |DONE      |Manifest: NOSIGNATURE
		ecologics-forge-1.20.1-2.2.0.jar                  |Ecologics                     |ecologics                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_23.9.7_Forge_1.20.jar              |Xaero's Minimap               |xaerominimap                  |23.9.7              |DONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.15a.jar                       |Oculus                        |oculus                        |1.6.15a             |DONE      |Manifest: NOSIGNATURE
		collective-1.20.1-7.30.jar                        |Collective                    |collective                    |7.30                |DONE      |Manifest: NOSIGNATURE
		camera-1.20.1-1.0.6.jar                           |Camera Mod                    |camera                        |1.20.1-1.0.6        |DONE      |Manifest: NOSIGNATURE
		YungsExtras-1.20-Forge-4.0.3.jar                  |YUNG's Extras                 |yungsextras                   |1.20-Forge-4.0.3    |DONE      |Manifest: NOSIGNATURE
		ToughAsNails-1.20.1-9.0.0.96.jar                  |Tough As Nails                |toughasnails                  |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		backpacked-forge-1.20.1-2.2.5.jar                 |Backpacked                    |backpacked                    |2.2.5               |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		coroutil-forge-1.20.1-1.3.7.jar                   |CoroUtil                      |coroutil                      |1.20.1-1.3.7        |DONE      |Manifest: NOSIGNATURE
		mcw-roofs-2.3.0-mc1.20.1forge.jar                 |Macaw's Roofs                 |mcwroofs                      |2.3.0               |DONE      |Manifest: NOSIGNATURE
		mvs-4.1.1-1.20-forge.jar                          |Moog's Voyager Structures     |mvs                           |4.1.1-1.20-forge    |DONE      |Manifest: NOSIGNATURE
		architectury-9.1.13-forge.jar                     |Architectury                  |architectury                  |9.1.13              |DONE      |Manifest: NOSIGNATURE
		minecraft-comes-alive-7.5.14+1.20.1-universal.jar |Minecraft Comes Alive         |mca                           |7.5.14+1.20.1       |DONE      |Manifest: NOSIGNATURE
		off-hand-combat-2.0.0-forge.jar                   |Off Hand Combat               |offhandcombat                 |2.0.0               |DONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.2.2-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.2               |DONE      |Manifest: NOSIGNATURE
		cryingportals-1.20.1-2.7.jar                      |Crying Portals                |cryingportals                 |2.7                 |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.20.1-2.5.1.jar                      |Aquaculture 2                 |aquaculture                   |2.5.1               |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.20.1-10.1.4.0-build.0314.jar         |Advanced Chimneys             |adchimneys                    |10.1.4.0            |DONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.6.26.jar                 |Framework                     |framework                     |0.6.26              |DONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		sullysmod-3.1.2-beta.jar                          |Sully's Mod                   |sullysmod                     |3.1.2-beta          |DONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.2.jar                   |GeckoLib 4                    |geckolib                      |4.4.2               |DONE      |Manifest: NOSIGNATURE
		blueprint-1.20.1-7.0.0.jar                        |Blueprint                     |blueprint                     |7.0.0               |DONE      |Manifest: NOSIGNATURE
		smallships-forge-1.20.1-2.0.0-b1.0.jar            |Small Ships                   |smallships                    |2.0.0-b1.0          |DONE      |Manifest: NOSIGNATURE
		bushierflowers-0.0.3-1.20.1.jar                   |Bushier Flowers               |bushierflowers                |0.0.3-1.20.1        |DONE      |Manifest: NOSIGNATURE
		HopoBetterMineshaft-[1.20-1.20.1]-1.1.8.jar       |HopoBetterMineshaft           |hopo                          |1.1.8               |DONE      |Manifest: NOSIGNATURE
		DarkPaintings-Forge-1.20.1-17.0.4.jar             |DarkPaintings                 |darkpaintings                 |17.0.4              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		mcw-lights-1.0.6-mc1.20.1forge.jar                |Macaw's Lights and Lamps      |mcwlights                     |1.0.6               |DONE      |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.20-Forge-2.0.4.jar     |YUNG's Better Jungle Temples  |betterjungletemples           |1.20-Forge-2.0.4    |DONE      |Manifest: NOSIGNATURE

### Logs

https://pastebin.com/r0KJNPdE

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Some mod is breaking the `forge:tools/knives` tag, which causes knife cutting recipes to fail.

My guess is something related to Oreganized, as your log shows errors related to the Electrum Knife. I suggest trying to disable it temporarily, and testing the Cutting Board on a separate save, to see if the issue is fixed. If not, take a look at any FD addons you might have. @Ophelia-Sakura

**Comment by vectorwing** [comment]
Closing this issue, as it's gotten stale.
