### ISSUE TITLE
Wild crop generation cannot be disabled

### ISSUE THREAD

**Issue by Roonas** [vectorwing/FarmersDelight#889]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

1.20.1-47.1.46

### Description

Config lacks option to completely disable the generation of wild crops, setting the range to 0, or as far from 0 as possible, still results in crop generation.

### Mod list

n/a

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
All worldgen is data driven so you can remove it with datapack

**Comment by vectorwing** [comment]
As said above, world gen features are based on datapacks now, which means it can't be disabled with configs.
You can disable FD's wild crops by making a datapack which replaces files in `biome_modifiers` with blank {} tags.

**Comment by singlain** [comment]
> As said above, world gen features are based on datapacks now, which means it can't be disabled with configs. You can disable FD's wild crops by making a datapack which replaces files in `biome_modifiers` with blank {} tags.

Either I'm doing something wrong or changing any json within `biome_modifiers` to be

```
{
}
```

or

```
{

}
```

causes the game to crash on the world creation  screen

**Comment by vectorwing** [comment]
I believe that you need to enter a condition inside the brackets for biome modifiers in specific, though I'm uncertain which one exactly. You can refer to [this doc](https://docs.minecraftforge.net/en/latest/resources/server/conditional/#true-and-false) for 1.20.1 syntax on this part.

However, I was told that on 1.20.1 and above, pack.mcmeta has a filtering feature, where you can exclude files altogether. You can use that to exclude the biome modifiers you want to disable.

Check this pack.mcmeta generator to build one with filtering:
https://misode.github.io/pack-mcmeta/

I hope that helps! ^^
