### ISSUE TITLE
[1.16.3] Item disappears when you try to harvest fully ripe Onion crop to use right click

### ISSUE THREAD

**Issue by itzmily** [vectorwing/FarmersDelight#89]
**Description**
If you right click to fully ripe onion crop for harvest, the crop has return to unripe thing but the Onion item to should be come out hasn't drops.

**Steps to reproduce:**
1. Just like a normal farming, grows onion crops until it fully grows.
2. After it is fully grown, right click to the crop.

**Expected behavior:**
The onion Item normally should be drops like the other crops.

**Screenshots**
![2020-11-29_13 17 18](https://user-images.githubusercontent.com/74253526/100533226-4d8ab400-3245-11eb-8a38-ad28e9022ed0.png)
![2020-11-29_13 17 25](https://user-images.githubusercontent.com/74253526/100533227-4f547780-3245-11eb-9376-20c9530af3df.png)
![2020-11-29_13 17 33](https://user-images.githubusercontent.com/74253526/100533228-5085a480-3245-11eb-9649-9ff2b1647041.png)

**Mod list:**
Farmer's delight version: 1.16.3-0.2.3 (Latest)
Forge Version: 34.1.35
Minecraft version: 1.16.3

**Comment by vectorwing** [comment]
Hello! The right-click harvesting feature belongs to the mod Quark. This issue also tends to happen when harvesting carrots and potatoes, as Quark subtracts a unit to replant, and they may result in zero. Not much I can do about it besides run a few tests on 1.16.3 again.

**Comment by itzmily** [comment]
Thanks for commenting vectorwing!
first of all, I'd tested right-clicking harvest every crops includes the vanilla one, only this onion happens the thing.
as you said there is no solution but to test, so I will wait till this problem can no longer happens.

**Comment by vectorwing** [comment]
Hello! It's been a while, huh?

Sorry, I haven't been able to replicate this problem at all across my tests; onions seem to right-click-harvest normally under the latest versions of Quark and FD.

Are you still facing issues when updating to the latest versions of both mods? Or are you using a different right-click harvest solution? If the issue persists, please post a **full** mod list if possible to help troubleshoot, as FD does not have right-click harvest on any crops besides Tomatoes.

**Comment by vectorwing** [comment]
I'll be closing this issue as it is stale. If the problem persists, feel free to reopen with the answers I requested above.
