### ISSUE TITLE
Bulk blasting in the Create mod does not work with raw food items

### ISSUE THREAD

**Issue by agr-97** [vectorwing/FarmersDelight#893]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

Forge - 47.2.20

### Description

When using Bulk Blasting in the Create Mod to smelt raw items (e.g. raw beef patty, uncooked bacon, wheat dough, etc.), the raw items burn away (disappear) instead of turning into the cooked item (e.g. cooked beef patty, cooked bacon, bread). 

### Steps to reproduce

1. place any smeltable item in bulk blasting system
2. observe item disappear

### Mod list

Create mod latest version
Farmer's delight

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by MythrilBagels** [comment]
Keep in mind there is a difference between Bulk Smoking and Bulk Cooking.

**Comment by agr-97** [comment]
Wow, you are right, I will remove this post thank you @MythrilBagels
