### ISSUE TITLE
[Fabric] Crash when eating a cake

### ISSUE THREAD

**Issue by joernott** [vectorwing/FarmersDelight#907]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

Fabric 0.15.7

### Description

When trying to eat a cake, the game crashes with the following stack trace:
```
[15:41:51] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoClassDefFoundError: com/nhoryzon/mc/farmersdelight/registry/TagsRegistry
	at net.mehvahdjukaar.amendments.integration.fabric.FarmersDelightCompatImpl.onCakeInteract(FarmersDelightCompatImpl.java:20) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.mehvahdjukaar.amendments.integration.FarmersDelightCompat.onCakeInteract(FarmersDelightCompat.java) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.mehvahdjukaar.amendments.common.block.DirectionalCakeBlock.useGeneric(DirectionalCakeBlock.java:104) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.mehvahdjukaar.amendments.common.block.DirectionalCakeBlock.method_9534(DirectionalCakeBlock.java:94) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:1133) ~[client-intermediary.jar:?]
	at net.mehvahdjukaar.amendments.events.behaviors.DirectionalCakeConversion.tryPerformingAction(DirectionalCakeConversion.java:58) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.mehvahdjukaar.amendments.events.behaviors.InteractEvents.onItemUsedOnBlock(InteractEvents.java:158) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.mehvahdjukaar.amendments.events.ModEvents.onRightClickBlock(ModEvents.java:20) ~[amendments-1.20-1.1.10-fabric.jar:?]
	at net.fabricmc.fabric.api.event.player.UseBlockCallback.lambda$static$0(UseBlockCallback.java:41) ~[fabric-events-interaction-v0-0.6+1802ada577-6fc36030f9858a64.jar:?]
	at net.minecraft.class_636.handler$ckf000$fabric-events-interaction-v0$interactBlock(class_636.java:2188) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1802) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
Caused by: java.lang.ClassNotFoundException: com.nhoryzon.mc.farmersdelight.registry.TagsRegistry
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 28 more
```

### Steps to reproduce

1. Bake a cake (vanilla recipe or the one using milk bottles)
2. Place the cake
3. Try to eat a slice and crash the game instead

### Mod list

	- additionalplacements 1.8.0
	- advancementinfo 1.20-fabric0.83.0-1.4
	- ae2 15.1.0
	   \-- team_reborn_energy 3.0.0
	- ae2wtlib 15.2.1-fabric
	- amendments 1.20-1.1.10
	   \-- mixinsquared 0.1.1
	- architectury 9.2.14
	- argonauts 1.0.9
	   \-- placeholder-api 2.1.1+1.20
	- armorposer 2.1.3
	- athena 3.1.2
	- bellsandwhistles 0.4.5
	- betteradvancements 0.3.2.161
	- betterf3 7.0.2
	- bobby 5.0.1
	   |-- com_typesafe_config 1.4.2
	   |-- io_leangen_geantyref_geantyref 1.3.13
	   |-- org_spongepowered_configurate-core 4.1.2
	   \-- org_spongepowered_configurate-hocon 4.1.2
	- botania 1.20.1-443-FABRIC
	   |-- fiber 0.23.0-2
	   |-- reach-entity-attributes 2.4.0
	   \-- step-height-entity-attribute 1.2.0
	- cadmus 1.0.7
	   \-- common-protection-api 1.0.0
	- camerautils 1.20.1-1.0.5
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- carpet 1.4.112+v230608
	- carryon 2.1.2.7
	- chipped 3.0.4
	- chisel 1.6.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.4+1.20.1
	- controlling 12.0.2
	- copycats 1.20.1-1.2.6
	- corgilib 4.0.1.1
	   |-- com_electronwill_night-config_core 3.6.7
	   \-- com_electronwill_night-config_toml 3.6.7
	- create 0.5.1-f-build.1417+mc1.20.1
	   |-- com_google_code_findbugs_jsr305 3.0.2
	   |-- flywheel 0.6.10-2
	   |-- forgeconfigapiport 8.0.0
	   |-- milk 1.2.60
	   |    \-- dripstone_fluid_lib 3.0.2
	   |-- porting_lib_accessors 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_base 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_config 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    |-- porting_lib_lazy_registration 2.3.2+1.20.1
	   |    |-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_utility 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_brewing 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_client_events 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_entity 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_mixin_extensions 2.3.2+1.20.1
	   |-- porting_lib_extensions 2.3.2+1.20.1
	   |    |-- porting_lib_attributes 2.3.2+1.20.1
	   |    |-- porting_lib_common 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- reach-entity-attributes 2.4.0
	   |-- porting_lib_models 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    |-- porting_lib_fluids 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_networking 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_obj_loader 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_model_loader 2.3.2+1.20.1
	   |-- porting_lib_tags 3.0
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_tool_actions 2.3.2+1.20.1
	   |    \-- porting_lib_core 2.3.2+1.20.1
	   |-- porting_lib_transfer 2.3.2+1.20.1
	   |    |-- porting_lib_core 2.3.2+1.20.1
	   |    \-- porting_lib_fluids 2.3.2+1.20.1
	   |-- reach-entity-attributes 2.4.0
	   \-- registrate-fabric 1.3.62-MC1.20.1
	        |-- porting_lib_data 2.1.1090+1.20
	        |    \-- porting_lib_gametest 2.1.1090+1.20
	        \-- porting_lib_model_generators 2.1.1090+1.20
	             |-- porting_lib_gametest 2.1.1090+1.20
	             \-- porting_lib_model_materials 2.1.1090+1.20
	- create_power_loader 1.4.3-mc1.20.1-fabric
	   \-- porting_lib_chunk_loading 2.3.0+1.20.1
	- createaddition 1.2.3
	- createdieselgenerators 1.2.3h
	- createutilities 0.3.0+1.20.1
	   \-- team_reborn_energy 3.0.0
	- cristellib 1.1.5
	   \-- blue_endless_jankson 1.2.3
	- ctov 3.4.2
	- enderchests 1.20.1-1.2
	- entityculling 1.6.2-mc1.20.1
	- extended_drawers 2.1.1+mc.1.20.1
	   |-- config_toolkit 1.0.0
	   |    |-- io_determann_shadow-api-17 0.1.1
	   |    \-- net_fabricmc_javapoet 0.1.0
	   |-- graphlib 1.4.0+1.20
	   |    |-- kmodlib-overlay 0.2.12+1.20
	   |    \-- libnetworkstack 0.10.0
	   |-- noindium 1.1.0+1.20
	   \-- yet_another_config_lib_v3 3.2.1+1.20
	        |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
	- extremesoundmuffler 3.41-fabric-1.20
	   \-- fiber 0.23.0-2
	- fabric-api 0.92.1+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- farmersdelight 1.20.1-2.0.9
	   |-- porting_lib_loot 2.3.0+1.20.1
	   |-- porting_lib_recipe_book_categories 2.3.0+1.20.1
	   \-- porting_lib_registries 2.3.0+1.20.1
	- faux-custom-entity-data 6.0.1
	- freecam 1.2.1+1.20
	- fusion 1.1.1
	- fwaystones 3.3.2+mc1.20.1
	- geckoanimfix 1.0.0
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- gravestones v1.15
	- handcrafted 3.0.6
	- heracles 1.1.12
	   \-- hermes 1.6.0
	- hullabaloo 1.0.0+1.20.1
	   \-- team_reborn_energy 3.0.0
	- immersive_paintings 0.6.7+1.20.1
	- indium 1.0.30+mc1.20.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- ironchest 2.0.2
	   \-- libgui 8.1.1+1.20.1
	        |-- jankson 6.0.0+j1.2.3
	        \-- libninepatch 1.2.0
	- jade 11.8.0
	- java 17
	- kubejs 2001.6.4-build.138
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.3
	- mca 7.5.14+1.20.1
	- mcwbridges 3.0.0
	- mcwdoors 1.1.0
	- mcwfences 1.1.1
	- mcwfurnitures 3.2.2
	- mcwholidays 1.1.0
	- mcwlights 1.0.6
	- mcwpaintings 1.0.5
	- mcwpaths 1.0.4
	- mcwroofs 2.3.0
	- mcwtrpdoors 1.1.2
	- mcwwindows 2.2.1
	- merequester 1.20.1-1.1.4
	   \-- midnightlib 1.2.1
	- mi_sound_addon 1.0.1-1.20.1
	   \-- magna 1.10.1+1.20.1
	        \-- omega-config 1.0.8
	- minecraft 1.20.1
	- missions 0.3.1
	- modern_industrialization 1.8.3
	   |-- magna 1.10.1+1.20.1
	   |    \-- omega-config 1.0.8
	   |-- noindium 1.1.0+1.20
	   |-- playerabilitylib 1.8.0
	   \-- team_reborn_energy 3.0.0
	- modernfix 5.15.0+mc1.20.1
	- modmenu 7.2.2
	- moonlight 1.20-2.11.1
	- opaccreatesupport 1.3.0
	- openpartiesandclaims 0.20.4
	- owo 0.11.2+1.20
	- patchouli 1.20.1-84-FABRIC
	   \-- fiber 0.23.0-2
	- philipsruins 1.20.1
	- prometheus 1.2.5
	- railways 1.6.0+fabric-mc1.20.1
	   |-- mixinextras 0.3.5
	   \-- mm 2.3
	- rechiseled 1.1.5+b
	- rechiseledcreate 1.0.2
	- resourcefullib 2.1.23
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- rhino 2001.2.2-build.18
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- searchables 1.0.2
	- shetiphiancore 1.20.1-1.2
	- sodium 0.5.8+mc1.20.1
	- supermartijn642configlib 1.1.8+a
	- supermartijn642corelib 1.1.17
	- supplementaries 1.20-2.8.10
	   \-- mixinsquared 0.1.1
	- t_and_t 1.12
	- tinymobfarm 1.2-1.20.1
	- toggleableitemframes 4.1.0-1.20.1
	- too-cheap 1.2.0
	- trashcans 1.0.18
	   \-- team_reborn_energy 3.0.0
	- travelersbackpack fabric-1.20.1-9.1.11
	   \-- reach-entity-attributes 2.4.0
	- trinkets 3.7.1
	- uilib 0.3.5
	- xaerominimap 24.0.3
	- xaeroworldmap 1.38.1

### Logs

https://pastebin.com/Jk9XVQGv

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by RaymondBlaze** [comment]
This is the repository of the Forge version of FD, so the issue doesn't really belong to here.

Please try [Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated) and possibly newer versions of Amendments, since MehVahdJukaar made both mods, they should be compatible on the newest version I believe.

**Comment by joernott** [comment]
ok, closing it here
