### ISSUE TITLE
[1.16.4] Rice and Tomato Seed Tags are inverted

### ISSUE THREAD

**Issue by MuteTiefling** [vectorwing/FarmersDelight#91]
**Description**
Rice tagged as seeds/tomato
Tomato seeds are tagged as seeds/rice

**Expected behavior:**
The reverse

**Screenshots**

![image](https://user-images.githubusercontent.com/9543430/101047387-cd6b9380-354f-11eb-82ad-01c7d43c6338.png)

![image](https://user-images.githubusercontent.com/9543430/101047455-d9efec00-354f-11eb-9c8e-a10a080f14b0.png)

**Mod list:**
Forge: 35.1.0
FarmersDelight-1.16.3-0.2.3

Other mods:
[crash-2020-12-03_10.12.17-client.txt](https://github.com/vectorwing/FarmersDelight/files/5636974/crash-2020-12-03_10.12.17-client.txt)

**Comment by vectorwing** [comment]
Oh my, it's indeed inverted. For all versions too... 😅
I'll compile this one in a future correction. Thank you for letting me know. 👍

**Comment by vectorwing** [comment]
Fixed on commit 9a04a62

**Comment by MuteTiefling** [comment]
awesome, thanks!
