### ISSUE TITLE
Recipes don't use `"group"` flag

### ISSUE THREAD

**Issue by Johnyel** [vectorwing/FarmersDelight#912]
### Minecraft version

Any

### Farmer's Delight version

All

### Forge version

Any

### Recipes from Farmer's Delight do not use the `"group":` flag, like recipes from minecraft.
This causes the recipes are not grouped into one tab in vanilla minecraft recipe book.

![Report-Image](https://github.com/vectorwing/FarmersDelight/assets/98728406/12689971-632f-447e-bc25-189f48152b7a)

### The full list of recipes that need to use the `"group":` flag.

- `"group":"cabinet"`
acacia_cabinet.json
birch_cabinet.json
crimson_cabinet.json
dark_oak_cabinet.json
jungle_cabinet.json
mangrove_cabinet.json
oak_cabinet.json
spruce_cabinet.json
warped_cabinet.json

- `"group":"apple_pie"`
apple_pie.json
apple_pie_from_slices.json

- `"group":"cabbage"`
cabbage.json
cabbage_from_leaves.json

- `"group":"cake"`
cake_from_milk_bottle.json
cake_from_slices.json
minecraft\recipes\ cake.json (vanilla recipe to be changed)

- `"group":"canvas"`
canvas.json
canvas_from_canvas_rug.json

- `"group":"chocolate_pie"`
chocolate_pie.json
chocolate_pie_from_slices.json

- `"group":"full_tatami_mat"`
full_tatami_mat.json
full_tatami_mat_from_halves.json

- `"group":"gold_nugget"`
gold_nugget_from_blasting_knife.json
minecraft\recipes\ gold_nugget_from_blasting.json (vanilla recipe to be changed)
gold_nugget_from_smelting_knife.json
minecraft\recipes\ gold_nugget_from_smelting.json (vanilla recipe to be changed)

- `"group":"iron_nugget"`
iron_nugget_from_blasting_knife.json
minecraft\recipes\ iron_nugget_from_blasting.json (vanilla recipe to be changed)
iron_nugget_from_smelting_knife.json
minecraft\recipes\ iron_nugget_from_smelting.json (vanilla recipe to be changed)

- `"group":"lead"`
lead_from_straw.json
minecraft\recipes\ lead.json (vanilla recipe to be changed)

- `"group":"organic_compost"`
organic_compost_from_rotten_flesh.json
organic_compost_from_tree_bark.json

- `"group":"pumpkin_seeds"`
pumpkin_seeds_from_slice.json
minecraft\recipes\ pumpkin_seeds.json (vanilla recipe to be changed)

- `"group":"rice"`
rice.json
rice_from_bag.json

- `"group":"rope"`
rope.json
rope_from_safety_net.json

- `"group":"scaffolding"`
scaffolding_from_canvas.json
minecraft\recipes\ scaffolding.json (vanilla recipe to be changed)

- `"group":"sweet_berry_cheesecake"`
sweet_berry_cheesecake.json
sweet_berry_cheesecake_from_slices.json

- `"group":"tatami"`
tatami.json
tatami_block_from_full.json

- `"group":"wheat_dough"`
wheat_dough_from_eggs.json
wheat_dough_from_water.json

### A possible solution is provided.
[data (FIXED).zip](https://github.com/vectorwing/FarmersDelight/files/15210425/data.FIXED.zip)

### Mod list

No need

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Interesting find! I never noticed those occurrences before. Funny enough, FD does make use of `group` for certain things like Canvas Signs. Guess it skipped me.

I will go over these and correct them. However, I don't think I can easily edit vanilla recipes so that they have a `group` defined, as that may mess up compatibility with other mods. They might have to remain their own separate entries.

**Comment by vectorwing** [comment]
Added on commit b7c82db! As mentioned above, some can't be grouped without vanilla overrides, which I'd rather not do. But the remaining ones should be suficient!
