### ISSUE TITLE
The game crashed whilst initializing game

### ISSUE THREAD

**Issue by JoFrankT** [vectorwing/FarmersDelight#915]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.32

### Description

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Farmer's Delight (farmersdelight) encountered an error during the common_setup event phase

### Steps to reproduce

On Launch

### Mod list

createbigcannons-forge-1.20.1-0.5.4.jar           |Create Big Cannons            |createbigcannons              |0.5.4-nightly-8b9cea|COMMON_SET|Manifest: NOSIGNATURE
		create_misc_and_things_ 1.20.1_4.0A.jar           |create: things and misc       |create_things_and_misc        |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		amendments-1.20-1.0.6.jar                         |Amendments                    |amendments                    |1.20-1.0.6          |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.4.jar                   |GeckoLib 4                    |geckolib                      |4.4.4               |COMMON_SET|Manifest: NOSIGNATURE
		createdeco-2.0.2-1.20.1-forge.jar                 |Create Deco                   |createdeco                    |2.0.2-1.20.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
		cccbridge-mc1.20.1-forge-1.6.3.jar                |CC:C Bridge                   |cccbridge                     |1.6.3-forge         |COMMON_SET|Manifest: NOSIGNATURE
		mimimod-1.20.1-4.0.5.jar                          |MIMI                          |mimi                          |1.20.1-4.0.5        |COMMON_SET|Manifest: NOSIGNATURE
		botarium-forge-1.20.1-2.3.3.jar                   |Botarium                      |botarium                      |2.3.3               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.3.0.4.jar                     |Just Enough Items             |jei                           |15.3.0.4            |COMMON_SET|Manifest: NOSIGNATURE
		Pehkui-3.8.0+1.20.1-forge.jar                     |Pehkui                        |pehkui                        |3.8.0+1.20.1-forge  |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.20-14.1.3.jar                   |Waystones                     |waystones                     |14.1.3              |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.20.1-11.1.3.0-build.0398.jar     |ForgeEndertech                |forgeendertech                |11.1.3.0            |COMMON_SET|Manifest: NOSIGNATURE
		ritchiesprojectilelib-1.0.0-369e88d+1.20.1-forge.j|Ritchie's Projectile Library  |ritchiesprojectilelib         |1.0.0-369e88d+1.20.1|COMMON_SET|Manifest: NOSIGNATURE
		mixinextras-forge-0.3.5.jar                       |MixinExtras                   |mixinextras                   |0.3.5               |COMMON_SET|Manifest: NOSIGNATURE
		design_decor-0.4-1.20.1.jar                       |Create: Design n' Decor       |design_decor                  |0.4.0               |COMMON_SET|Manifest: NOSIGNATURE
		create-confectionery1.20.1_v1.1.0.jar             |Create Confectionery          |create_confectionery          |1.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		CreateNumismatics-1.0.4+forge-mc1.20.1.jar        |Create: Numismatics           |numismatics                   |1.0.4+forge-mc1.20.1|COMMON_SET|Manifest: NOSIGNATURE
		create_dragon_lib-1.20.1-1.4.3.jar                |Create: Dragon Lib            |create_dragon_lib             |1.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		createdieselgenerators-1.20.1-1.2h.jar            |Create Diesel Generators      |createdieselgenerators        |1.20.1-1.2h         |COMMON_SET|Manifest: NOSIGNATURE
		sculkhorde-1.20.1-0.8.9.jar                       |Sculk Horde                   |sculkhorde                    |1.20.1-0.8.9        |COMMON_SET|Manifest: NOSIGNATURE
		Steam_Rails-1.6.3+forge-mc1.20.1.jar              |Create: Steam 'n' Rails       |railways                      |1.6.3+forge-mc1.20.1|COMMON_SET|Manifest: NOSIGNATURE
		DistantHorizons-2.0.1-a-1.20.1.jar                |Distant Horizons              |distanthorizons               |2.0.1-a             |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.20.1-7.2.2.jar                       |Balm                          |balm                          |7.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-11.1.118-forge.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		sound-physics-remastered-forge-1.20.1-1.3.1.jar   |Sound Physics Remastered      |sound_physics_remastered      |1.20.1-1.3.1        |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.2.32-universal.jar                |Forge                         |forge                         |47.2.32             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		modflared-1.2.0+release.47.jar                    |Modflared                     |modflared                     |1.2.0+release.47    |COMMON_SET|Manifest: NOSIGNATURE
		embeddium-0.3.14+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.14+mc1.20.1     |COMMON_SET|Manifest: NOSIGNATURE
		create_connected-0.7.4-mc1.20.1-all.jar           |Create: Connected             |create_connected              |0.7.4-mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.11.12-forge.jar                  |Moonlight Library             |moonlight                     |1.20-2.11.12        |COMMON_SET|Manifest: NOSIGNATURE
		Create-Guardian-Beam-Defense-1.3.0b-1.20.1.jar    |Guardian Beam Defense         |creategbd                     |1.3.0b-1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		mixinsquared-forge-0.1.1.jar                      |MixinSquared                  |mixinsquared                  |0.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		Jade-1.20.1-forge-11.7.1.jar                      |Jade                          |jade                          |11.7.1              |COMMON_SET|Manifest: NOSIGNATURE
		kffmod-4.10.0.jar                                 |Kotlin For Forge              |kotlinforforge                |4.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		curios-forge-5.9.0+1.20.1.jar                     |Curios API                    |curios                        |5.9.0+1.20.1        |COMMON_SET|Manifest: NOSIGNATURE
		ars_nouveau-1.20.1-4.6.0-all.jar                  |Ars Nouveau                   |ars_nouveau                   |4.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |COMMON_SET|Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.f.jar                         |Create                        |create                        |0.5.1.f             |COMMON_SET|Manifest: NOSIGNATURE
		create_central_kitchen-1.20.1-for-create-0.5.1.f-1|Create: Central Kitchen       |create_central_kitchen        |1.3.12              |COMMON_SET|Manifest: NOSIGNATURE
		destroy-1.20.1-0.8.jar                            |Destroy                       |destroy                       |0.8                 |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.20.1-84-FORGE.jar                     |Patchouli                     |patchouli                     |1.20.1-84-FORGE     |COMMON_SET|Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.6.15a.jar                       |Oculus                        |oculus                        |1.6.15a             |COMMON_SET|Manifest: NOSIGNATURE
		storagedrawers-1.20.1-12.0.3.jar                  |Storage Drawers               |storagedrawers                |12.0.3              |COMMON_SET|Manifest: NOSIGNATURE
		resourcefullib-forge-1.20.1-2.1.24.jar            |Resourceful Lib               |resourcefullib                |2.1.24              |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.15.jar                          |WorldEdit                     |worldedit                     |7.2.15+6463-5ca4dff |COMMON_SET|Manifest: NOSIGNATURE
		ars_creo-1.20.1-4.0.1.jar                         |Ars Creo                      |ars_creo                      |4.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		moremobvariants-forge+1.20.1-1.3.0.1.jar          |More Mob Variants             |moremobvariants               |1.3.0.1             |COMMON_SET|Manifest: NOSIGNATURE
		cc-tweaked-1.20.1-forge-1.110.3.jar               |CC: Tweaked                   |computercraft                 |1.110.3             |COMMON_SET|Manifest: NOSIGNATURE
		create_power_loader-1.4.0-mc1.20.1.jar            |Create: Power Loader          |create_power_loader           |1.4.0-mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		create-track-map-1.4+mc1.20.1-neoforge.jar        |Create Track Map              |createtrackmap                |1.4                 |COMMON_SET|Manifest: NOSIGNATURE
		AdChimneys-1.20.1-10.1.5.1-build.0365.jar         |Advanced Chimneys             |adchimneys                    |10.1.5.1            |COMMON_SET|Manifest: NOSIGNATURE
		valkyrienskies-120-2.3.0-beta.5.jar               |Valkyrien Skies 2             |valkyrienskies                |2.3.0-beta.5        |COMMON_SET|Manifest: NOSIGNATURE
		eureka-1201-1.5.0-beta.3.jar                      |VS Eureka Mod                 |vs_eureka                     |1.5.0-beta.3        |COMMON_SET|Manifest: NOSIGNATURE
		clockwork-1.20.1-0.1.16-forge-b3b22e39fe.jar      |Clockwork: Create x Valkyrien |vs_clockwork                  |1.20.1-0.1.16-forge-|COMMON_SET|Manifest: NOSIGNATURE
		cc_vs-1.20.1-forge-0.0.9.jar                      |CC: VS                        |cc_vs                         |1.20.1-forge-0.0.9  |COMMON_SET|Manifest: NOSIGNATURE
		create_enchantment_industry-1.20.1-for-create-0.5.|Create Enchantment Industry   |create_enchantment_industry   |1.2.9.c             |COMMON_SET|Manifest: NOSIGNATURE
		sliceanddice-forge-3.2.0.jar                      |Create Slice & Dice           |sliceanddice                  |3.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.20.1-1.2.2.jar                   |Create Crafts & Additions     |createaddition                |1.20.1-1.2.2        |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 3f54e658-7fed-4f66-a71b-b4de7de74404

### Logs

https://pastebin.com/yhb64PNu

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
This is a mixin-related crash with the mod **Supplementaries**. Farmer's Delight was simply the mod where the loading failed after this error happened.

Please try updating Supplementaries to the latest version. If that doesn't fix the issue, you can report the issue on their repository:
https://github.com/MehVahdJukaar/Supplementaries/issues
