### ISSUE TITLE
Rabbit Stew Jump Boost Description

### ISSUE THREAD

**Issue by QwertRvg** [vectorwing/FarmersDelight#916]
Could you make the description of Rabbit Stew mention the Jump Boost? That would be quite important for the player to know about.
![image](https://github.com/vectorwing/FarmersDelight/assets/89683173/4839a800-a90e-4d4b-a742-08f807be1308)

**Comment by vectorwing** [comment]
It was supposed to be a surprise effect, in the same vein as Golden Apples.
However, as of 1.21, this effect was removed, in favor of simply boosting the food properties of Rabbit Stew instead. 👍
