### ISSUE TITLE
Cutting Board Recipes Gone.

### ISSUE THREAD

**Issue by XenoHoe** [vectorwing/FarmersDelight#918]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.17

### Description

All farmer's delight cutting board recipes are gone. They were not removed by Craft tweaker nor KubeJS, as removing those mods and loading the game does not resolve the issue. It is also not the recipe type removed as cutting board recipes added by delightful still exist. I suspect it's some undocumented incompatibility but can't identify its cause.

### Steps to reproduce

1. Load game with following mods
2. Check any recipe checker/try cutting beef in cutting board

### Mod list

- additionalentityattributes 1.4.0.5+1.20.1
	- amendments 1.20-1.1.22
	- another_furniture 1.20.1-3.0.1
	- apoli 1.20.1-2.9.0.6
	- appleskin 2.5.1+mc1.20.1
	- architectury 9.2.14
	- argonauts 1.0.10
	- badoptimizations 2.1.1
	- bakery 1.1.10
	- balm 7.2.2
	- beachparty 1.1.5
	- bellsandwhistles 0.4.3-1.20.x
	- betteranimationscollection 8.0.0
	- bloomingnature 1.0.7
	- botarium 2.3.3
	- brewery 1.1.8
	- bucketlib 1.20.1-2.3.3.2
	- cadmus 1.0.8
	- caelus 3.2.0+1.20.1
	- calio 1.20.1-1.11.0.3
	- canary 0.3.3
	- candlelight 1.2.12.1
	- cloth_config 11.1.118
	- comforts 6.3.5+1.20.1
	- configurabledeath 1.20.1-1.0.0
	- constructionwand 1.20.1-2.11
	- copycats 1.20.1-1.2.6
	- crafttweaker 14.0.38
	- create 0.5.1.f
	- create_aquatic_ambitions 1.20.1-0.0.1
	- create_central_kitchen 1.3.12
	- create_connected 0.8.2-mc1.20.1
	- create_dragon_lib 1.4.3
	- create_enchantment_industry 1.2.9.d
	- create_high_pressure 1.1.0
	- create_jetpack 4.2.1
	- create_structures 0.1.1
	- create_things_and_misc 1.0.0
	- createaddition 1.20.1-1.2.3
	- createdeco 2.0.2-1.20.1-forge
	- createoreexcavation 1.4.3
	- createrailwaysnavigator 0.5.3-beta-1.20.1-forge
	- createtweaker 4.0.9
	- creativecore 2.11.30
	- culllessleaves 1.20.1-1.0.5
	- curios 5.9.1+1.20.1
	- curtain 1.3.2
	- deathfinder 8.0.1
	- distanthorizons 2.0.1-a
	- do_a_barrel_roll 3.5.6+1.20.1
	- doapi 1.2.12
	- dragonlib 1.20.1-2.1.8
	- easyanvils 8.0.2
	- easymagic 8.0.1
	- elytraslot 6.3.0+1.20.1
	- embeddium 0.3.19+mc1.20.1
	- embeddium_extra 0.5.4.2+mc1.20.1-build.118
	- embeddiumplus 1.2.12
	- emi 1.1.6+1.20.1+forge
	- entityculling 1.6.5
	- everycomp 1.20-2.6.56
	- explorerscompass 1.20.1-1.3.3-forge
	- farmersdelight 1.20.1-1.2.4
	- fastload 3.4.0
	- ferritecore 6.0.1
	- flightlib 2.1.0
	- flywheel 0.6.10-7
	- forge 47.2.17
	- fpsreducer 1.20-2.5
	- freecam 1.2.1+1.20
	- fusion 1.20.1-6.0.0.3
	- geckolib 4.4.4
	- goldenglitter 1.20.1-5.0.0.0
	- heracles 1.1.12
	- herbalbrews 1.0.7
	- hermes 1.6.0
	- immediatelyfast 1.2.17+1.20.4
	- iron_ender_chests 1.20-1.0.3
	- ironchests 5.0.2
	- item_obliterator 2.2.0
	- itemphysic 1.7.1
	- jade 11.9.2+forge
	- jadeaddons 5.2.2
	- jei 15.3.0.4
	- jeitweaker 8.0.6
	- jeresources 1.4.0.247
	- kotlinforforge 4.5.0
	- kubejs 2001.6.5-build.7
	- kubejs_create 2001.2.5-build.2
	- kubejsadditions 4.3.0
	- kubejsoffline 4.0.2
	- lanserverproperties 1.11.1
	- leavesbegone 8.0.0
	- letsdoaddon_compat 1.4.1
	- letsdoaddonstructures 1.7.1
	- libx 1.20.1-5.0.5
	- lmft 1.0.4+1.20.1
	- lootjs 1.20.1-2.11.0
	- meadow 1.3.15
	- memoryleakfix 1.1.5
	- minecraft 1.20.1
	- mixinextras 0.3.5
	- mixinsquared 0.1.2-beta.5
	- modernfix 5.17.0+mc1.20.1
	- moonlight 1.20-2.11.12
	- morevanillalib 1.20.1-5.0.1
	- mousetweaks 2.25.1
	- mr_piseks_cheaptemplates 1.0
	- naturescompass 1.20.1-1.11.2-forge
	- necronomicon 1.4.2
	- nethervinery 1.2.12
	- netmusic 0.0NONE
	- nochatreports 1.20.1-v2.2.2
	- noisium 2.0.3+mc1.20-1.20.1
	- obsidianui 0.2.1+mc1.20.1
	- oculus 1.6.15a
	- onlysilver 1.20.1-6.0.0.0
	- openpartiesandclaims 0.22.0
	- origins 1.20.1-1.10.0.7
	- packingtape 0.14.2
	- polymorph 0.49.5+1.20.1
	- ponderjs 1.3.1
	- probejs 6.0.0
	- puzzlesaccessapi 8.0.7
	- puzzleslib 8.1.18
	- quark 4.0-441
	- railways 1.6.4+forge-mc1.20.1
	- ratatouille 1.0
	- resourcefullib 2.1.24
	- rhino 2001.2.2-build.18
	- rubidium 0.7.1
	- ryoamiclights 0.2.1+mc1.20.1
	- simplecobalt 1.20.1-5.0.0.0
	- simplecorelib 1.20.1-6.0.1.2
	- simpleores 1.20.1-6.0.0.3
	- simpletungsten 1.20.1-5.0.0.0
	- simplytools 1.20.1-2.0.5
	- sliceanddice 3.2.0
	- spectrelib 0.13.15+1.20.1
	- sterlingblack 1.20.1-5.0.0.0
	- supplementaries 1.20-2.8.10
	- tectonic 2.3.4
	- terrablender 3.0.1.4
	- terraform 7.0.1
	- terralith 2.4.11
	- tfmg 0.8.0b
	- toms_storage 1.6.6
	- travelersbackpack 9.1.14
	- twigs 1.20.1-3.1.0
	- v_slab_compat 1.20-2.3
	- viner 2.2.0
	- vinery 1.4.19
	- visuality 2.0.2
	- w2w2 1.0
	- waystones 14.1.3
	- xaerominimap 24.1.1
	- xaeroworldmap 1.38.4
	- yet_another_config_lib_v3 3.4.4+1.20.1-forge
	- zeta 1.0-16

### Logs

https://pastebin.com/CkApLK5n

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by MetGang** [comment]
Caused by Item Obliterator and fixed in 2.2.1 version

See changelog
https://modrinth.com/mod/item-obliterator/version/2.2.1

**Comment by XenoHoe** [comment]
> Caused by Item Obliterator and fixed in 2.2.1 version
> 
> See changelog https://modrinth.com/mod/item-obliterator/version/2.2.1

Issue Fixed. Thanks.
