### ISSUE TITLE
Tomato Sauce recipe unavailable

### ISSUE THREAD

**Issue by Cakeykins** [vectorwing/FarmersDelight#919]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.32

### Description

The tomato sauce recipe just doesnt exist. Its an item i can use, but when i try to craft it or look for a recipe, it doesnt show up no matter where i look. I tested this on vanilla with just the mod installed, and I discovered it worked fine just as is, so its a matter of what mod is messing with it.

### Mod list

AdFinders-1.20.1-9.1.6.0-build.0424
AdFinders-1.20.1-9.1.7.0-build.0514
AdLods-1.20.1-8.1.2.0-build.0424
aether_delight_1.0.0_forge_1.20.1
aether-1.20.1-1.4.2-neoforge
aether-redux-2.0.15-1.20.1-neoforge 
Architects-Palette-1.20.1-1.3.6.1
architectury-9.2.14-forge
ascended quark-1.20.1-1.0.3
balm-forge-1.20.1-7.2.2
baubley-heart-canisters-1.20.1-1.0.5
BiomesOPlenty-1.20.1-18.0.0.598
Blocks+1.20.1-1.7
chefs-delight-1.0.3-forge-1.20.1
chisel+forge+1.20.1-1.7.2
collectorsreap-1.20.1-1.3
constructionwand-1.20.1-2.11
Croptopia-1.20.1-FABRIC-3.0.4
Croptopia Delight-1.20.1_1.2.2-forge
curios-forge-5.9.1+1.20.1
deep_aether-1.20.1-1.0.3
Delightful-1.20.1-3.5.5
EasyMagic-v8.0.1-1.20.1-Forge
easy-villagers-forge-1.20.1-1.1.4
embeddium-0.3.19+mc1.20.1-all
endersdelight-1.20.1-1.0.3
FarmersDelight-1.20.1-1.2.4
ferritecore-6.0.1-forge
flib-1.20.1-0.0.13
ForgeEndertech-1.20.1-11.1.3.1-build.0496
FramedBlocks-9.2.2
fruitsdelight-1.0.9
geckolib-forge-1.20.1-4.4.4
Gobber2-Forge-1.20.1-2.8.9
ImmediatelyFast-Forge-1.2.15+1.20.4
Jade-1.20.1-forge-11.9.2
jei-1.20.1-forge-15.3.0.4
JRFTL-1.20.1-1.6.0
mcw-lights-1.0.6-mc1.20.1forge
miners_delight-1.20.1-1.2.3
MobCapturing Tool-forge-1.20.1-3.0.2
Mouse Tweaks-forge-mc1.20.1-2.25.1
NaturesCompass-1.20.1-1.11.2-forge
nethersdelight-1.20.1-4.0
oreexcavation-1.13.170
Patchouli-1.20.1-84-FORGE
PuzzlesLib-v8.1.20-1.20.1-Forge
quark_delight_1.0.0_forge_1.20.1
Quark-4.0-450
SimpleStorageNetwork-1.20.1-1.10.0
sophisticatedbackpacks-1.20.1-3.20.5.1044
sophisticatedcore-1.20.1-0.6.22.611
storagedrawers-1.20.1-12.0.3
TerraBlender-forge-1.20.1-3.0.1.7
Twigs-1.20.1-3.1.0
Unusual Delight_2.3
VariantCrafting Tables-1.20.1-2.0.2
waystones-forge-1.20-14.1.3
Xaeros_Minimap_24.1.1_Forge_1.20 
XaerosWorldMap_1.38.4_Forge_1.20
Zeta-1.0-16

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
I need more information about this before I can help you. Please provide:
- Your game logs (latest.log in your instance folder);
- Some screenshots of the item, or of you trying to craft the item.

Tomato Sauce is prepared on a Cooking Pot, with 2 Tomatoes (in separate stacks on the grid). Are you able to press R to check its recipe on JEI?

**Comment by vectorwing** [comment]
Closing this issue for now. Feel free to reopen with the info requested above.
