### ISSUE TITLE
Placing Canvas Sign BUG (archlight)

### ISSUE THREAD

**Issue by CookieComSorvet** [vectorwing/FarmersDelight#920]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.20

### Description

It’s a bug where the placed signs simply vanish, yet they are still there! They only break when I remove the block where they are positioned and then replace it, after which they turn into an item. A HUGE crash report appears in the server console when this issue occurs.
This issue don't exist on Singleplayer. B

### Steps to reproduce

I had already played normally with this mod on the regular Forge server.

1. Installed Archlight 1.20.1 but using the same "world", in the host i just switched Forge for Archlight server

2. Pick the sign
3. Put on the floor and Done.

https://github.com/vectorwing/FarmersDelight/assets/111860641/e98e9c1d-6b17-413b-8b6a-fa05d1310d3f

### Mod list

- architectury-9.2.14-forge
- FarmersDelight-1.20.1-1.2.4
- letsdo-API-forge-1.2.13-forge
- letsdo-beachparty-forge-1.1.5

i tested with 1 - 190 mods, and the issue is the same on both scenarius. 

### Logs

[latest.log](https://github.com/user-attachments/files/15896284/latest.log)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [x] I am using performance or shader mods

**Comment by vectorwing** [comment]
Arclight uses a custom implementation of Forge and Bukkit, which are known to conflict with mods, so I'm unable to support it.

You should try and report this issue to the Arclight issues board, as they may have a better idea of what's going on, or if they're able to support modded signs.
