### ISSUE TITLE
Bugged Cooking pod recipes

### ISSUE THREAD

**Issue by Maxi90909** [vectorwing/FarmersDelight#922]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.3.1

### Description

Some cooking recipes are unavalible due to missing forge tags, Only way to fix this is to reload with the /reload command. If it works and doesn't trow up any errors.

### Steps to reproduce

1. Launch the game
2. Load a world
3. Look up cooking recipes in of the cooking pot
4. Some recipes are unavalible and have a missing forge tag with items that are in the game.

### Mod list

https://pastebin.com/vuLHZZFf

### Logs

Lastest Logs: https://mclo.gs/HtNKAKZ

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by Maxi90909** [comment]
Some screenshots so you know what I mean.
![Screenshot (36)](https://github.com/vectorwing/FarmersDelight/assets/76815835/f0625b48-8ee7-4bc2-9828-fe23a15e6dbe)
![Screenshot (37)](https://github.com/vectorwing/FarmersDelight/assets/76815835/70c75650-a8f0-48b0-82f9-33b4d2553098)

**Comment by vectorwing** [comment]
These kinds of tag errors are usually caused by add-ons, when they wrongly assign tags items which don't exist, such as from a missing mod.

Try disabling Farmer's Delight add-ons and see if the issue is resolved; chances are one of them is causing it.
