### ISSUE TITLE
Items displaying incorrectly

### ISSUE THREAD

**Issue by wonkers27** [vectorwing/FarmersDelight#923]
### Minecraft version

1.18.2

### Farmer's Delight version

1.2.3

### Forge version

40.2.7

### Description

Item names not displaying properly in inventory
![Minecraft_ 1 18 2 2024-06-25 10_14_55 PM](https://github.com/vectorwing/FarmersDelight/assets/148589588/915d118e-0ce3-4ede-b9f3-9503c68e992e)
![Minecraft_ 1 18 2 2024-06-25 10_15_44 PM](https://github.com/vectorwing/FarmersDelight/assets/148589588/c480c7b5-c8af-4c1d-9459-b090832f2937)

### Steps to reproduce

1. Open creative inventory
2. Go to the Farmer's Delight tab
3. All the names are displaying incorrectly

### Mod list

Mod List: 
		TreeChop-forge-1.18.2-0.17.7.jar
		YungsBetterDungeons-1.18.2-Forge-2.1.0.jar
		ftb-essentials-1802.2.2-build.83.jar
		YungsBetterWitchHuts-1.18.2-Forge-1.0.1.jar
		netherportalfix-forge-1.18.2-9.0.1.jar
		areas-1.18.2-5.2.jar
		YungsBetterOceanMonuments-1.18.2-Forge-1.0.3.jar
		Tips-Forge-1.18.2-5.0.11.jar
		mcw-windows-2.2.1-mc1.18.2forge.jar
		macawsbridgesbyg-1.18.2-1.6.jar
		aquaculture_delight_1.0.0_forge_1.18.2.jar
		sophisticatedcore-1.18.2-0.6.4.604.jar
		rubidium-0.5.6.jar
		villagernames-1.18.2-7.0.jar
		CTM-1.18.2-1.1.5+5.jar
		Controlling-forge-1.18.2-9.0+23.jar
		Placebo-1.18.2-6.6.7.jar
		modernfix-forge-5.18.0+mc1.18.2.jar
		YungsApi-1.18.2-Forge-2.2.9.jar
		mixinextras-forge-0.3.2.jar
	 	Bookshelf-Forge-1.18.2-13.3.56.jar
		sophisticatedbackpacks-1.18.2-3.20.2.1036.jar
		twigs-1.1.4-patch4+1.18.2-forge.jar
		takesapillage-1.0.3-1.18.2.jar		
                mcw-doors-1.1.1forge-mc1.18.2.jar
		jeed-1.18.2-1.11.jar
	        TreeChop-Jade-1.18.2-forge-0.1.1.jar
		Steam_Rails-1.4.8+forge-mc1.18.2-build.23.jar
		balm-3.2.6.jar
		SnowRealMagic-1.18.2-forge-4.2.4.jar
		kelpfertilizer-1.18.2-3.1.jar
		JustEnoughResources-1.18.2-0.14.1.171.jar
		YungsBetterNetherFortresses-1.18.2-Forge-1.0.0.jar
		LeavesBeGone-v3.0.0-1.18.2-Forge.jar
		corpse-1.18.2-1.0.1.jar
		AdvancementPlaques-1.18.2-1.4.5.1.jar
		chipped-forge-1.18.2-2.0.1.jar
		mcw-bridges-3.0.1-mc1.18.2forge.jar
		endrem_forge-5.2.0-R-1.18.2.jar
		mcw-trapdoors-1.1.3-mc1.18.2forge.jar
		mcw-fences-1.1.2-mc1.18.2forge.jar
		supermartijn642corelib-1.1.17-forge-mc1.18.jar
		curios-forge-1.18.2-5.0.9.2.jar
		Patchouli-1.18.2-71.1.jar
		oculus-mc1.18.2-1.6.4.jar
		collective-1.18.2-7.7.jar
		YungsExtras-1.18.2-Forge-2.1.0.jar
		bettervillage-forge-1.18.2-3.2.0.jar
		BetterThirdPerson-Forge-1.18.2-1.9.0.jar
		YungsBetterStrongholds-1.18.2-Forge-2.1.1.jar
		mcw-roofs-2.3.0-mc1.18.2forge.jar
		cfm-7.0.0-pre35-1.18.2.jar
		architectury-4.12.94-forge.jar
		mcw-furniture-3.2.2-mc1.18.2forge.jar
		YungsBetterEndIsland-1.18.2-Forge-1.0.jar
		JadeAddons-1.18.2-forge-2.5.0.jar
		inventoryessentials-forge-1.18.2-4.0.3.jar
		towns_and_towers_forge-1.10.0.1+1.18.2.jar
		YungsBetterMineshafts-1.18.2-Forge-2.2.jar
		geckolib-forge-1.18-3.0.57.jar
		BetterAdvancements-1.18.2-0.2.0.146.jar
		Kiwi-1.18.2-forge-6.1.4.jar
		inventorysorter-1.18-19.0.0.jar
		Cucumber-1.18.2-5.1.5.jar
		ftb-library-forge-1802.3.11-build.177.jar
		nourished-nether-1.18.2-v22.jar
		jei-1.18.2-forge-10.2.1.1005.jar
		VisualWorkbench-v3.3.0-1.18.2-Forge.jar
		libraryferret-forge-1.18.2-4.0.0.jar
		goblintraders-1.8.0-1.18.2.jar
		waystones-forge-1.18.2-10.2.2.jar
		Structory-1.18.2-1.0.2.jar
		FastSuite-1.18.2-3.0.2.jar
		Clumps-forge-1.18.2-8.0.0+17.jar
		journeymap-1.18.2-5.9.8-forge.jar
		comforts-forge-1.18.2-5.0.0.6.jar
		NaturesCompass-1.18.2-1.9.7-forge.jar
		artifacts-1.18.2-4.2.3.jar
		configured-2.0.1-1.18.2.jar
		lazydfu-1.0-1.18+.jar
		YungsBetterDesertTemples-1.18.2-Forge-1.3.1.jar
		fusion-1.1.1-forge-mc1.18.jar
		blueprint-1.18.2-5.5.0.jar
		woodworks-1.18.2-1.2.0.jar
		buzzier_bees-1.18.2-4.0.0.jar
		forge-1.18.2-40.2.7-universal.jar
		morezombievillagers-1.18.2-3.4.jar
		friendsandfoes-forge-mc1.18.2-1.4.8.jar
		selene-1.18.2-1.17.14.jar
		supplementaries-1.18.2-1.5.18.jar
		craftingtweaks-forge-1.18.2-14.0.9.jar
		client-1.18.2-20220404.173914-srg.jar
		upgrade_aquatic-1.18.2-4.0.0.jar
		TConstruct-1.18.2-3.6.4.113.jar
		voicechat-forge-1.18.2-2.5.17.jar
		EnchantmentDescriptions-Forge-1.18.2-10.0.12.jar
		TerraBlender-forge-1.18.2-1.2.0.126.jar
		MouseTweaks-forge-mc1.18-2.21.jar
		Jade-1.18.2-forge-5.3.2.jar
		CullLessLeaves-Reforged-1.18.2-1.0.5.jar
		e4mc_minecraft-5.0.0-forge.jar
		jeiintegration_1.18.2-9.0.0.37.jar
		Iceberg-1.18.2-forge-1.0.49.jar
		flywheel-forge-1.18.2-0.6.10-105.jar
		create-1.18.2-0.5.1.f.jar
		create_central_kitchen-1.18.2-for-create-0.5.1.f-1.39.d.jar
		Mantle-1.18.2-1.9.50.jar
		Croptopia-1.18.2-FORGE-2.1.0.jar
		create-stuff-additions1.18.2_v2.0.4a.jar
		FastWorkbench-1.18.2-6.1.1.jar
		polymorph-forge-1.18.2-0.50.jar
		JustEnoughProfessions-1.18.2-1.3.0.jar
		CroptopiaDelight-1.18.2_1.2.2-forge.jar
		StorageDrawers-1.18.2-10.2.1.jar
		randomvillagenames-1.18.2-3.4.jar
		PickleTweaks-1.18.2-6.1.2.jar
		FastFurnace-1.18.2-6.0.3.jar
		creeperoverhaul-1.3.1-forge.jar
		appleskin-forge-mc1.18.2-2.5.1.jar
		alexsdelight-1.18.2-1.3.3.jar
		citadel-1.11.3-1.18.2.jar
		alexsmobs-1.18.6.jar
		FarmersDelight-1.18.2-1.2.1.jar
		NethersDelight-1.18.2-2.2.0.jar
		lootr-forge-1.18.2-0.3.29.71.jar
		ferritecore-4.2.2-forge.jar
		connectedglass-1.1.11-forge-mc1.18.jar
		PuzzlesLib-v3.5.9-1.18.2-Forge.jar
		Oh_The_Biomes_You'll_Go-forge-1.18.2-1.5.1.jar
		macawsroofsbyg-1.18.2-1.3.jar
		mcwfencesbyg-forge-1.18.2-1.4.jar
		Aquaculture-1.18.2-2.3.12.jar
		Healing Bed 1.18.2.jar
		mcwfurnituresbyg-1.18.2-1.2.jar
		expandability-6.0.0.jar
		End's Phantasm - BETAv1.2.10.5 - 1.18.2.jar
		healingcampfire-1.18.2-5.2.jar                    

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by wonkers27** [comment]
Nvm I found the issue

**Comment by KatoNamus** [comment]
> Nvm I found the issue

Hi, I'm experiencing the same problem. What solution did you find, please?
