### ISSUE TITLE
Not Launching in Multiplayer Server

### ISSUE THREAD

**Issue by Kuvorious** [vectorwing/FarmersDelight#924]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.18

### Description

When trying to load into a multiplayer server that I'm locally hosting, the game will end the connection before I can load in. It says:
Internal Exception: io.netty.handler.codec.DecoderException:java.lang.IndexOutOfBoundsException: index 14. length: 105 (expected: range(0, 62)

### Steps to reproduce

1. join a hosted server

### Mod list

Just Farmer's Delight alone

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by echoless3484** [comment]
Try running this in a vanilla server and a forge server same version without Farmers Delight.

**Comment by Kuvorious** [comment]
> Try running this in a vanilla server and a forge server same version without Farmers Delight.

Ironically I actually just tried running a forge server before checking this, i can't even get that to work. something seems to be wrong with the run.bat file

**Comment by vectorwing** [comment]
Please provide your server logs, and if possible, client logs, so I can have more info on what's going on.

**Comment by vectorwing** [comment]
Closing this issue for now. Feel free to reopen with the info requested above.

**Comment by rob816** [comment]
hey @vectorwing, I have the same problem and also found out it had to do with Farmers Delight. When trying to connect to a Paper server acting as a lobby for my modded server I am getting the error mentioned in the issue. 

I regonize my situation is a bit unique, but here are my logs anyway incase there is anything useful in there for you

These are the logs from the client side as I dont see anything other than the client being disconnected on the server logs. 

[debug.log](https://github.com/user-attachments/files/17264422/debug.log)
[latest.log](https://github.com/user-attachments/files/17264423/latest.log)
