### ISSUE TITLE
Rice is not harvested correctly by Create's Mechanical Harvester blocks

### ISSUE THREAD

**Issue by BlackCat64** [vectorwing/FarmersDelight#926]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.0

### Description

Mechanical Harvesters break Rice Panicles as soon as they grow to be 2 blocks tall, not when they are actually fully grown. This means they always drop nothing, making Rice farms useless. This didn't happen in previous versions of the mod, although it may be a Create issue, so I will post a bug report there as well.

### Steps to reproduce

1. Build a rice farm, like the one in [this video](https://www.youtube.com/watch?v=5zQDbNrEg8w)
2. Turn on the contraption
3. The harvesters will not harvest Rice Panicle items, instead they will break the rice before it has the chance to grow fully

### Mod list

[crash-2024-06-29_21.44.08-client.txt](https://github.com/user-attachments/files/16042159/crash-2024-06-29_21.44.08-client.txt)
Crash report file attached

### Logs

[latest.log](https://github.com/user-attachments/files/16042160/latest.log)
latest.log file attached

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by DariusZeBaguette** [comment]
try installing create: central kitchen, it makes farmers delight and create fully compatible together, should fix that issue

**Comment by BlackCat64** [comment]
Ok that worked, thank you.
