### ISSUE TITLE
Vegetable soup 

### ISSUE THREAD

**Issue by whymehers** [vectorwing/FarmersDelight#931]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### Forge version

dont know

### Description

When ever I try and make vegetable soup it always makes a cabbage rap and I can only make vegetable soup with clover and I have tried everything the layout the bowls and its worked on other versions but not the lattest Better Mc v28.

### Mod list

It is the better mc modpack v28

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Cabbage Rolls have a very broad recipe. If you're adding cabbage first, then a second valid ingredient, it will lock into making Cabbage Rolls before you add the remaining ingredients for Vegetable Soup.

Try adding Cabbage last, and the recipe should work again. You can leave 1 serving into the pot as well, to lock it into only making that recipe.
