### ISSUE TITLE
Make 1 rope from 1 stick

### ISSUE THREAD

**Issue by Obogger** [vectorwing/FarmersDelight#932]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.3.1

### Description

Currently playing Better MC 4, version 28, 1.20.1. 

When placing sticks with the help of the mod Supplementaries above a tomato plant it will act as a rope and when the plant grows and becomes 2 blocks high the stick is then converted in to a rope which you can then mine functionally giving you 1 rope from 1 stick.
![image](https://github.com/user-attachments/assets/b0bac2b1-1672-4d61-93d4-172d30f0dc72)
![image](https://github.com/user-attachments/assets/844156e4-9acb-4d6c-8ece-2895b611e36a)

Thus giving me one extra rope and not allowing me to place sticks above tomato plants without them converting to ropes.

### Steps to reproduce

1. Place a tomato plant
2. Place stick above tomato plant
3. Wait for it to grow 2 blocks tall
4. Mine rope that got converted from the stick

### Mod list

https://www.modpackindex.com/modpack/64026/better-mc-forge-bmc4

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [x] I am using performance or shader mods

**Comment by MehVahdJukaar** [comment]
will be fixed next supplementaries update

**Comment by vectorwing** [comment]
As mentioned above, this seems to be an issue with Supplementaries.
Please follow the mod's updates for a potential fix. 👍
