### ISSUE TITLE
Feature Request: Datapack support for Cutting Board recipes

### ISSUE THREAD

**Issue by FrogBirddd** [vectorwing/FarmersDelight#94]
Basically what the title says, for my modpack I'd like to add more to the cutting board but currently it does not seem to work.

**Comment by vectorwing** [comment]
The Cutting Board is already fully compatible with .json recipes, much like other forms of crafting. Chances are something went wrong on your setup. 

Could you post your .json files here, and the filepath/namespace you're putting them on? I can take a look.
Also, check your game logs during world load; if something failed on your recipes, there might be something there.

**Comment by FrogBirddd** [comment]
After checking the logs I found the issue, I had used the wrong tags for the tool types. Thanks for the help:)

**Comment by FrogBirddd** [comment]
Can confirm that they now work, thanks again!
