### ISSUE TITLE
Kelp Roll is horribly underpowered

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#940]
### Minecraft version

1.21

### Farmer's Delight version

Newest

### Forge version

133

### Description

For some unknown reason, Kelp Rolls (not slices) are horribly weak, being worse than Kelp Roll Sliced

### Steps to reproduce

1. View Kelp Roll with Apple Skin mod
2. See how little hunger and saturation it gives

### Mod list

N/A

### Logs

N/A

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Seems I copied the wrong line when rewriting its food properties.

**Comment by vectorwing** [comment]
Fixed on commit 779c87f.
