### ISSUE TITLE
[Suggestion] Canvas Signs Tags

### ISSUE THREAD

**Issue by TheBedrockMaster** [vectorwing/FarmersDelight#941]
I know they already share a tag but it would be nice if Farmer's Delight Signs and Hanging Signs had the `minecraft:signs` and `minecraft:hanging_signs` item tags.

**Comment by vectorwing** [comment]
Canvas Signs are already tagged as blocks, but turns out I never tagged them as items. I can take a look at it.

**Comment by vectorwing** [comment]
Added on commit cd4eed8. 👍
