### ISSUE TITLE
Stuffed Pumpkin gives Comfort instead of Nourishment

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#943]
![image](https://github.com/user-attachments/assets/74168ee4-172b-47df-b6ae-08b29bd1bfef)

### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### Forge version

145

### Description

Instead of giving Nourishment, Stuffed Pumpkin gives Comfort instead

### Steps to reproduce

1. View tooltip on Bowl of Stuffed Pumpkin
2. See result

### Mod list

N/A

### Logs

N/A

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
I had indeed changed this on 1.21 only, but didn't realize it wasn't always this way before you mentioned it.

Stuffed Pumpkin's portion is served on a bowl, so it should have given Comfort. Thie fact that it always gave Nourishment might have been a relic from back then, when Comfort wasn't as good as it is now. I'll likely update the 1.20 ports to also have it give Comfort.
