### ISSUE TITLE
Knife cannot be enchanted with Looting in Survival

### ISSUE THREAD

**Issue by dragonfire0612** [vectorwing/FarmersDelight#944]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### Forge version

21.0.139

### Description

![2024-07-29_17 48 30](https://github.com/user-attachments/assets/229d7ac2-1420-465d-a97e-2835ba79b809)
![2024-07-29_17 48 31](https://github.com/user-attachments/assets/5009ad27-8df2-4593-ab1c-3ee402fd99bb)
![2024-07-29_17 48 38](https://github.com/user-attachments/assets/e64b734e-665d-4c0c-9a4a-f0ad26cded92)
![2024-07-29_17 48 39](https://github.com/user-attachments/assets/26e0bd2f-c276-4db7-8ca2-bb76e91155be)
![2024-07-29_17 48 41](https://github.com/user-attachments/assets/9a2bfbe2-e4f4-4179-89ce-c68d4d743e60)
![2024-07-29_17 48 29](https://github.com/user-attachments/assets/5d58d076-94e8-4434-ab5f-9f657a3d8ab7)

### Steps to reproduce

1. Open world in Creative mode
2. Place down anvil
3. Grab Knife from Creative inventory
4. Grab Looting from Creative inventory
5. Try to enchant knife in Creative
6. Switch to Survival
7. Try to enchant knife in Survival

### Mod list

appleskin-neoforge-mc1.21-3.0.4
Aquaculture-1.21-2.7.7
arts-and-crafts-neoforge-1.21-1.1.7
balm-neoforge-1.21-21.0.14-all
BiomesOPlenty-neoforge-1.21-21.0.0.12
easy-villagers-neoforge-1.21-1.1.15
enchanted-vertical-slabs-2.0.2-neoforge-mc1.21
FarmersDelight-1.21-1.2.4
ferritecore-7.0.0-neoforge
GlitchCore-neoforge-1.21-2.0.0.2
goldenhopper-neoforge-1.21-1.5.3
jei-1.21-neoforge-19.5.0.56
kleeslabs-neoforge-1.21-21.0.2
modernfix-neoforge-5.19.0+mc1.21
SereneSeasons-neoforge-1.21-10.0.0.2
squidnoglitch-mc1.21-v1.0.3-neoforge
TerraBlender-neoforge-1.21-4.0.0.1
Xaeros_Minimap_24.2.1_NeoForge_1.21
XaerosWorldMap_1.38.8_NeoForge_1.21

### Minimal instance

- [x] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Should be fixed on commit 779c87f.
