### ISSUE TITLE
[1.21 Crash] Client crashing opening inventory

### ISSUE THREAD

**Issue by MokahTGS** [vectorwing/FarmersDelight#945]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### Forge version

Neoforge 21.0.145

### Description

Crash when trying to open the inventory: https://pastebin.com/3Y6aJYxb

### Mod list

https://pastebin.com/3Y6aJYxb

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This crash is unrelated to Farmer's Delight, and is instead caused by an add-on called **Sweet Delight**.
Please forward this issue to its creator here: https://www.curseforge.com/minecraft/mc-mods/sweet-delight
