### ISSUE TITLE
[1.21] Mod loading error has occurred - Neoforge

### ISSUE THREAD

**Issue by fragilember** [vectorwing/FarmersDelight#950]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### Forge version

21.0.95-beta

### Description

I am using the Complementaries shaders with Iris & Sodium (beta versions) installed as well.

![image](https://github.com/user-attachments/assets/8f799d87-b800-48b3-9851-cd1b8d07af5d)

### Steps to reproduce

This happens when I try to load up the game after putting the .jar file into /mod folder

### Mod list

	ModLauncher: 11.0.4+main.d2e20e43
	ModLauncher launch target: forgeclient
	ModLauncher services: 
		sponge-mixin-0.14.0+mixin.0.8.6.jar mixin PLUGINSERVICE 
		loader-4.0.18.jar slf4jfixer PLUGINSERVICE 
		loader-4.0.18.jar runtime_enum_extender PLUGINSERVICE 
		at-modlauncher-10.0.1.jar accesstransformer PLUGINSERVICE 
		loader-4.0.18.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-11.0.4.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-11.0.4.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		javafml@4.0
		lowcodefml@4.0
		minecraft@4.0
	Mod List: 
		FarmersDelight-1.21-1.2.4.jar                     |Farmer's Delight              |farmersdelight                |1.2.4               |Manifest: NOSIGNATURE
		client-1.21-20240613.152323-srg.jar               |Minecraft                     |minecraft                     |1.21                |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		freecam-neoforge-1.3.0-beta1+mc1.21.jar           |Freecam                       |freecam                       |1.3.0-beta1+mc1.21  |Manifest: NOSIGNATURE
		iris-neoforge-1.8.0-snapshot+mc1.21-local.jar     |Iris                          |iris                          |1.8.0-snapshot+mc1.2|Manifest: NOSIGNATURE
		handcrafted-neoforge-1.21-4.0.1.jar               |Handcrafted                   |handcrafted                   |4.0.1               |Manifest: NOSIGNATURE
		fabric-api-base-0.4.42+d1308dedd1.jar             |Forgified Fabric API Base     |fabric_api_base               |0.100.4             |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.3.0+e3455cb4d1.jar       |Forgified Fabric Renderer API |fabric_renderer_api_v1        |0.100.4             |Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.21-3.0.9.jar            |Resourceful Lib               |resourcefullib                |3.0.9               |Manifest: NOSIGNATURE
		bagofyurting-1.21-5.0.0.0.jar                     |Bag of Yurting                |bagofyurting                  |5.0.0.0             |Manifest: NOSIGNATURE
		jei-1.21-neoforge-19.5.0.35.jar                   |Just Enough Items             |jei                           |19.5.0.35           |Manifest: NOSIGNATURE
		fabric_rendering_data_attachment_v1-0.3.46+1.21.ja|Fabric Data Attachment API    |fabric_rendering_data_attachme|0.3.46+1.21         |Manifest: NOSIGNATURE
		sodium-neoforge-1.21-0.6.0-alpha.2.jar            |Sodium                        |sodium                        |0.6.0-alpha.2       |Manifest: NOSIGNATURE
		BetterF3-11.0.1-NeoForge-1.21.jar                 |BetterF3                      |betterf3                      |11.0.1              |Manifest: NOSIGNATURE
		In-Control-Mod-NeoForge-1.21.jar                  |InControl                     |incontrol                     |1.21-10.0.0         |Manifest: NOSIGNATURE
		cloth-config-neoforge-15.0.127-neoforge.jar       |Cloth Config v15 API          |cloth_config                  |15.0.127            |Manifest: NOSIGNATURE
		neoforge-21.0.95-beta-universal.jar               |NeoForge                      |neoforge                      |21.0.95-beta        |Manifest: NOSIGNATURE
		travelersbackpack-neoforge-1.21-10.0.2.jar        |Traveler's Backpack           |travelersbackpack             |10.0.2              |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.10+9afaaf8cd1.jar    |Forgified Fabric BlockView API|fabric_block_view_api_v2      |0.100.4             |Manifest: NOSIGNATURE

### Logs

log: https://mclo.gs/AatvoXJ
crash report: https://mclo.gs/VWPVw1l

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
You are using an outdated version of NeoForge. Update it to latest and it should fix the issue.
