### ISSUE TITLE
knife durability doesn't go down during normal use

### ISSUE THREAD

**Issue by NeoForce0** [vectorwing/FarmersDelight#956]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### Forge version

47.2.30

### Description

I noticed when I'm cutting down grass and wheat with knife, the knife durability isn't going down with normal use as any other tool. 

### Mod list

doesn't crash

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
In Minecraft, tools don't lose durability when breaking blocks with no hardness (instamine), like grass and crops. Knives are no exception here, and it's somewhat intended.

The only exception is when the block has hardness, but the tool is efficient enough to instamine it; in such cases, the tool takes damage normally.
