### ISSUE TITLE
[1.21] add missing `c:foods/soup` tag to food items

### ISSUE THREAD

**Issue by ffuentesm** [vectorwing/FarmersDelight#960]
I noticed that a lot of the food items that would fall under the soup/stew category have no tags on them, as vanilla soup/stew items do have those tags.
![image](https://github.com/user-attachments/assets/be2d0f39-825e-464c-90bf-ecd8e1182cb7)
![image](https://github.com/user-attachments/assets/6d0eaf25-8777-43ff-8568-559c466ed9a0)

So food items like bone broth, beef stew, chicken soup, baked cod stew, vegetable soup, etc. Should have that tag as they fall under what the vanilla items are tagged as.

**Comment by vectorwing** [comment]
Added on PR https://github.com/vectorwing/FarmersDelight/pull/973 by @MerchantPug.
