### ISSUE TITLE
server crashed after opening a chest loot

### ISSUE THREAD

**Issue by Saobby** [vectorwing/FarmersDelight#968]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.2

### NeoForge version

47.3.0

### Description

Server crashed after opening a chest loot.

### Steps to reproduce

1. Open any chest loot

### Mod list

		server-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: NOSIGNATURE
		Terralith_1.20.x_v2.5.4.jar                       |Terralith                     |terralith                     |2.5.4               |DONE      |Manifest: NOSIGNATURE
		[ũ������] FarmersDelight-1.20.1-1.2.2.jar         |Farmer's Delight              |farmersdelight                |1.20.1-1.2.2        |DONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		flywheel-forge-1.20.1-0.6.10-7.jar                |Flywheel                      |flywheel                      |0.6.10-7            |DONE      |Manifest: NOSIGNATURE
		[��е����] create-1.20.1-0.5.1.f.jar               |Create                        |create                        |0.5.1.f             |DONE      |Manifest: NOSIGNATURE
		[ʷʫս��] epicfight-forge-20.9.1-1.20.1.jar         |Epic Fight                    |epicfight                     |20.9.1              |DONE      |Manifest: NOSIGNATURE
		corpse-forge-1.20.1-1.0.12.jar                    |Corpse                        |corpse                        |1.20.1-1.0.12       |DONE      |Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.12.1.46.jar                   |Just Enough Items             |jei                           |15.12.1.46          |DONE      |Manifest: NOSIGNATURE

### Logs

[crash-2024-08-22_15.04.23-server.txt](https://github.com/user-attachments/files/16706827/crash-2024-08-22_15.04.23-server.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [x] I am using performance or shader mods

**Comment by vectorwing** [comment]
You are using an outdated version of Farmer's Delight; this bug was fixed in 1.2.2a and above.
Please update to the current latest version, **1.2.4**, and the issue should be fixed. 👍
