### ISSUE TITLE
Crash on item place

### ISSUE THREAD

**Issue by Zelioth** [vectorwing/FarmersDelight#975]
### Minecraft version

1.21/1.21.1

### Farmer's Delight version

1.2.4

### NeoForge version

21.1.23

### Description

When placing some blocks the game game and server will crash 

### Steps to reproduce

place the block in the log

### Mod list

Friends United 2.1 https://www.curseforge.com/minecraft/modpacks/friends-united-2-1

### Logs

[crash-2024-08-24_07.39.53-client.txt](https://github.com/user-attachments/files/16737437/crash-2024-08-24_07.39.53-client.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by theendercore** [comment]
this is fixed in pr #977

**Comment by Zelioth** [comment]
Your mod is also (From testing) mostly compatible with 1.21.1 unless issues are found in further testing once this update is released. I was wondering if you'd mark it as 1.21.1 so the updates would show in that version as well

**Comment by theendercore** [comment]
Fun fact that this is an issue on 1.20 :)

**Comment by vectorwing** [comment]
Fixed on PR #977 by @theendercore, as mentioned above. Should be out in the next hotfix, which will technically just be the port to 1.21.1 :smile:
