### ISSUE TITLE
Eating a pie doesn't change its hitbox

### ISSUE THREAD

**Issue by lzm11111111** [vectorwing/FarmersDelight#978]
### Minecraft version

1.21.1

### Farmer's Delight version

1.2.4

### NeoForge version

21.1.27

### Description

When eating a pie, its hitbox doesn't changed, this is inconsistent with cakes.
![2024-08-26_22 17 26](https://github.com/user-attachments/assets/637b26b1-9634-4ee6-9f2f-66a81ce533fb)
![2024-08-26_22 17 31](https://github.com/user-attachments/assets/1d9838e2-d932-4d78-8ad1-95802b63caf2)

### Steps to reproduce

1. Place a pie
2. Eat it

### Mod list

Farmer's Delight
Guard Villagers
MoonLight Lib
SmarterFarmers

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
This is sadly intentional. Pies can rotate horizontally, so the logic to create partially-eaten hitboxes on each rotation gets very long and verbose; I settled for just giving it a full one instead.

This could change in the future, though. 👍
