### ISSUE TITLE
(CRITICAL) 1.21 Placing a Mangrove Cabinet crashes the game

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#983]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### NeoForge version

21.1.42

### Description

When placing a Mangrove Cabinet, the game crashes

### Steps to reproduce

1. Get a Mangrove Cabinet
2. Place it
3. See crash

### Mod list

		kuma-api-neoforge-21.0.5-SNAPSHOT.jar             |KumaAPI                       |kuma_api                      |21.0.5-SNAPSHOT     |Manifest: NOSIGNATURE
		fabric-renderer-api-v1-3.4.0+acb05a3919.jar       |Forgified Fabric Renderer API |fabric_renderer_api_v1        |3.4.0+acb05a3919    |Manifest: NOSIGNATURE
		geckolib-neoforge-1.21.1-4.6.3.jar                |GeckoLib 4                    |geckolib                      |4.6.3               |Manifest: NOSIGNATURE
		fabric-item-api-v1-11.0.0+f56196c219.jar          |Forgified Fabric Item API (v1)|fabric_item_api_v1            |11.0.0+f56196c219   |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$json-0.2.1_m|json                          |org_quiltmc_parsers_json      |0.2.1               |Manifest: NOSIGNATURE
		fabric-rendering-fluids-v1-3.1.6+857185bc19.jar   |Forgified Fabric Rendering Flu|fabric_rendering_fluids_v1    |3.1.6+857185bc19    |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.21-NeoForge-4.0.0.jar |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.21-NeoForge-4.0.0 |Manifest: NOSIGNATURE
		DnT-ancient-city-overhaul-v2 [NeoForge].jar       |Dungeons and Taverns Ancient C|mr_dungeons_andtavernsancientc|1-v2                |Manifest: NOSIGNATURE
		fabric-convention-tags-v1-2.0.19+7f945d5b19.jar   |Forgified Fabric Convention Ta|fabric_convention_tags_v1     |2.0.19+7f945d5b19   |Manifest: NOSIGNATURE
		neoforge-21.1.42-universal.jar                    |NeoForge                      |neoforge                      |21.1.42             |Manifest: NOSIGNATURE
		modernfix-neoforge-5.19.3+mc1.21.1.jar            |ModernFix                     |modernfix                     |5.19.3+mc1.21.1     |Manifest: NOSIGNATURE
		fabric-command-api-v2-2.2.28+36d727be19.jar       |Forgified Fabric Command API (|fabric_command_api_v2         |2.2.28+36d727be19   |Manifest: NOSIGNATURE
		fabric-convention-tags-v2-2.5.0+ae4389fe19.jar    |Forgified Fabric Convention Ta|fabric_convention_tags_v2     |2.5.0+ae4389fe19    |Manifest: NOSIGNATURE
		fabric-block-view-api-v2-1.0.10+9afaaf8c19.jar    |Forgified Fabric BlockView API|fabric_block_view_api_v2      |1.0.10+9afaaf8c19   |Manifest: NOSIGNATURE
		YungsApi-1.21-NeoForge-5.0.0.jar                  |YUNG's API                    |yungsapi                      |1.21-NeoForge-5.0.0 |Manifest: NOSIGNATURE
		fabric-data-attachment-api-v1-1.1.27+d82d50ba19.ja|Forgified Fabric Data Attachme|fabric_data_attachment_api_v1 |1.1.27+d82d50ba19   |Manifest: NOSIGNATURE
		Forgematica-0.1.11-mc1.21.1.jar                   |Forgematica                   |forgematica                   |0.1.11-mc1.21.1     |Manifest: NOSIGNATURE
		custom-portals-3.6.1-1.21$cardinal-components-worl|Cardinal Components API (world|cardinal_components_world     |6.1.0               |Manifest: NOSIGNATURE
		jeed-1.21-2.2.9.jar                               |Just Enough Effects Descriptio|jeed                          |1.21-2.2.9          |Manifest: NOSIGNATURE
		balm-neoforge-1.21.1-21.0.19.jar                  |Balm                          |balm                          |21.0.19             |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$gson-0.2.1_m|gson                          |org_quiltmc_parsers_gson      |0.2.1               |Manifest: NOSIGNATURE
		fabric-screen-api-v1-2.0.24+79a4c2b019.jar        |Forgified Fabric Screen API (v|fabric_screen_api_v1          |2.0.24+79a4c2b019   |Manifest: NOSIGNATURE
		org.sinytra.connector-2.0.0-beta.2+1.21.1-mod.jar |Sinytra Connector             |connector                     |2.0.0-beta.2+1.21.1 |Manifest: NOSIGNATURE
		YungsBetterNetherFortresses-1.21-NeoForge-3.0.0.ja|YUNG's Better Nether Fortresse|betterfortresses              |1.21-NeoForge-3.0.0 |Manifest: NOSIGNATURE
		sawmill-1.21-1.5.2-neoforge.jar                   |Universal Sawmill             |sawmill                       |1.21-1.5.2          |Manifest: NOSIGNATURE
		forgified-fabric-api-0.102.0+2.0.12+1.21.1.jar    |Forgified Fabric API          |fabric_api                    |0.102.0+2.0.12+1.21.|Manifest: NOSIGNATURE
		fabric-content-registries-v0-8.0.16+0a0c14ff19.jar|Forgified Fabric Content Regis|fabric_content_registries_v0  |8.0.16+0a0c14ff19   |Manifest: NOSIGNATURE
		embeddium-1.0.11+mc1.21.1.jar                     |Embeddium                     |embeddium                     |1.0.11+mc1.21.1     |Manifest: NOSIGNATURE
		athena-neoforge-1.21-4.0.0.jar                    |Athena                        |athena                        |4.0.0               |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$common-lang-|common-lang                   |com_twelvemonkeys_common_commo|3.10.0              |Manifest: NOSIGNATURE
		FarmersDelight-1.21-1.2.4.jar                     |Farmer's Delight              |farmersdelight                |1.2.4               |Manifest: NOSIGNATURE
		entity_model_features_neoforge_1.21-2.2.4.jar     |Entity Model Features         |entity_model_features         |2.2.4               |Manifest: NOSIGNATURE
		entity_texture_features_neoforge_1.21-6.2.3.jar   |Entity Texture Features       |entity_texture_features       |6.2.3               |Manifest: NOSIGNATURE
		fabric-game-rule-api-v1-1.0.53+36d727be19.jar     |Forgified Fabric Game Rule API|fabric_game_rule_api_v1       |1.0.53+36d727be19   |Manifest: NOSIGNATURE
		fabric-api-lookup-api-v1-1.6.68+c21168c319.jar    |Forgified Fabric API Lookup AP|fabric_api_lookup_api_v1      |1.6.68+c21168c319   |Manifest: NOSIGNATURE
		MaFgLib-0.1.22-mc1.21.1.jar                       |MaFgLib                       |mafglib                       |0.1.22-mc1.21.1     |Manifest: NOSIGNATURE
		mcw-trapdoors-1.1.3-mc1.21.1neoforge.jar          |Macaw's Trapdoors             |mcwtrpdoors                   |1.1.3               |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$common-io-3.|common-io                     |com_twelvemonkeys_common_commo|3.10.0              |Manifest: NOSIGNATURE
		spark-1.10.97-neoforge.jar                        |spark                         |spark                         |1.10.97             |Manifest: NOSIGNATURE
		MyNethersDelight-1.21-1.7.7.jar                   |My Nether's Delight           |mynethersdelight              |1.7.7               |Manifest: NOSIGNATURE
		dungeons-and-taverns-v4.3 [NeoForge].jar          |Dungeons and Taverns          |mr_dungeons_andtaverns        |1-v4.3              |Manifest: NOSIGNATURE
		fabric-entity-events-v1-1.6.12+0a0c14ff19.jar     |Forgified Fabric Entity Events|fabric_entity_events_v1       |1.6.12+0a0c14ff19   |Manifest: NOSIGNATURE
		resourcefullib-neoforge-1.21-3.0.9.jar            |Resourceful Lib               |resourcefullib                |3.0.9               |Manifest: NOSIGNATURE
		worldedit-mod-7.3.6.jar                           |WorldEdit                     |worldedit                     |7.3.6+6892-3d660b8  |Manifest: NOSIGNATURE
		custom-portals-3.6.1-1.21$cardinal-components-base|Cardinal Components API (base)|cardinal_components_base      |6.1.0               |Manifest: NOSIGNATURE
		architectury-13.0.6-neoforge.jar                  |Architectury                  |architectury                  |13.0.6              |Manifest: NOSIGNATURE
		accelerated-decay-neoforge-21.0.0.jar             |Accelerated Decay             |accelerateddecay              |21.0.0              |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$common-image|common-image                  |com_twelvemonkeys_common_commo|3.10.0              |Manifest: NOSIGNATURE
		fabric-loot-api-v2-3.0.14+a3ee712d19.jar          |Forgified Fabric Loot API (v2)|fabric_loot_api_v2            |3.0.14+a3ee712d19   |Manifest: NOSIGNATURE
		fabric-loot-api-v3-1.0.2+333dfad919.jar           |Forgified Fabric Loot API (v3)|fabric_loot_api_v3            |1.0.2+333dfad919    |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.21-NeoForge-3.0.0.jar      |YUNG's Better End Island      |betterendisland               |1.21-NeoForge-3.0.0 |Manifest: NOSIGNATURE
		fabric-rendering-data-attachment-v1-0.3.48+73761d2|Forgified Fabric Rendering Dat|fabric_rendering_data_attachme|0.3.48+73761d2e19   |Manifest: NOSIGNATURE
		the_bumblezone-7.6.26+1.21.1-neoforge.jar         |The Bumblezone                |the_bumblezone                |7.6.26+1.21.1-neofor|Manifest: NOSIGNATURE
		fabric-networking-api-v1-4.2.2+a92978fd19.jar     |Forgified Fabric Networking AP|fabric_networking_api_v1      |4.2.2+a92978fd19    |Manifest: NOSIGNATURE
		yeetusexperimentus-neoforge-87.0.0.jar            |Yeetus Experimentus           |yeetusexperimentus            |87.0.0              |Manifest: NOSIGNATURE
		shulkerboxtooltip-neoforge-5.1.0+1.21.1.jar       |ShulkerBoxTooltip             |shulkerboxtooltip             |5.1.0+1.21.1        |Manifest: NOSIGNATURE
		fabric-lifecycle-events-v1-2.3.12+88bf4f7f19.jar  |Forgified Fabric Lifecycle Eve|fabric_lifecycle_events_v1    |2.3.12+88bf4f7f19   |Manifest: NOSIGNATURE
		fabric-key-binding-api-v1-1.0.47+62cc7ce119.jar   |Forgified Fabric Key Binding A|fabric_key_binding_api_v1     |1.0.47+62cc7ce119   |Manifest: NOSIGNATURE
		YungsBetterJungleTemples-1.21-NeoForge-3.0.0.jar  |YUNG's Better Jungle Temples  |betterjungletemples           |1.21-NeoForge-3.0.0 |Manifest: NOSIGNATURE
		fabric-client-tags-api-v1-1.1.15+e053909619.jar   |Forgified Fabric Client Tags  |fabric_client_tags_api_v1     |1.1.15+e053909619   |Manifest: NOSIGNATURE
		fabric-transfer-api-v1-5.1.16+7f12564f19.jar      |Forgified Fabric Transfer API |fabric_transfer_api_v1        |5.1.16+7f12564f19   |Manifest: NOSIGNATURE
		fishermens_trap-3.0.2.jar                         |Fishermens Trap               |fishermens_trap               |3.0.2               |Manifest: NOSIGNATURE
		Cucumber-1.21.1-8.0.3.jar                         |Cucumber Library              |cucumber                      |8.0.3               |Manifest: NOSIGNATURE
		amendments-1.21-1.2.10-neoforge.jar               |Amendments                    |amendments                    |1.21-1.2.10         |Manifest: NOSIGNATURE
		fabric-model-loading-api-v1-2.0.0+a6e994cd19.jar  |Forgified Fabric Model Loading|fabric_model_loading_api_v1   |2.0.0+a6e994cd19    |Manifest: NOSIGNATURE
		jei-1.21.1-neoforge-19.16.4.183.jar               |Just Enough Items             |jei                           |19.16.4.183         |Manifest: NOSIGNATURE
		fabric-screen-handler-api-v1-1.3.86+8dbc56dd19.jar|Forgified Fabric Screen Handle|fabric_screen_handler_api_v1  |1.3.86+8dbc56dd19   |Manifest: NOSIGNATURE
		fabric-resource-loader-v0-1.3.0+bcae32ce19.jar    |Forgified Fabric Resource Load|fabric_resource_loader_v0     |1.3.0+bcae32ce19    |Manifest: NOSIGNATURE
		fabric-rendering-v1-5.0.5+2df007aa19.jar          |Forgified Fabric Rendering (v1|fabric_rendering_v1           |5.0.5+2df007aa19    |Manifest: NOSIGNATURE
		waystones-neoforge-1.21.1-21.1.3.jar              |Waystones                     |waystones                     |21.1.3              |Manifest: NOSIGNATURE
		fabric-renderer-indigo-1.7.0+acb05a3919.jar       |Forgified Fabric Renderer - In|fabric_renderer_indigo        |1.7.0+acb05a3919    |Manifest: NOSIGNATURE
		smarterfarmers-1.21-2.0.2-neoforge.jar            |Smarter Farmers               |smarterfarmers                |1.21-2.0.2          |Manifest: NOSIGNATURE
		badpackets-neo-0.8.1.jar                          |Bad Packets                   |badpackets                    |0.8.1               |Manifest: NOSIGNATURE
		CustomPlayerModels-1.21-0.6.19a.jar               |Customize your minecraft avata|cpm                           |0.6.19a             |Manifest: NOSIGNATURE
		YungsBetterDesertTemples-1.21-NeoForge-4.0.0.jar  |YUNG's Better Desert Temples  |betterdeserttemples           |1.21-NeoForge-4.0.0 |Manifest: NOSIGNATURE
		cratedelight-24.09.03-1.21-neoforge.jar           |Crate Delight                 |cratedelight                  |24.09.03-1.21-neofor|Manifest: NOSIGNATURE
		CraftTweaker-neoforge-1.21.1-21.0.2.jar           |CraftTweaker                  |crafttweaker                  |21.0.2              |Manifest: NOSIGNATURE
		fabric-particles-v1-4.0.2+824f924c19.jar          |Forgified Fabric Particles (v1|fabric_particles_v1           |4.0.2+824f924c19    |Manifest: NOSIGNATURE
		fabric-transitive-access-wideners-v1-6.1.0+0df3143|Forgified Fabric Transitive Ac|fabric_transitive_access_widen|6.1.0+0df3143b19    |Manifest: NOSIGNATURE
		client-1.21.1-20240808.144430-srg.jar             |Minecraft                     |minecraft                     |1.21.1              |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		moonlight-1.21-2.14.15-neoforge.jar               |Moonlight Lib                 |moonlight                     |1.21-2.14.15        |Manifest: NOSIGNATURE
		fabric-api-base-0.4.42+d1308ded19.jar             |Forgified Fabric API Base     |fabric_api_base               |0.4.42+d1308ded19   |Manifest: NOSIGNATURE
		fabric-blockrenderlayer-v1-1.1.52+b089b4bd19.jar  |Forgified Fabric BlockRenderLa|fabric_blockrenderlayer_v1    |1.1.52+b089b4bd19   |Manifest: NOSIGNATURE
		Jade-1.21.1-NeoForge-15.2.1.jar                   |Jade                          |jade                          |15.2.1+neoforge     |Manifest: NOSIGNATURE
		fabric-block-api-v1-1.0.22+a6e994cd19.jar         |Forgified Fabric Block API (v1|fabric_block_api_v1           |1.0.22+a6e994cd19   |Manifest: NOSIGNATURE
		fabric-resource-conditions-api-v1-4.3.0+ea90ec3c19|Forgified Fabric Resource Cond|fabric_resource_conditions_api|4.3.0+ea90ec3c19    |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$imageio-core|imageio-core                  |com_twelvemonkeys_imageio_imag|3.10.0              |Manifest: NOSIGNATURE
		notenoughanimations-neoforge-1.7.6-mc1.21.jar     |NotEnoughAnimations           |notenoughanimations           |1.7.6               |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$imageio-meta|imageio-metadata              |com_twelvemonkeys_imageio_imag|3.10.0              |Manifest: NOSIGNATURE
		fabric-item-group-api-v1-4.1.4+262bc2d219.jar     |Forgified Fabric Item Group AP|fabric_item_group_api_v1      |4.1.4+262bc2d219    |Manifest: NOSIGNATURE
		fabric-gametest-api-v1-2.0.4+29f188ce19.jar       |Forgified Fabric Game Test API|fabric_gametest_api_v1        |2.0.4+29f188ce19    |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric$imageio-webp|imageio-webp                  |com_twelvemonkeys_imageio_imag|3.10.0              |Manifest: NOSIGNATURE
		unloadedactivity-v0.6.4+1.21-1.21.1.jar           |Unloaded Activity             |unloaded_activity             |0.6.4               |Manifest: NOSIGNATURE
		entityculling-neoforge-1.7.0-mc1.21.jar           |EntityCulling                 |entityculling                 |1.7.0               |Manifest: NOSIGNATURE
		fabric-biome-api-v1-13.0.29+1e62d33c19.jar        |Forgified Fabric Biome API (v1|fabric_biome_api_v1           |13.0.29+1e62d33c19  |Manifest: NOSIGNATURE
		figura-0.1.5-rc.2+1.21-neoforge-mc.jar            |Figura                        |figura                        |0.1.5-rc.2+1.21     |Manifest: NOSIGNATURE
		DnT-stronghold-overhaul-v2.1 [NeoForge].jar       |Dungeons and Taverns Stronghol|mr_dungeons_andtavernsstrongho|1-v2.1              |Manifest: NOSIGNATURE
		fabric-registry-sync-v0-5.1.2+0c9b5b5419.jar      |Forgified Fabric Registry Sync|fabric_registry_sync_v0       |5.1.2+0c9b5b5419    |Manifest: NOSIGNATURE
		ImmediatelyFast-NeoForge-1.2.21+1.21.1.jar        |ImmediatelyFast               |immediatelyfast               |1.2.21+1.21.1       |Manifest: NOSIGNATURE
		appleskin-neoforge-mc1.21-3.0.5.jar               |AppleSkin                     |appleskin                     |3.0.5+mc1.21        |Manifest: NOSIGNATURE
		fabric-recipe-api-v1-5.0.12+c653ba0e19.jar        |Forgified Fabric Recipe API (v|fabric_recipe_api_v1          |5.0.12+c653ba0e19   |Manifest: NOSIGNATURE
		ferritecore-7.0.0-neoforge.jar                    |Ferrite Core                  |ferritecore                   |7.0.0               |Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		DnT-end-castle-standalone-v1 [NeoForge].jar       |Dungeons and Taverns End Castl|mr_dungeons_andtavernsendcastl|1-v1                |Manifest: NOSIGNATURE
		fabric-object-builder-api-v1-15.2.0+9815f61f19.jar|Forgified Fabric Object Builde|fabric_object_builder_api_v1  |15.2.0+9815f61f19   |Manifest: NOSIGNATURE
		YetAnotherConfigLib-3.5.0+1.21-fabric_mapped_moj_1|YetAnotherConfigLib           |yet_another_config_lib_v3     |3.5.01.21-fabric    |Manifest: NOSIGNATURE
		fabric-sound-api-v1-1.0.23+d80d32ac19.jar         |Forgified Fabric Sound API (v1|fabric_sound_api_v1           |1.0.23+d80d32ac19   |Manifest: NOSIGNATURE
		fabric-message-api-v1-6.0.13+e053909619.jar       |Forgified Fabric Message API (|fabric_message_api_v1         |6.0.13+e053909619   |Manifest: NOSIGNATURE
		cosmeticarmorreworked-1.21.1-v1-neoforge.jar      |CosmeticArmorReworked         |cosmeticarmorreworked         |1.21.1-v1-neoforge  |Manifest: 5e:ed:25:99:e4:44:14:c0:dd:89:c1:a9:4c:10:b5:0d:e4:b1:52:50:45:82:13:d8:d0:32:89:67:56:57:01:53
		custom-portals-3.6.1-1.21_mapped_moj_1.21.1.jar   |Custom Portals                |customportals                 |3.6.0               |Manifest: NOSIGNATURE
		fabric-data-generation-api-v1-20.2.16+ed29d49b19.j|Forgified Fabric Data Generati|fabric_data_generation_api_v1 |20.2.16+ed29d49b19  |Manifest: NOSIGNATURE
		fabric-events-interaction-v0-0.7.12+7b71cc1619.jar|Forgified Fabric Events Intera|fabric_events_interaction_v0  |0.7.12+7b71cc1619   |Manifest: NOSIGNATURE

### Logs

[crash-2024-09-06_20.39.01-client.txt](https://github.com/user-attachments/files/16913839/crash-2024-09-06_20.39.01-client.txt)

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Fixed on PR #977 by theendercore, should be out in a hotfix soon.
