### ISSUE TITLE
Cooking Pot Servings don't save upon saving and exiting

### ISSUE THREAD

**Issue by Inonedn** [vectorwing/FarmersDelight#986]
### Minecraft version

1.21

### Farmer's Delight version

1.2.4

### NeoForge version

21.1.55

### Description

When saving and exiting with a taken serving from a cooking pot, it will refill back to what it was originally.

### Steps to reproduce

1. Get 64 servings from a cooking pot
2. take some servings from it
3. save and exit the game
4. see error

### Mod list

N/A

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Turns out this is also a bug on 1.20.1, and I noticed it during a personal playthrough. I'll include it in the next hotfix, and in the next 1.20.1 update when it comes out.

**Comment by vectorwing** [comment]
Fixed on commits eb9f183 and 0d9a5c9.
