### ISSUE TITLE
Vegetable Soup recipe with Cabbage produces Cabbage Rolls instead

### ISSUE THREAD

**Issue by Holgast** [vectorwing/FarmersDelight#991]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### NeoForge version

I am using regular Forge.

### Description

Inputting the ingredients for Vegetable Soup using Cabbage as the green always produces Cabbage Rolls instead. This occurs both while clicking the recipe from the list and manually placing the ingredients in the pot. I do have bowls in the pot.

### Mod list

Unmodified Better MC BMC4 modpack

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Sorry, I wasn't able to replicate this locally. Although Cabbage Rolls use a subset of the Vegetable Soup recipe, adding more than 2 stacks would automatically invalidate Cabbage Rolls from cooking.

Though this seems strange, there is a chance some add-on could be changing how the Cooking Pot resolves its ingredients.

Could you please provide the full mod list directly? You can get one by forcing a test crash:
1. Hold down F3+C for roughly 10 seconds. The game will instruct you in chat;
2. Wait for the game to crash;
3. Navigate to your instance folder, and the crash will be in the `logs` folder. It will show a mod list.

**Comment by Holgast** [comment]
Hmm, you're right in that putting more stacks in resolves it. Odd, I would never have thought that would make a difference, it's not mentioned in the documentation. I'll go ahead and close this.

**Comment by Holgast** [comment]
x
