### ISSUE TITLE
Please update to 1.21.1

### ISSUE THREAD

**Issue by Shadowblitz16** [vectorwing/FarmersDelight#992]
### Minecraft version

1.21.1

### Farmer's Delight version

na

### NeoForge version

I use forge for compatability.

### Description

na

### Steps to reproduce

na

### Mod list

![image](https://github.com/user-attachments/assets/7bf6a644-5adb-4ad5-ad7f-cf34caf3da90)
not tested.

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I am using performance or shader mods

**Comment by vectorwing** [comment]
Please don't open issues to ask for ports or ETA's. This is not what this board is for.
A 1.21.1 build will be released soon with a few bugfixes.
