### ISSUE TITLE
Vinery wine bottles do not output from Cooking recipes that use vinery wines

### ISSUE THREAD

**Issue by Barerock** [vectorwing/FarmersDelight#993]
### Minecraft version

1.20.1

### Farmer's Delight version

1.2.4

### NeoForge version

Forge 47.2.20 - 47.3.0 for these tests

### Description

A vinery wine, such as noir_wine, will not pop its wine_bottle out of the pot once the recipe is done. This is separate from wine bottles not being valid containers for recipes at some point.

### Steps to reproduce

Make or find a custom recipe using KubeJS datapack that contains a Vinery wine
Complete the recipe
Observe no bottle produced in any field, inside or popping out of the pot

### Mod list

[energetic_poultice_cooking.json](https://github.com/user-attachments/files/17196470/energetic_poultice_cooking.json)
![image](https://github.com/user-attachments/assets/3d876d8b-f09e-4560-9195-7ce24a63e02b)

### Logs

[latest.log](https://github.com/user-attachments/files/17196480/latest.log)

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
In order for ingredients to "pop out" a craft remainder post-cooking, they must specify that remainder in their item properties, which is done through code. For example:
https://github.com/vectorwing/FarmersDelight/blob/140804c707645070f9a287ce258225a06c9961eb/src/main/java/vectorwing/farmersdelight/common/registry/ModItems.java#L40

Vinery's wines might not have craft remainders defined (they might not need to, if wines aren't used in crafting), and I'm unable to check if that's the case, as the mod appears to be closed source. If no bottles are popping, they likely don't define it.

This doesn't seem like a bug per se. Might be worth suggesting this to the mod author, if it's useful for modpacks.
