### ISSUE TITLE
OVEN ISSUE

### ISSUE THREAD

**Issue by AMERICANBEAR** [vectorwing/FarmersDelight#994]
### Minecraft version

1.20.1

### Farmer's Delight version

1.20.1+12

### NeoForge version

s

### Description

THE OVEN WILL NOT LIGHT WITH THE FLINT AND STEEL OR THE fire charge and when you do right click on it it just pulls up the smoker menu 

### Steps to reproduce

s

### Mod list

better-nether-9.0.10_mapped_srg_1.20.1.jar         | Better Nether                  | betternether                   | 9.0.10               |
		| Eldritch_End-FORGE-MC1.20.1-0.2.31_mapped_srg_1.20 | Eldritch End                   | eldritch_end                   | 0.2.31               |
		| continuity-3.0.0-beta.5+1.20.1_mapped_srg_1.20.1.j | Continuity                     | continuity                     | 3.0.0-beta.51.20.1   |
		| fasterrandom-5.1.0_mapped_srg_1.20.1.jar           | Faster Random                  | faster_random                  | 5.1.0                |
		| better-end-4.0.11_mapped_srg_1.20.1.jar            | Better End                     | betterend                      | 4.0.11               |
		| bclib-3.0.14$wunderlib-1.1.5_mapped_srg_1.20.1.jar | WunderLib                      | wunderlib                      | 1.1.5                |
		| bclib-3.0.14_mapped_srg_1.20.1.jar                 | BCLib                          | bclib                          | 3.0.14               |
		| ucrashedlol-0.0.3+1.20.1_mapped_srg_1.20.1.jar     | ucrashedlol                    | ucrashedlol                    | 0.0.31.20.1          |
		| inventorymanagement-1.3.1+1.20_mapped_srg_1.20.1.j | Inventory Management           | inventorymanagement            | 1.3.1                |
		| betterend-crashed-ships-1.0.0_mapped_srg_1.20.1.ja | BetterEnd Crashed Ships        | betterend_crashed_ships        | 1.0.0                |
		| spawnersplus-4.0-1.20.1_mapped_srg_1.20.1.jar      | Spawners+                      | spawners_plus                  | 4.0-1.20.1  

### Logs

s

### Minimal instance

- [X] I have tested this on a minimal instance

### Performance and shader mods

- [ ] I am using performance or shader mods

**Comment by vectorwing** [comment]
Please fill out the bug report form correctly, or I won't be able to investigate your issue.

FD does not add an oven, it adds a Stove and a Cooking Pot, neither of which should open the Smoker interface.
Can you please post a screenshot of your block setup?

**Comment by AMERICANBEAR** [comment]
I'm sorry bro I'm retarded and was using the wrong thing it works great
sorry for wasting ur time
